### ISSUE TITLE
Products out of Stock (Frontend) in non Default Website

### ISSUE THREAD

**Issue by larsroettig** [magento/inventory#1001]
### Preconditions
1.  Instal Last  2.3-develop ( f2fdae5246c1b859e4ce7532458dd1243eff0991)
2. PHP 7.1

### Steps to reproduce
1. Create **New Website** with **Store** and **Store View**
<img width="1429" alt="stores___settings___stores___magento_admin" src="https://user-images.githubusercontent.com/5289370/39100097-4bc996c2-4639-11e8-988d-10b754dec2b4.png">

2.  Enable **web/url/use_store** for your magento 
3.  Create Two new Sources
4.  Create One Stock and assigned your **new Website** and **Sources**
5. Create new Product with Stock of 10 in **every Sources**

### Info
- The Index Table is correct 

### Expected result
<img width="1400" alt="expected_result" src="https://user-images.githubusercontent.com/5289370/39100046-ad9ab6ca-4638-11e8-9a1e-85205dbf8ca7.png">

### Actual result
<img width="1316" alt="actual_result" src="https://user-images.githubusercontent.com/5289370/39100059-d3d7ae38-4638-11e8-9db8-fc3358b8f5a9.png">

**Comment by smoskaluk** [comment]
@larsroettig For new product you need to set it to your custom website on Product page in admin if you want it to be displayed on custom website.

![image](https://user-images.githubusercontent.com/27818516/39115711-36684a14-46eb-11e8-9976-5e9f4297cf30.png)
