### ISSUE TITLE
Reservation for configurable product after placing order should not be created

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1002]
### Preconditions

1. Magento MSI
2. New stock with new source created
3. Configurable product created and assigned to default source woth qty = 100

### Steps to reproduce

1. Create aorder with one of the option of cinfigurable product
2. Check in DB table inventory_reservation

### Expected result

1. Reservation should be created only for configurable option child product

### Actual result

1. Reservations created for configuarble product and for configurable option child product

![image](https://user-images.githubusercontent.com/27818516/39123298-22140930-4700-11e8-8aa3-6405256dda51.png)

**Comment by RomaKis** [comment]
Close this issue as not reproducible after communication with @smoskaluk .
