### ISSUE TITLE
Creating an order with a product that has a number in the product name causes fatal error 

### ISSUE THREAD

**Issue by jhill-magento** [magento/inventory#1007]
Creating an order with a product that has a numeric name causes the returning page to be the following 2 errors:

`( ! ) Fatal error: Uncaught TypeError: Argument 1 passed to Magento\InventorySales\Model\IsProductSalableForRequestedQtyCondition\IsProductSalableForRequestedQtyConditionChain::execute() must be of the type string, integer given, called in /Users/jhill/Vagrant/magento-vagrant/magento2ce/app/code/Magento/InventorySales/Model/CheckItemsQuantity.php on line 57 and defined in /Users/jhill/Vagrant/magento-vagrant/magento2ce/app/code/Magento/InventorySales/Model/IsProductSalableForRequestedQtyCondition/IsProductSalableForRequestedQtyConditionChain.php on line 129`

`( ! ) TypeError: Argument 1 passed to Magento\InventorySales\Model\IsProductSalableForRequestedQtyCondition\IsProductSalableForRequestedQtyConditionChain::execute() must be of the type string, integer given, called in /Users/jhill/Vagrant/magento-vagrant/magento2ce/app/code/Magento/InventorySales/Model/CheckItemsQuantity.php on line 57 in /Users/jhill/Vagrant/magento-vagrant/magento2ce/app/code/Magento/InventorySales/Model/IsProductSalableForRequestedQtyCondition/IsProductSalableForRequestedQtyConditionChain.php on line 129`

*STEPS*
1. Add a Product
    * Name: 901
    * Sku: 901
    * Price: $3.50
2. Place an Order with the above Product, via the Admin
3. Note the following error message:
![fatal-error-number-for-name.png](https://images.zenhubusercontent.com/5a8311d54b5806bc2bc6c492/57b26fd2-68d1-4cc4-99a0-c17ae5ccca6a)

**Comment by RomaKis** [comment]
We have sku as an array key in 
```
https://github.com/magento-engcom/msi/blob/2.3-develop/app/code/Magento/InventorySales/Plugin/CatalogInventory/StockManagement/ProcessRegisterProductsSalePlugin.php#L86
```
And as the [documentation](http://php.net/manual/en/language.types.array.php) say

`
Strings containing valid decimal integers, unless the number is preceded by a + sign, will be cast to the integer type. E.g. the key "8" will actually be stored under 8. On the other hand "08" will not be cast, as it isn't a valid decimal integer.
`

So if we have numeric sku like "901" it will be converted to 901 as a key of array. And some of methods wait exactly string, but not integer value of sku.

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/1013
