### ISSUE TITLE
Double compensational reservation for one order

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1026]
### Preconditions

1. Magento MSI single stock mode
2. Simple product created with qty = 100 

### Steps to reproduce

1. Order placed from admin with qty = 5 of simple product
2. Invoice created for whole order (Qty = 5)
3. Shipment created for whole order (Qty = 5)
4. Credit memo with Return to the stock created for whole order (Qty = 5)

### Expected result

1. Only one compensational reservation should be created

### Actual result

1. Compensational reservations created after shipment and after credit memo

![image](https://user-images.githubusercontent.com/27818516/39251584-5c05928c-48ac-11e8-901d-e7780d534a69.png)

![image](https://user-images.githubusercontent.com/27818516/39251906-15fd9aa4-48ad-11e8-91b2-96e05f3ffe7c.png)

**Comment by p-bystritsky** [comment]
Duplicates https://github.com/magento-engcom/msi/issues/377
