### ISSUE TITLE
Configurable Product is "Out of Stock" In Case Unassigned Custom Source Presents In System.

### ISSUE THREAD

**Issue by nmalevanec** [magento/inventory#1028]
### Preconditions
1. Magento with enabled MSI

### Steps to reproduce
1. Login to admin area.
2. Navigate to Store > Manage Sources.
3. Add new source "Test Source"(code: "test_source"). Leave it unassigned.
7. Do not add any custom Stocks. 
8. Navigate to Catalog > Products.
9. Start creating configurable product by pressing "Add Product" button. Note: Do not choose initially type of the product..
10. Fill necessary data:
Product Name: "configurable product"
SKU: configurable product
Price: 3
11. Assign it some category.
12. Start creating configurations.
13. At "Select Attributes" step select color attribute.
14. At "Attribute Value" step create two options: "blue" and "red".
15. At "Bulk Images & Price" step check "Apply single quantity to each SKUs" and assign "default" source with qty = 100 (NOTE: do not assign options to custom source).
16. Generate products.
17. Set some weight for generated products.
12. Save configurable.
19.  Navigate to storefront configurable product category. 
20. Navigate to storefront, configurable product view page. 

### Expected result
1. Configurable product is present on category page.
2. Configurable product has "In Stock" status on it's view page.

### Actual result
1. Configurable product is absent on category page.
2. Configurable product has "Out of Stock" status on it's view page.

**Comment by silyadev** [comment]
Reproduced. The cause of the issue that "Stock status" after product creation become "Out of stock"

**Comment by smoskaluk** [comment]
Reproducing on 2.3 develop

**Comment by smoskaluk** [comment]
Redescribed in https://github.com/magento-engcom/msi/issues/1541
