### ISSUE TITLE
Saving configurable product automatically makes its children in stock

### ISSUE THREAD

**Issue by RomaKis** [magento/inventory#1033]
### Preconditions
1. Magento with enabled MSI

### Steps to reproduce
1. Login to admin area.
2. Navigate to Store > Manage Sources.
3. Add new source "Test Source"(code: "test_source").
4. Navigate to Store > Manage Stocks.
5. Add new stock "Test Stock". Do not assign it current website.
6. Assign "Test Source" to "Test Stock".
7. Perform reindex and flush cache.
8. Navigate to Catalog > Products.
9. Start creating configurable product.
10. Fill necessary data:
Product Name: "configurable product"
SKU: configurable product
Price: 3
11. Start creating configurations.
12. At "Select Attributes" step select color attribute.
13. At "Attribute Value" step create two options: "blue" and "red".
14. At "Bulk Images & Price" step check "Apply single quantity to each SKUs" and assign "default" source with qty = 100.
15. Generate products.
17. Set some weight for generated products.
18. Save configurable.
19. Set both configurable options to "Out of Stock" on default source.
20. Go to configurable page and save it.

### Expected result
- Configurable children still out of stock.

### Actual result
- Configurable children are in stock.

Problem can be in `Magento/InventoryConfigurableProductAdminUi/Observer/ProcessSourceItemsObserver::processSourceItems()`

**Comment by smoskaluk** [comment]
@RomaKis  On current develop branch still reproducible, please recheck

**Comment by RomaKis** [comment]
@smoskaluk, this issue isn't reproducible on latest develop branch. Please recheck it again.
