### ISSUE TITLE
"sourceItems" is required even when included to payload

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/inventory#1036]
### Preconditions
1. Magento MSI

### Steps to reproduce
1. Send request to set a variable:
`endpoint="http://msi.conf/rest"`
2. Send request to save Admin Authorization Token to a variable:
```
auth_token=$(curl -X POST "$endpoint/V1/integration/admin/token" \
 --header "Content-Type: application/json" \
 -d '{"username":"admin","password":"123123q"}') && auth_token=$(echo $auth_token | tr -d '"')
```
2. Send request to reduce source items:
```
curl -X DELETE "$endpoint/all/V1/inventory/source-item" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $auth_token" \
-d '{"sourceItems":[{"sku":"Simple Product 1","source_code":"source1","quantity":64,"status":0,"extension_attributes":{}}]}'
```

### Expected result
1. Qty was reduced from the source

### Actual result
1. Response:
```
{"message":"\"%fieldName\" is required. Enter and try again.","parameters":{"fieldName":"sourceItems"}}
```

**Comment by TomashKhamlai** [comment]
While we have a working example of DELETE operation sent by cURL with XML payload, we should keep in mind that many HTTP client libraries don't support a request body for DELETE http requests and some popular web servers if use them as the proxy,  will cut body for DELETE requests as they do for GET requests.

>    A payload within a DELETE request message has no defined semantics;
>    sending a payload body on a DELETE request might cause some existing
>    implementations to reject the request.

source: [rfc7231](https://tools.ietf.org/html/rfc7231#section-4.3.5)

According to this source [curl.haxx.se](https://curl.haxx.se/mail/lib-2012-11/0006.html), there were some problems with sending JSON payloads.

You can find a lot of Github issues in other repositories and that proves that sending Payloads within HTTP request is a bad practice.

@p-bystritsky, please put a breakpoint here
https://github.com/magento-engcom/msi/blob/fd409293a0f1303fc1e9746e5f05634f9de5c800/app/code/Magento/Webapi/Controller/Rest.php#L182 and check it. If it is not reproducible then you may try to use GP or some proxy enabled.

**Comment by p-bystritsky** [comment]
Closed due to more general issue https://github.com/magento-engcom/msi/issues/1039

**Comment by RishiRanjan21** [comment]
> {"message":"\"%fieldName\" is required. Enter and try again.","parameters":{"fieldName":"sourceItems"}}

I am facing the same issue.
