### ISSUE TITLE
Cannot disable multiple Sources by one operation like with Stocks

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/inventory#1041]
### Preconditions
1. Magento MSI
2. Three Sources created

### Steps to reproduce
1. Navigate to Stores > Settings > Manage Sources

### Expected result
1. There is 'Actions' Select with 'Disable/Enable' actions.
![expected](https://user-images.githubusercontent.com/11827230/39367646-1808bb78-4a40-11e8-99b6-2ab4e276d82d.png)

### Actual result
1. There is no 'Actions' Select with 'Disable/Enable' actions.
![actual](https://user-images.githubusercontent.com/11827230/39367659-1e90b0d6-4a40-11e8-9758-8b2b163f69d0.png)

**Comment by ivy00johns** [comment]
*Skipped Tests:*
1. `<testCaseId value="494"/>`
