### ISSUE TITLE
[Catalog-Products-Virtual Product] Virtual Product assigned to Test Stock created by Admin user

### ISSUE THREAD

**Issue by ivy00johns** [magento/inventory#1042]
1. Login to backend as admin
2. Go to Catalog -> Categories
3. Select Default Category on Categories Tree
4. Click button "Add Subcategory"
5. set "Enable Category" to "Yes"
6. set "Include in Menu" to "Yes"
7. Fill in "Category Name" = "Category 1"
8. Click button "Save"
9. Success  message "You saved the category." appears
10. Verify that Category 1 appeared in Categories tree as subcategory of Default category
11. Login to backend as admin
12. Go to Stores -> Manage Sources
13. Click button "Add New Source"
14. fill New Source data in General tab - Name, Code etc:
    * name = Test Source 1
    * code = test_source_1
15. Set your New Source "Is Enabled" = Yes
16. Fill all fields with data of your New Source in Contact Info tab
17. Fill in address data of your New Source in Address Data tab:
    * Country: United States
    * State/Province: California (CA)
    * City: Culver City
    * Street: 6161 West Centinela Avenue
    * Postсode: 90230
18. Set In "Carriers" tab "Use global Shipping configuration" to Yes
19. Click button "Save & close"
20. Confirmation message "The Source has been saved" appears
21. verify that data in all tabs is correct
22. Login to backend as admin
23. Go to Stores -> Manage Stocks
24. Click button "Add New Stock"
25. Fill in field "Name" = "Test Stock 1"
26. In "Sales Channels" Tab select website "Main Website"
27. Click button "Assign Sources" In "Sources" Tab
28. modal window "Assign Sources" opened
29. Select  "Test Source 1"  in sources list
30. Click button "Done"
31. Click button "Save & close"
32. Success message "The Stock have been saved" appeared
33. Login to backend as admin
34. Go to Catalog -> Products
35. Click button "Add Virual product"
36. set "Enable Product" to "Yes"
37. fill Name = "Virtual Product 1"
38. set Price = "10"
39. select Category = "Category 1"
40. click button "Assign Sources"
41. select in sources grid "Default Source", "Test Source 1" and click 'Done'
42. in "Assigned Sources" grid set
    * Qty for  "Default Source" = 100,
    * Qty for "Test Source 1"  = "100"
43. in "Product in Websites" tab  select "Main Website"
44. Open "Content" tab
45. In "Decription" text field put text "Best product"
46. click button "Save"
47. Success  message "You saved the product." appears
48. Go to "Catalog" -> "Products"
49. verify that "Virtual Product 1" appeared in "Products" grid
50. verify that "Name", "SKU", "Price" and "Website" correct
51. Go to "Home page"
52. Open "Category 1" page
53. verify that "Virtual Product 1" is present on category page
54. verify that "Name" and "Price" are correct
55. Open "Virtual Product 1" page
56. verify that "Name", "SKU" and "Price" are correct

----

Original HipTest ID: 1454592

**Comment by smoskaluk** [comment]
https://app.hiptest.com/projects/69435/test-plan/folders/457015/scenarios/1454592
