### ISSUE TITLE
"Out of Stock" Configurable Product Assigned to Custom Stock Shows "In Stock" on Storefront.

### ISSUE THREAD

**Issue by nmalevanec** [magento/inventory#1046]
### Preconditions
1. Magento with enabled MSI

### Steps to reproduce
1. Login to admin area.
2. Navigate to Store > Manage Sources.
3. Add new source "Test Source"(code: "test_source").
4. Navigate to Store > Manage Stocks.
5. Add new stock "Test Stock". Assign it to current website.
6. Assign "Test Source" to "Test Stock".
7. Perform reindex and flush cache.
8. Navigate to Catalog > Products.
9. Start creating configurable product.
10. Fill necessary data:
Product Name: "configurable product"
SKU: configurable product
Price: 3
11. Assign it to some category.
12. Start creating configurations.
13. At "Select Attributes" step select color attribute.
14. At "Attribute Value" step create two options: "blue" and "red".
15. At "Bulk Images & Price" step check "Apply single quantity to each SKUs" and assign "test_source" with qty = 100 
16. Generate products.
17. Set some weight for generated products.
18. Save configurable.
19. Navigate to storefront, configurable category view page .
20. Check configurable is present on category view page..
21. Login to admin area.
22. Set configurable product to "Out of Stock". Leave it's options "In Stock".
23. Navigate to storefront, category view page.
24. Navigate to storefront, configurable product view page. 

### Expected result
1. Configurable product is absent on category view page.
2. Configurable product has "Out of Stock" status.

### Actual result
1. Configurable product is present on category view page.
1.  Configurable product has "In Stock" status on it's view page.

### Additional info:
Looks like custom stock reindex doesn't take into consideration configurable product status itself, but only it's children statuses. Therefore, if configurable product children is "In Stock" on some custom source, it will be "In Stock" on storefront, even if it has own status "Out of Stock".

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/1153
