### ISSUE TITLE
Error on category page on frontend when Scheduled update created for simple product

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1048]
### Preconditions

1. Magento EE with MSI single stock mode
2. Simple product "Sim1" created on new category "Category 1"

### Steps to reproduce

1. On the simple product "Sim1" page in admin create schedule update to change name and price of the product for some period of time several minutes ahead from current time (with some start date and end date) and save it
2. Open "Category1" page on frontend
3. 

### Expected result

1. Category page opened correctly

### Actual result

1. [Screenshot, logs]
{"0":"Item (Magento\\Catalog\\Model\\Product\\Interceptor) with the same ID \"2\" already exists.","1":"#0 \/app\/vendor\/magento\/module-eav\/Model\/Entity\/Collection\/AbstractCollection.php(312): Magento\\Framework\\Data\\Collection->addItem(Object(Magento\\Catalog\\Model\\Product\\Interceptor))\n#1 \/app\/vendor\/magento\/module-eav\/Model\/Entity\/Collection\/AbstractCollection.php(1133): Magento\\Eav\\Model\\Entity\\Collection\\AbstractCollection->addItem(Object(Magento\\Catalog\\Model\\Product\\Interceptor))\n#2 \/app\/vendor\/magento\/module-eav\/Model\/Entity\/Collection\/AbstractCollection.php(923): Magento\\Eav\\Model\\Entity\\Collection\\AbstractCollection->_loadEntities(false, false)\n#3 \/app\/vendor\/magento\/module-catalog\/Model\/ResourceModel\/Product\/Collection.php(750): Magento\\Ea
v\\Model\\Entity\\Collection\\AbstractCollection->load(false, false)\n#4 \/app\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Catalog\\Model\\ResourceModel\\Product\\Collection->load(false, false)\n#5 \/app\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\CatalogStaging\\Model\\ResourceModel\\Fulltext\\Collection\\Interceptor->___callParent('load', Array)\n#6 \/app\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\CatalogStaging\\Model\\ResourceModel\\Fulltext\\C
ollection\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#7 \/app\/generated\/code\/Magento\/CatalogStaging\/Model\/ResourceModel\/Fulltext\/Collection\/Interceptor.php(26): Magento\\CatalogStaging\\Model\\ResourceModel\\Fulltext\\Collection\\Interceptor->_
__callPlugins('load', Array, Array)\n#8 \/app\/vendor\/magento\/module-review\/Observer\/CatalogBlockProductCollectionBeforeToHtmlObserver.php(38): Magento\\CatalogStaging\\Model\\ResourceModel\\Fulltext\\Collection\\Interceptor->load()\n#9 \/app\/vendor\/magento\/framew
ork\/Event\/Invoker\/InvokerDefault.php(72): Magento\\Review\\Observer\\CatalogBlockProductCollectionBeforeToHtmlObserver->execute(Object(Magento\\Framework\\Event\\Observer))\n#10 \/app\/vendor\/magento\/framework\/Event\/Invoker\/InvokerDefault.php(60): Magento\\Framew
ork\\Event\\Invoker\\InvokerDefault->_callObserverMethod(Object(Magento\\Review\\Observer\\CatalogBlockProductCollectionBeforeToHtmlObserver), Object(Magento\\Framework\\Event\\Observer))\n#11 \/app\/vendor\/magento\/module-staging\/Model\/Event\/Manager.php(97): Magento
\\Framework\\Event\\Invoker\\InvokerDefault->dispatch(Array, Object(Magento\\Framework\\Event\\Observer))\n#12 \/app\/generated\/code\/Magento\/Staging\/Model\/Event\/Manager\/Proxy.php(95): Magento\\Staging\\Model\\Event\\Manager->dispatch('catalog_block_p...', Array)\n
#13 \/app\/vendor\/magento\/module-catalog\/Block\/Product\/ListProduct.php(471): Magento\\Staging\\Model\\Event\\Manager\\Proxy->dispatch('catalog_block_p...', Array)\n#14 \/app\/vendor\/magento\/module-catalog\/Block\/Product\/ListProduct.php(116): Magento\\Catalog\\Bl
ock\\Product\\ListProduct->initializeProductCollection()\n#15 \/app\/vendor\/magento\/module-catalog\/Block\/Product\/ListProduct.php(348): Magento\\Catalog\\Block\\Product\\ListProduct->_getProductCollection()\n#16 \/app\/vendor\/magento\/module-page-cache\/Model\/Layou
t\/LayoutPlugin.php(71): Magento\\Catalog\\Block\\Product\\ListProduct->getIdentities()\n#17 \/app\/vendor\/magento\/framework\/Interception\/Interceptor.php(146): Magento\\PageCache\\Model\\Layout\\LayoutPlugin->afterGetOutput(Object(Magento\\Framework\\View\\Layout\\In
terceptor), '\\n    <script ty...')\n#18 \/app\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\View\\Layout\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#19 \/app\/generated\/code\/Magento\/Framework\/View\/Layout\/Int
erceptor.php(52): Magento\\Framework\\View\\Layout\\Interceptor->___callPlugins('getOutput', Array, Array)\n#20 \/app\/vendor\/magento\/framework\/View\/Result\/Page.php(257): Magento\\Framework\\View\\Layout\\Interceptor->getOutput()\n#21 \/app\/vendor\/magento\/framewo
rk\/View\/Result\/Layout.php(170): Magento\\Framework\\View\\Result\\Page->render(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n#22 \/app\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Framework\\View\\Result\\Layout->renderResu
lt(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n#23 \/app\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Framework\\View\\Result\\Page\\Interceptor->___callParent('renderResult', Array)\n#24 \/app\/vendor\/magento\/framework\/
Interception\/Interceptor.php(153): Magento\\Framework\\View\\Result\\Page\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n#25 \/app\/generated\/code\/Magento\/Framework\/View\/Result\/Page\/Interce
ptor.php(26): Magento\\Framework\\View\\Result\\Page\\Interceptor->___callPlugins('renderResult', Array, Array)\n#26 \/app\/vendor\/magento\/framework\/App\/Http.php(139): Magento\\Framework\\View\\Result\\Page\\Interceptor->renderResult(Object(Magento\\Framework\\App\\R
esponse\\Http\\Interceptor))\n#27 \/app\/vendor\/magento\/framework\/App\/Bootstrap.php(256): Magento\\Framework\\App\\Http->launch()\n#28 \/app\/pub\/index.php(37): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#29 {main}",
"url":"\/index.php\/cat1.html","script_name":"\/index.php"}

**Comment by smoskaluk** [comment]
still reproducing on current MSI branch 2.3 develop with EE

**Comment by kisroman** [comment]
@smoskaluk are you testing on PR branch? If yes, so you need to reinstall Magento after branch checkout.

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/1323
