### ISSUE TITLE
Try to eliminate all setter methods from DTO interface being manipulated via Web API 

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#1051]
After this PR https://github.com/magento/magento2/pull/14801 would be merged into Magento 2.3 mainline and changes get into MSI `2.3-develop` branch.

We would have an ability to eliminate setter methods from Data Interface being manipulated via Web APIs such as:
`SourceIntemInterface` , `StockItemInterface` and others.

In the scope of the current ticket, it's proposed to make refactoring of one of such interfaces and make sure that fix provided in 14801 PR is appropriate. 

The most interesting part is Web API test coverage of corresponding APIs which manipulate which Data Interface being refactored. 

Also, taking into account that PR 14801 is not yet in Magento 2.3-develop it's proposed to port it to MSI `2.3-develop` branch

**Comment by maghamed** [comment]
https://github.com/magento/magento2/pull/14801

**Comment by sidolov** [comment]
Already implemented and used for the new implementation.
