### ISSUE TITLE
Fix naming for Source Deducation API

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#1053]
\Magento\InventoryShipping\Model\SourceDeduction\Request\SourceDeductionRequestInterface::getWebsiteId

```
interface SourceDeductionRequestInterface
{
    /**
     * @return int
     */
    public function getWebsiteId(): int;

    /**
     * @return string
     */
    public function getSourceCode(): string;

    /**
     * @return ItemToDeductInterface[]
     */
    public function getItems(): array;

    /**
     * @return SalesEventInterface
     */
    public function getSalesEvent(): SalesEventInterface;
}

```

WebsiteId -> SalesChannelId

all usages of WebsiteId should be eliminated from interfaces.

Btw, why did we change StockId to WebsiteId?

**Comment by seruymt** [comment]
@maghamed Probably you mean SalesChannelInterface, because we haven't SalesChannelId
so, 
WebsiteId -> SalesChannelInterface

**Comment by maghamed** [comment]
@seruymt yes, you are correct
