### ISSUE TITLE
Remove explicit Sequence tables generation in fixture Magento/InventorySalesApi/Test/_files/websites_with_stores.php

### ISSUE THREAD

**Issue by p-bystritsky** [magento/inventory#1054]
Remove explicit Sequence tables generation in fixture Magento/InventorySalesApi/Test/_files/websites_with_stores.php (added in https://github.com/magento-engcom/msi/pull/921/).

```
/**
 * \Magento\TestFramework\Application by default generates 10 Sequence tables of each kind
 * with indexes form 0 to 9, but last created Store id is greater than 9.
 */
$sequence->generateSequences($store->getId());

/* Refresh stores memory cache */
$objectManager->get(\Magento\Store\Model\StoreManagerInterface::class)->reinitStores();
```

**Comment by roma-glushko** [comment]
Just let you know that the point is being investigating. 
Without the line:
`$sequence->generateSequences($store->getId());`
We are having issue with running \Magento\InventoryShipping\Test\Integration\SourceDeductionForVirtualProductsOnMultiStockTest 
It could not generate invoices for orders.
This issue occurs when msi testsuite is executed.

However, the issue doesn't occur if the test class is executed only. 

Probably there is a dependency in the testsuite that is an obstacle to execute the test class.
Keep you posted on progress in the task.
Thanks.

**Comment by naydav** [comment]
`\Magento\InventoryShipping\Test\Integration\SourceDeductionForVirtualProductsOnMultiStockTest` marked as skipped
Need to find the more proper solution for work sequence then
```
/**
 * \Magento\TestFramework\Application by default generates 10 Sequence tables of each kind
 * with indexes form 0 to 9, but last created Store id is greater than 9.
 */
$sequence->generateSequences($store->getId());

/* Refresh stores memory cache */
$objectManager->get(\Magento\Store\Model\StoreManagerInterface::class)->reinitStores();
```
