### ISSUE TITLE
'NoSuchEntityException' even when full reindex was performed after website code was modified

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/inventory#1059]
### Preconditions
1. Magento MSI

### Steps to reproduce
1. Navigate to Stores > Settings > All Stores and create Website with Store and Store View using data from the table:
```
+-------------+--------------------+--------------------+
|             |        Name        |        Code        |
+-------------+--------------------+--------------------+
| Website:    | Test Website       | additional         |
| Store:      | Test Website Store | test_website_store |
| Store View: | Test Store View    | test               |
+-------------+--------------------+--------------------+
```
2. Navigate to Stores > Settings > Manage Sources and create one Source
3. Navigate to Stores > Settings > All Stores and change Website `code` from "additional" to "test"
4. Press F12 in the User Agent
5. Navigate to Stores > Settings > Manage Stocks

### Expected result
1. Stocks Grid is rendered and Admin User can create Stocks using UI

### Actual result
1. Error in the User Agent Console
```
actions.js:104 Uncaught TypeError: Cannot read property 'map' of undefined
    at UiClass.updateActions (actions.js:104)
    at setNested (objects.js:43)
    at Object.nested (objects.js:117)
    at UiClass.set (element.js:305)
    at updateValue (links.js:80)
    at events.js:87
    at Array.forEach (<anonymous>)
    at trigger (events.js:84)
    at UiClass.trigger (events.js:162)
    at UiClass.<anonymous> (element.js:424)
```
2. NoSuchEntityException is thrown
3. User cannot see the Grid with Stocks and perform any actions with Stocks
![actual](https://user-images.githubusercontent.com/11827230/39585060-916042be-4efc-11e8-9e57-a8ccdad0befd.png)

**Comment by phoenix128** [comment]
Fixed by https://github.com/magento-engcom/msi/pull/1344 .

**Comment by TomashKhamlai** [comment]
Related to #1386

**Comment by TomashKhamlai** [comment]
Related to #1401

**Comment by naydav** [comment]
Fixed in https://github.com/magento-engcom/msi/pull/1344
