### ISSUE TITLE
Divide Magento\InventoryCatalog\Model\StockSourceLink\Validator\AssignToDefaultStockDefaultSourceValidator into two separate validators.

### ISSUE THREAD

**Issue by nmalevanec** [magento/inventory#1062]
Currently https://github.com/magento-engcom/msi/blob/d961c54914febd4a823be7e67ec388747d527fd3/app/code/Magento/InventoryCatalog/Model/StockSourceLink/Validator/AssignToDefaultStockDefaultSourceValidator.php#L17 violates single responsibility principle.
Should be divided into two separate validators:
default stock validator: AssignNonDefaultSourceToDefaultStockValidator
default source validator: AssignDefaultSourceToNonDefaultStockValidator

**Comment by larsroettig** [comment]
@maghamed is Issue still relevant I think two separated validator will not check the same.  This issue was created bevor the last refactoring.
