### ISSUE TITLE
Change format of Reservation metadata to JSON

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#1071]
Change format of Reservation metadata to JSON.

That will add an ability to support MySQL 5.7 JSON Type 
https://dev.mysql.com/doc/refman/5.7/en/json.html
having indexes on JSON nested values

Use `\Magento\Framework\Serialize\Serializer\Json` for these purposes 

Now I am getting approval to drop support of MySQL 5.6 in Magento 2.3

**Comment by maghamed** [comment]
There is a blocker currently, because Magento 2.3 still supports MySQL 5.6

The decision to drop 5.6 has not made yet

**Comment by aleron75** [comment]
Which is the format we want to obtain @maghamed ?

Example 1: json array:
```
["shipment_created","order",1]
```

Example 2: json object:
```
{"event_type":"shipment_created","object_type":"order","object_id":1}
```

Other ideas?

**Comment by maghamed** [comment]
Looks good to me
```
{"event_type":"shipment_created", "object_type":"order", "object_id":1}
```

@seruymt  do you have concerns from your side?

**Comment by kirill533** [comment]
Please, revise the topic of Normalization in DBMS. The decision discussed here is against the First Normal Form: Each table cell should contain a single value. There are good reasons, why it is advisable to follow the Normalization rules while modeling the DBMS tables.
