### ISSUE TITLE
Add missing steps and correct description to MFTF test for HipTest scenario 1695735.

### ISSUE THREAD

**Issue by nmalevanec** [magento/inventory#1100]
As, initially I misunderstood steps from HipTest scenario 1695735, AdminConfigurableProductManageStockOnDefaultStock.xml test has incorrect name, description and missed some steps, related to adjusting "Manage Stock" configuration.
Initial pull request: magento-engcom/msi#1030

**Comment by ivy00johns** [comment]
Merged to Mainline.
