### ISSUE TITLE
Move Api\AppendReservationsInterface and Api\ReservationBuilderInterface to Model namespace

### ISSUE THREAD

**Issue by naydav** [magento/inventory#1105]
We considered that `\Magento\InventoryReservationsApi\Api\AppendReservationsInterface`  and `\Magento\InventoryReservationsApi\Api\ReservationBuilderInterface` should be called under the hood of more high-level services (OrderPlace, OrderCancel)

According to introducing `Model` namespace, we need to move corresponding interfaces in the new namespace

**Comment by naydav** [comment]
@maghamed 
Do we need to move `\Magento\InventoryReservationsApi\Api\Data\ReservationInterface`  to `Model` namespace?

**Comment by maghamed** [comment]
@naydav yes
