### ISSUE TITLE
Resolve dependency InventoryCatalog module on Inventory

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#1118]
InventoryCatalog should use InventoryApi module only

**Comment by VitaliyBoyko** [comment]
Hi @maghamed 
Seams like InventoryApi does not have all required methods.
For example `Magento\InventoryCatalog\Setup\Operation\AssignDefaultSourceToDefaultStock::execute` use `Magento\Inventory\Model\ResourceModel\StockSourceLink\SaveMultiple::execute` directly to avoid validation for source links during installation. Do we have API contract in InventoryApi to perform this action?
