### ISSUE TITLE
Fix Functional Test Magento\Checkout\Test\TestCase\OnePageCheckoutOfflinePaymentMethodsTest::test with data set "OnePageCheckoutTestVariation4_0"

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/inventory#1188]
### Preconditions
1. Magento 2

### Steps to reproduce
1. Run Functional Test Magento\Checkout\Test\TestCase\OnePageCheckoutOfflinePaymentMethodsTest::test with data set "OnePageCheckoutTestVariation4_0" with data set OnePageCheckoutUsingNewAddress_0

### Expected result
1. The test should pass successfully.

### Actual result
1. Error occurred on attempt to get element. Message: "Timed out after 180 seconds". Locator: "css selector(#checkout-step-shipping)" . Wait: "1"

The test is passing on local env.

**Comment by nmalevanec** [comment]
Duplicate magento-engcom/msi#1217
