### ISSUE TITLE
Fix Functional Test Magento\Checkout\Test\TestCase\OnePageCheckoutTest::test with data set "OnePageCheckoutUsingNewAddress_0" 

### ISSUE THREAD

**Issue by p-bystritsky** [magento/inventory#1189]
### Preconditions
1. Magento 2

### Steps to reproduce

1. Run Functional Test Magento\Checkout\Test\TestCase\OnePageCheckoutTest::test with data set "OnePageCheckoutUsingNewAddress_0" 

### Expected result

1. Test should pass successfully.

### Actual result

1. PHPUnit_Extensions_Selenium2TestCase_WebDriverException: Error occurred on attempt to get element. Message: "Timed out after 180 seconds". Locator: "css selector(#checkout-step-shipping)" . Wait: "1"

### Note
Issue is caused by Magento core. After adding new shipping address:
Magento 2.2: 
![image](https://user-images.githubusercontent.com/22593218/40172614-d2a11074-59d7-11e8-803c-cfa2430f1995.png)

Magento 2.3: 
![image](https://user-images.githubusercontent.com/22593218/40172619-d8f8714c-59d7-11e8-9daa-b9deb4001859.png)

**Comment by ishakhsuvarov** [comment]
Currently test seems to be passing on CI. Closing.
