### ISSUE TITLE
Fix Functional Test Magento\Sales\Test\TestCase\CreateOrderBackendPartOneTest::test with data set "CreateOrderBackendTestVariation1_0"

### ISSUE THREAD

**Issue by p-bystritsky** [magento/inventory#1190]
### Preconditions
1. Magento 2

### Steps to reproduce

1. Run Functional Test Magento\Sales\Test\TestCase\CreateOrderBackendPartOneTest::test with data set "CreateOrderBackendTestVariation1_0"

### Expected result

1. Test should pass successfully.

### Actual result

1. Form data not equals to passed from fixture:
quantity_and_stock_status:
	- qty: "63" instead of "62"
Failed asserting that false is true.

### Note
In Magento without MSI products are deducted from Stock immediately after Order is placed, but in Magento with MSI only after Order is shipped / invoiced.

**Comment by p-bystritsky** [comment]
Should be fixed in https://github.com/magento-engcom/msi/issues/1164

**Comment by ishakhsuvarov** [comment]
Fixed in https://github.com/magento/magento2/pull/16153
