### ISSUE TITLE
Installation B2b with MSI fails

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1198]
Installation B2b with MSI fails

Schema creation/updates:
[ERROR] ReflectionException: Class Magento\Framework\Setup\Declaration\Schema\Db\MySQL\DDL\Triggers\MigrateSequenceColumnData does not exist in /var/www/html/magento2ce/msi4/lib/internal/Magento/Framework/Code/Reader/ClassReader.php:19
Stack trace:
#0 /var/www/html/magento2ce/msi4/lib/internal/Magento/Framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('Magento\\Framewo...')
#1 /var/www/html/magento2ce/msi4/lib/internal/Magento/Framework/ObjectManager/Definition/Runtime.php(49): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\\Framewo...')
#2 /var/www/html/magento2ce/msi4/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(48): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Magento\\Framewo...')
#3 /var/www/html/magento2ce/msi4/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#4 /var/www/html/magento2ce/msi4/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(180): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#5 /var/www/html/magento2ce/msi4/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(156): Magento\Framework\ObjectManager\Factory\AbstractFactory->parseArray(Array)
#6 /var/www/html/magento2ce/msi4/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(230): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, NULL, Array, 'triggers', 'Magento\\Framewo...')
#7 /var/www/html/magento2ce/msi4/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Framewo...', Array, Array)
#8 /var/www/html/magento2ce/msi4/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#9 /var/www/html/magento2ce/msi4/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#10 /var/www/html/magento2ce/msi4/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(144): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#11 /var/www/html/magento2ce/msi4/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(230): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'createTable', 'Magento\\Framewo...')
#12 /var/www/html/magento2ce/msi4/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Framewo...', Array, Array)
#13 /var/www/html/magento2ce/msi4/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#14 /var/www/html/magento2ce/msi4/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#15 /var/www/html/magento2ce/msi4/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(180): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#16 /var/www/html/magento2ce/msi4/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(156): Magento\Framework\ObjectManager\Factory\AbstractFactory->parseArray(Array)
#17 /var/www/html/magento2ce/msi4/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(230): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, NULL, NULL, 'operations', 'Magento\\Framewo...')
#18 /var/www/html/magento2ce/msi4/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Framewo...', Array, Array)
#19 /var/www/html/magento2ce/msi4/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#20 /var/www/html/magento2ce/msi4/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#21 /var/www/html/magento2ce/msi4/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(144): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#22 /var/www/html/magento2ce/msi4/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(230): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'operationsExecu...', 'Magento\\Framewo...')
#23 /var/www/html/magento2ce/msi4/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Framewo...', Array, Array)
#24 /var/www/html/magento2ce/msi4/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#25 /var/www/html/magento2ce/msi4/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#26 /var/www/html/magento2ce/msi4/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(144): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#27 /var/www/html/magento2ce/msi4/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(230): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'schemaDiff', 'Magento\\Setup\\M...')
#28 /var/www/html/magento2ce/msi4/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Setup\\M...', Array, Array)
#29 /var/www/html/magento2ce/msi4/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Setup\\M...', Array, Array)
#30 /var/www/html/magento2ce/msi4/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Setup\\M...')
#31 /var/www/html/magento2ce/msi4/setup/src/Magento/Setup/Model/Installer.php(392): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Setup\\M...')
#32 /var/www/html/magento2ce/msi4/setup/src/Magento/Setup/Model/Installer.php(807): Magento\Setup\Model\Installer->getDeclarationInstaller()
#33 /var/www/html/magento2ce/msi4/setup/src/Magento/Setup/Model/Installer.php(824): Magento\Setup\Model\Installer->declarativeInstallSchema(Array)
#34 [internal function]: Magento\Setup\Model\Installer->installSchema(Array)
#35 /var/www/html/magento2ce/msi4/setup/src/Magento/Setup/Model/Installer.php(366): call_user_func_array(Array, Array)
#36 /var/www/html/magento2ce/msi4/setup/src/Magento/Setup/Controller/Install.php(109): Magento\Setup\Model\Installer->install(Array)
#37 /var/www/html/magento2ce/msi4/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(84): Magento\Setup\Controller\Install->startAction()
#38 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#39 /var/www/html/magento2ce/msi4/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#40 /var/www/html/magento2ce/msi4/vendor/zendframework/zend-eventmanager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#41 /var/www/html/magento2ce/msi4/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#42 /var/www/html/magento2ce/msi4/vendor/zendframework/zend-mvc/src/DispatchListener.php(118): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#43 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#44 /var/www/html/magento2ce/msi4/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#45 /var/www/html/magento2ce/msi4/vendor/zendframework/zend-eventmanager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#46 /var/www/html/magento2ce/msi4/vendor/zendframework/zend-mvc/src/Application.php(340): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#47 /var/www/html/magento2ce/msi4/setup/index.php(39): Zend\Mvc\Application->run()
#48 {main}

**Comment by maghamed** [comment]
Can you please provide more details @smoskaluk ?
