### ISSUE TITLE
Cannot place order with configurable product on single stock mode.

### ISSUE THREAD

**Issue by nmalevanec** [magento/inventory#1209]
### Preconditions
1. Magento with enabled MSI in single stock mode.

### Steps to reproduce
1. Login to admin area.
2. Navigate to Catalog > Products.
3. Start creating configurable product.
4. Fill necessary data:
Product Name: "configurable product"
SKU: configurable product
Price: 3
5. Start creating configurations.
6. At "Select Attributes" step select color attribute.
7. At "Attribute Value" step create two options: "blue" and "red".
8. At "Bulk Images & Price" step check "Apply single quantity to each SKUs" , set quantity to 100.
15. Generate products.
16. Set some weight for generated products.
17. Save configurable.
18. Navigate to storefront, configurable product view page 
19. Add some configurable product option to cart.
20. Proceed to checkout.
21. Try to place order

### Expected result
1. Order placed successfully.

### Actual result
1. "Can't check requested quantity for products without Source items supporting." error message appears.

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/1242

**Comment by lucasvm** [comment]
Hello, is there a fix for this? im getting this error on a Magento 2.3 site when access to admin area -> Products view i can´t list the products, im getting "Can't check requested quantity for products without Source Items support." 
Is this a Magento error?
