### ISSUE TITLE
Cover with Integration Tests Order Placement for Grouped product on Default Stock

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#1215]
Cover with Integration Tests Order Placement for the Grouped product on Default Stock in Single Source Mode

we already have similar tests covering functionality for Simple Product in
`Magento\InventorySales\Test\Integration\Order\*`

New tests should be placed into the InventoryGroupedProduct module

**Comment by ishakhsuvarov** [comment]
Done in #1245
