### ISSUE TITLE
 Decrease CatalogInventory/Model/Quote/Item/QuantityValidator::validate() time execution.

### ISSUE THREAD

**Issue by nmalevanec** [magento/inventory#1217]
### Preconditions
1. Magento with MSI in single stock mode.
2.  Firefox 45.0

### Steps to reproduce
1. Run `Magento\Checkout\Test\TestCase\OnePageCheckoutOfflinePaymentMethodsTest::OnePageCheckout` TestVariation4 couple times.

### Expected result
1. Test should pass successfully

### Actual result
2. Test fails most of the time.

### Manual steps Firefox 45.0
1. Navigate to admin area.
2. Create simple and configurable products.
3. Navigate to storefront.
3. Create customer without addresses.
4. Add two products to cart as a guest.
5. Proceed to checkout.
6. On 'Shipping Step' login as created customer.

### Expected result
1. Login is successful. There is ability to proceed further to place order.

### Actual result
2. Redirect to customer login page.

### Additional info
On mainline `CatalogInventory/Model/Quote/Item/QuantityValidator::validate()` in overall process takes around 0.04 seconds. On 2.3-develop MSI branch - 0.617
Looks like we need to rework `AdaptGetStockStatusPlugin.php`, `AdaptGetStockStatusBySkuPlugin.php`, `AdaptGetProductStockStatusPlugin.php` and `AdaptGetProductStockStatusBySkuPlugin.php` to decrease overall time `CatalogInventory/Model/Quote/Item/QuantityValidator::validate()` takes.

**Comment by maghamed** [comment]
Internal issues 
https://jira.corp.magento.com/browse/MAGETWO-91293
https://jira.corp.magento.com/browse/MAGETWO-93111
