### ISSUE TITLE
Can't delete the product that is assigned to Additional Stock when Additional Stock is the Sales Channel for the Main Website

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/inventory#1234]
### Preconditions
1. Magento MSI with EE

### Steps to reproduce
1. Login to backend as admin
2. Go to Stores -> Manage Sources
3. Click button "Add New Source"
4. Fill New Source data in General tab - Name, Code etc:
 - > name = Test Source 1
 - > code = test_source_1
5. Set your New Source "Is Enabled" = Yes
6. Fill all fields with data of your New Source in Contact Info tab
7. Fill in address data of your New Source in Address Data tab:
 - > Country: United States
 - > State/Province: California (CA)
 - > City: Culver City
 - > Street: 6161 West Centinela Avenue
 - > Postсode: 90230
8. Set In "Carriers" tab "Use global Shipping configuration" to Yes
9. Click button "Save & close"
10. Go to Stores -> Manage Stocks
11. Click button "Add New Stock"
12. Fill in field "Name" = "Test Stock 1"
13. In "Sales Channels" Tab select website "Main Website"
14. Click button "Assign Sources" In "Sources" Tab
15. In the modal window "Assign Sources" select "Test Source 1" in the sources list
16. Click button "Done"
20. Click button "Save & close"
21. Go to Catalog -> Categories
22. Select Default Category on Categories Tree
23. Click button "Add Subcategory"
24. Set "Enable Category" to "Yes"
25. Set "Include in Menu" to "Yes"
26. Fill in "Category Name" = "Category 1"
27. Click button "Save"
28. Go to Catalog -> Products
29. Click button "Add Simple product"
30. Set "Enable Product" to "Yes"
31. Fill Name = "Simple Product 1"
32. Set Price = "10"
33. Set Weight = "1"
34. Select Category = "Category 1"
35. Click button "Assign Sources"
36. Select in sources grid "Test Source 1" and click "Done"
37. in "Assigned Sources" grid set  Qty for "Test Source 1"  = 100
38. in "Product in Websites" tab  select "Main Website"
39. Click 'Save and Close' button
40. In the Products Grid tick the box next to the product field and select 'Delete' action from the mass-action dropdown.

### Expected result
1. The product was successfully removed

### Actual result
1. Exception in `var/report/`:
```
{"0":"The \"Simple Product 1\" product couldn't be removed.","1":"#0 \/app\/vendor\/magento\/module-catalog\/Controller\/Adminhtml\/Product\/MassDelete.php(64): Magento\\Catalog\\Model\\ProductRepository->delete(Object(Magento\\Catalog\\Model\\Product\\Interceptor))\n#1 \/app\/vendor\/magento\/framework\/App\/Action\/Action.php(107): Magento\\Catalog\\Controller\\Adminhtml\\Product\\MassDelete->execute()\n#2 \/app\/vendor\/magento\/module-backend\/App\/AbstractAction.php(229): Magento\\Framework\\App\\Action\\Action->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#3 \/app\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Backend\\App\\AbstractAction->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#4 \/app\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Catalog\\Controller\\Adminhtml\\Product\\MassDelete\\Interceptor->___callParent('dispatch', Array)\n#5 \/app\/vendor\/magento\/module-backend\/App\/Action\/Plugin\/Authentication.php(143): Magento\\Catalog\\Controller\\Adminhtml\\Product\\MassDelete\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#6 \/app\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch(Object(Magento\\Catalog\\Controller\\Adminhtml\\Product\\MassDelete\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#7 \/app\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Catalog\\Controller\\Adminhtml\\Product\\MassDelete\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#8 \/app\/generated\/code\/Magento\/Catalog\/Controller\/Adminhtml\/Product\/MassDelete\/Interceptor.php(26): Magento\\Catalog\\Controller\\Adminhtml\\Product\\MassDelete\\Interceptor->___callPlugins('dispatch', Array, NULL)\n#9 \/app\/vendor\/magento\/framework\/App\/FrontController.php(55): Magento\\Catalog\\Controller\\Adminhtml\\Product\\MassDelete\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#10 \/app\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Framework\\App\\FrontController->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#11 \/app\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Framework\\App\\FrontController\\Interceptor->___callParent('dispatch', Array)\n#12 \/app\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#13 \/app\/generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php(26): Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins('dispatch', Array, Array)\n#14 \/app\/vendor\/magento\/framework\/App\/Http.php(135): Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#15 \/app\/vendor\/magento\/framework\/App\/Bootstrap.php(256): Magento\\Framework\\App\\Http->launch()\n#16 \/app\/pub\/index.php(37): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#17 {main}","url":"\/index.php\/admin\/catalog\/product\/massDelete\/key\/0f78557a45f4f852c9c807e879832bf17be5b72507e82b25562de23f5fc38a2c\/","script_name":"\/index.php"}
```

**Comment by TomashKhamlai** [comment]
Workaround:
Switch to Default Stock (make it as Sales Channel for the Main Website)
Disable Test Source
Remove any products without any error

**Comment by daniloargentiero** [comment]
Unable to reproduce.

I followed all steps, but n°8 (Set In "Carriers" tab "Use global Shipping configuration" to Yes), because "Carriers" tab was removed in commit dc9d40ef748b

In my case, the product was successfully removed.

**Comment by TomashKhamlai** [comment]
@DaniloEmpire, excuse me, it is my mistake. This issue is reproducible when Magento MSI is combined with Magento Commerce modules as it was mentioned in #873 

The description of the issue was updated.

**Comment by boldbart** [comment]
I'm experiencing the same issue (Magento 2.3 EE and MSI).

**Comment by staywithabhi** [comment]
i am also getting the same issue in magento 2.3.1
