### ISSUE TITLE
Export file "Stock Sources" contains sources from deleted products.

### ISSUE THREAD

**Issue by nmalevanec** [magento/inventory#1237]
### Preconditions
1. Magento with MSI

### Steps to reproduce
1. Navigate to admin area.
2. Navigate to Stores > Manage Sources.
3. Add new custom Source.
4. Navigate to Stores > Manage Stocks.
5. Create new custom Stock.
6. Assign "Main Website" as sales channel to created custom stock.
7. Assign custom source to custom stock.
8. Perform reindex.
9. Navigate to Catalog > Products.
10. Create two simple products sku='simple product 1' and 'simple product 2' respectively.
11. Assign 'default' and 'custom source' to both products with qty = 100.
12. Navigate to Catalog >Products.
13. Select 'simple product 1' in product grid and delete it.
14. Navigate to System > Export.
15. Select "Entity Type" = "Stock Sources" and press "continue" button.
16. Check export file.

### Expected result
1. Export file should contain sources only for product with sku 'simple product 2'.

### Actual result
1. Export file contains sources for both, deleted 'simple product 1' and existing 'simple product 2'.

**Comment by maghamed** [comment]
not a bug.
By design behaviour
