### ISSUE TITLE
Simple product visible on category page and has "In Stock" status after all it's qty was bought.

### ISSUE THREAD

**Issue by nmalevanec** [magento/inventory#1239]
### Preconditions

1. Magento with MSI on cloud.

### Steps to reproduce

1. Login to admin area.
2. Navigate to Stores > Manage Sources.
3. Create new custom source.
4. Navigate to Stores > Manage Stocks.
5. Create new custom stock.
6. Assign "Default Website" to created custom stock as sales channel.
7. Assign created custom source to custom stock.
8. Navigate to Catalog > Products.
9. Create simple product and assign to some category.
10. Assign custom source with qty = 100 to simple product.
11. Navigate to storefront.
12. Buy 100 pieces of created simple product.
13. Proceed to checkout and place order.
14. Navigate to simple product category page.
15. Navigate to simple product view page.

### Expected result

1. Simple product is absent on category page.
2. Simple product has "Out of Stock" status on product view page.

### Actual result

1. Simple product is present on category page.
2. Simple product has "In Stock" status on product view page.

**Comment by maghamed** [comment]
It's by design,
as we don't apply Reservations for Category Page and Search Result page for better performance.

Along with that reservations would be applied on Product page and at the time product would be added to shopping cart (mini shopping cart)
