### ISSUE TITLE
Credit memo with return to stock works incorrect.

### ISSUE THREAD

**Issue by RomaKis** [magento/inventory#1240]
### Preconditions
1. Magento 2 installed with MSI.
2. Create Virtual Product with qty 100.
3. Make an Order and buy 5 virtual products.
4. Create Invoice. 

### Steps to reproduce
1. Go to Sales -> Order.
2. Press "Credit memo" button.
3. In "Items to Refund" field check "Return to Stock".
4. Click Refund.
5. Open Virtual Product.

### Expected result
1. Qty: 100.
2. Salable qty: 100

### Actual result
1. Qty: 95.
2. Salable qty: 100

**Comment by Jupagar77** [comment]
This exact same error is happening when using refund rest endpoints and sending the return to stock items:
```
    "arguments": {
        "extension_attributes": {
            "return_to_stock_items": [....]
        }
    }
```
