### ISSUE TITLE
Configurable product is "In Stock" on Storefront while all it's children are disabled.

### ISSUE THREAD

**Issue by p-bystritsky** [magento/inventory#1241]
### Steps to reproduce

1. Create Custom Source.
2. Create Custom Stock, assign Custom Source and Main Website to it.
3. Create Configurable Product with one Child.
4. Disable Child.
5. Open Configurable Product page on Storefront via direct link.

### Expected result

1. Configurable Product has Status "Out of Stock".

### Actual result

1. Configurable Product has Status "In Stock".

**Comment by maghamed** [comment]
As it was discussed in issues:
#856  and #904 
This is not an MSI bug, https://github.com/magento-engcom/msi/issues/856#issuecomment-392030116

This issue should be solved on the level of Configurable product configuration
