### ISSUE TITLE
Prevent Disabling Default Source by Disabling 'Is Enabled' Switcher

### ISSUE THREAD

**Issue by AleksLi** [magento/inventory#1250]
### Preconditions

1. Magento with MSI.

### Steps to reproduce

1. Go to Manage Sources
2. Open Disable Source

### Expected result

<img width="1221" alt="screenshot 2018-05-24 23 30 51" src="https://user-images.githubusercontent.com/10618641/40559897-f7a1408a-6060-11e8-8356-fa6d963e84a8.png">

### Actual result

1. You can disable Default Source using Switcher. Switcher is Enabled for User

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/1410
