### ISSUE TITLE
Incorrect Quantity calculation for orders with Configurable products.

### ISSUE THREAD

**Issue by p-bystritsky** [magento/inventory#1266]
### Preconditions

1. Magento with MSI.

### Steps to reproduce

1. Create Custom Source.
2. Create Custom Stock, assign Custom Source and Default Sales Channel to it.
3. Create Configurable Product with Subproduct.
4. Set Subproduct quantity on Custom Source to 100.
5. Go to the Storefront, buy all quantity of Subproduct.
6. Ship & Invoice Order created in step 5.
7. Open Products grid in Admin.

### Expected result

1. Subproducts Quantity on Custom Source = 0
2. Subproducts Salable Quantity on Custom Stock = 0

### Actual result

1. Subproducts Quantity on Custom Source = 100
2. Subproducts Salable Quantity on Custom Stock = 100

### Note 
Issue found on cloud instance https://msi-regression-3-wqbsz5a-aqldk5bfo7sai.us.magentosite.cloud

**Comment by maghamed** [comment]
Can't reproduce the current issue locally on branch 2.3-develop

**Comment by smoskaluk** [comment]
Can't reproduce on local instance MSI with EE
