### ISSUE TITLE
Source items left after products been deleted.

### ISSUE THREAD

**Issue by IvanPletnyov** [magento/inventory#1273]
### Preconditions

1. Magento with MSI.

### Steps to reproduce

1. Navigate to admin area.
2. Navigate to Catalog > Products.
3. Create new simple product qty = 100.
4. Perform reindex.
5. Make API request GET http://domain/rest/all/V1/inventory/source-item with params
searchCriteria[filterGroups][0][filters][0][field] = 'source_code'
searchCriteria[filterGroups][0][filters][0][value] = 'default'
6. Check, response returns one result.
7. Navigate to product grid.
8. Select and delete created simple product.
9. Make API request GET http://domain/rest/all/V1/inventory/source-item with params
searchCriteria[filterGroups][0][filters][0][field] = 'source_code'
searchCriteria[filterGroups][0][filters][0][value] = 'default'

### Expected result

1. Response contains zero results.

### Actual result

1. Response contains deleted simple product.

**Comment by maghamed** [comment]
Duplicate #1237 
#1256
