### ISSUE TITLE
Change Default state of "Notify Quantity Use default" checkbox on "checked" the first time user assigns sources to a product

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#1282]
### Preconditions

1. Multiple Custom Sources created 

### Steps to reproduce

1. When a user creates a new product and assigns Sources to it 
2. There are two fields "Notify Quantity" and "Notify Quantity Use default" available
3. When a user assigns sources for the first time both of the fields are empty 
4. And when a user saves the product "Notify Quantity" becomes "0.0000"

### Expected result

1. Default state ideally should be "Notify Quantity Use default" checkbox checked the first time we assign source

### Actual result

1.  When a user assigns sources for the first time both of the fields are empty

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/1428
