### ISSUE TITLE
Renaming website breaks MSI grid

### ISSUE THREAD

**Issue by paales** [magento/inventory#1306]
### Preconditions
1. Latest 2.3-develop branch as of 4 june. https://github.com/magento-engcom/msi/commit/36c638ec91d23694fed6246a48a0e2770ccdbac9

### Steps to reproduce

1. Install module
2. Rename the 'base' website to something different.

### Expected result
1. Everything keeps working.

### Actual result

![schermafbeelding 2018-06-05 om 10 06 58](https://user-images.githubusercontent.com/1244416/40963568-3c77b8b0-68a9-11e8-8905-b7545faa69e6.png)

Fault seems to be in the `inventory_stock_sales_channel` table, it still has the old website code.

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/1344

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/1356

**Comment by TomashKhamlai** [comment]
Duplicate of #1059
