### ISSUE TITLE
Simple product assigned to Test source after schedule update applied got assigned to Default source

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1310]
### Preconditions

1. Magento EE with MSI installed
2. Test stock with Test Source created and assigned to Main Website

### Steps to reproduce

1. Simple product created and assigned to Test source with qty= 100
2. Shedule update created for this product to update its name and price with some start and end time and date
3. Wait till start time and run cron twice

### Expected result

1.  Products name and price updated properly

### Actual result

1.  Product got assigned to Default source with Qty = 0 and stock status 'Out of stock'

**Comment by naydav** [comment]
Fixed in 
https://github.com/magento-engcom/msi/pull/1371
