### ISSUE TITLE
Fix Magento\Sales\Service\V1\ShipmentGetTest::testShipmentGet

### ISSUE THREAD

**Issue by p-bystritsky** [magento/inventory#1336]
### Preconditions

1. Magento 2 with MSI.

### Steps to reproduce

1. Run test Magento\Sales\Service\V1\ShipmentGetTest::testShipmentGet.

### Expected result

1. Test run finished without any errors.

### Actual result

1. Test run fails.

### Note 
Fail is caused by direct comparison of "extension_attributes" field of Shipment record loaded from database and Shipment information returned by API call. 

![image](https://user-images.githubusercontent.com/22593218/41159514-6dc4d7fc-6b35-11e8-8da7-cea5ea68a010.png)

**Comment by denteblu** [comment]
already in progress in #1155

**Comment by ishakhsuvarov** [comment]
Fixed in 
https://github.com/magento-engcom/msi/pull/1350
https://github.com/magento/magento2/pull/15982
