### ISSUE TITLE
Cannot create shipment via REST API.

### ISSUE THREAD

**Issue by nmalevanec** [magento/inventory#1337]
### Preconditions

1. Magento with MSI.
2. Single stock mode.

### Steps to reproduce

1. Navigate to admin area Catalog > Products.
2. Create simple product SKU = 'simple', Name = 'simple', Price = '10', Quantity = '100
3. Navigate to storefront.
4. Buy one piece of created simple product and create order.
5. Make REST API request with admin token GET http://domain/rest/V1/orders/{created_order_id} to get order item id..
6. Make REST API request with admin token POST http://domain/rest/V1/shipment
body: 
`{
  "entity": {
    "order_id": "{created_order_id}",
    "entity_id": null,
    "store_id": null,
    "total_weight": null,
    "total_qty": null,
    "email_sent": null,
    "customer_id": null,
    "shipping_address_id": null,
    "billing_address_id": null,
    "shipment_status": null,
    "increment_id": null,
    "created_at": null,
    "updated_at": null,
    "shipping_label": null,
    "tracks": [
      {
        "carrier_code": "UPS",
        "order_id": "5",
        "title": "ground",
        "description": null,
        "track_number": "12345678",
        "parent_id": null,
        "created_at": null,
        "updated_at": null,
        "qty": null,
        "weight": null
      }
    ],
    "items": [
      {
        "order_item_id": "{order_item_id_from_step_5}",
        "qty": "1.0000",
        "additional_data": null,
        "description": null,
        "entity_id": null,
        "name": null,
        "parent_id": null,
        "price": null,
        "product_id": null,
        "row_total": null,
        "sku": null,
        "weight": null
      }
    ],
    "comments": [
      {
        "comment": "Shipment-related comment.",
        "is_customer_notified": null,
        "is_visible_on_front": null,
        "parent_id": null
      }
    ]
  }
}`

### Expected result

1. Shipment created successfully.

### Actual result

1. {"messages":{"error":[{"code":500,"message":"Server internal error. See details in report api\/some_report_number"}]}}
2. Error is: PHP Fatal error: Uncaught Error: Call to a member function getSourceCode() on null in /var/www/html/msi/app/code/Magento/InventoryShipping/Observer/SourceDeductionProcessor.php on line 114

### Details
https://github.com/magento-engcom/msi/blob/dccea5c2887ebd7b436a9eceaa342e9fe41b3a80/app/code/Magento/InventoryShipping/Observer/SourceDeductionProcessor.php#L114 fails with such condition structure in case shipment has no extension attributes.

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/1338
