### ISSUE TITLE
Error during mass action 'delete' on products grid with product on Test stock MSI + EE 

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1385]
### Preconditions

1. Magento MSI + EE
2. Test stock with test source created and assigned to Main website
3. Create product and assign it to Test source with qty= 10

### Steps to reproduce

1. Navigate to Products grid in admin
2. Select your product in the grid
3. Choose mass action 'Delete' and click 'Ok" to comfirm deletion

### Expected result

1.  Product should be deleted 

### Actual result

There has been an error processing your request

{"0":"The \"sim1\" product couldn't be removed.","1":"#0 \/var\/www\/html\/magento2ce\/msiee\/generated\/code\/Magento\/Catalog\/Model\/ProductRepository\/Interceptor.php(63): Magento\\Catalog\\Model\\ProductRepository->delete(Object(Magento\\Catalog\\Model\\Product\\Int
erceptor))\n#1 \/var\/www\/html\/magento2ce\/msiee\/app\/code\/Magento\/Catalog\/Controller\/Adminhtml\/Product\/MassDelete.php(64): Magento\\Catalog\\Model\\ProductRepository\\Interceptor->delete(Object(Magento\\Catalog\\Model\\Product\\Interceptor))\n#2 \/var\/www\/htm
l\/magento2ce\/msiee\/generated\/code\/Magento\/Catalog\/Controller\/Adminhtml\/Product\/MassDelete\/Interceptor.php(24): Magento\\Catalog\\Controller\\Adminhtml\\Product\\MassDelete->execute()\n#3 \/var\/www\/html\/magento2ce\/msiee\/lib\/internal\/Magento\/Framework\/A
pp\/Action\/Action.php(107): Magento\\Catalog\\Controller\\Adminhtml\\Product\\MassDelete\\Interceptor->execute()\n#4 \/var\/www\/html\/magento2ce\/msiee\/app\/code\/Magento\/Backend\/App\/AbstractAction.php(229): Magento\\Framework\\App\\Action\\Action->dispatch(Object(
Magento\\Framework\\App\\Request\\Http))\n#5 \/var\/www\/html\/magento2ce\/msiee\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(58): Magento\\Backend\\App\\AbstractAction->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#6 \/var\/www\/html\/m
agento2ce\/msiee\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(138): Magento\\Catalog\\Controller\\Adminhtml\\Product\\MassDelete\\Interceptor->___callParent('dispatch', Array)\n#7 \/var\/www\/html\/magento2ce\/msiee\/app\/code\/Magento\/Backend\/App\
/Action\/Plugin\/Authentication.php(143): Magento\\Catalog\\Controller\\Adminhtml\\Product\\MassDelete\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#8 \/var\/www\/html\/magento2ce\/msiee\/lib\/internal\/Magent
o\/Framework\/Interception\/Interceptor.php(135): Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch(Object(Magento\\Catalog\\Controller\\Adminhtml\\Product\\MassDelete\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#9
 \/var\/www\/html\/magento2ce\/msiee\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(153): Magento\\Catalog\\Controller\\Adminhtml\\Product\\MassDelete\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Ht
tp))\n#10 \/var\/www\/html\/magento2ce\/msiee\/generated\/code\/Magento\/Catalog\/Controller\/Adminhtml\/Product\/MassDelete\/Interceptor.php(39): Magento\\Catalog\\Controller\\Adminhtml\\Product\\MassDelete\\Interceptor->___callPlugins('dispatch', Array, NULL)\n#11 \/va
r\/www\/html\/magento2ce\/msiee\/lib\/internal\/Magento\/Framework\/App\/FrontController.php(55): Magento\\Catalog\\Controller\\Adminhtml\\Product\\MassDelete\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#12 \/var\/www\/html\/magento2ce\/msiee\
/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(58): Magento\\Framework\\App\\FrontController->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#13 \/var\/www\/html\/magento2ce\/msiee\/lib\/internal\/Magento\/Framework\/Interception\/Intercepto
r.php(138): Magento\\Framework\\App\\FrontController\\Interceptor->___callParent('dispatch', Array)\n#14 \/var\/www\/html\/magento2ce\/msiee\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(153): Magento\\Framework\\App\\FrontController\\Interceptor->Mag
ento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#15 \/var\/www\/html\/magento2ce\/msiee\/generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php(26): Magento\\Framework\\App\\FrontController\\Interceptor->___ca
llPlugins('dispatch', Array, Array)\n#16 \/var\/www\/html\/magento2ce\/msiee\/lib\/internal\/Magento\/Framework\/App\/Http.php(135): Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#17 \/var\/www\/html\/mag
ento2ce\/msiee\/generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php(24): Magento\\Framework\\App\\Http->launch()\n#18 \/var\/www\/html\/magento2ce\/msiee\/lib\/internal\/Magento\/Framework\/App\/Bootstrap.php(256): Magento\\Framework\\App\\Http\\Interceptor->
launch()\n#19 \/var\/www\/html\/magento2ce\/msiee\/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#20 {main}","url":"\/msiee\/admin\/catalog\/product\/massDelete\/key\/621a7996769357cc029727c38d82f775eeb9700439
5ff1d6704aeba88959f363\/","script_name":"\/msiee\/index.php"}

**Comment by TomashKhamlai** [comment]
Duplicates #1234
