### ISSUE TITLE
Add tooltip to Product grid as well as Product page describing what is "Salable Quantity"

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#1389]
Add tooltip to Product page describing what is "Salable Quantity"

Describe behavior with negative Min Qty Threshold 

**Tooltip for Salable Quantity**:
Aggregated inventory available to purchase for a stock. The amount aggregates assigned source's Quantity subtracting the Out-of-Stock Threshold (or MinQty)

**Comment by maghamed** [comment]
@lorikrell looks like we need your help here

**Comment by lorikrell** [comment]
@maghamed How is this? Trying to keep the content concise. If we end up renaming Out-of-Stock to Safety Quantity, that would need to be edited. You can also drop the content in ( ) to make it shorter.

Tooltip for Salable Quantity: 
Aggregated inventory available to purchase for a stock. The amount aggregates assigned source's Quantity subtracting the Out-of-Stock Threshold (or MinQty).
