### ISSUE TITLE
Magento logs out unexpectedly when you log in first time after reinstallation or after clean installation

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/inventory#1397]
### Preconditions
1. Magento MSI is installed (according to my scenario)
2. Magento MSI is not installed (you may try this also)

### Steps to reproduce
1. Remove some files from the previous installation, otherwise, you will get "Invalid Form Key. Please refresh the page." error. **It is not reproducible** when you get this error. I remove all files because I have no idea what exact file can preserve `Form Key` between installations. Remove that file or do what I do.
`git clean -xdf var/ pub/ app/etc/`
2. Reinstall Magento like this:
```shell
my_db_name="<place yours>"
my_db_user="<place yours>"
my_db_password="<place yours>"
mage_admin="<place yours>"
mage_pass="<place yours>"
mage_email="<place yours>"
mage_base_url="<place yours>"
echo y | bin/magento s:un && git reset --hard HEAD && git pull && rm -rf generated/* vendor/* && composer install && bin/magento s:in --backend-frontname="admin" --db-host="localhost" --db-name=$my_db_name --db-user=$my_db_user --db-password=$my_db_password --admin-user=$mage_admin --admin-password=$mage_pass --admin-email=$mage_email --admin-firstname="Admin" --admin-lastname="Super" --base-url=$mage_base_url --cleanup-database --use-rewrites 1
```
3. Log in to Admin
4. Select **Stores > Settings > Manage Sources**
The whole process looks like this:
![reproduced](https://user-images.githubusercontent.com/11827230/41645813-c2a32de8-747a-11e8-9721-efc709a59e87.gif)

### Expected result
1. The page loads and I can manage sources.
![expected](https://user-images.githubusercontent.com/11827230/41645547-fbdab370-7479-11e8-88ce-a9880a16da06.png)

### Actual result
1. Magento logs out.
![actual](https://user-images.githubusercontent.com/11827230/41645546-fbb4de84-7479-11e8-8a25-82c172e5d8c3.png)

**Comment by smoskaluk** [comment]
reproducing on vanila Magento 2.3. Please create ticket in Jira
