### ISSUE TITLE
Avoid code duplication in source_items_rollback.php and source_items_on_default_source_rollback.php fixtures.

### ISSUE THREAD

**Issue by nmalevanec** [magento/inventory#1411]
### Preconditions

1. Magento with MSI

### Steps to reproduce

1. Observe [source_items_rollback.php](https://github.com/magento-engcom/msi/blob/2.3-develop/app/code/Magento/InventoryApi/Test/_files/source_items_rollback.php) and [source_items_on_default_source_rollback](https://github.com/magento-engcom/msi/blob/2.3-develop/app/code/Magento/InventoryCatalog/Test/_files/source_items_on_default_source_rollback.php)

### Expected result

1. There should be no code duplication, therefore Magento\Test\Php\LiveCodeTest::testCopyPaste should not fail.

### Actual result

1. Both files almost identical, which cause failure of Magento\Test\Php\LiveCodeTest::testCopyPaste.

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/1450
https://github.com/magento/magento2/pull/16508
