### ISSUE TITLE
Avoid code fragments duplication in default_stock_configurable_products.php.

### ISSUE THREAD

**Issue by nmalevanec** [magento/inventory#1412]
### Preconditions

1. Magento with MSI.

### Steps to reproduce

1.  Observe 
https://github.com/magento-engcom/msi/blob/14f70cd6393c62b0a821cd7d77bff5673871eb01/app/code/Magento/InventoryConfigurableProduct/Test/_files/default_stock_configurable_products.php#L39-L83
and https://github.com/magento-engcom/msi/blob/14f70cd6393c62b0a821cd7d77bff5673871eb01/app/code/Magento/InventoryConfigurableProduct/Test/_files/default_stock_configurable_products.php#L105-L154
code fragments.

### Expected result

1. There should be no code fragments duplication, to make Magento\Test\Php\LiveCodeTest::testCopyPaste pass successfully.

### Actual result

1. Two fragments are identical except some empty lines and therefore Magento\Test\Php\LiveCodeTest::testCopyPaste fails.

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/1450
https://github.com/magento/magento2/pull/16508
