### ISSUE TITLE
Avoid code duplication in set_product_bundle_out_of_stock.php and set_product_configurable_out_of_stock.php fixtures.

### ISSUE THREAD

**Issue by nmalevanec** [magento/inventory#1415]
### Preconditions

1. Magento with MSI

### Steps to reproduce

1. Observe [set_product_bundle_out_of_stock](https://github.com/magento-engcom/msi/blob/2.3-develop/app/code/Magento/InventoryBundleProduct/Test/_files/set_product_bundle_out_of_stock.php) and [set_product_configurable_out_of_stock](https://github.com/magento-engcom/msi/blob/2.3-develop/app/code/Magento/InventoryConfigurableProduct/Test/_files/set_product_configurable_out_of_stock.php)

### Expected result

1. There should be no code duplication, therefore Magento\Test\Php\LiveCodeTest::testCopyPaste should not fail.

### Actual result

1. Both files are identical, which cause failure of Magento\Test\Php\LiveCodeTest::testCopyPaste.

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/1450
https://github.com/magento/magento2/pull/16508
