### ISSUE TITLE
Avoid code fragments duplication in products_rollback.php and products_virtual_rollback.php fixtures

### ISSUE THREAD

**Issue by nmalevanec** [magento/inventory#1421]
### Preconditions

1.  Magento with MSI.

### Steps to reproduce

1. Observe https://github.com/magento-engcom/msi/blob/14f70cd6393c62b0a821cd7d77bff5673871eb01/app/code/Magento/InventoryApi/Test/_files/products_rollback.php#L31-L58 and https://github.com/magento-engcom/msi/blob/14f70cd6393c62b0a821cd7d77bff5673871eb01/app/code/Magento/InventoryShipping/Test/_files/products_virtual_rollback.php#L31-L58 code fragments.

### Expected result

1. There should be no code fragments duplication and therefore Magento\Test\Php\LiveCodeTest::testCopyPaste should pass successfully.
 
### Actual result

1. Two fragments are identical, so Magento\Test\Php\LiveCodeTest::testCopyPaste fails.

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/1450
https://github.com/magento/magento2/pull/16508
