### ISSUE TITLE
Avoid code duplication in Magento/Inventory/Model/ResourceModel/PredefinedId and Magento/Framework/Model/ResourceModel/PredefinedId traits.

### ISSUE THREAD

**Issue by nmalevanec** [magento/inventory#1422]
### Preconditions

1. Magento with MSI

### Steps to reproduce

1. Observe [Inventory/Model/ResourceModel/PredefinedId](https://github.com/magento-engcom/msi/blob/2.3-develop/app/code/Magento/Inventory/Model/ResourceModel/PredefinedId.php) and [Magento/Framework/Model/ResourceModel/PredefinedId](https://github.com/magento-engcom/msi/blob/2.3-develop/lib/internal/Magento/Framework/Model/ResourceModel/PredefinedId.php)

### Expected result

1. There should be no code duplication, therefore Magento\Test\Php\LiveCodeTest::testCopyPaste should not fail.

### Actual result

1. Both traits are identical except namespace, which cause failure of Magento\Test\Php\LiveCodeTest::testCopyPaste.

**Comment by silyadev** [comment]
Removed duplicate  Inventory/Model/ResourceModel/PredefinedId and changes use cases

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/1424
