### ISSUE TITLE
DOCS - integrations with 3rd parties

### ISSUE THREAD

**Issue by lorikrell** [magento/inventory#1448]
We may not need to document this information. It may be covered by 3rd parties. TBD.

----

Need to document how to integration with 3rd parties/ERP/etc with MSI. 

* Manage orders but not inventory - ERP handles the inventory - how reservations work in this situation/stock/sources
* Manage inventory but not orders - orders and shipment in a 3rd party - how reservations work
* Orders and inventory handled entirely by 3rd party. What parts of MSI function in this situation?

Caveats? Best practices?
Import and export in these situations?

Need feedback from SMEs - check existing content and issues/PRs

**Comment by sidolov** [comment]
Will be covered in scope of devdocs issue
