### ISSUE TITLE
DOCS - State diagrams for SSA, reservations

### ISSUE THREAD

**Issue by lorikrell** [magento/inventory#1461]
Overhaul all diagrams using SKETCH and Infographics.

* Reservations through the process (https://github.com/magento-engcom/msi/wiki/MSI-features-and-processes#order-reservations)
* SSA runs at the time of Shipping for products with weight 
* SSA runs at the time of Invoicing for products without weight

Try to come up with a full pass diagram with technical info and SSA included. Current diagram not quite right on https://raw.githubusercontent.com/wiki/magento-engcom/msi/images/msi-reservations.png

**Comment by lorikrell** [comment]
Diagrams added and updated in 2.3.0
https://docs.magento.com/m2/ee/user_guide/catalog/inventory-about-order-status-reservation.html
https://docs.magento.com/m2/ee/user_guide/Resources/Images/inventory-diagram-simple-order.png
https://docs.magento.com/m2/ee/user_guide/Resources/Images/inventory-diagram-complicated-order.png

May add additional diagrams based on doc updates by Igor in https://github.com/magento-engcom/msi/wiki/Salable-Quantity-Calculation-and-Mechanism-of-Reservations

**Comment by sidolov** [comment]
Should be implemented in scope of devdocs issue.
