### ISSUE TITLE
Editing code of source is not possible

### ISSUE THREAD

**Issue by dingsbams** [magento/inventory#1462]
### Preconditions

1. PHP 7.1.12
2. Magento 2.3-develop

### Steps to reproduce

1. Add new source (e.g. Name => New York, Code => newyork)
2. Edit previously created source
3. Change Code (code => newyork2)
4. Click on Save & Close

### Expected result

1. Code should be changed to newyork2

### Actual result

1. A new source is created (so there are two sources: newyork and newyork2)

**Comment by dingsbams** [comment]
Found on the wiki page:
**Modify source data**
All entered information for all sources can be modified except the code. This value cannot be changed through the Admin. It connects the source to inventory, stocks, orders, shipments, and much more.

**Comment by lorikrell** [comment]
Hi @dingsbams! The source code value should not be editable. We are investigating this possible issue. For more info on this code, please see https://github.com/magento-engcom/msi/wiki/MSI-FAQs#q-i-cant-delete-a-source-or-change-the-code-what-can-i-do . More info coming soon from development.
