### ISSUE TITLE
Delete sources is not possible in manage sources and edit source

### ISSUE THREAD

**Issue by dingsbams** [magento/inventory#1463]
In manage sources and edit source is no way to delete a source.

![manage source](https://user-images.githubusercontent.com/16029597/42617127-ef1f6ea8-85b0-11e8-83f5-220f8e7f3413.png)

### Preconditions

1. PHP 7.1.12 
2. Magento 2.3-develop

### Steps to reproduce

1. Manage Sources
2. Select sources in the list

### Expected result

1. Get some actions (delete, change status, ... )

### Actual result

1. Nothing (no action)

**Comment by lorikrell** [comment]
Hi @dingsbams! Currently you can manage/disable sources, but not delete sources. For more info, please see MSI docs at https://github.com/magento-engcom/msi/wiki/Create-Sources#manage-sources 
I'm sure Igor and others may also provide further info.
