### ISSUE TITLE
Introduce new InventorySales module

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#149]
For all the operations related to Sales and Inventory to follow good modularity principles new module - InventorySales should be created 

Read more details in the scope of this story - https://github.com/magento-engcom/msi/wiki/Stocks-to-Sales-Channel-Mapping

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/173
https://github.com/magento-engcom/msi/pull/150
