### ISSUE TITLE
DOCS - Source and Stock configurations 

### ISSUE THREAD

**Issue by lorikrell** [magento/inventory#1507]
https://github.com/magento-engcom/msi/wiki/Stock-and-Source-Configuration-design

Add information and updates for Source and Stock configuration changes. 

* Assigned Sources grid on Product page will include these options per source: Source Item Status, Qty, Notify Quantity, Notify Quantity Use Default checkbox, Backorders (enable/disable checkbox).
* Catalog > Product > Sources > Advanced Inventory will contain global settings per stock (including Out of Stock Threshold).
* Stores > Manage Sources > Source page will include a section for global settings at the source level.
* Stores > Manage Stocks > Stock page will include a section for global settings at the stock level.

**Comment by lorikrell** [comment]
Updated all content for the changes in https://github.com/magento-engcom/msi/pull/1553

Current content updates available:
https://github.com/magento-engcom/msi/wiki/MSI-Global-Settings
https://github.com/magento-engcom/msi/wiki/Create-Sources
https://github.com/magento-engcom/msi/wiki/Create-Stock
https://github.com/magento-engcom/msi/wiki/Configure-MSI-backorders

Steps and screenshots updated.

Adding additional content based on question of Use Config Settings vs Use system value.

**Comment by lorikrell** [comment]
Content written and prepped. Moving to Milestone 3

**Comment by sidolov** [comment]
Will be delivered in scope of devdocs ticket.
