### ISSUE TITLE
Introduce API interfaces for Assigning Stocks to Sales channels 

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#151]
- New API for assigning Stocks to Sales Channels should be introduced  
- Resolver which returns Stock_id based on Sales channel data (type and code) should be introduced
- Add extension attribute SalesChannels to the StockInterface

Read more details in the scope of this story - https://github.com/magento-engcom/msi/wiki/Stocks-to-Sales-Channel-Mapping

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/173
https://github.com/magento-engcom/msi/pull/150
