### ISSUE TITLE
Value of 'Notify Quantity' for sources should be transferred during mass action 'Transfer Inventory To Source' on Products grid

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1510]
Value of 'Notify Quantity' for sources should be transferred during mass action 'Transfer Inventory To Source' on Products grid

**Comment by phoenix128** [comment]
Hello @smoskaluk ,
see my comment on https://github.com/magento-engcom/msi/issues/1509, I think we have a similar scenario here.

**Comment by phoenix128** [comment]
Fixed in https://github.com/magento-engcom/msi/pull/1648 .
