### ISSUE TITLE
Only X left doesn't appear on product page  

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1535]
### Preconditions
1. Magento with MSI (reproducing on single stock mode and multi stock mode)

### Steps to reproduce
1. Navigate to admin area.
2. Create simple product with qty = 10
3. Navigate to Stores > Configuration > Catalog > Inventory > Stock Options
4. Set Only X left Threshold to 5.
5. Navigate to storefront.
6. Register and login with customer.
7. Add 5 pieces of product to cart and proceed to checkout.
8. Place order.
9. Navigate to product view page.

### Expected result
1. "Only 5 left" message appears on product view page.

### Actual result
1. "Only 5 left" message doesn't appear on product view page.

Note: message 'Only x left' appear on product page only after flushing the cache.

**Comment by maghamed** [comment]
Expected behavior.
Cache invalidation will introduce drastic performance degradation

**Comment by ivy00johns** [comment]
*Skipped Tests:*
1. `<testCaseId value="1501"/>`
2. `<testCaseId value="1578"/>`
