### ISSUE TITLE
Provide robust fix for nested object instantiation via Web API

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#1537]
Initial fix delivered for #1524 
but the root cause of the problem is @phoenix128  PR with the instantiation of DTOs without setters

**Comment by phoenix128** [comment]
Fixed by https://github.com/magento-engcom/msi/pull/1546 .

**Comment by ishakhsuvarov** [comment]
Merged in https://github.com/magento/magento2/pull/17424
