### ISSUE TITLE
Configurable product get 'Out of stock' if created via button 'Add product' 

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1541]
### Preconditions
1. Magento with MSI

### Steps to reproduce
1. Login to admin area.
2. Navigate to Catalog > Products.
3. Start creating configurable product by pressing "Add Product" button. Note: Do not choose initially type 'Configurable product'.
4. Fill necessary data:
Product Name: "configurable product"
SKU: configurable product
Price: 3
Weight: 1
5. Assign it some category.
6. Click button 'Create configurations'.
7. At "Select Attributes" step select color attribute.
8. At "Attribute Value" step create two options: "blue" and "red".
9. At "Bulk Images & Price" step check "Apply single quantity to each SKUs" and set qty = 100 
10. Generate products.
11. Save product.

### Expected result
1. Configurable product is present on category page.
2. Configurable product has "In Stock" status on it's view page.

### Actual result
1. Configurable product is absent on category page.
2. Configurable product has "Out of Stock" status on it's view page.

Note: Reproducing in Single stock mode and Multi stock mode

**Comment by makkoff** [comment]
![Peek 2019-06-06 12-12](https://user-images.githubusercontent.com/49763551/59021869-5b7c9600-8855-11e9-99a4-22a542f7b071.gif)

**Comment by makkoff** [comment]
Hello.I can't reproduce this issue on magento 2.3 msi.
