### ISSUE TITLE
Inconsistent menu names in backoffice

### ISSUE THREAD

**Issue by dverkade** [magento/inventory#1547]
### Preconditions
1. Magento 2.3.0 alpha 
2. MSI 1.0.0 beta

### Steps to reproduce
1. Open backoffice go to stores menu, see screenshot.
![image](https://user-images.githubusercontent.com/1058480/43738345-4a232a66-9992-11e8-8f10-6409340aa3a4.png)

### Expected result
1. A new menu item called "Inventory" should be present, just like the one for "Currency"
2. Menu names should be "Sources" and "Stocks"

### Actual result
1. Settings for sources and stock available under "sections". 
2. Both use a verb in the menu name. No other menu in Magento uses a verb.

**Comment by mbrinton01** [comment]
@lorikrell can you review these titles?

**Comment by lorikrell** [comment]
@mbrinton01  Good point on these titles. 

Section name, no link: Inventory
Menu options, with links: Sources, Stocks

Attached mockup for example. The section may need to be placed in a different column, UX can advise.
![mock-msi-stores](https://user-images.githubusercontent.com/29388020/43780271-d3489ce4-9a1f-11e8-9841-4fce43824c07.png)

**Comment by mbrinton01** [comment]
@dverkade please proceed with changes approved above by @lorikrell. @belbiy, please review the placement of the "Inventory" section on this menu and approve or suggest changes.

**Comment by dverkade** [comment]
Thanks @mbrinton01,

I have created a PR for fixing this.

**Comment by mbrinton01** [comment]
Thank you @dverkade.  @lorikrell please note we may need to update any references to these titles in the MSI documentation.

**Comment by lorikrell** [comment]
Will do! Created https://app.zenhub.com/workspace/o/magento-engcom/msi/issues/1550 to track updates.

**Comment by belbiy** [comment]
The change looks good from a UX perspective.

**Comment by lorikrell** [comment]
@mbrinton01 @dverkade This ticket may need to be assigned to another for completing the development? Perhaps to Danny to connect with his PR? Thanks!

**Comment by dverkade** [comment]
Hi @mbrinton01,

I have already created a PR for resolving this issue. Don't know how the process for the MSI project exactly works. So I'm wondering if someone can clarify or if this issue should be indeed assigned to me or someone else.

**Comment by mbrinton01** [comment]
I've reassigned to @maghamed for assistance. He is on holiday so it may be a few days before it's reviewed.

**Comment by maghamed** [comment]
merged
