### ISSUE TITLE
Provide an implementation for interfaces described in #151

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#155]
Provide an implementation for interfaces described in #151
https://github.com/magento-engcom/msi/issues/151

Read more details in the scope of this story - https://github.com/magento-engcom/msi/wiki/Stocks-to-Sales-Channel-Mapping

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/173
https://github.com/magento-engcom/msi/pull/150
