### ISSUE TITLE
Magento.Sales.Service.V1.ShipOrderTest.testConfigurableShipOrder Web API test failure

### ISSUE THREAD

**Issue by vkublytskyi** [magento/inventory#1562]
### Preconditions

1. Latest code of Magento MSI from `magento-engcom/msi:2.3-develop`

### Steps to reproduce

1. [Run WebAPI tests](https://devdocs.magento.com/guides/v2.2/get-started/web-api-functional-testing.html) for `Magento.Sales.Service.V1.ShipOrderTest.testConfigurableShipOrder` (both, SOAP and REST)

### Expected result

1. Tests are green

### Actual result

1. Tests failed
```
Magento\Sales\Service\V1\ShipOrderTest::testConfigurableShipOrder
SoapFault: Call to a member function getQuantity() on null

---

Magento\Sales\Service\V1\ShipOrderTest::testConfigurableShipOrder
Exception: {"messages":{"error":[{"code":500,"message":"Server internal error. See details in report api\/1069312954567"}]}}
```

Note: probably related to magento-engcom/msi#1561

**Comment by okorshenko** [comment]
Duplicates #1335
