### ISSUE TITLE
Stock Removal. Throw an exception and allow to delete just unassigned stocks

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#157]
It should not be possible to delete stock which is assigned to one or more Sales Channels, as Sales Channels would be left without inventory after that action.

Currently in the scope of PR #150 SalesChannel interface has been introduced
https://github.com/magento-engcom/msi/blob/3ca6de9977091eca076a5bad9c7754cfc6880a17/app/code/Magento/InventorySalesApi/Api/Data/SalesChannelInterface.php

[Extension attribute](https://magento.stackexchange.com/questions/113447/how-to-use-extension-attributes-in-magento2) with SalesChannles has been added to StockInterface. 
As we have an assignment Stock -> SalesChannel

![image](https://user-images.githubusercontent.com/1928215/32095461-ef3fb200-bb0b-11e7-9db3-5d36ef207ef2.png)

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/171
