### ISSUE TITLE
UX Text - Max Actions Transfer Inventory to Source

### ISSUE THREAD

**Issue by lorikrell** [magento/inventory#1584]
Need to update text descriptions for **Mass Actions - Unassign Sources**. I am including all feedback, proposed text changes, with screenshots to help.

I discussed and reviewed these changes with UX.

### Pop-up for mass transfer
Screenshot:
![image](https://user-images.githubusercontent.com/29388020/44542651-137bf080-a6d3-11e8-92ce-5ed679647ce0.png)

1. Edit content: Transfer all inventory quantities and additional settings from one source to another for products you selected. Do you want to continue?

### Bulk Transfer 
Screenshot:
![image](https://user-images.githubusercontent.com/29388020/44542732-49b97000-a6d3-11e8-9051-639f3d641c49.png)

1. Add content, plain text: Select the origin and destination sources to transfer product inventory quantities and additional settings. This transfers all existing quantities, setting a 0 quantity on the origin source. You have an option to unassign the origin source from the products you selected.

2. Add "the origin" and "the destination" to the sentence: Transfer from the origin source (selection) to the destination source (selection)

3. Edit the checkbox content: Unassign the origin source from selected products after transfer. 

4. Edit the button text: Transfer Inventory

### Transfer Error Message
When you select the same source for origin and destination, you get a Validation Error. If possible, we may need a better error? Unsure what situations will display this error. 

The following is an example error message when selecting the same source:

`Validation Error: Select different sources for origin and destination.`

Screenshot:
![image](https://user-images.githubusercontent.com/29388020/44542778-6e154c80-a6d3-11e8-8af8-a731c89f52f8.png)

**Comment by lorikrell** [comment]
FYI this is for changes in the Admin UI, worked on with UX.

**Comment by sidolov** [comment]
@joridos could you please take a look at comment https://github.com/magento/inventory/pull/2818#issuecomment-585820938?
