### ISSUE TITLE
Fix the functional test "Verify credit memo grand total after shipping discount is applied via Cart Price Rule"

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1606]
Investigate and fix the functional test "Verify credit memo grand total after shipping discount is applied via Cart Price Rule" - it pass manually but fail on Jenkins - http://10.234.148.146:8080/job/Functional-Tests-CE/1353/allure/#suites/8187718e2fd144987673ef34ee62b41b/39ed4f2d5a412b5a/

**Comment by ivy00johns** [comment]
Issue no longer present. Closing bug.
