### ISSUE TITLE
Configurable product on custom stock doesn't disappear from category page on frontend when totally sold out

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1614]
### Preconditions
1. Magento with enabled MSI

### Steps to reproduce
1. Create custom Stock with custom Source and assign it to Main website
2. Create configurable product with 2 simple variables - set the weight = 1 (red and blue) with qty = 10 on custom Source.
3. Go to Main website and place order with all qty of configurable product 
(red qty = 10 and blue qty = 10)
4. Go to admin and create shipment for your order
5. Navigate to storefront to category view page.
 
### Expected result
1. Configurable product is absent on category view page.

### Actual result
1. Configurable product is present on category view page.

**Comment by naydav** [comment]
Current problem is related to cache invalidation
