### ISSUE TITLE
Implement Low Stock Notification on the level of Sources

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#162]
As a Merchant, I want to be notified regarding product storage is running out on some particular Source.

A merchant should have an ability to specify Stock Notification threshold at the level of SourceItem as well as the Global threshold applied for all products.

New module - InventoryConfiguration suppose to be introduced. And all the logic regarding Low Stock notification should be placed there.
The module should provide basic interfaces for managing configuration as well as a fall-back from SourceItem to Global Configuration.

Extension point for the module is 
Pluginization of SourceItem save operation where Stock education operation happened.

**Comment by naydav** [comment]
This task has been split into a few ones (with the same label)
