### ISSUE TITLE
Unskip and fix \Magento\Catalog\Test\TestCase\Product\CreateSimpleProductEntityTest::testCreate

### ISSUE THREAD

**Issue by naydav** [magento/inventory#1620]
During merge with mainline
\Magento\Catalog\Test\TestCase\Product\CreateSimpleProductEntityTest::testCreate
has been skipped

Need to unskip and fix the functional test

**Comment by lbajsarowicz** [comment]
Does it make sense if we have MFTF coverage on this?
`app/code/Magento/Catalog/Test/Mftf/Test/AdminCreateSimpleProductTest.xml`
