### ISSUE TITLE
The limit is 100 times less than in magento/magento2#2.3-develop

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/inventory#1622]
### Preconditions
Magento MSI
At least one additional source is enabled

### Steps to reproduce
1. Start creating a Simple Product and fill all the required fields.
2. Assign product to any source and Set the quantity to be equal to 100000000 

### Expected result
JS validation message appeared right after you typed the last digit with the next content:
'Please enter a value less than or equal to 99999999.'

### Actual result
999999.9999 is saved and no validation (try Import/Export the same there: only 999999.9999 will be imported)

This means the limit is 100 times less than in magento/magento2#2.3-develop

**Comment by lorikrell** [comment]
If we need a note in documentation, I can add that to the user guide.
