### ISSUE TITLE
Unnecessary warning message during creating order with configurable product with disabled options

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1639]
### Preconditions

1. Magento MSI
2. Configurable product created with two options
3. Disable both options of configurable product

### Steps to reproduce

1. Goto to admin
2. Start to create order from admin and try to add to 'Items Ordered' configurable product by sku (one of the option)

### Expected result

1. Error message should be only : 'This product is out of stock.'

### Actual result

1. 2 error messages are displayed : 
'The requested sku is not assigned to given stock' - is unnecessary,
'This product is out of stock.' - is  correct

![image](https://user-images.githubusercontent.com/27818516/45493783-35b7da00-b778-11e8-9219-658959e70488.png)

**Comment by kisroman** [comment]
This bug will be fixed in https://github.com/magento-engcom/msi/issues/1638.
