### ISSUE TITLE
Multi website support for separate iInventory limits (min/max qty, QTY increments)

### ISSUE THREAD

**Issue by tomekjordan** [magento/inventory#1644]
Will MSI support separate fields per website scope

Min QTY allowed in the Cart
Max QTY allowed in the Cart
QTY increments

Now Magento 1 and Magento 2 - allows us to fill those values on global scope which is not sufficient if you have 2 different websites - example B2C and B2B sites, or if you manage different stores (different domains, inventory strategy and pricing).

Hope it could be added to the project at core level

Thanks

**Comment by maghamed** [comment]
hey @tomekjordan ,

we will do a bit different. Thus, in MSI we have own scopes (SourceItem / Source / Global   and StockItem / Stock / Global) comparing to Magento ones (Store View / Website / Global).

We are going to provide an ability to specify Inventory configuration values on these scopes.
Here you can read more about the idea:
https://github.com/magento-engcom/msi/wiki/Inventory-configuration-Design-and-DB-structure
https://github.com/magento-engcom/msi/wiki/Stock-and-Source-Configuration-design

The work devoted to these changes is in progress, you can find it in this PR 
https://github.com/magento-engcom/msi/pull/1553

Let me know if you have further questions/ideas

**Comment by sidolov** [comment]
Hi @tomekjordan , I'm closing this issue since it's already supported in different way as described by @maghamed .
Thank you for your involvement!
