### ISSUE TITLE
404 error after source selection during creating shipment

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1655]
After merge of the task https://jira.corp.magento.com/browse/MAGETWO-93969 to magento 2.3 to controllers was added validation of call type. For controller Magento\Shipping\Controller\Adminhtml\Order\Shipment\NewAction set GET calls only, but in MSI we have additional step (source selection algorithm) which do POST call and this cause error.

**Comment by maghamed** [comment]
Quick Fix is delivered to MSI.

Need to provide robust fix in future
