### ISSUE TITLE
'Salable Quantity' column is empty after deploying small.xml preset

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/inventory#1667]
### Preconditions
1. Magento MSI

### Steps to reproduce
1. Execute:
```
bin/magento setup:perf:generate-fixtures setup/performance-toolkit/profiles/ce/small.xml
``` 
2. Navigate to Catalog > Products

### Expected result

1. Products Salable Quantity is equal to 100500

### Actual result

1. 'Salable Quantity' column is empty

**Comment by p-bystritsky** [comment]
In \Magento\Setup\Model\FixtureGenerator\ProductGenerator::generate for each Product Attribute Set a Product template is generated, saved and immediately deleted. 
While the Product template is saved, \Magento\Setup\Model\FixtureGenerator\SqlCollector class collects SQL queries. Also, at this point, inventory_source_item records are created.
After that, SQL queries collected by \Magento\Setup\Model\FixtureGenerator\SqlCollector class are used as pattern to generate new SQL queries in \Magento\Setup\Model\FixtureGenerator\EntityGenerator::getSqlQueries, that are directly inserted to database in \Magento\Setup\Model\FixtureGenerator\EntityGenerator::saveEntities, so neither of MSI plugins are called.
