### ISSUE TITLE
Update old StockItem and Stock Status DB table at the time of Reservation appended

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#167]
Update old StockItem and Stock Status DB table at the time of Reservation appended.

We need to pluginize (?) Reservation Append process and update StockItem and StockStatus tables introduced in CatalogInventory module

**Comment by larsroettig** [comment]
I will write a around plugin for 
**\Magento\InventoryApi\Api\ReservationsAppendInterface::execute** as extenstions  point.
