### ISSUE TITLE
Low stock report not displays products on custom Source

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1687]
### Preconditions

1. Magento with MSI 
2. Custom Stock with custom Source created
2. Simple or virtual product created assigned to custom source with Qty = 10 

### Steps to reproduce

1. Set in Configuration - Catalog - Inventory - Notify for Quantity Below = 20
2. Run full index and flush cache
3. Open Reports - Low Stock

### Expected result

1. Product should be displayed in Low stock report

### Actual result

1. Product is not displayed in report

**Comment by maghamed** [comment]
hey @aleron75  are there any updates?
