### ISSUE TITLE
Low stock report displays 'Out of stock' products

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1688]
### Preconditions

1. Magento with MSI  + EE in Single stock mode (No sources created)
2. Simple or virtual product created with Qty = 10

### Steps to reproduce

1. Set in Configuration - Catalog - Inventory - Notify for Quantity Below = 20
2. Open Reports - Low Stock
3. Products are displayed
4. Make your products 'Out of stock' on product page in admin and save
5. Open Reports - Low Stock

### Expected result

1. Products should not be displayed in report

### Actual result

1. Products are displayed in report

### Note:
Now it reproducing on default and custom stocks as well

**Comment by larsroettig** [comment]
Hi @smoskaluk,
I can not reproduce this Issue. 
![msi_repo_2](https://user-images.githubusercontent.com/5289370/46915931-65464600-cfb3-11e8-8dd0-8bb9ae185dad.gif)

**Comment by smoskaluk** [comment]
Problem is reproducing in Single stock mode

**Comment by smoskaluk** [comment]
Now it reproducing on default and custom stocks as well

**Comment by ishakhsuvarov** [comment]
Duplicate: https://github.com/magento-engcom/msi/issues/1875
Duplicate: https://github.com/magento-engcom/msi/issues/1858

This issue seems to be reproducible only on EE

**Comment by ishakhsuvarov** [comment]
This issue is caused by incorrect processing of Modules Sequence in the core Module Manager. Fix is unlikely to be delivered to Inventory.

**Comment by ishakhsuvarov** [comment]
Fixed in https://github.com/magento/inventory/pull/2684
