### ISSUE TITLE
Cannot add grouped product to cart.

### ISSUE THREAD

**Issue by nmalevanec** [magento/inventory#1691]
### Preconditions
1. Magento 2 B2B with MSI.
2. Clean installation(Single stock mode).

### Steps to reproduce
1. Login to admin area.
2. Create simple product price = 3, qty = 100.
3. Create virtual product price = 10, qty = 100.
4. Create grouped product and assign it to category. Add both simple and virtual to group. Set default quantity = 2 for both products.
5. Navigate to storefront category page. 
6. Click "Add to cart" button on grouped product.
7. Navigate to grouped product page.
8. Click "Add to cart" button.

### Expected result
1. Product successfully added to cart in both cases(from category page and product page).

### Actual result
1. Button "Add to cart" changes to "Adding...", "Added" but product is not added to cart. No additional errors occur.

**Comment by IvanPletnyov** [comment]
Cannot reproduce.
