### ISSUE TITLE
Grouped product with stock status "Out of Stock" presented on storefront as in stock.

### ISSUE THREAD

**Issue by nmalevanec** [magento/inventory#1693]
### Preconditions
1. Magento with MSI.
2. Additional Stock and Source created. 
3. Default website assigned as sales channel to additional stock.

### Steps to reproduce
1. Login to admin area.
2. Create simple product and assign it to custom source from preconditions with qty = 100.
3. Create grouped product with stock status "In Stock" and add created simple product to group.
4. Assign grouped product to category.
5. Update grouped product stock status to "Out of Stock".
6. Navigate to storefront category page.
7. Navigate to storefront grouped product page.

### Expected result
1. Grouped product is absent on category page.
2. Grouped product has "Out of Stock" status on it's details page.
3. There is no ability to add grouped product to cart.

### Actual result
1. Grouped product is present on category page.
2. Grouped product has "In Stock" status on it's details page.
3. You can add grouped product to cart.

**Comment by maghamed** [comment]
@smoskaluk can you please check it one more time, I think after merging #1693 the case you refered here is fixed
