### ISSUE TITLE
Add 'Assigned sources list' column to 'Manage Stock' grid 

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1711]
### Description

Add 'Assigned sources list' column to 'Manage Stock' grid 

### Benefits

User might see in the 'Stock' grid which sources assigned to the stock

**Comment by Stepa4man** [comment]
@smoskaluk, he question is how much sources do you want to see there. In case if there will be hundreds of sources we have to limit it. So what does this limited list could provide you?
Anyway, I made an initial commit and pull [request](https://github.com/magento-engcom/msi/pull/1726), @maghamed please take a look at the branch [#1711_Add_Assigned_sources_list_column_to_Manage_Stock_grid](https://github.com/magento-engcom/msi/commit/1a5f7f6f565d1fedfc75d8f9305bb90c36fee5a7)

**Comment by smoskaluk** [comment]
@Stepa4man Hi, I think we may inherit behaviour of 'Sales channels' column
