### ISSUE TITLE
Default source assigned to products after import

### ISSUE THREAD

**Issue by IvanPletnyov** [magento/inventory#1718]
### Preconditions
1. Magento CE with MSI

### Steps to reproduce
1. Create custom source
2. Create custom stock with assigned custom source and selected "main website" in sales channels
3. Create product with created custom source (only custom source) with quantity = 100
4. Run Export (entity type - Products)
5. Delete created product
6. Run import (entity type - Products, import behavior - add/update)

### Expected result
1. Product will be create only with custom source with qty = 100

### Actual result
1. Product created with custom source(qty = 100) and default source(qty = 0)

**Comment by seruymt** [comment]
In fact, the SourceItem is created only for default source. For custom source magento use old data from db.

@maghamed could you please describe correct behavior of import?

**Comment by maghamed** [comment]
not a bug.
current Behavior is expected

**Comment by lorikrell** [comment]
I added info to https://github.com/magento-engcom/msi/wiki/MSI-FAQs and https://github.com/magento-engcom/msi/wiki/MSI-Import-and-Export-Product-Data with info.
