### ISSUE TITLE
Incorrect amount suggested by SSA on multiple shipments

### ISSUE THREAD

**Issue by mbrinton01** [magento/inventory#1728]
### Preconditions

1. Install MSI 2.3-develop

### Steps to reproduce

1. Create two sources - A and B
1. Assign a product to both sources: qty A: 2, qty B: 100
1. Create a stock containing two sources: A and B
1. Adjust source priority in the stock so A is the highest priority source
1. Create an order for qty 6 of product
1. In admin panel, ship the product. First suggestion will be qty 2 from A. Make this shipment.
1. Click Ship again on the order
1. View page suggestions by SSA

### Expected result

Qty to Ship = 4 (because 2 of 6 total have already been shipped)
Qty to Deduct = 4 from Source B (because 2 of 6 total have already been shipped and available qty on Source A is 0)

### Actual result

Qty to Ship = 6
Qty to Deduct = 6 from Source B

### Important Note

After clicking Proceed to Shipment when shipping the second time (for source B), the proposed amount to ship (Qty to Ship) will be the correct amount (4). So the correct amount is shipped, but there is an inconsistency between what is proposed on the SSA page and the shipment page.

**Comment by maghamed** [comment]
can't reproduce the bug following the steps described on provided video.

using laters 2.3-develop branch
