### ISSUE TITLE
Customer not receiving 'Back in stock' alert letter 

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1729]
### Preconditions

1. Magento MSI
2. Product created with 'Out of stock' status
3. Back in stock alerts enabled in configuration 
4. Customer create account on Home page

### Steps to reproduce

1. By direct url open product page on frontend
2. Subscribe for 'Product back in stock' alert
3. In admin set status for product 'In stock'

### Expected result

1. Customer get letter with alert that product 'Back in stock' (after scheduled cron run) 

### Actual result

1. Letter doesn't come

**Comment by larsroettig** [comment]
Hi @smoskaluk,
i try to reproduce this Issue but it is not reproducibly.


[![Watch the video]()](https://streamable.com/s/98rv5/odidqx )


usually this cron run only at "0 * * * "
` crontab/default/jobs/catalog_product_alert/schedule/cron_expr`
