### ISSUE TITLE
"Show more - Show less" sources in field "quantity per source" at product grids

### ISSUE THREAD

**Issue by Stepa4man** [magento/inventory#1730]
When there are a lot of sources assigned to the product - > field "quantity per source" at product grid become very large and row also

### Preconditions
1. Create more than 10 sources
2. Create new stock
3. Assign all sources to new stock

### Steps to reproduce
1. Create a new product
2. Assign all available sources to  the product and fill QTY fields with 1 or more and set "in stock" for all sources
3. Save
4. Go to the product grid and see how big every row become

### Expected result
1. Field "quantity per source" limited by 3-5 item and "show more" link.
2. All other sources in a row will be shown after hitting "show more" link

### Actual result
1. All sources are shown in field  "quantity per source"
2. Row height is as big as much sources assigned to current product

**Comment by Stepa4man** [comment]
The same should be implemented for stock grid after merging https://github.com/magento-engcom/msi/pull/1726

**Comment by maghamed** [comment]
@Stepa4man  the #1726 is merged (/)
