### ISSUE TITLE
Deprecate CatalogInventory before 2.3.0 release 

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#1735]
Deprecate CatalogInventory before 2.3.0 release

**Comment by maghamed** [comment]
https://github.com/magento/magento2ce/pull/3263

**Comment by lorikrell** [comment]
FYI docs for this are live! Kevin pushed content to 
https://devdocs.magento.com/guides/v2.3/inventory/overview.html
https://devdocs.magento.com/guides/v2.3/inventory/catalog-inventory-replacements.html
