### ISSUE TITLE
Add Support for "Download Sample File" link for Inventory Import

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#174]
Add Support for "Download Sample File" link for Inventory Import.

Currently, user is given a message: "There is no sample file for this entity"

<img width="1174" alt="screen shot 2017-11-04 at 10 38 38" src="https://user-images.githubusercontent.com/1928215/32404470-c0e7d31c-c158-11e7-922b-2a7e762a2558.png">

**Comment by rogyar** [comment]
I can handle it. Thanks
