### ISSUE TITLE
Error after create credit_memo on order with bundle product

### ISSUE THREAD

**Issue by IvanPletnyov** [magento/inventory#1751]
### Preconditions
1. Magento with MSI

### Steps to reproduce
1. Create simple product
2. Create fixed bundle product (with fixed price - "Dynamic Price" => false) and assign created simple product.
3. Create order with created bundle product
4. Create invoice on created order
5. Create credit memo on created order (with enabled "Return to Stock")

### Expected result
1. credit memo has created

### Actual result
1. Error 500 
`... PHP Fatal error:  Uncaught Exception: Notice: Undefined variable: sourceCode in /var/www/html/msi/app/code/Magento/InventorySales/Model/ReturnProcessor/GetInvoicedItemsPerSourceByPriority.php on line 162 ...`

**Comment by smoskaluk** [comment]
@IvanPletnyov  I've check this issue, but instead of 500 fatal error during saving Credit memo I've got message "The credit memo couldn't be saved."
![image](https://user-images.githubusercontent.com/27818516/47078698-8ce41b00-d20c-11e8-8dd2-007a0664b1d0.png)

**Comment by achleitner** [comment]
> @IvanPletnyov I've check this issue, but instead of 500 fatal error during saving Credit memo I've got message "The credit memo couldn't be saved."
> ![image](https://user-images.githubusercontent.com/27818516/47078698-8ce41b00-d20c-11e8-8dd2-007a0664b1d0.png)

Hello, did you ever find a solution for this. We get this when refunding via Braintree. Refund goes though in Braintree but no credit memo is created. When trying to create offline memo we get "cant save credit memo"

Thanks!
