### ISSUE TITLE
Fix test Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.AdminAddRemoveStockColumnsTest

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1755]
Fix functional test Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.AdminAddRemoveStockColumnsTest

Failed asserting that any element by '.admin__data-grid-header[data-bind='afterRender: $data.setToolbarNode'] .admin__data-grid-action-columns-menu' on page /admin/inventory/stock/index/
Elements: 
+ <div> 5 out of 5 visible
ID
Name
Sales Channels
Assigned sources
Action
Reset
Cancel
contains text '4 out of 4 visible'

![image](https://user-images.githubusercontent.com/27818516/46719467-a1f20480-cc76-11e8-9909-b47e1757e319.png)

**Comment by ivy00johns** [comment]
- Branch with fix:
    - https://github.com/magento-engcom/msi/tree/1755-Admin-Add-Remove-Stock-Columns-Broken-Test
- PR:
    - https://github.com/magento-engcom/msi/pull/1758

**Comment by ivy00johns** [comment]
PR merged. Closing issue.
