### ISSUE TITLE
Fix test Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.AdminManageStockGridChangeColumnOrderByDragAndDropTest

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1756]
Fix functional test Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.AdminManageStockGridChangeColumnOrderByDragAndDropTest

Failed asserting that two arrays are equal.

![image](https://user-images.githubusercontent.com/27818516/46719525-c817a480-cc76-11e8-9eb7-cad196f4a944.png)

**Comment by ivy00johns** [comment]
- Branch with fix:
    - https://github.com/magento-engcom/msi/tree/1756-Admin-Manage-Stock-Grid-Broken-Test
- PR:
    - https://github.com/magento-engcom/msi/pull/1757

**Comment by ivy00johns** [comment]
PR merged. Closing issue.
