### ISSUE TITLE
[BUG] There is an error message appearing on the Stock/Source Grid pages when you delete items or randomly on page load.

### ISSUE THREAD

**Issue by ivy00johns** [magento/inventory#1759]
1. Go to the "Manage Stock" page.
     - You will need to have an existing Stock in the grid.
2. Click on the "Select All" drop down.
3. Click on "Select All".
4. Click on "Actions".
5. Click on "Delete".
6. Click on "Ok".
7. Note the error message.

*Expected*
- No error message on page load.
- No error message after deleting items via the grid.

*Actual*
![image.png](https://images.zenhubusercontent.com/5a679b134b5806bc2bc400ab/70d2f2a4-8ed9-4bae-8ccf-f787b175e9f2)

**Comment by ivy00johns** [comment]
*Skipped Tests Due to Bug*
1. ~AdminCreateOrderWithVirtualProductFromTestSourceWithBackordersTest~
2. ~AdminStockDeletedFromGridWhenNoSalesChannelsAssignedTest~
3. ~StorefrontLoggedInCustomerOrderedVirtualProductOnDefaultStockTest~
4. ~AdminOrderCreatedWithSimpleProductViaTheAdminTest~
5. ~AdminMassActionUnAssignAllProductSourcesFromSimpleProductTest~
6. ~AdminPriorityOfSourcesChangedByDragAndDropTest~
7. ~AdminUpdateStockDataTest~
8. ~AdminAddConfigurableProductWithTextSwatchAttributeAndDefaultSourceTest~

**Comment by ivy00johns** [comment]
All tests effected by this bug have been unskipped at this time. Every time I'd skip a group of Tests a new group would pop up. 

It appears that depending on how many times the Stock/Source grids are accessed it will randomly error. I've received the error by visiting the page once. Other times I can replicate it by deleting items like the instructions above outline.

**Comment by ivy00johns** [comment]
This PR may fix this issue. Will run a build to verify: 
- https://app.zenhub.com/workspace/o/magento-engcom/msi/issues/1763
    - https://github.com/magento-engcom/msi/issues/1762
    - https://github.com/magento-engcom/msi/pull/1763
- https://m2build-ur.devops.magento.com/job/All-User-Requested-Tests/6602/

**Comment by IvanPletnyov** [comment]
@ivy00johns I think it's dublicate [issue 1767](https://github.com/magento-engcom/msi/issues/1767) . You can check it because I've created [PR 1769](https://github.com/magento-engcom/msi/pull/1769) which fixed problem with stock grid.

**Comment by ivy00johns** [comment]
PR was merged last night. Running new builds now to verify the issue has been fixed. Will close if everything is cleared up.

**Comment by ivy00johns** [comment]
Builds are finally done. The issue no longer appears. Woot! Closing issue.
