### ISSUE TITLE
No returns to the source after Credit memo for order with Grouped product

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1761]
### Preconditions

1. Magento MSI with test source created
2. Simple product created with qty = 100 on test source
3. Virtual product created with qty = 100 on test source
4. Grouped product created with with simple and virtual products as a childs (qty=5 for both)

### Steps to reproduce

1. Place order with Grouped product (simple and virtual products  qty = 5 for both)
2. Verify that Salable Qty of both product get = 95
3. Create Invoice for this order (Qty on test source for virtual product get = 95)
4. Create Shipment for this order (Qty on test source for simple product get = 95)
5. Create Credit Memo for this order with 'Return to stock' enabled option for both products

### Expected result
1. Qty on test source for both products  has to get back = 100 

### Actual result

1. Qty on test source for both products  = 95 (nothing returned)

Note. The same behaviour for Qty on default source as well

**Comment by seruymt** [comment]
@maghamed The main problem is Magento for grouped product creates order items as simple product with type "grouped" instead of "simple"
