### ISSUE TITLE
Fix errors for PR #1709 

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1762]
Fix all errors for PR #1709 "MSI-1707: Introduced PHP 7.1 syntax for API interfaces" caused failures on Functional test 
latest builds - https://m2build-ur.devops.magento.com/job/All-User-Requested-Tests/6449/
Functional-Tests-CE-UR ( FAILURE ) ( w/extensions )
Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.AdminCreateOrderWithSimpleProductFromTestSourceWithBackordersTest - Failed asserting that an array is not empty.  500 error
Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.AdminCreateOrderWithVirtualProductFromDefaultSourceWithBackordersTest - Failed asserting that an array is not empty.  500 error
Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.AdminMassActionAssignProductSourcesForSimpleProductsTest - Failed asserting that an array is not empty.  500 error
Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.AdminMassActionAssignProductSourcesForDifferentTypesOfProductsTest - Failed asserting that an array is not empty.  500 error
Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.AdminMassActionUnAssignAllProductSourcesFromSimpleProductTest - Failed asserting that an array is not empty.  500 error
Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.AdminMassActionUnassignProductSourcesForDifferentTypesOfProductsTest - Failed asserting that an array is not empty.  500 error
Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.AdminMassActionTransferInventoryToSourceForSimpleProductsTest - Failed asserting that an array is not empty.  500 error
Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.AdminMassActionTransferInventoryToSourceForDifferentTypeOfProductsTest - Failed asserting that an array is not empty.  500 error
Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.AdminBackordersEnabledOnConfigurationPageAndAppliedToSimpleProductOnDefaultSourceTest - Failed asserting that an array is not empty.  500 error
Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.BackordersEnabledOnProductPageAndAppliedToSimpleProductOnDefaultSourceTest - Failed asserting that an array is not empty.  500 error
Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.AdminManageSourceGridChangeColumnOrderByDragAndDropTest - Failed asserting that an array is not empty.  500 error
Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.AdminBackordersEnabledOnConfigurationPageAndAppliedToSimpleProductOnTestSourceTest- Failed asserting that an array is not empty.  500 error
Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.BackordersEnabledOnProductPageAndAppliedToSimpleProductOnDefaultSourceTest- Failed asserting that an array is not empty.  500 error
Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.BackordersEnabledOnProductPageAndAppliedToSimpleProductOnTestSourceTest- Failed asserting that an array is not empty.  500 error
Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.AdminManageSourceGridChangeColumnOrderByDragAndDropTest- Failed asserting that an array is not empty.  500 error
Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.AdminNotifyQuantityUseDefaultAppliedToSimpleProductOnConfigurationAdminPageTest- Failed asserting that an array is not empty.  500 error
Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.AdminConfigurableProductDisabledManageStockOnProductPageForCustomStockTest- Failed asserting that an array is not empty.  500 error
Magento\FunctionalTestingFramework.functional\MSI_Sort_Order_Tests.AdminManageSourceGridColumnsSortingTest- Failed asserting that an array is not empty.  500 error
![image](https://user-images.githubusercontent.com/27818516/46787019-43448d80-cd3f-11e8-9d9e-907edf06d1a8.png)

Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.AdminUserApplyOnlyXLeftThresholdForSimpleProductOnDefaultSourceModeTest - CSS or XPath element with '//a[@class='product-item-link'][contains(text(), 'SimpleProduct5bbdcff61fc5c9')]' was not found.
![image](https://user-images.githubusercontent.com/27818516/46787724-15604880-cd41-11e8-98ac-77fd255c3bd5.png)

Functional-Tests-B2B-UR ( FAILURE ) ( w/extensions )
Magento\FunctionalTestingFramework.functional.AdminAddImageToWYSIWYGNewsletterTest 
![image](https://user-images.githubusercontent.com/27818516/46803311-73545680-cd68-11e8-9a49-e7e09ff32a58.png)

Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.StorefrontLoggedInCustomerCreateOrderWithBundleProductDefaultStockTest - stale element reference: element is not attached to the page document 
![image](https://user-images.githubusercontent.com/27818516/46803475-d0500c80-cd68-11e8-8fe1-6cd69ff31fc4.png)

Sample-Data-Functional-Tests-EE-UR ( FAILURE ) ( w/extensions ) 
Magento\Install\Test\TestCase\InstallTest.test with data set "InstallTestVariation5_0" - Timed out after 720 seconds

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/1769
