### ISSUE TITLE
Fix MFTF test AdminManageStockGridChangeColumnOrderByDragAndDropTest

### ISSUE THREAD

**Issue by IvanPletnyov** [magento/inventory#1766]
# Preconditions
1. Magento with MSI

### Steps to reproduce
1. Run tests `app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminManageStockGridChangeColumnOrderByDragAndDropTest.xml`

### Expected result
1. Test passed

### Actual result
1. Test are failing with message: Failed asserting that two arrays are equal.

**Comment by smoskaluk** [comment]
duplicate https://github.com/magento-engcom/msi/issues/1756
