### ISSUE TITLE
Fix error of functional tests on 2.3-develop

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1768]
http://10.234.234.30:8080/job/Functional-Tests-CE/136 
Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.AdminSourceForEachQuantityCanBeSetByAdminTest  - invalid element state: Element is not currently interactable and may not be manipulated 
![image](https://user-images.githubusercontent.com/27818516/46853509-03e17400-ce07-11e8-8f7b-c68aeeeac4e9.png)

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/1771
