### ISSUE TITLE
Fix errors of functional tests on 2.3-develop with B2B

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1784]
Fix errors of functional tests on 2.3-develop with B2B
Functional-Tests-B2B-UR ( FAILURE ) ( w/extensions )  http://10.234.237.24:8080/job/Functional-Tests-B2B/1323
Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.AdminSourcePrioritySelectionAlgorithmSimpleProductCustomStockTest
Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.GuestCustomerOrderedDownloadableProductOnDefaultStockFromHomepageTest
Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.GuestCustomerOrderedDownloadableProductOnCustomStockFromHomepageTest
Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.AdminCreateOrderWithVirtualProductFromTestSourceWithBackordersTest
Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.AdminMassActionTransferInventoryToSourceForSimpleProductsTest
Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.AdminMassActionTransferInventoryToSourceForDifferentTypeOfProductsTest
Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.AdminUserApplyOnlyXLeftThresholdForSimpleProductOnTestSourceTest
Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.BackordersEnabledOnProductPageAndAppliedToSimpleProductOnDefaultSourceTest
Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.BackordersEnabledOnProductPageAndAppliedToSimpleProductOnTestSourceTest
Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.AdminPriorityOfSourcesChangedByDragAndDropTest
![image](https://user-images.githubusercontent.com/27818516/47014365-bc365180-d152-11e8-9894-ad361bdfb3bb.png)

**Comment by IvanPletnyov** [comment]
I've tried to reproduce it fail, but it has not reproduced yet.

**Comment by smoskaluk** [comment]
Not reproducing on last bild https://m2build-ur.devops.magento.com/job/All-User-Requested-Tests/6881/
