### ISSUE TITLE
Fix error of failed functional test Functional-Tests-EE-UR 

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1794]
Functional-Tests-EE-UR ( FAILURE ) ( w/extensions )
 http://10.234.148.146:8080/job/Functional-Tests-EE/1487 
Magento\FunctionalTestingFramework.functional.AdminAbleToShipPartiallyInvoicedItemsTest -  Element located either by name, CSS or XPath element with 'div.message-success' was not found.
![image](https://user-images.githubusercontent.com/27818516/47066761-ce1a0200-d1ef-11e8-864f-7dd257796e64.png)

**Comment by IvanPletnyov** [comment]
Isn't reproduce on a new build

**Comment by smoskaluk** [comment]
Not reproducing on last bild https://m2build-ur.devops.magento.com/job/All-User-Requested-Tests/6881/
