### ISSUE TITLE
Low stock report not displays products on single stock mode untill any custom source created

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1800]
### Preconditions

1. Magento with MSI  (single stock mode) - fresh installation, no any custom sources created yet
2. Simple or virtual product created with Qty = 10 

### Steps to reproduce

1. Set in Configuration - Catalog - Inventory - Notify for Quantity Below = 20
2. Run full index and flush cache
3. Open Reports - Low Stock

### Expected result

1. Product should be displayed in Low stock report

### Actual result

1. Product is not displayed in report

Notice: After creating any custom source Low stock report works.

**Comment by maghamed** [comment]
#1543 closed as duplicate
