### ISSUE TITLE
Fix failure of Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.AdminAddConfigurableProductWithTextSwatchAttributeAndDefaultSourceTest

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1801]
Fix failure of functional test  http://10.234.148.146:8080/job/Functional-Tests-CE/1760
Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.AdminAddConfigurableProductWithTextSwatchAttributeAndDefaultSourceTest  -  CSS or XPath element with '//input[ancestor::tr[contains(., 'Test Source 1 5bc6e242870292')]]' was not found. 
![image](https://user-images.githubusercontent.com/27818516/47083953-d8052a80-d21a-11e8-854f-847f322cdf57.png)

**Comment by IvanPletnyov** [comment]
Manually I've not reproduced yet this fail, I've run it's test but it passed

**Comment by ivy00johns** [comment]
I will add an action that clicks on "Clear All" before it tries to click on the grid row.

**Comment by ivy00johns** [comment]
Issue no longer present. Closing ticket.
