### ISSUE TITLE
Fix failure of  Magento\FunctionalTestingFramework.functional.StorefrontPurchaseProductCustomOptionsDifferentStoreViewsTest

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1806]
Fix failure on http://10.234.194.23:8080/job/Functional-Tests-EE/553 Magento\FunctionalTestingFramework.functional.StorefrontPurchaseProductCustomOptionsDifferentStoreViewsTest  -  Field by name, label, CSS or XPath element with '#store_group_id' was not found.
![image](https://user-images.githubusercontent.com/27818516/47138974-646b2800-d2c3-11e8-970d-e7d39690aaa7.png)

**Comment by IvanPletnyov** [comment]
I've tried to run test locally, fail has not reproduced yet.

**Comment by okorshenko** [comment]
@smoskaluk please revalidate

**Comment by ishakhsuvarov** [comment]
Test seems to be passing at the moment. Closing.
