### ISSUE TITLE
Fix failure of Magento\FunctionalTestingFramework.functional.CreationScheduledUpdateForStagingDashboardTest

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1807]
Fix failure on http://10.234.194.23:8080/job/Functional-Tests-EE/553 Magento\FunctionalTestingFramework.functional.CreationScheduledUpdateForStagingDashboardTest  - CSS or XPath element with '#menu-magento-backend-marketing' was not found. 
![image](https://user-images.githubusercontent.com/27818516/47139072-9b413e00-d2c3-11e8-9a20-3c24f4bd7c3c.png)

**Comment by IvanPletnyov** [comment]
I've tried to run test locally, fail has not reproduced yet.

**Comment by okorshenko** [comment]
@smoskaluk please revalidate

**Comment by ishakhsuvarov** [comment]
Test does not relate to MSI and currently skipped. Presumably it would be maintained outside of MSI scope. Closing.
