### ISSUE TITLE
Fix failure of Magento\FunctionalTestingFramework.functional.CheckTierPricingOfProductsTest

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1808]
Fix failure on http://10.234.194.23:8080/job/Functional-Tests-EE/553 Magento\FunctionalTestingFramework.functional.CheckTierPricingOfProductsTest  -  Field by name, label, CSS or XPath element with '#website_name' was not found.

![image](https://user-images.githubusercontent.com/27818516/47139278-13a7ff00-d2c4-11e8-97af-f50e4c82d37d.png)

**Comment by IvanPletnyov** [comment]
I've tried to run test locally, fail has not reproduced yet.

**Comment by okorshenko** [comment]
@smoskaluk please revalidate

**Comment by ishakhsuvarov** [comment]
Test is passing in the latest Jenkins CI Builds. Closing.
[Reference](https://testing-service.magento-community.engineering/reports/magento/msi-automated-testing/pull/3/4067d1f9-6905-48e1-b63a-195c65a305b6/19223/Functional/allure-report-ce/index.html#suites/8187718e2fd144987673ef34ee62b41b/445a488d260502cf/)
