### ISSUE TITLE
Fix failure of Magento\FunctionalTestingFramework.functional.AdminRemoveDefaultVideoGiftCardProductTest

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1809]
Fix failure on http://10.234.158.55:8080/job/Functional-Tests-B2B/446 Magento\FunctionalTestingFramework.functional.AdminRemoveDefaultVideoGiftCardProductTest  -  
Error HTTP response code: 500    Response:<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" >
<head>
    <title>There has been an error processing your request</title>
    <base href="http://extfat.devops.magento.com/pub/errors/default/" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="robots" content="*"/>
    <link rel="stylesheet" href="css/styles.css" type="text/css" />
    <link rel="icon" href="images/favicon.ico" type="image/x-icon" />
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
</head>
<body>
    <main class="page-main">
        
<h1>There has been an error processing your request</h1>
    <p><em>Exception printing is disabled by default for security reasons.</em></p>

    <p>Error log record number: 679046540430</p>
    </main>
</body>
</html>

**Comment by IvanPletnyov** [comment]
I've tried to run test locally, fail has not reproduced yet.

**Comment by okorshenko** [comment]
@smoskaluk, please revalidate

**Comment by ishakhsuvarov** [comment]
Test is not skipped or blocked by MSI. Closing.
