### ISSUE TITLE
Bugfixing of Default Source and Default Stock

### ISSUE THREAD

**Issue by naydav** [magento/inventory#181]
After adding Default Source and Default Stock we have collision in
\Magento\InventoryApi\Test\Api\SourceRepository\GetListTest
\Magento\InventoryApi\Test\Api\StockRepository\GetListTest

**Comment by aleron75** [comment]
@naydav I assume the starting branch is `develop` so I branch from there.

**Comment by aleron75** [comment]
submitted PR #195 to fix this issue
