### ISSUE TITLE
Fix failure of Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.AdminUserApplyOnlyXLeftThresholdForSimpleProductOnDefaultSourceModeTest

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1810]
Fix failure on http://10.234.158.55:8080/job/Functional-Tests-B2B/446
 Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.AdminUserApplyOnlyXLeftThresholdForSimpleProductOnDefaultSourceModeTest  -  stale element reference: element is not attached to the page document

![image](https://user-images.githubusercontent.com/27818516/47140798-da718e00-d2c7-11e8-88a7-07109009c2ce.png)

**Comment by IvanPletnyov** [comment]
I've tried to run test locally, fail has not reproduced yet.

**Comment by okorshenko** [comment]
@smoskaluk, please revalidate

**Comment by ishakhsuvarov** [comment]
Test is passing on Jenkins CI. [Reference](https://testing-service.magento-community.engineering/reports/magento/msi-automated-testing/pull/3/4067d1f9-6905-48e1-b63a-195c65a305b6/19223/Functional/allure-report-ce/index.html#suites/bdc4ca065a74e08e1ba241240cb112bd/d6cc884dde305eec/)

Closing
