### ISSUE TITLE
Fix failing of Magento\FunctionalTestingFramework.functional\MSI_Sort_Order_Tests.AdminSelectDeselectManipulationsInManageStocksGridTest

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1819]
Fix failing on http://10.234.206.72:8080/job/Functional-Tests-CE/200 
Magento\FunctionalTestingFramework.functional\MSI_Sort_Order_Tests.AdminSelectDeselectManipulationsInManageStocksGridTest  -  Field by name, label, CSS or XPath element with '#idscheck21' was not found.

![image](https://user-images.githubusercontent.com/27818516/47203819-26850700-d38a-11e8-8567-aff74d8b8db0.png)

**Comment by konarshankar07** [comment]
Hello @okorshenko ,
I have tested in my local and not getting this issue. Here is the screenshot of my test results
![image](https://user-images.githubusercontent.com/39480008/63584206-15181700-c5ba-11e9-8814-d2c620099760.png)
![image](https://user-images.githubusercontent.com/39480008/63584226-1f3a1580-c5ba-11e9-9fd1-27f437bd2b16.png)

**Comment by ishakhsuvarov** [comment]
Thanks you for investigation @konarshankar07 
Looks like the issue had been fixed at some point.
