### ISSUE TITLE
Add B2B support for Multi Stock  (RequisitionListItem)

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#1823]
Based on investigation provided by @vadimjustus 

### Preconditions (*)

```
"require": {
        "composer/composer": "@alpha",
        "magento/extension-b2b": "^1.1@beta",
        "magento/inventory-composer-metapackage": "^1.0@beta",
        "magento/module-page-builder-commerce": "^100.0@alpha",
        "magento/product-enterprise-edition": "2.3.0-beta23"
    },
```

### Steps to reproduce (*)

1.  Configure 3 Sources 
2.  Configure 2 Stocks 
3.  Assign Stock A ->  Source A and Source B
3.  Assign Stock B ->  Source B and Source C
4.  Create Simple Product with the following Settings
![unnamed 1](https://user-images.githubusercontent.com/5289370/47239080-91632c00-d3e4-11e8-91f6-f30b3d63ca4f.png)

### Expected result (*)

1. [Screenshots, logs or description]
2.
![requisition_list](https://user-images.githubusercontent.com/5289370/47239261-18b09f80-d3e5-11e8-906b-794e2155fb77.jpg)

### Actual result (*)

![requisition_list_error](https://user-images.githubusercontent.com/5289370/47239229-fdde2b00-d3e4-11e8-8cab-599abb0d8b9d.jpg)

**Comment by maghamed** [comment]
https://github.com/magento/magento2b2b/pull/537

**Comment by larsroettig** [comment]
Can you review pls
https://github.com/magento/magento2b2b/pull/547/commits

**Comment by ishakhsuvarov** [comment]
Work from all linked Pull Requests was combined into a `InventoryRequisitionList` module and delivered to 1.1.3 version of Magento Inventory.
