### ISSUE TITLE
B2B QuickOrder and AdvancedCheckout MSI Support

### ISSUE THREAD

**Issue by larsroettig** [magento/inventory#1828]
### Preconditions

1.  Configure 3 Sources
2.  Configure 2 Stocks
3.  Assign Stock A -> Source A and Source B
4.  Assign Stock B -> Source B and Source C
5.  Create Simple Product with the following Settings.

### Expected result

1. [Screenshots, logs or description]
2. ![quick_order_should](https://user-images.githubusercontent.com/5289370/47269434-cf379000-d55d-11e8-98d4-4061e58aad88.jpg)

### Actual result

**B2B Quik Order Problem**
![quick_order_current](https://user-images.githubusercontent.com/5289370/47269456-0e65e100-d55e-11e8-981e-4af06b59022a.jpg)

**Advance Checkout Problem**
![shopping_cart_current](https://user-images.githubusercontent.com/5289370/47269503-ea56cf80-d55e-11e8-9da9-6a9d7218e21d.jpg)

### Info

1. B2B QuikOrder Fedure use the AdvancedCheckout to find is the Product **Out of Stock** 
```
\Magento\AdvancedCheckout\Model\Cart::_isProductOutOfStock
```

**Comment by daniloargentiero** [comment]
Waiting for ee pull request approval:

https://github.com/magento/partners-magento2ee/pull/18

**Comment by ishakhsuvarov** [comment]
One more PR has to be merged to close: https://github.com/magento/magento2b2b/pull/728

**Comment by ishakhsuvarov** [comment]
Fixed from all linked Pull Requests were combined into `InventoryAdvancedCheckout` module and added to 1.1.3 release of MSI.
