### ISSUE TITLE
Low stock report failure with simple/virtual product on custom stock

### ISSUE THREAD

**Issue by IvanPletnyov** [magento/inventory#1858]
### Hiptest scenario
https://app.hiptest.com/projects/69435/test-runs/203632/folder-snapshots/1636896/scenario-snapshots/6364815/test-snapshots/8237605

### Preconditions
1. Magento with MSI + EE version
2. Create custom stock with assigned main website and created custom source
3. Create simple(virtual) product with custom source with quantity equal to 100
4. Go to Stores -> Configuration -> Catalog -> Inventory -> Product Stock Options and set "Notify For Quantity Below" = 96 (save, run reindex and flush cache)

### Steps to reproduce
1. Create order with simple(virtual) product with quantity = 5
2. Ship(Invoice) order

### Expected result
1. Product display on Low stock report

### Actual result
1. Product is not displayed on Low stock report

### Notice! 
If you set for product  'Notify For Quantity Below' on product page  - it will be displayed in 'Low stock' report with 0 qty (updated)

**Comment by VitaliyBoyko** [comment]
HI @IvanPletnyov 
I cannot reproduce this one.
![image](https://user-images.githubusercontent.com/20116393/47804248-fc91f400-dd3c-11e8-928c-82b1d502b8de.png)

Could you please recheck the issue?

**Comment by IvanPletnyov** [comment]
@VitaliyBoyko Hello! It's reproduce only with EE version. I will continue work with this ticket.

**Comment by IvanPletnyov** [comment]
The problem is that lowstock page render in core block `Magento/Reports/Block/Adminhtml/Product/Lowstock.php` (not MSI block `Magento/InventoryLowQuantityNotificationAdminUi/Block/Adminhtml/Product/Lowstock/Grid.php`).

I think it happens because with EE version adding module Magento_Invitation which affect order of layout merge and because of that MSI layout changes to standard

**Comment by ishakhsuvarov** [comment]
Consolidating with https://github.com/magento-engcom/msi/issues/1688
