### ISSUE TITLE
 php bin/magento setup:performance:generate-fixtures  does not work with MSI

### ISSUE THREAD

**Issue by larsroettig** [magento/inventory#1870]
### Preconditions

1. Install 2.3-develop with MSI Meta package

### Steps to reproduce

1.  Run ```php bin/magento setup:performance:generate-fixtures -s setup/performance-toolkit/profiles/ce/small.xml```

### Expected result

1. All Products have a correct **Salable Quantity**

### Actual result

1. All Products have **Salable Quantity** of **null**

### Info
After i run an extra ``` bin/magento index:reindex ``` it works

**Comment by maghamed** [comment]
Looks like a duplication #1667

**Comment by larsroettig** [comment]
@maghamed i close this issue yep it is really duplication
