### ISSUE TITLE
Low stock report displays 'Out of stock' products assigned to default source

### ISSUE THREAD

**Issue by IvanPletnyov** [magento/inventory#1875]
### Preconditions
1. Magento with MSI and EE
2. Create source
3. Create stock with assigned created source
4. Create simple/virtual product . Assign it to default source with qty = 100 and save product

### Steps to reproduce
1. On created product set on default source "Notify quantity" = 101 and source item status = "Out of Stock"
2. Go to "Reports" → "Low Stock"

### Expected result
1. Product not display on low stock grid

### Actual result
1. Product present on low stock grid
![image](https://user-images.githubusercontent.com/26973706/48056393-5a4d9280-e1ba-11e8-99fc-c8d544f9be8c.png)

**Comment by SergeyP18** [comment]
1. Cretate product
![2018-11-14 09-30-42](https://user-images.githubusercontent.com/37869098/48466935-0103e580-e7f0-11e8-9229-af23fb1a2f24.png)
2. Go to "Reports" → "Low Stock"
![2018-11-14 09-32-04](https://user-images.githubusercontent.com/37869098/48467018-53dd9d00-e7f0-11e8-8f7a-d21ec36356f7.png)
Product not view in report.

**Comment by IvanPletnyov** [comment]
@SergeyP18 Hi! I've rechecked this bug, it still reproduce(low stock report displays 'Out of stock' products).
Gif:
![low stock proof](https://user-images.githubusercontent.com/26973706/48605288-021a4b80-e985-11e8-8f33-216a38a0492b.gif)

**Comment by ishakhsuvarov** [comment]
Consolidating with https://github.com/magento-engcom/msi/issues/1688
