### ISSUE TITLE
Return to stock during Credit memo for order with virtual product not respecting sources priority for stock

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1895]
### Preconditions

1. Magento MSI
2. Custom stock with two custom sources created
3. Set 'custom source 2' to have higher priority then 'custom source 1'
4. Create virtual product with qty = 100 on both custom sources

### Steps to reproduce

1. Place order with 1 item of virtual product and make invoice for it
2. Verify that 1 item of virtual product deducted from 'custom source 2'
3. Create credit memo with return to stock on 
4. Check qty on sources for your virtual product

### Expected result

1. 'custom source 2' should have qty = 100 and 'custom source 1' should have qty = 100

### Actual result

1. 'custom source 2' has qty = 99 and 'custom source 1' has qty = 101

![image](https://user-images.githubusercontent.com/27818516/48418751-c3a34780-e75e-11e8-8f3a-72cacbf5c4ac.png)

**Comment by VitaliyBoyko** [comment]
Hi @smoskaluk 
I can't reproduce the issue on the latest 2.3-develop branch of CE Magento with MSI. Could you please recheck it?
![image](https://user-images.githubusercontent.com/20116393/48439906-22cd8000-e790-11e8-98b1-d9f530445910.png)

**Comment by smoskaluk** [comment]
@VitaliyBoyko I can still reproduce this issue on latest 2.3-develop branch

**Comment by maghamed** [comment]
Step 1
![image](https://i.imgur.com/Nk4g2gk.png)

Step 2
![image](https://i.imgur.com/yQq6SPt.png)

Step 3
![image](https://i.imgur.com/f6OKPg6.png)

Step 4
![image](https://i.imgur.com/L8WVZdF.png)
