### ISSUE TITLE
Cancellation of partially invoiced order with fixed bundle product isn't create

### ISSUE THREAD

**Issue by IvanPletnyov** [magento/inventory#1906]
### Preconditions
1. Magento with MSI
2. Multi source mode
3. Create Simple product on default source with quantity equal to 100
4. Create fixed bundle product (with created simple product with default quantity = 1)
Example:
- Dynamic SKU = No
- Dynamic Price = No
- Dynamic weight = No
![image](https://user-images.githubusercontent.com/26973706/48544312-fd459100-e8cb-11e8-8341-5dc651a0c016.png)

- Ship Bundle Items = Together
![image](https://user-images.githubusercontent.com/26973706/48544346-0f273400-e8cc-11e8-9977-22e48a14c593.png)

### Steps to reproduce
1. Create order with bundle product with quantity equal to 5
2. Create invoice with quantity equal to 3
3. Cancel order

### Expected result
1. Salable quantity on Default stock = 97
2. Canellation reservation was created

### Actual result
1. Salable quantity on Default stock = 95
2. Canellation reservation isn't created

### Additional screenshots
1. Products grid
![image](https://user-images.githubusercontent.com/26973706/48544656-c02dce80-e8cc-11e8-9e31-5fa306794eea.png)

2. Order
![image](https://user-images.githubusercontent.com/26973706/48544691-d20f7180-e8cc-11e8-9669-8254eec84821.png)

**Comment by ishakhsuvarov** [comment]
Seems to be merged in #1919
