### ISSUE TITLE
Credit memo work incorrectly on invoiced and partially shipped order with configurable

### ISSUE THREAD

**Issue by IvanPletnyov** [magento/inventory#1910]
### Preconditions
1. Magento 2.3 with MSI
2. Create configurable with two option with quantity = 100
3. Create order with configurable option with quantity equal to 10

### Steps to reproduce
1. Create shipping with quantity = 6
2. Create invoice with quantity = 10 (all ordered quantity)
3. Create credit memo with quantity = 7

### Expected result
1. Quantity of ordered product = 100

### Actual result
1. Quantity of ordered product = 97

### Additional screenshots
1. Order
![image](https://user-images.githubusercontent.com/26973706/48559608-9be5e800-e8f4-11e8-97b8-49ab40bbc779.png)

2. Products grid 
![image](https://user-images.githubusercontent.com/26973706/48559659-b1f3a880-e8f4-11e8-9b21-b528769d60e2.png)

3. Reservations
![image](https://user-images.githubusercontent.com/26973706/48559692-c2a41e80-e8f4-11e8-8ae7-f7cb56e36494.png)

**Comment by maghamed** [comment]
This is expected behavior
