### ISSUE TITLE
Feature Request: Assign price or discount price based on inventory

### ISSUE THREAD

**Issue by seansan** [magento/inventory#1925]
### Description
Feature Request: Assign price or discount price based on inventory

### Expected behavior
Some inventory is old or consists of returns or we need to get rid of it. The same product however might exist in other inventories. Or at an inventory at the supplier. 

So to start it would be really great of we are able to 
- create a (dynamic) category that consts ONLY of products from inventory = X
- assign a catalog price rule to : only this inventory, or only this category -- and more importantly ONLY this product
(both would work; but a little differently)

Important checkpoint for understanding. Suppose we have Bicycles Red and Blue. Where the bicycle is a configurable. Red and BLue are the simple product children. Suppose all Blue Bicycles are on sale because they exist in the certain _cleanup_ WH. Then the category + layered navigaiton should contain Blue Bicycles **only**. And the discount is also for the Blue Bicycles **only**.

### Benefits
Some inventory is old or consists of returns or we need to get rid of it. We can discount only the products that really need to be discounted. Please realize that sometimes we have an inventory clearance and you would want to get rid (really get rid) of these products with say 50% or 70% discounts.

**Comment by maghamed** [comment]
This is definitely an interesting idea to consider especially it would be useful for merchants who build a marketplace. But here we need no consider B2B requirements first. I believe this topic deserves a dedicated grooming meeting with @mbrinton01

**Comment by seansan** [comment]
groomed? ;P

**Comment by mbrinton01** [comment]
Currently several members of the team are traveling to support community events. We will add this for discussion in the next grooming meeting.

**Comment by seansan** [comment]
Thanks I see many status changes ... but? where is it now

In fashion when the sales season starts one often wants to discount particular products from 1 stock only. For instance: suppose we want to het rid of ALL the returned items only using a whopping! 50% discount

It would be great if we can target these products only ... create a category based on these items only or show the option that 1 product in size 44 is available with 50%

**Comment by mbrinton01** [comment]
We are still working on the B2B items mentioned above. In the use case you list above, it is already possible to discount the Blue bicycles because _all_ of them are in a single warehouse, and it is a different warehouse for Red bicycles. How would you handle a more complex case where there are Blue bicycles in multiple warehouses, but you only want to discount the bicycles in one warehouse? In such case what price do you expect to show on the frontend to the customer? Because in this case _some_ of the SKU would be at a discount and some not.

**Comment by seansan** [comment]
>> How would you handle a more complex case where there are Blue bicycles in multiple warehouses, but you only want to discount the bicycles in one warehouse? I

Yes one would want to discount the bikes from 1 source only ... maybe create a separate category for it where the category "only" sources availability from that 1 ware house. 

A good example in NL is het "second chance" model. Here merchants send returns (so red bikes that were sold, unpackaged and returned) to a separate warehouse. Merchants then try to sell these bikes _before_ any other bike is sold. At a discounted rate. 

Another example is in the case of configurable products where say only 1 size TSHIRT should be discounted because only that size lives in the discounted source.

I can imagine some logic where the catalog grid is loaded from 1 source only. Filters and availability is loaded from 1 source only.

**Comment by mbrinton01** [comment]
Would adding an option or filter to category settings meet the use case? For example, when setting “Products in Category” the admin user would have a multi-select option for inventory sources. They could select Warehouse A and Warehouse B as a filter and only products with inventory in these sources would appear in the category.

Also, how would you expect this to be handled at checkout? Right now the Source Selection Algorithm is not be aware of any category filtering.  Example:

Product xyz
Warehouse A: qty 20
Warehouse B: qty 4
Warehouse C: qty 5

Category 1: Configured for Warehouse A + Warehouse B for Product xyz
Category 2: Configured for Warehouse C for Product xyz

20% Discount Price rule assigned for Category 2.

In this case if a customer browses Category 2 and places an order for Product xyz, the Source Selection Algorithm would not necessarily recommend delivery from Warehouse C. It would recommend shipments based on the settings used (source priority or distance). Also, if a product is in multiple categories and discounted in one of them, it will be discounted in all of them. It doesn’t make sense to have a different price for the product depending on where it is in the site navigation. How would you handle this pricing issue?

**Comment by seansan** [comment]
Thanks Mark and good questions. I do agree there is some complexity here. 

>> Also, how would you expect this to be handled at checkout? Right now the Source Selection Algorithm is not be aware of any category filtering.

If a category would be sourced by only source A + B (where A + B + C are the regular Stock for this Channel) then when adding to cart it could ignore Source C. So the addtocart action would influence the source selection logic based on the category. 

Another options and more in line with reality is that often the products that are in scope are no longer available elsewhere. And also the stock source offering the discount would often in real life have the lower prio (selected first). 

However thus/when the product is no longer in stock in A + B / discounted category it should fallback to regular pricing and processes.

>> 20% Discount Price rule assigned for Category 2.

This would mean there is a Shopping Cart Pricerule, another option would be an Catalog Price Rule = but this would infer prices _per_ simple product _per_ store _per_ source location. But yes this would solve the idea for a large part.

So - just to be clear - and this is not the solution, just the idea: 

- one would want to create a category having products only from 1 source
- these products and only these products are discounted / maybe even only in this 1 category (and if found elsewhere in the same store they are not discounted)
- when adding to cart the discounted price for this product (alone) is used

**Comment by mbrinton01** [comment]
I understand your proposal. It would require several significant changes:

- Update category settings to add the ability to define "Products in Category" with inventory sources.
- Verify frontend category products are displayed properly after making changes to category settings options
- Modify catalog rules to allow including inventory sources as a condition for rules (also it still does not make sense to have a product available for a lower price in one category vs. another on the frontend. The current cart does not know which category a product "came from" when calculating any cart price rules)

It's not likely we will take up work on this in the near future given other features in consideration. In the meantime, we'd still be interested in more feedback on how to address the pricing issue (customer could see different prices for same product based on category).

**Comment by seansan** [comment]
Yes I think this captures it. And yes it is difficult ... but it would also
add a great feature that maybe solves an even larger issue: that is of
returns / damaged products / old stock

Here you can find an example case that is quite popular over here - and
demonstrates why one could have 2 prices for the same product :
https://www.coolblue.nl/en/second-chance-product/783107

The item under the link is availabel BOTH for price X and Y ... and the
producut with pricee X comes from another WH and has been returned before
by a customer ... the store owner wants to offer a small price reduction to
sell this item first

Hope it helps

thanks, Sean

**Comment by mbrinton01** [comment]
Thank you for the example. From browsing the site it appears they are using two different SKUs to handle this situation - one for the New product and a separate SKU for the "Second Chance" product. Will note this for future development.

**Comment by sidolov** [comment]
Hi @seansan  , we are about to complete MSI project feature development and keep issues of defined scope only to have clean and transparent backlog. 
Unfortunately, the current issue is out of scope and should be closed. 
Thank you for your involvement!

**Comment by seansan** [comment]
My advise is NOT to close this issue. It is of strategic importance and can already be executed by other SW solutions. 

What I see is that Magento is implementing mostly already existing logic ... whilst sometimes we shoud stretch ourselves and try to add something new
