### ISSUE TITLE
DOCS - Store Pick Up Documentation

### ISSUE THREAD

**Issue by lorikrell** [magento/inventory#1932]
Add documentation and information for implementing in-store pickup option for orders. This affects the following merchant information:

- Create/add sources for storefronts supporting shipping and in-store pickup
- Cancelations and returns may be affected on timing of fulfilled purchases, invoicing to affect stock (when picked up only? etc)
- In-store returns for credit memos

Requires docs, screenshots, and workflow

**Comment by sidolov** [comment]
Will be delivered in scope of devdocs issues
