### ISSUE TITLE
Configurable product out of stock after mass transfer from default source

### ISSUE THREAD

**Issue by lorikrell** [magento/inventory#1939]
Updated steps after reindexing test. 

Only an issue if you Mass Transfer quantity with the configurable + simple product configurations all selected, moving Default Stock to a custom stock. Works fine if you only select simple product configurations (not the configurable).

### Preconditions

1. Installed 2.3.0 + MSI.
2. This occurred with and without sample data installed.
3. With sample data, existing products have quantities assigned to Default Source. 
4. Main website assigned to Default Stock. 
5. No custom sources/stocks.

### Steps to reproduce

1. Create 2 custom sources, 1 custom stock. 
2. Assign custom sources and main website to custom stock.
3. Verify existing Configurable Product is in stock.
4. Select configurable product and configuration simple products (not only configurations).
5. Select Actions > Transfer Inventory to Source.
6. Select  custom source and complete. Even if you remove Default Source during transfer, still occurs.
7. Reindex/clear caches.

If you create a new configurable product, and add a custom source, it works fine. Only occurs for Default Source transfers 

### Expected result

1. Configurations update with 100% of Default Source quantity transferred to custom source.
2. Configurable product in stock.

### Actual result

1. 100% of Default Source quantity transferred to custom source.
2. Configurable product is out of stock in Admin.
3. Products show as Out of Stock on storefront even if the configurations have quantities on a custom source, and source assigned to the custom stock and website sales channel. Reindex/cache clear doesn't help.

![image](https://user-images.githubusercontent.com/29388020/49905686-4f7ac300-fe34-11e8-9e7b-6deded35a5bf.png)

## More info

Only occurred when transferring from Default Source and configurable product selected with all configurations.
Works as expected if you only select the Configurations, not the Configurable Product. 
Verified issue with Mark Brinton.

**Comment by smoskaluk** [comment]
@lorikrell Hi, Lori! I guess problem is that your current stock assigned to Main website is Default stock - so on it you have no quantity for your Configurable child products - so Configurable  has status 'Out of stock'. If you assign Main website to your custom stock - where your Austin Warehouse assigned as well - and perform reindex - the status of Configurable will be 'In stock'.

**Comment by lorikrell** [comment]
From Slava:  Hi, Lori! I guess problem is that your current stock assigned to Main website is Default stock - so on it you have no quantity for your Configurable child products - so Configurable has status 'Out of stock'. If you assign Main website to your custom stock - where your Austin Warehouse assigned as well - and perform reindex - the status of Configurable will be 'In stock'.


Lori reply: In the example, we have the main website assigned to a custom stock, not default stock, and added custom sources. Mark brought this one to me to figure out why mass transferring the quantity from default source to custom source still hid the configurable product.

He had an existing product with quantities on default source. He wanted to mass transfer to new custom source. But if you select the configurable and it’s configuration simple products, it puts it into Out of Stock. If you only select the simple product configurations, not the configurable, it remains in stock.

I’ll run another check to see if reindexing fixes it. It hadn’t worked for us when we tested

**Comment by lorikrell** [comment]
Checking this out based on feedback from Slava. Will verify his info to see if this is an issue or requires additional documentation to solve. Thanks!

**Comment by lorikrell** [comment]
Tried the reindexing, didn't help. If you have configurable product selected AND simple product configurations, transfer from Default Source to custom source, it is out of stock. Reindex/cache clear didn't fix.
Updated steps with more info and screenshot.

**Comment by slacka1** [comment]
Not 100% sure if related, but on Magento2.3/msi-1.1, using Default Stock in single store mode, my configurable product shows as out of stock, despite children all having stock and showing as in stock.
