### ISSUE TITLE
Source items deduction during Credit memo creation for unshipped order items

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1947]
During creating Credit memo for unshipped order next changes should be applied:
1. Set by default in new Credit memo document option "Return to stock" if order items was not shipped yet.
2. If merchant choose to not "Return to stock" orders items - deduct them from the source using SSA by  sources priority
3. Compensational reservations should be created for deducted items on corresponding Stock.

**Comment by ishakhsuvarov** [comment]
Fixed in #2179 

Many thanks @seruymt

**Comment by xavierojeda** [comment]
Point 2 (Line 97 in InventorySales/Model/ReturnProcessor/DeductSourceItemQuantityOnRefund.php [commit](https://github.com/magento/inventory/commit/c74de3a1b6dbf41bc3c2d5adf9f9c7cbbba54e12)) makes no sense with MSI enabled. Why would we be deducting the stock from the order item if the merchant chooses not to "Return to stock"?
