### ISSUE TITLE
Invalid type cast and status calculation based on quantity column during stock_sources import

### ISSUE THREAD

**Issue by zebimax** [magento/inventory#1948]
### Preconditions

1. Magento 2.3-develop msi `version`

### Steps to reproduce

1. Try to Import stock_sources data
2. do not fill status column in csv
3. Use standart import page to import file
### Expected result

1. Validation is successfull
2. Status column is set based on quantity column
3. Import is successful

### Actual result

1. Validation is successfull
2. Import is not successfull

`PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Magento\Inventory\Model\SourceItem::setStatus() must be of the type integer or null, boolean given, called in /vendor/magento/module-inventory-import-export/Model/Import/SourceItemConvert.php on line 47 and defined in /vendor/magento/module-inventory/Model/SourceItem.php:93
Stack trace:
#0 /vendor/magento/module-inventory-import-export/Model/Import/SourceItemConvert.php(47): Magento\Inventory\Model\SourceItem->setStatus(true)
#1 /vendor/magento/module-inventory-import-export/Model/Import/Command/Append.php(45): Magento\InventoryImportExport\Model\Import\SourceItemConvert->convert(Array)
#2 /vendor/magento/module-inventory-import-export/Model/Import/Sources.php(94): Magento\InventoryImportExport\Model\Import\Command\Append->execute(Array)
#3 /vendor/magento/module-import-export/Model/Import/Entity/A in /vendor/magento/module-inventory/Model/SourceItem.php on line 93
`
I assume there is no valid casting to (int) at https://github.com/magento-engcom/msi/blob/2.3-develop/app/code/Magento/InventoryImportExport/Model/Import/SourceItemConvert.php#L43:
insead of
       `$status = (int)$rowData[Sources::COL_QTY] > 0;`
should be
 `$status = (int)($rowData[Sources::COL_QTY] > 0);`

**Comment by maghamed** [comment]
Thanks for this bug report @zebimax ! We will add it to the scope of the current Milestone
