### ISSUE TITLE
Argument 1 passed to Magento\InventoryShipping\Model\GetSourceSelectionResultFromInvoice::getSelectionRequestItems() must implement interface Traversable, array given

### ISSUE THREAD

**Issue by cscd98** [magento/inventory#1952]
### Preconditions (*)
1. Magento 2.3.0 EE
2. PHP 7.2.13
3. MySQL 5.7.24

### Steps to reproduce (*)
1. Add to basket a simple product and a virtual product
2. Proceed to checkout
3. In code, the invoice is captured and saved in my own controller after 3dsecure has completed. This code works perfectly when payment for a simple sku on it's own.

```
 /**
     * @param OrderInterface $order
     */
    private function capture($order) {

        /** @var Invoice $invoice */
        $invoice = null;

        foreach ($order->getInvoiceCollection() as $previousInvoice) {
            $invoice = $previousInvoice;
            $invoice->capture();
        }

        if($invoice && $invoice->getId()) {
            $this->invoiceRepository->save($invoice);
        }
    }
```

After save, VirtualSourceDeductionProcessor is called from here due to event 'sales_order_invoice_save_after' in vendor/magento/module-inventory-shipping/etc/events.xml

An exception is generated below.

### Expected result (*)
1. No crash

### Actual result (*)
1.

Exception thrown:

```
2018/12/18 16:59:26 [error] 18261#18261: *8430 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Magento\InventoryShipping\Model\GetSourceSelectionResultFromInvoice::getSelectionRequestItems() must implement interface Traversable, array given, called in /home/ccarnell/Sites/xx-uk2/vendor/magento/module-inventory-shipping/Model/GetSourceSelectionResultFromInvoice.php on line 96 and defined in /home/ccarnell/Sites/xx-uk2/vendor/magento/module-inventory-shipping/Model/GetSourceSelectionResultFromInvoice.php:107
Stack trace:
#0 /home/ccarnell/Sites/xx-uk2/vendor/magento/module-inventory-shipping/Model/GetSourceSelectionResultFromInvoice.php(96): Magento\InventoryShipping\Model\GetSourceSelectionResultFromInvoice->getSelectionRequestItems(Array)
#1 /home/ccarnell/Sites/xx-uk2/vendor/magento/module-inventory-shipping/Observer/VirtualSourceDeductionProcessor.php(96): Magento\InventoryShipping\Model\GetSourceSelectionResultFromInvoice->execute(Object(Magento\Sales\Model\Order\Invoice))
#2 /home/ccarnell/Sites/xx-uk2/vendor/magento/f" while reading response header from upstream, client: 127.0.0.1, server: www-local2.xx.co.uk, request: "POST /realex/remote/validate3d/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "www-local2.xx.co.uk", referrer: "https://pit.3dsecure.net/VbVTestSuiteService/pit1/acsService/paReq?summary=xx"
````

**Comment by maghamed** [comment]
@craigcarnell thanks for this bug report! We will deal with it shortly.

Looks like the main issue here is the contract of 

```php
    /**
     * @param InvoiceItemInterface[]|Traversable $invoiceItems
     * @return array
     */
    private function getSelectionRequestItems(Traversable $invoiceItems): array
```

Because PHP can't deal with `array|Traversable` as a type. 

What supposed to be here is `iterable` pseudo type introduced since PHP 7.1 - http://php.net/manual/en/language.types.iterable.php

_Iterable is a pseudo-type introduced in PHP 7.1. It accepts any array or object implementing the Traversable interface. Both of these types are iterable using foreach and can be used with yield from within a generator._

and we can easily introduce these changes as type of the method is `private`

**Comment by cscd98** [comment]
@Stepa4man @maghamed Can confirm that PR fixes my issue, thanks :+1: 

Hope it's included in 2.3.1.

**Comment by maghamed** [comment]
@craigcarnell  it would be delivered much sooner than 2.3.1 release, as MSI releases are not coupled to main Magento project release timeline.
Currently, we plan to bundle next patch release of MSI at the beginning on January, 2019

btw, merged this PR into MSI mainline, thanks @Stepa4man for contribution!

**Comment by Stepa4man** [comment]
@craigcarnell, @maghamed 
It's pleasure!!! Thanks!

**Comment by cscd98** [comment]
@maghamed Do you have an update on when the next release is please?

**Comment by maghamed** [comment]
@craigcarnell  this week
