### ISSUE TITLE
Fix work of asynchronous  bulk inventory  operations configured on MySQL DB connection 

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1962]
Fix work of asynchronous  bulk inventory  operations configured on MySQL DB connection via message queue in module InventoryCatalogApi
https://devdocs.magento.com/guides/v2.3/extension-dev-guide/message-queues/config-mq.html

**Comment by maghamed** [comment]
https://github.com/magento/async-import/issues/19

**Comment by sidolov** [comment]
Closing since it's not implemented in core and should be fixed across the platform after implementation
