### ISSUE TITLE
Make error message more informative for mass inventory transfer 

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1963]
Make error message more informative for mass inventory transfer 

![image](https://user-images.githubusercontent.com/27818516/50450959-c5ede980-0939-11e9-92c6-a81c59d4b0c6.png)

**Comment by lorikrell** [comment]
I can help with the error messaging, depending on the action that failed.

**Comment by lorikrell** [comment]
Could also make this part of this issue: https://github.com/magento-engcom/msi/issues/1584
Just need to know the scenarios that trigger an error. That error is a core Magento all else fails general error.

**Comment by phoenix128** [comment]
Displaying the real error may lead to a sensitive information discovery. The actual error should be available in the Magento error log.

**Comment by sidolov** [comment]
Totally agree with @phoenix128 , sensitive information may be exposed. Full error information should be available in the application log. Closing the issue since it not relevant anymore.
