### ISSUE TITLE
Improve performance of Sources sorting in SSA

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#1990]
Currently, the final order fulfillment among sorted sources list implemented not efficiently (especially for those merchants who have a lot of Sources)

```

        //TODO from performance perspective it's better to switch these foreaches and make the inner one
        //TODO which loops over sources to be outermost and iterate over inventory request items inside
```

https://github.com/magento-engcom/msi/blob/2.3-develop/app/code/Magento/InventorySourceSelectionApi/Model/Algorithms/Result/GetDefaultSortedSourcesResult.php#L108-L109

**Comment by bpetering** [comment]
#mlau
