### ISSUE TITLE
Magento_InventorySalesApi is missing acl.xml

### ISSUE THREAD

**Issue by m-schreiber** [magento/inventory#1995]
### Preconditions (*)

1. Magento Version 2.3.*
2. Magento_InventorySalesApi Version 1.0.0

### Steps to reproduce (*)

1. Add New Integration
2. Try to grant access to "InventorySalesApi::stock" as used in module-inventory-sales-api/etc/webapi.xml
3. Try to use API-Endpoint "GET http://<host>rest/us/V1/inventory/get-product-salable-quantity" as described in https://devdocs.magento.com/guides/v2.3/rest/tutorials/inventory/create-cart-add-products.html

### Expected result (*)

1. "InventorySalesApi::stock" should be available in ACL-List when adding Integrations
2. API-Endpoint should respond with HTTP-Status 200 and valid response

### Actual result (*)

1. "InventorySalesApi::stock" not available in ACL-List
2. API-Endpoint returns "401 Unauthenticated"

### Proposal:
1. Rename Resource "InventorySalesApi::stock" to "Magento_InventorySalesApi::stock" in "module-inventory-sales-api/etc/webapi.xml"
2. Add "inventory-sales-api//etc/acl.xml" with following content:
```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Acl/etc/acl.xsd">
    <acl>
        <resources>
            <resource id="Magento_Backend::admin">
                <resource id="Magento_Backend::stores">
                    <resource id="Magento_InventoryApi::inventory" title="Inventory" translate="title" sortOrder="10">
                        <resource id="Magento_InventorySalesApi::stock" title="Sales Stock" translate="title" sortOrder="10" />
                    </resource>
                </resource>
            </resource>
        </resources>
    </acl>
</config>
```

**Comment by maghamed** [comment]
The fix has been merged into MSI mainline 2.3-develop branch and would be released shortly
