### ISSUE TITLE
Delete disabling new inventory modules

### ISSUE THREAD

**Issue by IvanPletnyov** [magento/inventory#1996]
### Summary
Don't disable modules:
1. Magento_InventoryDistanceBasedSourceSelection
2. Magento_InventoryDistanceBasedSourceSelectionAdminUi
3. Magento_InventoryDistanceBasedSourceSelectionApi
4. Magento_InventoryElasticsearch

, if module Magento_InventoryApi already enabled.

**Comment by maghamed** [comment]
Not delete module disabling, but don't disable NEW MSI modules if some MSI modules already enabled

**Comment by maghamed** [comment]
Fixed
