### ISSUE TITLE
Provide API service which calculates nearby ZIP code addresses (functionality used in Store Pickup) by given ZIP code

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#2006]
Provide API service which provides nearby ZIP code addresses for a given ZIP code (functionality used in Store Pickup), based on downloaded GeoData for Distance-Based Algorithm.

The semantic of service should be similar to:

```
interface GetNearbyZipCodes
{
    /**
     * Get Nearby ZIP codes for the given one
     *
     * @return array  of SourceInterface
     */
    public function execute(string $zip, int $radius): array;
}
```

https://camo.githubusercontent.com/7ec324be02fcb73c8d7946f0a834cb37a0fafaec/68747470733a2f2f692e696d6775722e636f6d2f624739724773612e706e67

Documentation for Distance-Based algorithm could be find here - 
https://github.com/magento-engcom/msi/wiki/Configure-MSI-SSA

**Comment by mcspronko** [comment]
Talking this issue.

**Comment by kathyoungaligent** [comment]
Taking this ticket please

**Comment by kathyoungaligent** [comment]
@maghamed can you please provide any more detail on where/how to obtain the referenced GeoData?

**Comment by mcspronko** [comment]
@kathyoungaligent it appears that I am working on this ticket.

**Comment by kathyoungaligent** [comment]
I have an open PR for this issue on the store pick up epic
