### ISSUE TITLE
Rename "Shipping Step" into "Delivery Method" on Magento Checkout

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#2028]
Since Store Pickup added, it's not correctly anymore to use the term "Shipping Step".

Rename "Shipping Step" into "Delivery Method" on Magento Checkout
https://github.com/magento-engcom/msi/wiki/Support-of-Store-Pickup-for-Multi-Source-Inventory

**Comment by toddhainsworth** [comment]
Will take this for MLAU

**Comment by toddhainsworth** [comment]
Hi @maghamed !

Am I correct in thinking this is the "Shipping" label at the very top of this screenshot?
https://camo.githubusercontent.com/13004e078dbcad254523a4ac5fb72c45c955f98f/68747470733a2f2f692e696d6775722e636f6d2f4c7378464466722e706e67

-Todd

**Comment by toddhainsworth** [comment]
PR #2033 created and assigned to you @maghamed  :+1: :smile:

**Comment by ishakhsuvarov** [comment]
@toddhainsworth Thank you for the PR. It's now merged into `store-pickup` branch. I'm not closing this ticket at the moment, as it seems that Checkout label is still not renamed.
