### ISSUE TITLE
Add UI button "Shipping" and "Pick in Store" for Shipment step during Checkout

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#2029]
UI changes described on mockup here - https://github.com/magento-engcom/msi/wiki/Support-of-Store-Pickup-for-Multi-Source-Inventory

**Comment by krzksz** [comment]
As far as I can see in the linked document there are 2 approaches:
- Regular shipping address form with store pickup as a shipping option.
- Toggle between shipping and store pickup without shipping options selector.

Could you please clarify what is the final idea for checkout UI?

**Comment by ishakhsuvarov** [comment]
Closing in favor of #2227
