### ISSUE TITLE
Add possibility to define Source to use for In Store Pickup

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#2031]
How does Store Pickup work from a Merchant point of view

A merchant should have the ability to specify which Sources support Store Pickup. To do so we have to introduce corresponding Extension Attribute for Source entity and provide an ability to specify one via both Admin UI on the Source editing page and Web APIs. Based on the attribute value (whether it set) we will add the corresponding Source to the Store Pickup Drop-Down list.

https://github.com/magento-engcom/msi/wiki/Support-of-Store-Pickup-for-Multi-Source-Inventory#How-does-Store-Pickup-work-from-a-Merchant-point-of-view

**Comment by the-midi** [comment]
Will have a look at this one.
