### ISSUE TITLE
Add "Ready for Pickup" button on the Order page in Admin Panel which notifies Customer that Order could be picked up

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#2034]
Add "Ready for Pickup" button to the Order Admin page for orders created with Store Pickup method, click on this button will initiate email notification to the customer if there are enough Qty on a selected source to fulfill the order.

If there are NOT enough Qty to fulfill order the merchant should be notified that he has to proceed with  Internal Transition (from Source B -> Source A ) to increase Qty for the Source used in Store Pickup.

**Comment by TadeuRodrigues** [comment]
I'm starting to work.

**Comment by maghamed** [comment]
hey @TadeuRodrigues  do you have any result so far? or should we make this ticket available for up for grabs?

**Comment by TadeuRodrigues** [comment]
@maghamed yes I have, let me finish some tests than I will send my branch.

**Comment by novikor** [comment]
> If there are NOT enough Qty to fulfill order the merchant should be notified that he has to proceed with Internal Transition 

@maghamed, could you suggest a way we can implement this behavior?
How and where the notification should look like?
As I know, there are no mechanisms for Internal Transitions, are they?

**Comment by TadeuRodrigues** [comment]
@novikor i was working in this issue, let's me send my branch.

**Comment by novikor** [comment]
@TadeuRodrigues  - thanks, let`s try

**Comment by novikor** [comment]
@maghamed , I suggest just to display a warning when the button is not displayed.

**Comment by ishakhsuvarov** [comment]
Closing this ticket now, as initial implementation is already delivered to the `store-pickup` branch in #2127
