### ISSUE TITLE
"Only X left" message displays for out of stock products

### ISSUE THREAD

**Issue by krzksz** [magento/inventory#2042]
### Preconditions

1. Magento 2.3.0 with MSI.
2. `Only X left Threshold` option set to default `0`.
3. Simple product created with `0` quantity and `Out of Stock` status.

### Steps to reproduce

1. Go to product's page.
2. Check product's buybox.

### Expected result

1. `Out of stock` note is displayed.
2. `Only 0 left` note is not displayed.

### Actual result

1. Both `Out of stock` and `Only 0 left` messages are displayed.

If I understand the functionality and this issue correctly, then an additional check if saleable quantity is greater then `0` is missing under https://github.com/magento-engcom/msi/blob/2.3-develop/app/code/Magento/InventorySalesFrontendUi/Plugin/Block/Stockqty/AbstractStockqtyPlugin.php#L77

If you confirm that this is indeed an issue, then we have a patch already prepared and will be happy to submit a PR for it.

**Comment by smoskaluk** [comment]
Hi @krzksz, thank you for your report, I can confirm that bug is reproducing. Please provide PR as you wrote in your comment. We are grateful for your contribution!

**Comment by maghamed** [comment]
The Issue is added to the backlog of current Milestone
