### ISSUE TITLE
Product saleable qty displays wrong count

### ISSUE THREAD

**Issue by VZeroCool** [magento/inventory#2046]
### Preconditions

1. Magento 2.3 CE
2. Apache 2.4.37 PHP 7.2

### Steps to reproduce

1. Create 2 sources China and Germany.
![sources](https://user-images.githubusercontent.com/36662131/52929532-cb304900-336a-11e9-9235-f46b6c960ab0.png)

2. Assign created sources to stock.   
![stocks](https://user-images.githubusercontent.com/36662131/52929547-d3888400-336a-11e9-9593-0498f32acaf8.png)

3. Create simple product with 2 sources and add respectively 10 qty to both new sources china and germany.

4. Check product grid. 

### Expected result

1. Total salaeble qty has to be total count of assign sources.
2. China has to be 10 qty same for germany, Total salable ty has to be 20.

### Actual result

1. Displays worng count. ![product grid](https://user-images.githubusercontent.com/36662131/52929705-848f1e80-336b-11e9-98bf-0e04c60d3400.png)

**Comment by IvanPletnyov** [comment]
@VZeroCool Hello. I've checked this issue by your steps, I can't reproduce bug.
![image](https://user-images.githubusercontent.com/26973706/52962186-4b73a000-33a5-11e9-9482-77b654745c5f.png)

Maybe you can give me more information ? For example, is it fresh install ? Did you create orders with this product or maybe you did some other manipulations with the same sku, source codes etc...

**Comment by maghamed** [comment]
Hey @VZeroCool , thanks for your bug report. 

Looks like the root cause of the issue is the dirty state of your reservations. Read more about reservations mechanism here - https://github.com/magento-engcom/msi/wiki/Salable-Quantity-Calculation-and-Mechanism-of-Reservations

Can you please provide a dump of this SQL query to see what reservations are created for given SKU:
```
mysql> select * from inventory_reservation where sku = 'your_sku_here';
```

**Comment by maghamed** [comment]
Also, such situation is possible if you have the next configuration:
**Backorder** is enabled
AND
**Out-of-Stock Threshold** is set to -20

Read more about this here:
https://github.com/magento-engcom/msi/wiki/Configure-MSI-backorders

**Comment by VZeroCool** [comment]
@maghamed, If I execute your given SQL query it returns null for me. 

**No backorders enabled** and an **out-of-stock threshold is set to 0.**

**Comment by VZeroCool** [comment]
@maghamed, It was working expected when I set up and configured MSI than after I placed several orders and using PayPal and different payment methods it starts behaving weirdly.

**Comment by VZeroCool** [comment]
@maghamed, Is there any way by which I can clear all MSI data ? 
Possibly you can provide SQL to clear MSI information from DB. 
So that I can setup MSI from scratch and track where its causing problem ?

**Comment by IvanPletnyov** [comment]
@VZeroCool Could you please create test source with code which you never used in the system, create new test stock (assign created source to stock) and create product with sku which you never used (assign created source to product) and try to reproduce this issue.

**Comment by maghamed** [comment]
@VZeroCool 
>@maghamed, If I execute your given SQL query it returns null for me.

Sorry, just to clarify, did you substitute `your_sku_here` with SKU of your product? 
```
mysql> select * from inventory_reservation where sku = 'your_sku_here';
```

All the sources where MSI keeps its data are in tables:
`inventory_reservation` - storing reservations
`inventory_stock_N` - where N is stock ID, stores aggregated stock data without reservations
`inventory_source_item` - qty per each warehouse

That's all. So, you can track what makes 40 appear instead of 20

**Comment by maghamed** [comment]
@IvanPletnyov  the case you described would not show a problem in computation. 
We have to find a reason why data polluted. 
And the reason for this mistake is orders which have been placed, and probably some issue happened with the processing of these orders.

Based on the data in the tables I mentioned above we can try to define this reason

**Comment by VZeroCool** [comment]
@IvanPletnyov  and @maghamed, Thanks guys for an explanation but the problem was at ERP not in MSI.  

One more thing I need to know there's inbuilt inventory transfer available but it only transfers all qty's not specific.  

I think it's necessary to give an option to transfer specific qty to a specific source.

**Comment by maghamed** [comment]
>One more thing I need to know there's inbuilt inventory transfer available but it only transfers all qty's not specific.

Yes, currently it's not possible. Because there is no good proposal on how that could be implemented. 
 Feel free to describe the idea and create a dedicated GitHub ticket for consideration

**Comment by VZeroCool** [comment]
I would like to reopen it. I'm getting this issue even after disabling all custom modules.

Steps will be Place an order and cancel that order. After cancel qty has to be return to stock but its not returning. 

Due to this count is getting weird and weird. @maghamed

**Comment by FranRoy** [comment]
Hello @VZeroCool 

I think I'm having the same issue and it might be due to the same ERP module. How did you manage to solve it?

Best regards,

Fran

> @IvanPletnyov and @maghamed, Thanks guys for an explanation but the problem was at ERP not in MSI.
> 
> One more thing I need to know there's inbuilt inventory transfer available but it only transfers all qty's not specific.
> 
> I think it's necessary to give an option to transfer specific qty to a specific source.

**Comment by FranRoy** [comment]
Hello again,

@IvanPletnyov in my case, I did as you suggested @VZeroCool and created a new sku. The new sku has correct Source Quantity and Saleable Quantity, so it seems that the issue is with the old products (in my case, Salable quantity is always x3 the source quantity).
Do you have any suggestion on how to find the issue?

Thanks

Fran

**Comment by VZeroCool** [comment]
@FranRoy, I was using ERP from BoostMyShop and have to disable this. I'm in total loss for now :(

https://magento.stackexchange.com/questions/277026/trunacate-table-inventory-reservation/277267#277267

**Comment by FranRoy** [comment]
@VZeroCool I've been stuck for months with this issue. Have u finally solved the problem?

Best regards

**Comment by VZeroCool** [comment]
Its due to some qty has been reserved, You can truncate `inventroy_reservation` table. It will resolve your issue and salable qty will be fine after that. @FranRoy

**Comment by TheFrakes** [comment]
I had similar findings, the quantity was totally out of sync with the saleable quantity. Truncating `inventory_reservation` did the trick for me. I found many reserved quantities due to transactions in the shop. I expect the reserved amount to be removed once I manually edit stock quantities. Is this behaviour meant to be this way?

**Comment by FranRoy** [comment]
For my case, inventory_reservation is empty and yet, salable quantity is always x3 de real stock.
I have noticed that the salable quantity is fine if I just use the Default Stock/Source and remove the rest. So weird, i'm totally lost :(

**Comment by VZeroCool** [comment]
Try resetting magento, May be something messed up which magento team also not aware. Then check with couple of products by placing order, invoice and dont generate shipment.
