### ISSUE TITLE
Source zipcode dropshipping

### ISSUE THREAD

**Issue by guilhermetb** [magento/inventory#2048]
Good afternoon, I have installed Magento 2.3 and it comes with the MSI
I want to work with dropshipping but I'm having difficulty with freight calculation, instead of picking zipcode from store -> inventary -> sources -> Address Data -> postcode it picks the zip from store -> configuration -> sales -> Shipping Details
Can someone help me?

**Comment by smoskaluk** [comment]
Hi @guilhermetb ! Unfortunately, MSI doesn't support freight calculation for sources yet, so it calculating only from general shipping settings in configuration. I think you may look for such feature in third part extensions (like here https://marketplace.magento.com/)

**Comment by guilhermetb** [comment]
Hi @smoskaluk 

Could you tell me some free preference module that solves this problem?

**Comment by smoskaluk** [comment]
Hi @guilhermetb , sorry, I don't have such information, you need to search for it by yourself. And I'm not sure that it would be for free.

**Comment by ishakhsuvarov** [comment]
Hi @guilhermetb 
Closing ticket for now, as it seems that discussion has reached its logical end. Please reopen if you have any more questions. 

Thanks
