### ISSUE TITLE
PO Procurement Management + stock history

### ISSUE THREAD

**Issue by tomekjordan** [magento/inventory#2050]
### Description

True Inventory must have PO Procurement Management + Stock History + stock movements etc

### Expected behavior

Please add similar features that are available in many simple ERP systems, or Magento Embeded ERP or Shopware's PICKWARE

### Benefits

1. Now admin can change stock QTY by hand. this is danger, it doesnt provide stock movement history
2. Real Procurement Managent is just a background for all modern inventory systems - it allows stock movements, history tracking, ordering producs from vendors, tracking product delivery.

### Additional information

Please just check:
Embeded ERP modules for M1 & M2
Shopware's Pickware
They made it really good

**Comment by maghamed** [comment]
Hey @tomekjordan 

Magento is not going to become another ERP system and go deep into that direction. We've never had that goal before either. 

The cases you described are partially covered by Magento Order Management (https://magento.com/resources/magento-commerce-order-management) and Magento B2B 
the other gap is covered with 3rd party extensions like the one you mentioned. 

Why should we cannibalize the market and develop and distribute what's already available there and being a part of the whole Magento ecosystem? 

What is the real goal of MSI is to provide basic multi-stock management as well as Source Selection abilities at the time of order fulfillment, and flexible and easily customizable set of Inventory APIs being utilized and extended by both Magento devs and 3rd-party extension developers.  

We have a dedicated product line for big Merchants which supposedly need B2B, Commerce Order Management, Procurement Management where the Order and Inventory automatization take into place and so on and so forth, but this is not a common requirement for the medium-size merchants. 

Also, we have dedicated Stories in our Product Backlog where we going to change Inventory configuration per different scopes as you mentioned, you can read more about those activities here :
https://github.com/magento-engcom/msi/wiki/Inventory-configuration-Design-and-DB-structure
https://github.com/magento-engcom/msi/wiki/Stock-and-Source-Configuration-design

Join MSI Slack channel, join our weekly demos to be in touch with all that stuff happening on a project and get awareness about our future plans.
And of course - contribute to the project to shape the product you would love to use by yourself!﻿
