### ISSUE TITLE
Cache not flushed when grouped product on test stock totally sold

### ISSUE THREAD

**Issue by IvanPletnyov** [magento/inventory#2052]
### Preconditions
1. Magento with MSI.
2. Additional Stock and Source created.
3. Default website assigned as sales channel to additional stock.

### Steps to reproduce
1. Create simple product with qty = 100 on test source
2. Create virtual product with qty = 100 on test source
3. Create grouped product with assigned simple and virtual products (default qty for both product = 2)
4. Go to grouped product page on store front 
5. Set qty for simple and virtual = 100 and click "Add to cart"
6. Create order, ship and invoice this order.

### Expected result
1. Grouped product disappeared from category page

### Actual result
1. Grouped product present on category page

**Comment by maghamed** [comment]
if I am not wrong we have a duplicated issue in our backlog. Could you please check that out @IvanPletnyov

**Comment by IvanPletnyov** [comment]
@maghamed Yes, I've found old [issue 1695](https://github.com/magento-engcom/msi/issues/1695)
I'll close this issue.
