### ISSUE TITLE
Missing ClientInterface for Magento\InventoryDistanceBasedSourceSelection\Model\ImportGeoNames

### ISSUE THREAD

**Issue by azngeek** [magento/inventory#2053]
### Preconditions
1. Magento "magento/project-enterprise-edition" 2.3

### Steps to reproduce
1. Install Magento 2.3 with all modules except that ones which are defined in composer:

```
  "replace": {
    "magento/module-cybersource": "*",
    "magento/module-dhl": "*",
    "magento/module-fedex": "*",
    "magento/module-marketplace": "*",
    "magento/module-authorizenet": "*",
    "magento/module-google-adwords": "*",
    "magento/module-sample-data": "*",
    "magento/module-send-friend": "*",
    "magento/module-google-optimizer": "*",
    "magento/module-ups": "*",
    "magento/module-usps": "*",
    "magento/module-braintree": "*",
    "magento/module-signifyd": "*",
    "magento/module-analytics": "*",
    "magento/module-catalog-analytics": "*",
    "magento/module-customer-analytics": "*",
    "magento/module-quote-analytics": "*",
    "magento/module-review-analytics": "*",
    "magento/module-release-notification": "*",
    "magento/module-sales-analytics": "*",
    "magento/module-wishlist-analytics": "*",
    "temando/module-shipping-m2": "*",
    "dotmailer/dotmailer-magento2-extension": "*",
    "shopialfb/facebook-module": "*",
    "klarna/module-kp": "*",
    "klarna/module-ordermanagement": "*",
    "klarna/module-core": "*",
    "amzn/amazon-pay-sdk-php": "*",
    "amzn/amazon-pay-and-login-with-amazon-core-module": "*",
    "amzn/login-with-amazon-module": "*",
    "amzn/amazon-pay-module": "*",
    "vertex/module-tax": "*"
  }
```

### Expected result
1. I expect that at any step setup:di:compile will finish

### Actual result
1. There is no prefereed ClientInterface defined for the Module "Magento_InventoryDistanceBasedSourceSelection"

![image](https://user-images.githubusercontent.com/213429/53490205-69bb5900-3a93-11e9-8d6a-b1724865787d.png)

So the question is: Am i missing some dependencies?

**Comment by IvanPletnyov** [comment]
@azngeek 
1) I've downloaded composer СЕ version (composer create-project --repository=https://repo.magento.com/ magento/project-community-edition .)
2) Enabled all modules (bin/magento module:enable --all)
3) Run di compile (bin/magento setup:di:compile)
4) Install magento via web interface

I didn't found any problems. Could you please give more details about your problem.

**Comment by ishakhsuvarov** [comment]
Hi @azngeek 
Closing this ticket now. Please continue tracking under reference #2128 as it seems similar.

Thanks.

**Comment by maghamed** [comment]
@tephereth all the code changes which affect non-Inventory modules should be delivered via Magento 2 GitHub repository, but not MSI one. Could you please create an independent PR to Magento repo

**Comment by tephereth** [comment]
> @tephereth all the code changes which affect non-Inventory modules should be delivered via Magento 2 GitHub repository, but not MSI one. Could you please create an independent PR to Magento repo

yes @maghamed , my fix of MSI is just there as a reference and linked to the core fix https://github.com/magento/magento2/pull/22179
this one has been approved but then closed because is a duplicated one (another identical PR was approved 1 month ago, it seems).
