### ISSUE TITLE
Can we get some design/layout love for the Assigned Sources section?

### ISSUE THREAD

**Issue by paales** [magento/inventory#2061]
![schermafbeelding 2019-03-01 om 10 04 30](https://user-images.githubusercontent.com/1244416/53628318-09e7be00-3c0b-11e9-89a5-455c7cacfcc2.png)

- The rows should be full width, then you dont get those odd wrapping labels. If there is space, use it :)
- Row height is off 
- ‘Assigned Sources’ label can be removed.
- Assign Sources should me moved below the table and be right-aligned (all buttons on the product edit page are)
- ‘Unassign’ column label can be removed, trash icon is enough.
- Notify Quantity use Default should be moved below the input field `[ ] Use Default`
- ‘Source code’ can be hidden, maybe as a tooltip of the Name
- ‘Source status’: disabled can be rendered as a strike-through of a source and show full status in tooltip.
- Source Item Status: Can we fix those labels? ‘In Stock’ ‘Out of Stock’ actually an 'Enabled' field. Currently is is very unclear what is actually means. 'Out of Stock' doesn't actually mean it is out of stock, it just means that you dont want to sell it.

**Comment by smoskaluk** [comment]
@paales, all we need is love!

**Comment by maghamed** [comment]
Most of the described items (if not all) are nice to have in MSI.
Dedicated grooming meeting to discuss proposed UI changes would be scheduled nearest time. UI specialist from Magento would be either invited there. 

Sorry, for late response @paales

**Comment by lorikrell** [comment]
I would say we need In Stock / Out of Stock as that is an actual status used and understood for the product availability. 
Happy to review and help for any UX text! :)

**Comment by ishakhsuvarov** [comment]
Closing, as most of the items seem to be completed in 5 linked tickets.
