### ISSUE TITLE
Problem with adding decimal orderitems when negative Qty treshold 

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#2063]
### Preconditions

1. Create simple product with Qty = 2, set  'backorders' and 'use decimal'  - on, set ' Out-of-Stock Threshold' = -1; 

### Steps to reproduce

1. Place 9 orders with such ordered Qtys: 0.59, 0.37, 0.24, 0.1, 0.2, 0.41, 0.1, 0.82, 0.17

### Expected result

1. Orders placed correctly

### Actual result

1. When adding the last 0.17 to the quote: The requested qty is not available

**Comment by maghamed** [comment]
#2065
