### ISSUE TITLE
Stocktaking Feature

### ISSUE THREAD

**Issue by simonmaass** [magento/inventory#2075]
### Description (*)

For a better warehouse management a stocktaking feature is vital. It would be great if you could perform a regular stocktaking which matches the current stock status with a scannened stock...

### Expected behavior (*)

pretty much like this... http://documentation.boostmyshop.com/inventory_management_magento2/10_stock_take.html

### Benefits

should be clear...

**Comment by sidolov** [comment]
Hi @simonmaass  we are about to complete MSI project feature development and keep issues of defined scope only to have a clean and transparent backlog.
Unfortunately, the current issue is out of scope and should be closed.
The described feature may be implemented by 3d party developers.
Thank you for your involvement!

**Comment by seansan** [comment]
+1 would be great and really what a merchant would need

It is a realistic and existing business process that all merchants deal with
