### ISSUE TITLE
Sources with numeric source_code cannot be used for shipment

### ISSUE THREAD

**Issue by amelaraby** [magento/inventory#2079]
### Preconditions (*)

1. Magento version 2.3.0

### Steps to reproduce (*)

1. Create a new source with a numeric "source code" (just numbers)
2. Assign the newly created source to a stock
3. Assign a product to the newly created source and add a quantity
4. Create a new test order with the specified product
5. In order shipment source selection page, select the numeric code source

### Expected result (*)

The "Qty to Deduct" field for the selected source should be enabled to edit the quantity

### Actual result (*)
The "Qty to Deduct" field still disabled as per the below screenshot:

![0e9a2f43-ae8e-47ed-b4c2-18566a9b8edf](https://user-images.githubusercontent.com/4401142/54322366-95931e80-45fd-11e9-9a27-d09070ea6e5f.png)

**Comment by amelaraby** [comment]
@magento-engcom-team Please assign this task to me in order to fix it...

**Comment by araby93** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by ishakhsuvarov** [comment]
@araby93 Thank you for the PR!

As it's now merged I'm closing the issue.
