### ISSUE TITLE
Partial refund works incorrectly after partial shipment and partial invoice for configurable product 

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#2087]
### Preconditions (*)

1. Custom stock with custom source created
2. Configurable product with color option 'red" qty = 100 created on custom source
3. Order placed with 5 items of configurable product with option 'red'

### Steps to reproduce (*)

1. Make partial invoice for 3 items of configurable - red
2.  Make partial shipment for 2 items of configurable - red
3.  Make partial credit memo for 3 items of configurable - red with return to the stock enabled

### Expected result (*)

1. Quantity on custom source for 'configurable - red' should be = 100
2. Compensational reservation should be created for 'configurable - red' with Quantity = 1 on Custom stock

### Actual result (*)

1. Quantity on custom source for 'configurable - red'  = 98
2. Compensational reservation created for 'configurable - red' with Quantity = 3 on Custom stock

**Comment by maghamed** [comment]
I believe this case will reproduce for Default stock either

**Comment by malesh-v** [comment]
I can't reproduce this issue.
