### ISSUE TITLE
Products not visible on website after setting up MSI

### ISSUE THREAD

**Issue by routbiplab** [magento/inventory#2094]
### Preconditions (*)

1. Magento v2.3.0
2. mysql Ver 15.1 Distrib 10.1.38-MariaDB

### Steps to reproduce (*)

1. Deploy sample data
2. Set up multi source inventory

### Expected result (*)

1. Products visible on website.

### Actual result (*)

1. Products doesn't show up on website though they are present in the Magento admin.

**Comment by maghamed** [comment]
Hey @routbiplab 

there could be many reasons for that:
1. Did you assign a proper Stock to the Website you are approaching? 
2. What the "Salable Quantity" of the product which does not show up in Magento Admin Panel?

Most likely you assigned Stock with no products to your current wbsite.

Also, this documentation may be useful to get started with new Inventory mechanism:
- https://docs.magento.com/m2/ce/user_guide/catalog/inventory-management.html
- https://github.com/magento-engcom/msi/wiki/Get-Started-with-MSI
- https://github.com/magento-engcom/msi/wiki/MSI-features-and-processes

**Comment by IvanPletnyov** [comment]
Hello @routbiplab . I've checked your ticket by this steps:

**Products available on default source:**
1. Install magento 2.3 with sample data
2. Add custom source
3. Add stock with created source (without assigned sales channels)
4. Run reindex and flush cache: bin/magento indexer:reindex; bin/magento flush:cache;
5. Go to category page, all products available:

![image](https://user-images.githubusercontent.com/26973706/54593633-a09fe180-4a37-11e9-97dd-24cebb16f3ad.png)


**Products available on custom source:**
1. Install magento 2.3 with sample data
2. Add custom source
3. Add stock with created source and assigned main website
4. Run reindex and flush cache: bin/magento indexer:reindex; bin/magento flush:cache;
5. **_In admin panel go to products grid and assign products to custom stock_**

![image](https://user-images.githubusercontent.com/26973706/54594381-34be7880-4a39-11e9-9fea-fa49bc9c79c5.png)

6. All products available:

![image](https://user-images.githubusercontent.com/26973706/54594348-240e0280-4a39-11e9-8d12-b28ed9a1b2d3.png)

Could you please give me more information about your steps ?

**Comment by routbiplab** [comment]
Install magento 2.3 with sample data
Add custom source
Add stock with created source and assigned main website
Run reindex and flush cache: bin/magento indexer:reindex; bin/magento flush:cache;
In admin panel go to products grid and assign products to custom stock
Go to website and check for products visibile or not

**Comment by IvanPletnyov** [comment]
@routbiplab By this steps It's working for me.
1. Give me more information about your system.
2. Do you have any errors in log ?
3. Are you using CE version or EE ?
4. Do you use third party modules ?

**Comment by maghamed** [comment]
@routbiplab what the "Salable Quantity" you have in Magento Admin panel for the products which are absent on front-end?

**Comment by routbiplab** [comment]
It was above 100

**Comment by smoskaluk** [comment]
@routbiplab we can't reproduce this issue. Do you have any 3-d part modules installed? Do you have errors in log?

**Comment by ishakhsuvarov** [comment]
Hi @routbiplab 

I am closing this ticket now due to inactivity and the fact that we couldn't reliably reproduce the issue. Please feel free to reopen if you have any additional information.
