### ISSUE TITLE
Introduce a service to partially transfer Stock data from One Source to Another with possibility to set Qty being transferred

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#2101]
Introduce a service to partially transfer Stock data from One Source to Another with a possibility to set Qty being transferred per each SKU.

The existing set of services:
https://github.com/magento-engcom/msi/tree/2.3-develop/app/code/Magento/InventoryCatalogApi/Api/Bulk*

Does not cover partial stock transfer, so that we are always transferring the whole available Qty from Source-A to Source-B in the scope of that migration.  

There are currently no ideas on how to better name that service. Feel free to propose naming for it.

In general the semantic of service should look like

```
namespace Magento\InventoryCatalogApi\Api;
/**
 * Perform bulk product inventory transfer
 *
 * @api
 */
interface BulkInventoryTransferInterface
{
    /**
     * Run bulk inventory transfer
     * @param ProcurementItemInterface[] $procurementItems
     * @param string $originSource
     * @param string $destinationSource
     * @return bool
     * @throws \Magento\Framework\Exception\InputException 
     * @throws \Magento\Framework\Exception\LocalizedException . Not enought Qty exception
     */
    public function execute(
        array $procurementItems,
        string $originSource,
        string $destinationSource
    ): bool;
}

interface ProcurementItemInterface
{
    getSku(): string;

    setSku(string $sku);

    getQty(): float;

    setSku(float $qty);
}
```

Introduced service should be covered with Integration and Web API tests

**Comment by ishakhsuvarov** [comment]
Merged in #2117 

Thanks @bcerban !
