### ISSUE TITLE
Error on category page when Elasticsearch 6 enabled

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#2102]
Fatal error on category page on frontend when Elasticsearch 6 enabled

{"0":"Undefined factory elasticsearch6","1":"
#0 /app\/code\/Magento\/Catalog\/Model\/Layer.php(146): Magento\\Elasticsearch\\Model\\Layer\\Category\\ItemCollectionProvider->getCollection(Object(Magento\\Catalog\\Model\\Category\\Interceptor))\
n#1 /generated\/code\/Magento\/Catalog\/Model\/Layer\/Category\/Interceptor.php(37): Magento\\Catalog\\Model\\Layer->getProductCollection()\
n#2 /app\/code\/Magento\/Catalog\/Block\/Product\/ListProduct.php(470): Magento\\Catalog\\Model\\Layer\\Category\\Interceptor->getProductCollection()\
n#3 /app\/code\/Magento\/Catalog\/Block\/Product\/ListProduct.php(116): Magento\\Catalog\\Block\\Product\\ListProduct->initializeProductCollection()\
n#4  /app\/code\/Magento\/Catalog\/Block\/Product\/ListProduct.php(357): Magento\\Catalog\\Block\\Product\\ListProduct->_getProductCollection()\
n#5  /generated\/code\/Magento\/Catalog\/Block\/Product\/ListProduct\/Interceptor.php(154): Magento\\Catalog\\Block\\Product\\ListProduct->getIdentities()\
n#6  /app\/code\/Magento\/PageCache\/Model\/Layout\/LayoutPlugin.php(71): Magento\\Catalog\\Block\\Product\\ListProduct\\Interceptor->getIdentities()\
n#7  /lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(146): Magento\\PageCache\\Model\\Layout\\LayoutPlugin->afterGetOutput(Object(Magento\\Framework\\View\\Layout\\Interceptor), '    <script>\\n  ...')\
n#8  /lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(153): Magento\\Framework\\View\\Layout\\Interceptor->Magento\\Framework\\Interception\\{closure}()\
n#9  /generated\/code\/Magento\/Framework\/View\/Layout\/Interceptor.php(494): Magento\\Framework\\View\\Layout\\Interceptor->___callPlugins('getOutput', Array, Array)\
n#10  /lib\/internal\/Magento\/Framework\/View\/Result\/Page.php(257): Magento\\Framework\\View\\Layout\\Interceptor->getOutput()\
n#11  /lib\/internal\/Magento\/Framework\/View\/Result\/Layout.php(170): Magento\\Framework\\View\\Result\\Page->render(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\
n#12  /lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(58): Magento\\Framework\\View\\Result\\Layout->renderResult(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\
n#13  /lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(138): Magento\\Framework\\View\\Result\\Page\\Interceptor->___callParent('renderResult', Array)\
n#14  /lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(153): Magento\\Framework\\View\\Result\\Page\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\
n#15  /generated\/code\/Magento\/Framework\/View\/Result\/Page\/Interceptor.php(130): Magento\\Framework\\View\\Result\\Page\\Interceptor->___callPlugins('renderResult', Array, Array)\
n#16  /lib\/internal\/Magento\/Framework\/App\/Http.php(139): Magento\\Framework\\View\\Result\\Page\\Interceptor->renderResult(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\
n#17  /generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php(24): Magento\\Framework\\App\\Http->launch()\
n#18  /lib\/internal\/Magento\/Framework\/App\/Bootstrap.php(257): Magento\\Framework\\App\\Http\\Interceptor->launch()\
n#19  /index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\
n#20 {main}","url":"\/cat1.html","script_name":"\/index.php"}

**Comment by maghamed** [comment]
Not an MSI issue. 

The issue has been introduced into 2.3-develop branch a few days ago (2.3.0-release is not affected).

The fix for 2.3-develop is in the PR - https://github.com/magento/magento2ce/pull/3912
