### ISSUE TITLE
Not possible to save product in Multi Source environment just specifying Manage Source = fase

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#2106]
1. Start creating a product in admin panel
2. Fill all the mandatory attributes
3. Open Advanced Inventory
4. Set Manage Stock = false in advanced inventory
5. Save product

Actual result:
`The stock item was unable to be saved. Please try again.` error appeared

Expected Result:

Product Saved

**Comment by larsroettig** [comment]
Hi I cannot reproduce at Version: b1177797df0  new Installation 

### Repo Create:

2 Websites  Default and `Germany Website`
3 Sources Default, `Warehouse1`, `Warehouse2`
2 Stock Germany with `Warehouse1` and `Warehouse2` assigned to `Germany Website`

✅ 1. Start creating a product in admin panel
✅ 2. Fill all the mandatory attributes
✅ 3. Open Advanced Inventory
✅ 4. Set Manage Stock = false in advanced inventory
✅ 5. Save product


#### Result 
Product was Saved

**Comment by maghamed** [comment]
@larsroettig you should reproduce that bug having several sources created

**Comment by maghamed** [comment]
the bug is reproducible for me
