### ISSUE TITLE
Price field enabled when bundle product with dynamic price creating

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#2109]
During creation Bundle product with enabled 'Dynamic price' - by default - field 'Price' should be disabled 

![image](https://user-images.githubusercontent.com/27818516/54926946-fc77d800-4f19-11e9-9995-113c1f2fe214.png)

**Comment by diwipl** [comment]
I've tried to reproduce following issue using 2.3-develop branch, but I was not able to.

![image](https://user-images.githubusercontent.com/3406741/55278231-e434fe00-5309-11e9-9fa1-1347c5ac8641.png)

Can you provide more details (which branch you've used) ?

**Comment by smoskaluk** [comment]
Hi @diwipl, the issue is reproducible on branch 2.3.0-release, but it looks like it already fixed on 2.3-develop. Thank you for report!
