### ISSUE TITLE
Unskip MFTF for MAGETWO-44165

### ISSUE THREAD

**Issue by YuliyaLabudova** [magento/inventory#2110]
Please, unskip these tests in the next release: 
AdminCreateVirtualProductSwitchToConfigurableTest
AdminCreateSimpleProductSwitchToConfigurableTest
AdminCreateDownloadableProductSwitchToConfigurableTest

**Comment by ishakhsuvarov** [comment]
Unskipped in the scope of private PR https://github.com/magento/magento2ce/pull/4128
