### ISSUE TITLE
How to get salable qty on frontend?

### ISSUE THREAD

**Issue by jorgb90** [magento/inventory#2111]
Hi,

On the frontend we built some logic to determine the shipping time for our customers, but when using our current code the output is only from the Default source. It should output the total Salable qty of all sources as in the backend.

We are now using:

`<?php $qty = $_product->getExtensionAttributes()->getStockItem()->getQty(); ?>`

Or even:

`$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
$qty = $StockState->getStockQty($_product->getId());`

But these do not work anymore. Thanks for the help.

**Comment by jorgb90** [comment]
Found a solution in using:

`<?php 
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $StockState = $objectManager->get('\Magento\InventorySalesApi\Api\GetProductSalableQtyInterface');
	$qty = $StockState->execute($_product->getSku(), 2);
?>`

Is this the best way?

**Comment by Watch3ruk** [comment]
Hi,
i would like to know this as well. 
And is there a way to change the salable qty ? 
Product A friday qt is 50. monday qty is 50 and i have salable - 5 ?? i know WHY question is can i change so qty changes on order placement ??

**Comment by jorgb90** [comment]
Mm with my solution I am getting the following error for configurable products:

Can't check requested quantity for products without Source Items support.

**Comment by maghamed** [comment]
hey @jorgb90 

you should use `GetProductSalableQtyInterface` to determine correct quantity on front-end .
Try not to use interfaces from CatalogInventory module, as all those interfaces currently deprecated.

>And is there a way to change the salable qty ?

Salable Qty is changed when either Reservation is placed or SourceItem Qty is changed

>Mm with my solution I am getting the following error for configurable products:
>Can't check requested quantity for products without Source Items support.

That's because you are trying to set Qty for Configurable Product, which in fact can't have Quantity by its own. Only simple products from which the Configurable one is consists of could have Quantities assigned.

**Comment by jorgb90** [comment]
> That's because you are trying to set Qty for Configurable Product, which in fact can't have Quantity by its own. Only simple products from which the Configurable one is consists of could have Quantities assigned.

How do I request the qty of the simple products in a configurable product? I hope you can help me with that?

**Comment by ishakhsuvarov** [comment]
@jorgb90 It would work in the same way, just use sku of the specific simple product.

**Comment by afzelarshad** [comment]
> Found a solution in using:
> 
> `<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); $StockState = $objectManager->get('\Magento\InventorySalesApi\Api\GetProductSalableQtyInterface'); $qty = $StockState->execute($_product->getSku(), 2); ?>`
> 
> Is this the best way?

object manager is bad practices
