### ISSUE TITLE
In stock, 0 qty and backorders allowed products not visible on category pages

### ISSUE THREAD

**Issue by jorgb90** [magento/inventory#2113]
### Preconditions (*)
1. Magento 2.3 with MSI 

### Steps to reproduce (*)
1. Create custom stock with custom source and main website assigned
2. Create a simple product with custom source assigned with qty '0' and status 'In Stock'
3. Go to Advanced Inventory
4. Set Manage Stock to Yes
5. Set Backorders to 'Allow Qty Below 0 And Notify Customer'

### Expected result (*)
1. Product is visible on category page.

### Actual result (*)
1. Product is not visible on category page, but product can be visited with the url directly.

Notice: the same behavior if Backorders enabled on Configuration in admin

**Comment by ishakhsuvarov** [comment]
Fixed in #2139
