### ISSUE TITLE
source_code attribute is missing in REST API endpoint "shipments"

### ISSUE THREAD

**Issue by HS-Fachmarkt** [magento/inventory#2135]
### Preconditions (*)
1. Magento 2.3.1 Commerce
2. MSI with multiple stocks

### Steps to reproduce (*)
1. Call the magento 2 rest api on /rest/V1/shipment/22 ([shipment.txt](https://github.com/magento-engcom/msi/files/3037565/shipment.txt)). extension_attributes with attribute source_code is set. "extension_attributes: {source_code: "warehouse_poz"}"
2. Call the magento 2 rest api on /rest/V1/shipments ([shipments.txt](https://github.com/magento-engcom/msi/files/3037566/shipments.txt)). extension_attributes with attribute source_code is not set

### Expected result (*)
extension_attributes - source_code should be set on /rest/V1/shipments as well

**Comment by ishakhsuvarov** [comment]
Closing this ticket, as issue has already been fixed in #2142 

Thanks @tephereth
