### ISSUE TITLE
Disable fields in Mass action -> Update attributes -> Advanced inventory

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#2138]
When multi sources enabled, on Products grid in Mass action -> Update attributes -> Advanced inventory
next fields need to be disabled and hidden (How it implemented in Advanced inventory on Product page):
Qty, Notify for Quantity Below and Stock Status

![image](https://user-images.githubusercontent.com/27818516/55492403-d05a0680-563f-11e9-859c-6d9f00a1c4f5.png)

**Comment by giuseppemorelli** [comment]
Hey folks,
actually the form of mass attribute update is created with this phtml file

`app/code/Magento/Catalog/view/adminhtml/templates/catalog/product/edit/action/inventory.phtml` that has this Block php class `app/code/Magento/Catalog/Block/Adminhtml/Product/Edit/Action/Attribute/Tab/Inventory.php`

My first thought was to edit the .phtml and add a fuction on a block class. This kind of approach add an hard dependency with InventoryCatalogApi.

This topic was discussing with @phoenix128 and @maghamed and the best solution is rewrite the pthml with a ui component so we can extends all fields.
