### ISSUE TITLE
[UI Love for Assigned Sources] Move buttons

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#2151]
Description
This ticket is created in effort to split #2061 into smaller and more manageable items.

Assigned Sources panel, located on the Product Edit page has a lot of tightly packed controls, some of which may be (re)moved to maintain cleaner look and better experience.

### To Do
1.  Move buttons "Assign Sources" and "Advanced Inventory" to the right side and to the same level of the grid - as all buttons on the product edit page are
2. Eliminate empty space above the grid

![image](https://user-images.githubusercontent.com/27818516/55778142-c5253180-5aaa-11e9-93d7-d2420c12db07.png)

**Comment by ishakhsuvarov** [comment]
Implemented in #2266
