### ISSUE TITLE
[UI Love for Assigned Sources] Hide Headers 

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#2152]
Description
This ticket is created in effort to split #2061 into smaller and more manageable items.

Assigned Sources panel, located on the Product Edit page has a lot of tightly packed controls, some of which may be (re)moved to maintain cleaner look and better experience.

### To Do
Hide grid headers and label "Assigned Sources" when there are no Sources assigned 

![image](https://user-images.githubusercontent.com/27818516/55778701-3d402700-5aac-11e9-8a64-1d0595869779.png)

**Comment by ishakhsuvarov** [comment]
Implemented in #2266
