### ISSUE TITLE
UI Components in Store Pickup admin UI

### ISSUE THREAD

**Issue by ishakhsuvarov** [magento/inventory#2161]
### Description
UI Components has become a standard for Admin UI and must be used in favor of older backend UI widgets.

### To Do
* Investigate if it is viable to replace `\Magento\InventoryInStorePickupAdminUi\Block\Adminhtml\Order\View\ReadyForPickup` with a UI component
* Do it.

**Comment by TBlindaruk** [comment]
I will try to do it

**Comment by nmalevanec** [comment]
As admin sales order view page is not UI form, I couldn't find good solution to replace "Notify Order Is Ready For Pickup" with ui component. The only solution I found is add the whole UI form into admin sales order view form, which is seems not appropriate for adding just a single button.
@sidolov could you please advice?
