### ISSUE TITLE
Wrong output for "inventory:reservation:list-not-compensated" CLI command

### ISSUE THREAD

**Issue by phoenix128** [magento/inventory#2166]
`inventory:reservation:list-not-compensated` command line returns `Inconsistencies found on following entries:` without any order instead of `No order inconsistencies were found`.

This happens when items not compensated are found in non finalized orders.

### Preconditions (*)
1. Start with a clean database
2. Create one or more test orders and run a partial shipment

### Steps to reproduce (*)
1. Run `bin/magento inventory:reservation:list-not-compensated`

### Expected result (*)
1. `No order inconsistencies were found`
2. Return code 0

### Actual result (*)
1. `Inconsistencies found on following entries:`
2. Return code -1

**Comment by ishakhsuvarov** [comment]
Fixed in #2167 

@phoenix128 @riccardougolini Huge thanks to you guys!
