### ISSUE TITLE
Source Entity expansion with Pickup Location attributes

### ISSUE THREAD

**Issue by swnsma** [magento/inventory#2182]
### Description
Source entity need to be expanded with additional attributes for Pickup Location.
At least next attributes need to be added:
- Front Name - which will be used for name of Pickup Location on Magneto Frontend.
- Open Hours - attribute which will be used to show open hours of Pickup Location.

Please foresee next cases:
- if source is not Pickup Location - attributes should hided or should not be required.
- if source is Pickup Location - these attributes should become required.

**Comment by novikor** [comment]
PR is expected this week.

**Comment by swnsma** [comment]
Merged #2182.
