### ISSUE TITLE
Improve GetNearbySourcesByPostcode API

### ISSUE THREAD

**Issue by ishakhsuvarov** [magento/inventory#2185]
### Description
Current API for `GetNearbySourcesByPostcode` has multiple issues to it, potentially creating challenge for future customizations and improvements:
* API is not scoped
* Pickup location is represented only by `country` and `postcode` which is not ideal for many scenarios.

### To Do
Design a better API. For example (still has be refined) it could use an appropriate address object instead of country and post code and introduce a stock scope.

**Comment by swnsma** [comment]
Merged in #2214
