### ISSUE TITLE
Configurable product price is always 0 if 'Display Out of Stock Products' = Yes

### ISSUE THREAD

**Issue by lyusya-nnn** [magento/inventory#2190]
### Preconditions (*)

1. Magento 2.3.1 with MSI enabled and 3 websites
2. Custom stock with custom source created
![sources](https://user-images.githubusercontent.com/8502721/56353852-061ff300-61db-11e9-8c01-e01ac6718114.png)
![stocks](https://user-images.githubusercontent.com/8502721/56353919-2d76c000-61db-11e9-9e27-e20ac09b692f.png)

### Steps to reproduce (*)

1. Create configurable products
![products](https://user-images.githubusercontent.com/8502721/56354114-a544ea80-61db-11e9-8f73-402f27723cd2.png)

![conf 1](https://user-images.githubusercontent.com/8502721/56354378-39af4d00-61dc-11e9-9496-b5090d911401.png)

![conf 2](https://user-images.githubusercontent.com/8502721/56354481-7c712500-61dc-11e9-9d13-8fe8592ccd68.png)

2. Go to Stores -> Configuration -> Catalog -> Inventory -> Stock Options, set 'Display Out of Stock Products' = Yes
3. Go to Stores -> Configuration -> Catalog -> Catalog -> Storefront, set 'Use Flat Catalog Category' = yes, 'Use Flat Catalog Product' = yes
4. Switch to Main Website Store config, Go to  Stores -> Configuration -> Sales -> Tax,
 on Price display settings  set 'Display Product Prices In Catalog' = Including Tax, 'Display Shipping Prices' = Including Tax
on Shopping Cart Display setting set 'Display Prices' = Including tax, 'Display Sub total' => Including tax, 'Display Shipping Amount' = Including tax
![Configuration   Settings   Stores   Magento Admin](https://user-images.githubusercontent.com/8502721/56355005-dfaf8700-61dd-11e9-8219-7600f079b5bf.png)
5. Run reindex, flush magento cache
6. Open category view page

### Expected result (*)

Configurable products on category view page should have price as the lowest price of attched simple product

### Actual result (*)

Configurable products have price 0
![test](https://user-images.githubusercontent.com/8502721/56355203-66646400-61de-11e9-9880-9182d5be027d.png)

Now open product view page, there is the same issue with price:
![simple](https://user-images.githubusercontent.com/8502721/56355286-9d3a7a00-61de-11e9-8358-e5de6dcf5558.png)

Now if you change 'Display Out of Stock Products' = No, run reindex and flush cache, you will see correct prices on category page:
![test2](https://user-images.githubusercontent.com/8502721/56355535-349fcd00-61df-11e9-8457-738f556146ec.png)

**Comment by maghamed** [comment]
@vad1m777  this issue needs to be verified without MSI installed as MSI is not dealing with prices at all

**Comment by lyusya-nnn** [comment]
I think there is some configuration missing in module-inventory-configurable-product/etc/di.xml

```
<type name="Magento\ConfigurableProduct\Model\ResourceModel\Product\LinkedProductSelectBuilder">
        <arguments>
            <argument name="baseSelectProcessor" xsi:type="object">Magento\InventoryConfigurableProduct\Model\ResourceModel\Product\StockStatusBaseSelectProcessor</argument>
        </arguments>
    </type>
```

**Comment by smoskaluk** [comment]
Not reproducing on MSI mainline branch (1.2-develop)
