### ISSUE TITLE
Reservations can not be compensated for the configurable product using CLI

### ISSUE THREAD

**Issue by ishakhsuvarov** [magento/inventory#2203]
### Description
1. Place order for 1 child of configurable product from main website and default stock
2. Delete reservation from the DB
3. Run `bin/magento inventory:reservation:list-inconsistencies -r | bin/magento inventory:reservation:create-compensations`

❌Result:
> Following reservations were created: 
>  - Product conf1-bbb was compensated by +2.000000 for stock 1   -  **(should be +1.00000)**

4. Place order for 1 child of configurable product from Test website and Test stock
5. Delete reservation from the DB
6. Run `bin/magento inventory:reservation:list-inconsistencies -r | bin/magento inventory:reservation:create-compensations`

❌Result:
> Following reservations were created:
>  - Argument "2000000001:conf1-rrr:-1.000000:2" caused exception "The entity that was requested doesn't exist. Verify the entity and try again."

### Notice
Steps 4 - 6 also reproducible for another type of products - simple and etc 

### Reference:
https://github.com/magento-engcom/msi/pull/2199#issuecomment-486276160

**Comment by IvanPletnyov** [comment]
In service GetReservationFromCompensationArgument we load order by increment id via orderRepository, but method get in order repository use entity_id. I think for fix we need get entity_id by increment id and load order by received entity_id.

**Comment by ishakhsuvarov** [comment]
Hi @phoenix128 
Are you still interested in this item?

**Comment by inkobject** [comment]
Hi all,
I am running into this problem on my store.
Since I am unable to clear inconsistencies, I am unable to use the back-end to enter shipments as the backend reports insufficient stock when I try to enter shipping data.
Is there any advice of a work-around or another fix while we wait on a release of a bugfix?

**Comment by smoskaluk** [comment]
Problems are not fixed, wrong message about creating reservation - it should be negative and only for 1 item. The same story for reservation for custom stock and custom website.

![image](https://user-images.githubusercontent.com/27818516/61940232-a5ecda00-af9d-11e9-9597-fe333be140ed.png)

**Comment by arvind-curotec** [comment]
Not sure if its a bug. But in code they are trying to load the order by increment id using `$order = $this->orderRepository->get($argumentParts['increment_id']);` which fails. This code only works when you load the order by `entity_id` but not by `increment_id`.
I have made some changes in code to load the order by increment id using `searchCriteraBuilder` and it works after that.

File: `vendor/magento/module-inventory-reservation-cli/Command/Input/GetReservationFromCompensationArgument.php`

Replace the function `execute` with below code:

```
    public function execute(string $argument): ReservationInterface
    {
        $argumentParts = $this->parseArgument($argument);

        // This line fails
        // $order = $this->orderRepository->get($argumentParts['increment_id']);

        // Replace with below code
        // Fix start
        $searchCriteria = $this->searchCriteriaBuilder
                            ->addFilter('increment_id', $argumentParts['increment_id'], 'eq')->create();
        $orderList = $this->orderRepository->getList($searchCriteria)->getItems();
        $order = reset($orderList);
        // Fix ends

        return $this->reservationBuilder
            ->setSku((string)$argumentParts['sku'])
            ->setQuantity((float)$argumentParts['quantity'])
            ->setStockId((int)$argumentParts['stock_id'])
            ->setMetadata($this->serializer->serialize([
                'event_type' => 'manual_compensation',
                'object_type' => 'order',
                'object_id' => $order->getEntityId(),
            ]))
            ->build();
    }

```

Dont forget to inject the dependencies in the constructor:
```
...
use Magento\Framework\Api\SearchCriteriaBuilder;
...
private $searchCriteriaBuilder;
...
    public function __construct(
        OrderRepositoryInterface $orderRepository,
        ReservationBuilderInterface $reservationBuilder,
        SerializerInterface $serializer,
        SearchCriteriaBuilder $searchCriteriaBuilder
    ) {
        $this->orderRepository = $orderRepository;
        $this->reservationBuilder = $reservationBuilder;
        $this->serializer = $serializer;
        $this->searchCriteriaBuilder = $searchCriteriaBuilder;
    }
```
