### ISSUE TITLE
Shipping / Pick In Store switcher on Checkout

### ISSUE THREAD

**Issue by ishakhsuvarov** [magento/inventory#2227]
### Description
In order for Customer to select the Store pickup delivery method a new component has to be introduced. Component has to be a simple switcher, with 2 options "Shipping" and "Pick in Store". Ideally, component should be reusable and provide an interface for the developer to introduce more values or change it's behavior in a friendly way.

### Expected behavior
By default Checkout start page loads with "Shipping" option preselected. When user selects "Pick in Store" checkout should change from the default "#shipping" step to "#pickup" step. 

On pickup steps several changes from the Shipping UI are implemented:
* Customer Shipping Address selection interface is hidden (both for logged in customer with saved addresses and guest customer with the address form).
* Shipping method selection is hidden.
* "Shipping" label in step selector should be updated as well.
* Customer's address selection and all inputs should retain their values when switched between pickup and shipping and vice versa.
* When leaving checkout to a cart page or catalog customer should be able to return to the previously selected delivery type.

### Mockups
There is more UI information available in the Store Pickup documentation: https://github.com/magento-engcom/msi/wiki/Support-of-Store-Pickup-for-Multi-Source-Inventory

#### Shipping
![](https://camo.githubusercontent.com/88330cfafa057309ed0562aa4543993bd87c667e/68747470733a2f2f692e696d6775722e636f6d2f6e36356f6b66582e706e67)

#### Pick in Store
![](https://camo.githubusercontent.com/2561201103d1ace1d1d1f51a17e371178e92b492/68747470733a2f2f692e696d6775722e636f6d2f7a3854576c56442e706e67)

#### Clickable version
https://magento.invisionapp.com/share/MGPPI7MRJYN#/screens/337877902

### Additional information
* This ticket may be decomposed into multiple smaller tickets, as it touches multiple functional areas of Checkout (step selector, persistence, UI Component itself).
* Some additional logic like hiding the selector when no Pickup locations are assigned to the current Stock is left out from this ticket intentionally.
* Store Pickup Step UI is not intended to be developed in the scope of this ticket as well.

**Comment by swnsma** [comment]
#2029

**Comment by ishakhsuvarov** [comment]
Closing, as it was already merged
