### ISSUE TITLE
'Reorder' button is visible for order in customer cabinet when ordered item is sold out

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#2229]
### Preconditions

1. Create simple (or virtual or downloadable) product "Prod 1" with qty=1
2. Create customer account on Main website

### Steps to reproduce

1. Create order with 1 item of product "Prod 1" 
2. Make shipment and invoice for this order
3. Goto "My Orders" tab on personal cabinet of your customer

### Expected result

1. Button "Reorder" should't be visible for your order

### Actual result

1. Button "Reorder" present for your order

**Comment by willtran** [comment]
I have checked the behaviour on OOTB Magento 2.3 (without MSI)
Re-order button is available when product is out of stock.
However when you click on the link Magento will complain:

**Product that you are trying to add is not available.**

I think we should keep the current behaviour as it is more clear to the customer why they can't re-order. In addition to check whether or not the order can be re-order on the page it will require loading from stock item table (as opposed to just getting info from sales_order_item) which is not necessary and can possibly slow the page load if there're many orders.

**Comment by willtran** [comment]
Same with admin area, re-order button is available when you visit the order inside admin regardless of stock status.

**Comment by ishakhsuvarov** [comment]
@willtran Thanks for investigation. This seems to be reasonable, so I'll be closing this ticket
