### ISSUE TITLE
Introduce extension points in Save controllers of Inventory Module

### ISSUE THREAD

**Issue by naydav** [magento/inventory#225]
Introduce two extension point in controllers

1) The first point is needed for processing extension attributes
2) The second is needed for possibility to have call to a few services  based on data from one form

Example:

> 
`$this->_eventManager->dispatch(

            'controller_action_location_city_save_entity_before',
            [
                'controller' => $this,
                'request_data' => $requestData,
                'city' => $city,
            ]
        );
        $cityId = $this->cityRepository->save($city);
        $this->_eventManager->dispatch(
            'controller_action_location_city_save_entity_after',
            [
                'controller' => $this,
                'request_data' => $requestData,
                'city' => $city,
            ]
        );`

**Comment by furseyev** [comment]
PR is here: https://github.com/magento-engcom/msi/pull/240

**Comment by furseyev** [comment]
Updated event dispatchers to pass request instead of controller context or request params
