### ISSUE TITLE
Cover delete Stock by id with API functional tests 

### ISSUE THREAD

**Issue by naydav** [magento/inventory#226]
Need to cover delete Stock by id functionality with API functional tests 
Examples in `Magento\InventoryApi\Test\Api\*`

**Comment by Cahoo** [comment]
#mageconf

**Comment by naydav** [comment]
Looks like this task is not finished so we can reassign this ticket

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/339
