### ISSUE TITLE
Inventory Export Stock Api dump-stock-index-data fails

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#2260]
### Preconditions (*)

1. MSI + EE + B2B 
2. Multistock enabled
3. Products of various types created assigned to Default source (But reproducing for custom stock as well)

### Steps to reproduce (*)

1. Create Inventory Export Stock Api dump-stock-index-data for products on Default stock

### Expected result (*)

1. Export done successfully

### Actual result (*)

1. Export fails
[2019-05-13 14:56:18] report.CRITICAL: Report ID: webapi-5cd9859259535; Message: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento.catalog_pr                                                                               oduct_website' doesn't exist, query was: SELECT
        IF(
            `product_entity`.`type_id` IN (
                'configurable',
                'bundle',
                'grouped'),
                NULL,
            NULL
        ) AS `qty`, "1" as is_salable, `product_entity`.`sku` FROM `m2_cataloginventory_stock_item` AS `legacy_stock_item`
 INNER JOIN `m2_catalog_product_entity` AS `product_entity` ON legacy_stock_item.product_id = product_entity.entity_id AND (product_entity.created_in <= '1557                                                                               751140' AND product_entity.updated_in > '1557751140')
 INNER JOIN `catalog_product_website` AS `pr_web` ON legacy_stock_item.product_id = pr_web.product_id WHERE ((legacy_stock_item.use_config_manage_stock = 0 AN                                                                               D legacy_stock_item.manage_stock = 0)) AND (pr_web.website_id = 1) UNION SELECT
        IF(
            `product_entity`.`type_id` IN (
                'configurable',
                'bundle',
                'grouped'),
            NULL,
            `quantity`
        ) AS `qty`, `stock_index`.`is_salable`, `stock_index`.`sku` FROM `m2_inventory_stock_1` AS `stock_index`
 INNER JOIN `m2_catalog_product_entity` AS `product_entity` ON product_entity.sku=stock_index.sku AND (product_entity.created_in <= '1557751140' AND product_e                                                                               ntity.updated_in > '1557751140')
 INNER JOIN `m2_cataloginventory_stock_item` AS `legacy_stock_item` ON legacy_stock_item.product_id = product_entity.entity_id
 INNER JOIN `m2_catalog_product_website` AS `prod_website` ON legacy_stock_item.product_id = prod_website.product_id WHERE (
        (legacy_stock_item.use_config_manage_stock = 0 AND legacy_stock_item.manage_stock = 1) OR legacy_stock_item.use_config_manage_stock = 1) AND (prod_web                                                                               site.website_id = 1) {"exception":"[object] (Exception(code: 42): Report ID: webapi-5cd9859259535; Message: SQLSTATE[42S02]: Base table or view not found: 114                                                                               6 Table 'magento.catalog_product_website' doesn't exist, query was: SELECT
        IF(
            `product_entity`.`type_id` IN (
                'configurable',
                'bundle',
                'grouped'),
                NULL,
            NULL
        ) AS `qty`, \"1\" as is_salable, `product_entity`.`sku` FROM `m2_cataloginventory_stock_item` AS `legacy_stock_item`
 INNER JOIN `m2_catalog_product_entity` AS `product_entity` ON legacy_stock_item.product_id = product_entity.entity_id AND (product_entity.created_in <= '1557                                                                               751140' AND product_entity.updated_in > '1557751140')
 INNER JOIN `catalog_product_website` AS `pr_web` ON legacy_stock_item.product_id = pr_web.product_id WHERE ((legacy_stock_item.use_config_manage_stock = 0 AN                                                                               D legacy_stock_item.manage_stock = 0)) AND (pr_web.website_id = 1) UNION SELECT
        IF(
            `product_entity`.`type_id` IN (
                'configurable',
                'bundle',
                'grouped'),
            NULL,
            `quantity`
        ) AS `qty`, `stock_index`.`is_salable`, `stock_index`.`sku` FROM `m2_inventory_stock_1` AS `stock_index`
 INNER JOIN `m2_catalog_product_entity` AS `product_entity` ON product_entity.sku=stock_index.sku AND (product_entity.created_in <= '1557751140' AND product_e                                                                               ntity.updated_in > '1557751140')
 INNER JOIN `m2_cataloginventory_stock_item` AS `legacy_stock_item` ON legacy_stock_item.product_id = product_entity.entity_id
 INNER JOIN `m2_catalog_product_website` AS `prod_website` ON legacy_stock_item.product_id = prod_website.product_id WHERE (
        (legacy_stock_item.use_config_manage_stock = 0 AND legacy_stock_item.manage_stock = 1) OR legacy_stock_item.use_config_manage_stock = 1) AND (prod_web                                                                               site.website_id = 1) at /var/www/html/vendor/magento/framework/Webapi/ErrorProcessor.php:208, Zend_Db_Statement_Exception(code: 42): SQLSTATE[42S02]: Base tab                                                                               le or view not found: 1146 Table 'magento.catalog_product_website' doesn't exist, query was: SELECT
        IF(
            `product_entity`.`type_id` IN (
                'configurable',
                'bundle',
                'grouped'),
                NULL,
            NULL
        ) AS `qty`, \"1\" as is_salable, `product_entity`.`sku` FROM `m2_cataloginventory_stock_item` AS `legacy_stock_item`
 INNER JOIN `m2_catalog_product_entity` AS `product_entity` ON legacy_stock_item.product_id = product_entity.entity_id AND (product_entity.created_in <= '1557                                                                               751140' AND product_entity.updated_in > '1557751140')
 INNER JOIN `catalog_product_website` AS `pr_web` ON legacy_stock_item.product_id = pr_web.product_id WHERE ((legacy_stock_item.use_config_manage_stock = 0 AN                                                                               D legacy_stock_item.manage_stock = 0)) AND (pr_web.website_id = 1) UNION SELECT
        IF(
            `product_entity`.`type_id` IN (
                'configurable',
                'bundle',
                'grouped'),
            NULL,
            `quantity`
        ) AS `qty`, `stock_index`.`is_salable`, `stock_index`.`sku` FROM `m2_inventory_stock_1` AS `stock_index`
 INNER JOIN `m2_catalog_product_entity` AS `product_entity` ON product_entity.sku=stock_index.sku AND (product_entity.created_in <= '1557751140' AND product_e                                                                               ntity.updated_in > '1557751140')
 INNER JOIN `m2_cataloginventory_stock_item` AS `legacy_stock_item` ON legacy_stock_item.product_id = product_entity.entity_id
 INNER JOIN `m2_catalog_product_website` AS `prod_website` ON legacy_stock_item.product_id = prod_website.product_id WHERE (
        (legacy_stock_item.use_config_manage_stock = 0 AND legacy_stock_item.manage_stock = 1) OR legacy_stock_item.use_config_manage_stock = 1) AND (prod_web                                                                               site.website_id = 1) at /var/www/html/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:110, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view                                                                                not found: 1146 Table 'magento.catalog_product_website' doesn't exist at /var/www/html/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:91)"} []
[2019-05-13 14:56:18] report.CRITICAL: Report ID: webapi-5cd9859259535; Message: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento.catalog_pr                                                                               oduct_website' doesn't exist, query was: SELECT
        IF(
            `product_entity`.`type_id` IN (
                'configurable',
                'bundle',
                'grouped'),
                NULL,
            NULL
        ) AS `qty`, "1" as is_salable, `product_entity`.`sku` FROM `m2_cataloginventory_stock_item` AS `legacy_stock_item`
 INNER JOIN `m2_catalog_product_entity` AS `product_entity` ON legacy_stock_item.product_id = product_entity.entity_id AND (product_entity.created_in <= '1557                                                                               751140' AND product_entity.updated_in > '1557751140')
 INNER JOIN `catalog_product_website` AS `pr_web` ON legacy_stock_item.product_id = pr_web.product_id WHERE ((legacy_stock_item.use_config_manage_stock = 0 AN                                                                               D legacy_stock_item.manage_stock = 0)) AND (pr_web.website_id = 1) UNION SELECT
        IF(
            `product_entity`.`type_id` IN (
                'configurable',
                'bundle',
                'grouped'),
            NULL,
            `quantity`
        ) AS `qty`, `stock_index`.`is_salable`, `stock_index`.`sku` FROM `m2_inventory_stock_1` AS `stock_index`
 INNER JOIN `m2_catalog_product_entity` AS `product_entity` ON product_entity.sku=stock_index.sku AND (product_entity.created_in <= '1557751140' AND product_e                                                                               ntity.updated_in > '1557751140')
 INNER JOIN `m2_cataloginventory_stock_item` AS `legacy_stock_item` ON legacy_stock_item.product_id = product_entity.entity_id
 INNER JOIN `m2_catalog_product_website` AS `prod_website` ON legacy_stock_item.product_id = prod_website.product_id WHERE (
        (legacy_stock_item.use_config_manage_stock = 0 AND legacy_stock_item.manage_stock = 1) OR legacy_stock_item.use_config_manage_stock = 1) AND (prod_web                                                                               site.website_id = 1) {"exception":"[object] (Exception(code: 42): Report ID: webapi-5cd9859259535; Message: SQLSTATE[42S02]: Base table or view not found: 114                                                                               6 Table 'magento.catalog_product_website' doesn't exist, query was: SELECT
        IF(
            `product_entity`.`type_id` IN (
                'configurable',
                'bundle',
                'grouped'),
                NULL,
            NULL
        ) AS `qty`, \"1\" as is_salable, `product_entity`.`sku` FROM `m2_cataloginventory_stock_item` AS `legacy_stock_item`
 INNER JOIN `m2_catalog_product_entity` AS `product_entity` ON legacy_stock_item.product_id = product_entity.entity_id AND (product_entity.created_in <= '1557                                                                               751140' AND product_entity.updated_in > '1557751140')
 INNER JOIN `catalog_product_website` AS `pr_web` ON legacy_stock_item.product_id = pr_web.product_id WHERE ((legacy_stock_item.use_config_manage_stock = 0 AN                                                                               D legacy_stock_item.manage_stock = 0)) AND (pr_web.website_id = 1) UNION SELECT
        IF(
            `product_entity`.`type_id` IN (
                'configurable',
                'bundle',
                'grouped'),
            NULL,
            `quantity`
        ) AS `qty`, `stock_index`.`is_salable`, `stock_index`.`sku` FROM `m2_inventory_stock_1` AS `stock_index`
 INNER JOIN `m2_catalog_product_entity` AS `product_entity` ON product_entity.sku=stock_index.sku AND (product_entity.created_in <= '1557751140' AND product_e                                                                               ntity.updated_in > '1557751140')
 INNER JOIN `m2_cataloginventory_stock_item` AS `legacy_stock_item` ON legacy_stock_item.product_id = product_entity.entity_id
 INNER JOIN `m2_catalog_product_website` AS `prod_website` ON legacy_stock_item.product_id = prod_website.product_id WHERE (
        (legacy_stock_item.use_config_manage_stock = 0 AND legacy_stock_item.manage_stock = 1) OR legacy_stock_item.use_config_manage_stock = 1) AND (prod_web                                                                               site.website_id = 1) at /var/www/html/vendor/magento/framework/Webapi/ErrorProcessor.php:208, Zend_Db_Statement_Exception(code: 42): SQLSTATE[42S02]: Base tab                                                                               le or view not found: 1146 Table 'magento.catalog_product_website' doesn't exist, query was: SELECT
        IF(
            `product_entity`.`type_id` IN (
                'configurable',
                'bundle',
                'grouped'),
                NULL,
            NULL
        ) AS `qty`, \"1\" as is_salable, `product_entity`.`sku` FROM `m2_cataloginventory_stock_item` AS `legacy_stock_item`
 INNER JOIN `m2_catalog_product_entity` AS `product_entity` ON legacy_stock_item.product_id = product_entity.entity_id AND (product_entity.created_in <= '1557                                                                               751140' AND product_entity.updated_in > '1557751140')
 INNER JOIN `catalog_product_website` AS `pr_web` ON legacy_stock_item.product_id = pr_web.product_id WHERE ((legacy_stock_item.use_config_manage_stock = 0 AN                                                                               D legacy_stock_item.manage_stock = 0)) AND (pr_web.website_id = 1) UNION SELECT
        IF(
            `product_entity`.`type_id` IN (
                'configurable',
                'bundle',
                'grouped'),
            NULL,
            `quantity`
        ) AS `qty`, `stock_index`.`is_salable`, `stock_index`.`sku` FROM `m2_inventory_stock_1` AS `stock_index`
 INNER JOIN `m2_catalog_product_entity` AS `product_entity` ON product_entity.sku=stock_index.sku AND (product_entity.created_in <= '1557751140' AND product_e                                                                               ntity.updated_in > '1557751140')
 INNER JOIN `m2_cataloginventory_stock_item` AS `legacy_stock_item` ON legacy_stock_item.product_id = product_entity.entity_id
 INNER JOIN `m2_catalog_product_website` AS `prod_website` ON legacy_stock_item.product_id = prod_website.product_id WHERE (
        (legacy_stock_item.use_config_manage_stock = 0 AND legacy_stock_item.manage_stock = 1) OR legacy_stock_item.use_config_manage_stock = 1) AND (prod_web                                                                               site.website_id = 1) at /var/www/html/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:110, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view                                                                                not found: 1146 Table 'magento.catalog_product_website' doesn't exist at /var/www/html/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:91)"} []

**Comment by Stepa4man** [comment]
Thanks, for report @smoskaluk. It's a good issue. I missed this thing.

**Comment by ishakhsuvarov** [comment]
Seems to be fixed with https://github.com/magento-engcom/msi/pull/2263

Thanks @Stepa4man
