### ISSUE TITLE
Mass action 'Select all' doesn't work properly on product grid

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#2261]
### Preconditions (*)

1. MSI with multistock enabled
2. performance-toolkit/profiles/ce/small.xml preset applied

### Steps to reproduce (*)

1. Open 'Products' grid in admin
2. Choose 'Select All' for the grid (you got 1200 items selected) and select mass action 'Assign Inventory Source' 

### Expected result (*)

1. You may apply assigning custom source to all 1200 items

### Actual result (*)

1. You have only 20 products selected

![image](https://user-images.githubusercontent.com/27818516/57702982-cdebc300-7667-11e9-97e4-008871f9420d.png)

**Comment by ishakhsuvarov** [comment]
This seems to be issue primarily originating from https://github.com/magento/magento2

**Comment by ishakhsuvarov** [comment]
Looks like issue is unrelated to Inventory and was fixed in Core.
