### ISSUE TITLE
Exception on default stock edit

### ISSUE THREAD

**Issue by KhrystynaBalog** [magento/inventory#2273]
### Preconditions (*)

1. Magento with MSI

### Steps to reproduce (*)

1. Install Magento with MSI
2. Go to admin area
3. Navigate to Stores>Stocks
4. Create new Stock and assign Main website
5. Navigate to Stock grid
6. Press edit Default Stock

### Expected result (*)

1. Default stock edit page opened

### Actual result (*)

1. Exception occurred
![image](https://user-images.githubusercontent.com/46956333/58235487-93f67d00-7d49-11e9-8aa2-d3a607f392a8.png)

**Comment by ishakhsuvarov** [comment]
Hi @KhrystynaBalog 

Got this fixed in https://github.com/magento-engcom/msi/pull/2272 already! Thanks for reporting
