### ISSUE TITLE
DOCS: Add devdocs topic about integrating MSI with external ERP/stock keeping systems

### ISSUE THREAD

**Issue by keharper** [magento/inventory#2274]
### Summary (*)

Question on the MSI Slack channel

I have been reviewing this docs
https://devdocs.magento.com/guides/v2.3/rest/tutorials/inventory/index.html

The thing is that I need to catch the recently created order to be sent to a proprietary ERP , along with the data of the order I need to know from what source is the product going to be shipped

From what I have seen that data is created on "shipment" action. But my guess is that that product should have been reserved from a source in the moment the order was created

Igor M's response

for the integration with external ERP you can pluzinize interface `\Magento\InventorySalesApi\Api\PlaceReservationsForSalesEventInterface`
and sync up inventory changes correspondingly

> But my guess is that that product should have been reserved from a source in the moment the order was created

it's different in MSI. In fact reserving product on checkout we don't apply any Source reservation, we just reserve quantity from Stock.
Because at the time of checkout the system knows nothing about underlying sources at all.

The knowledge about Sources and which of those would be used to fulfil the order appears on the backend at the time of Shipment creation when admin runs Source Selection Algorithm

Navarr Barnier further comment:
Hmm... This could be problematic for tax calculation, which could vary based on where the inventory is physically coming from. Using an algorithm the tax system uses sounds like it could fix it, but then again I think there could be edge cases when a source is low and it needs to pull from another

### Examples (*)

None

### Proposed solution

A new topic that describes integrating MSI with external ERP / Stock keeping systems
and describes what API calls should be tracked and customised in this case.

Note: Igor's response was not complete

@lorikrell Feel free to throw this back at me.

### Additional info on topic

https://magento.stackexchange.com/questions/273156/disable-msi-in-magento-2-3/273239/
https://www.mexbs.com/magento-blog/disabling-the-magento-msi/
https://twitter.com/ryden_andrew/status/1135642817534058496

reasons why SMBs are disabling MSI
but in fact, in MSI the extension points are much more explicit than before

**Comment by ishakhsuvarov** [comment]
On a side note, when order is created product is reserved only at a stock level. Source deduction occurs later when order is shipped, as in multiple scenarios it would be a performance intense operation which we don’t want to happen during checkout.

**Comment by lorikrell** [comment]
Will check this out. Thanks!

**Comment by sidolov** [comment]
Will be covered in scope of devdocs issue
