### ISSUE TITLE
Error after adding grouped product to the cart from the category page

### ISSUE THREAD

**Issue by KhrystynaBalog** [magento/inventory#2275]
### Preconditions (*)

1. Create custom stock with custom source
2. Create grouped product with child simple product with default quantity 2 on custom source.

### Steps to reproduce (*)

1. Go to Category page 
2. Try to add Grouped product to the cart

### Expected result (*)

1. Grouped product added to the cart successfully.

### Actual result (*)

1. Grouped product isn't added to the cart, but message "You added grouped product to your shopping cart" appears.
![Screenshot](https://user-images.githubusercontent.com/46956333/58318599-c45d1a80-7e20-11e9-94f2-8504afc08ac5.png)

**Comment by ishakhsuvarov** [comment]
Closing as non-reproducible per offline discussion with @KhrystynaBalog
