### ISSUE TITLE
No linked stock found during the upgrade from 2.2 -> 2.3

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#2277]
2.2.7 -> 2.3.1

Composer installation, upgrade through UI wizard. 

For some reasons, Default Source and Stock have not been created during upgrade to Magento 2.3.1
\Magento\InventoryCatalog\Setup\Operation\CreateDefaultStock
\Magento\InventoryCatalog\Setup\Operation\CreateDefaultSource 
(two these setup operations were not executed).

As the result exception with a message "no linked stock found" thrown while resolving Stock by Website.

See similar exceptions for more details:
1. https://magento.stackexchange.com/questions/273802/after-upgrade-from-magento-2-2-x-to-2-3-x-getting-no-linked-stock-found-on-mul 
2. https://community.magento.com/t5/Magento-2-x-Version-Upgrades/Magento-update-to-2-3-compilation-errors/td-p/114524

Related issue:
1. https://github.com/magento/data-migration-tool/issues/634
2. https://github.com/magento-engcom/msi/issues/1440

Lastly reproduced with next business use case:
usecase: 2.2.7 
clean 2.3.1 + sample data connected to 2.2.7 db.  trying to use the setup wizard
and 2.2.7 was open source 2.3.1 is Commerce

**Comment by makkoff** [comment]
I can not reproduce. Give more details please.

**Comment by sidolov** [comment]
Hi @maghamed , we tried to reproduce the issue several times by a few team members and described flow working as expected. I'm closing the issue for now, feel free to reopen it if you find out how to reproduce it. Thank you!
