### ISSUE TITLE
Global refactoring of plugin namespaces and names

### ISSUE THREAD

**Issue by naydav** [magento/inventory#228]
1) Need to move all our plugins to Plugins namespace
2) Lead our namespace to `ModuleName\Plugins\{CustomizedModule}`
3) Provide more clear names of our plugins (describe behaviour in class name)

**Comment by roma-glushko** [comment]
Hi guys, 
I have prepared some changes to fix mentioned issues. 
Would be great if you have a chance to check them (https://github.com/magento-engcom/msi/pull/251).
Thanks.

**Comment by naydav** [comment]
Closed due to changes in mainline (We have finished refactoring in scope of Kyiv Contribution Day)
