### ISSUE TITLE
Add Sources column to the Sales Order Grid in Magento Admin panel

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#2281]
Igor Miniailo [12:46 PM]
But regarding Product Grid we need to think how to  do it properly, as we have too many states here:
1. Orders where SSA / Shipment is not run yet - so there is Source allocation at all
2. Orders for which we had partial shipment , but they are still not completed yet
3. Orders in complete state , whether canceled / refunded / or shipped
I believe the intermediate state could be confusing

Steve Kukla [12:56 PM]
(Agreed)
We ought to consider what would be most clearly useful (which to me, would be the sources used to _ship_ the items)
Meaning, we at least need to see the sources used to completely fulfill.

**Comment by skukla** [comment]
To clarify, the chief business value provided by this proposition is order visibility.  In the event of a need to clarify an error or the inability to fulfill, we should provide the merchant with the quickest possible method to find and diagnose those issues.

**Comment by ishakhsuvarov** [comment]
Clarification on requirements:
* Orders in all statuses should display allocated sources
* In case where multiple sources are allocated all of them must be displayed. When there are more then 5 sources, remaining should be moved to the tooltip (see implementation on product grid for reference).
* For orders with no source allocated field must remain blank.
