### ISSUE TITLE
In-Store Pickup orders adjustments in Admin Panel

### ISSUE THREAD

**Issue by swnsma** [magento/inventory#2285]
### Description  
For In-Store Pickup orders in Admin UI there is still possible to:
- create usual shipment, instead of notify customer that his/her order is ready for pickup
- edit shipping address 

### To Do 
- remove possibility to create usual shipment for In-Store Pickup orders
- make shipping address not editable for In-Store Pickup orders

**Comment by novikor** [comment]
On hold until checkout API is implemented, and Service Isolation is discussed.

**Comment by ishakhsuvarov** [comment]
Fixed in #2334
