### ISSUE TITLE
Create Orders With Simple Product In Multi Stock Mode - automation.

### ISSUE THREAD

**Issue by nmalevanec** [magento/inventory#2293]
Automate Web-Api tests scenarios:

1. https://app.hiptest.com/projects/69435/test-plan/folders/530370/scenarios/1837241
2. https://app.hiptest.com/projects/69435/test-plan/folders/530370/scenarios/1841119
3. https://app.hiptest.com/projects/69435/test-plan/folders/530370/scenarios/1841699
4. https://app.hiptest.com/projects/69435/test-plan/folders/530370/scenarios/1850104

**Comment by ishakhsuvarov** [comment]
Done
