### ISSUE TITLE
Create Orders With Virtual Product In Multi Stock Mode automation.

### ISSUE THREAD

**Issue by nmalevanec** [magento/inventory#2295]
Automate Web-Api tests scenarios:

1. https://app.hiptest.com/projects/69435/test-plan/folders/530380/scenarios/1851577
2. https://app.hiptest.com/projects/69435/test-plan/folders/530380/scenarios/1851580
3. https://app.hiptest.com/projects/69435/test-plan/folders/530380/scenarios/1851581
4. https://app.hiptest.com/projects/69435/test-plan/folders/530380/scenarios/1851582

**Comment by ishakhsuvarov** [comment]
Done
