### ISSUE TITLE
Staging Preview with Configurable Product and MSI enabled

### ISSUE THREAD

**Issue by ishakhsuvarov** [magento/inventory#2298]
### Preconditions
1. Create a simple product with "Enable Product" set to "No"
2. Add configurations based on "Color" with unique images. Keep price and inventory the same for all configurations, with inventory assigned to US Warehouse and US Store
     a. By default, configurations will be set to "Enable Product" = "Yes" but Visibility set to "None"
3. Schedule an update with no end date to the new parent configurable product. In the update, change the "Enable Product" value to "Yes"
4. Reindex and Flush Cache

### Steps to reproduce
1. Preview created content staging update

### Expected Result
✅Configurable Product is available for preview with options. It's possible to add Configurable Items to cart.

### Actual Result
❌Configurable Product is available, however options can not be added to cart. When trying to do so error message appears. System Log is populated with errors as well.

### Notes
This issue must be verified both with **MSI + Enterprise Edition** and **Community Edition + Enterprise Edition**. It can only be considered as MSI issue if it's reproducible with MSI + EE.

**Comment by KhrystynaBalog** [comment]
@ishakhsuvarov , I wasn't able to reproduce issue with the given steps: 
![Peek 2019-06-05 10-54](https://user-images.githubusercontent.com/46956333/58944639-ef356000-878a-11e9-8bc7-ec56abd329fd.gif)

But I encountered another issue on Single stock mode and Default Source on Multi Stock mode:
### Preconditions:
Magento EE with MSI.
### Steps for Single stock mode
1.  Create a simple product with "Enable Product" set to "No"
Add configurations based on "Color" with unique images. 
2. Apply single quantity = 100 to all SKUs
3. Create Schedule update for parent Configurable product with  "Enable Product" set to "Yes".
4. Reindex and Flush Cache.
5. Preview staging update.


Or:
### Steps for  Default source on Multi stock mode
1. Create Test Stock and test Source.
2.  Create a simple product with "Enable Product" set to "No"
3. Add configurations based on "Color" with unique images. 
4. Keep price and inventory the same for all configurations, with inventory assigned to Default source.
5. Create Schedule update for parent Configurable product with  "Enable Product" set to "Yes".
6. Reindex and Flush Cache.
7. Preview staging update.

### Expected result:
Configurable product has In stock status
### Actual result
Configurable product is out of stock.
