### ISSUE TITLE
manage stock = no but showing only X left

### ISSUE THREAD

**Issue by ishakhsuvarov** [magento/inventory#2299]
### Description
This ticket is intended to be processed with the information from https://magento.stackexchange.com/questions/275516/magento-2-3-1-manage-stock-no-but-showing-only-0-left

### Preconditions
1. Create Product with `manage stock = false` configuration.
2. Enable `Only show when X left` setting with any qty, say 5.

### Steps to reproduce
1. Verify the product on frontend

### Actual Result
❌Product has a message saying that only X left in stock

### Expected result
✅No redundant messages are displayed to customer

### Additional Information
It's best to verify this case with **CE /wo MSI** and **CE /w MSI**

**Comment by KhrystynaBalog** [comment]
@ishakhsuvarov, the two scenarios I was able to reproduce:
1. Create simple product with qty less then "only x left"
2. Disable "Manage Stock" only after buying product in order to make product qty less then "only x left".

Both scenarios reproduced, on mainline without MSI as well.

**Comment by alshulah** [comment]
Anyone tested 

below patch

https://support.magento.com/hc/en-us/articles/4410121211917-MDVA-37115-Only-0-left-notice-is-shown-on-product-page
