### ISSUE TITLE
Create Order with Downloadable, Grouped and Bundle Products in Multistock mode automation

### ISSUE THREAD

**Issue by nmalevanec** [magento/inventory#2300]
Test to be automated:

1. https://app.hiptest.com/projects/69435/test-plan/folders/530373/scenarios/1870535
2. https://app.hiptest.com/projects/69435/test-plan/folders/530373/scenarios/1870536
3. https://app.hiptest.com/projects/69435/test-plan/folders/530381/scenarios/1870317
4. https://app.hiptest.com/projects/69435/test-plan/folders/530381/scenarios/1870478
5. https://app.hiptest.com/projects/69435/test-plan/folders/530382/scenarios/1820317
6. https://app.hiptest.com/projects/69435/test-plan/folders/530382/scenarios/2270016

**Comment by ishakhsuvarov** [comment]
Done
