### ISSUE TITLE
Create Order with Configurable Product in Multistock mode automation

### ISSUE THREAD

**Issue by nmalevanec** [magento/inventory#2304]
Tests to be automated:
1. https://app.hiptest.com/projects/69435/test-plan/folders/530371/scenarios/1855154
2. https://app.hiptest.com/projects/69435/test-plan/folders/530371/scenarios/1855158
3. https://app.hiptest.com/projects/69435/test-plan/folders/530371/scenarios/1855166
4. https://app.hiptest.com/projects/69435/test-plan/folders/530371/scenarios/1855398

**Comment by ishakhsuvarov** [comment]
Done
