### ISSUE TITLE
Slow Inventory save with Web API

### ISSUE THREAD

**Issue by ishakhsuvarov** [magento/inventory#2306]
### Steps to reproduce
1. Use `POST rest/V1/inventory/source-items` to save larger amount of source items, like > 2000.

### Actual result (*)
1. Saving takes ~60 second in a production environment

### Expected result
1. Save time increases linearly instead of exponentially

**Comment by TadeuRodrigues** [comment]
Hi @ishakhsuvarov, i was think to use load data to finish this issue.
let's me explain.

We save a csv file in somewhere folder after that we insert from csv file with load data.
what do u think?

**Comment by ishakhsuvarov** [comment]
Hi @TadeuRodrigues 

Using files is more of an import feature to me. This ticket is more or less related to the web api performance, which in this case does not scale to well with the number of items. Reportedly, this service execution time does not increase linearly but in a more steep way. This is something worth investigating.

**Comment by nuzil** [comment]
So every Christmas MSI Santa is coming and looking if your performance issues were good maintained.

Hi @ishakhsuvarov 
Santa made some research on this topic.

Basically its taking for me 15 seconds for 2000 stock updates if you doing it for "default" stock, and 11 seconds for not default.

Difference in coming from functionality for "default" legacy code. Which makes additional updates.

From flow: 
- about 35% of the time execution takes reindexing and cache invalidation for those entries.
we have 
* Stock index
* Grouped products reindex
* Products reindex
* Configurable products reindex
* Price index
* Specific Product cache flush

I'm not sure there are a good optimisation possibilities. I see even logic with Index and Cache quite good made, for do not disturb customer

In any case for big operations flow make sense to use Asynchronous operations

**Comment by nuzil** [comment]
Sorry, I wanted to help at least somehow, so made a small PR :-)
