### ISSUE TITLE
Add column to Product grid with information about source items

### ISSUE THREAD

**Issue by naydav** [magento/inventory#231]
Need to add one more column to product grid with data about source items related to this products

Examples:
- Column class `\Magento\InventorySales\Ui\Component\Listing\Column\SalesChannels`
- UI component of cell `app\code\Magento\InventorySales\view\adminhtml\web\js\stock\grid\cell\sales-channels.js`
- Template `app\code\Magento\InventorySales\view\adminhtml\web\template\stock\grid\cell\sales-channel-cell.html`

**Comment by motorlesha** [comment]
created

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/305
