### ISSUE TITLE
Prevent Default Source Disabling API functional tests fails with SOAP adapter

### ISSUE THREAD

**Issue by ishakhsuvarov** [magento/inventory#2326]
### Preconditions (*)
1. Test is currently skipped in repository, has to be unskipped first.

### Steps to reproduce (*)
1. Execute `\Magento\InventoryCatalogApi\Test\Api\PreventDefaultSourceDisablingTest` with SOAP adapter.

### Actual result (*)
```
Magento\InventoryCatalogApi\Test\Api\PreventDefaultSourceDisablingTest::testPreventDefaultSourceDisabling
PHPUnit\Framework\Exception: Notice: Undefined property: stdClass::$parameters in dev/tests/api-functional/framework/Magento/TestFramework/TestCase/WebapiAbstract.php:675
```

**Comment by konarshankar07** [comment]
Hello @ishakhsuvarov 

I tested in my local and test has been passed and not getting any error
![image](https://user-images.githubusercontent.com/39480008/60769194-5cba1080-a0ea-11e9-8b5e-f0f709eb0113.png)
