### ISSUE TITLE
Admin user create order from Test website with Simple product with inventory on Default and Test stock Automation

### ISSUE THREAD

**Issue by Nazar65** [magento/inventory#2327]
### Steps to be automated

https://app.hiptest.com/projects/69435/test-plan/folders/735286/scenarios/3041899

1. Admin User creates custom Website with new Store and new Store View
2. Customer created from Test website
3. New Category created
4. New source created
5. New Stock created with New Source assigned and with Test Website assigned as Sales Channel
6. Simple Product created with Default and Test Source assigned and visible on Main and Test website
7. Admin user created Order with 5 items of Simple product from Test website
8. Verify in admin that Order created successfully
9. Verify quantity of Simple product on Test stock after placing order
10. Verify that reservation '-5' for Simple product on Test stock is created

**Comment by ishakhsuvarov** [comment]
Merged in #2328
