### ISSUE TITLE
Inventory Export Stock Api dump-stock-index-data for different types of products on Test stock and Test website Automation

### ISSUE THREAD

**Issue by Nazar65** [magento/inventory#2331]
### Steps to be automated
https://app.hiptest.com/projects/69435/test-plan/folders/908874/scenarios/3042517
https://app.hiptest.com/projects/69435/test-plan/folders/908874/scenarios/3042336

1. New Category created
2. New Website created with Store and new Store View
3. New source created
4. New Stock created with New Source assigned and with Test Website assigned as Sales Channel
5. Simple Product created with Test Source assigned and visible on Test website
6. Virtual Product created with Test Source assigned and visible on Test website
7. Downloadable Product created with several Sources assigned on Test website
8. Grouped Product created with child products assigned on Test Stock and to Test website
9. Configurable Product created with drop-down attribute and child product assigned to Test Source in admin
10. Create Inventory Export Stock Api dump-stock-index-data for products on Test stock 
11 nventory Export Stock Api for products on Test stock created export correctly

**Comment by ishakhsuvarov** [comment]
Status is now automated according to HipTest
