### ISSUE TITLE
Import with different kinds of behaviors with sample file - automation.

### ISSUE THREAD

**Issue by nmalevanec** [magento/inventory#2339]
Tests to be automated:
1. https://app.hiptest.com/projects/69435/test-plan/folders/908874/scenarios/1418539
2. https://app.hiptest.com/projects/69435/test-plan/folders/908874/scenarios/1465136
3. https://app.hiptest.com/projects/69435/test-plan/folders/908874/scenarios/1465165

**Comment by ishakhsuvarov** [comment]
Merged in #2342
