### ISSUE TITLE
Feature Request: Assign Source Selector for Processing of Returns/Credit Memo (with example use case and process)

### ISSUE THREAD

**Issue by seansan** [magento/inventory#2343]
## Description
Add ability to select return warehouse per product on credit note. 

The business rationale behind this - is that it is illogical to assume a return will alwats go back to its original source. The fact of the matter is that in real life it will - more often **not** go back to the original source.  Also consider a stock location where _all returns_ are held when received for reconditioning before they are moved to another source whenr ready for sale again.

Note. just like this has worked for us in M1 for years. Via an extension, but this way we can easily share and learn from the use case. I have attached a short video demonstrating final design and elements that can be used to create this addition to the process.

## Expected behavior (*)
When creating a credit note and when "return to stock" is selected, a drop down should appear with all the source locations belonging to the stock && that are accepting returns. This way the admin can administrate correctly and in 1 go: where the return was sent to (and received).

The default selected method is the originating source or a source location that is defined on source level for orders that have not been shipped (status processing) and have been shipped (status complete).

We recommend creating a dummy (extra) list element for the "originating source" or to mark the originating source with an asterisk or with string "OS" and preselecting this.

## Benefits
Dont know how to make this clear, but from our perspective: how can you use MSI without it? It almost seems un-usable. Of course we need to be able to set the source for where a return was snet to. And no it is hardly ever the same as the source.

Also here it looks like the author was meaning to differ between the processing of the credit note for single versus multisource vendors. For multisource there needs to be an option to select which of the _multi sources_ it should go back to.
https://github.com/magento/inventory/wiki/Stock-Management-for-Order-Cancelation#compensation-for-credit-memo-return-to-stock-is-checked

## Additional information
Please view the below animated gif to 
1. demonstrate the process of credit memo processing for multi sources
2. the necessary settings to achieve this
(do take in mind this is an example; and and example of M1. But it does show quite nicely how it should work. Also it has been perfected over many many years of use .. I hope this is take into account)

![PROCESS VIDEO DEMO WITH EXAMPLES](https://pasteboard.co/Ikkl1FR.gif)

### Global Config Settings

 - Config setting: Set default return source for PROCESSING orders (unshipped)
 - Config setting: Set default return source for COMPLETED orders (have been shipped)
For both dropdown elements: this can be either 1 of the sources (hardcoded) or the extra option originating source. (so 1 extra selection element is added called originating source)

ps. these settings may also be configured on the STOCK config level where sources are assigned and called something like returns configuration.

### Source Config Settings

 - Config setting: Source can accept returns (only for COMPLETED status type)

### GUI Design and data preparation/collection

 - On credit memo processing show dropdown with available sources that can receive returns. If Order status = processing then show all, if order status is complete then show only locations that accept returns
- On credit memo processing pre-select the correct (return) source based on config settings: if order status = processing then try to set to this selection; if order status is complete then use the config source selection for this state
- If checkmark RETURN STOCK is selected then enable dropdown; if unselected disable dropdown

### Backend processing

 - Controllers should call methods to process the credit memo stock return based on the selected option per product by the admin. And updated Salable Qty per source and stock accordingly.

## Importance

Without this we cannot go live using M2 - it is this important!

THE END

Hope this makes sense

**Comment by seansan** [comment]
Dont know why the img / movie gif is nog longer viewable .... this really added to the case

**Comment by sidolov** [comment]
@seansan the issue converted to story and located here: https://github.com/magento/inventory/wiki/Assign-Source-Selector-for-Processing-of-Returns-Credit-Memo
We are going to include it to the next milestone and start development soon.
