### ISSUE TITLE
Feature Request: Add simple Global Config option to log stock changes in order history

### ISSUE THREAD

**Issue by seansan** [magento/inventory#2344]
## Description
Add simple Global Config option to log stock changes in order history

This is the easiest way to investigate problems (hey! where is the product??!! during shipping) and should break nothing. Suggestion is to create 1 global option for this under shystem/developer or admin and set to OFF by default. If you turn it on then when a sale is made the sourcing is briefly logged, idem for shipment and processing of returns.

To us as a user it seems quite logic to see fast where did something come from and where did it go to, and when - and by whom.

## Expected behavior (*)
When a sale is made, shipment or return or cancellation processed, then
- log the qty change per product per source
- and in the process log the time and user who did it

## Benefits
Quick win. Breaks nothing. Adds a lot. 
For admin and distribution this is a very important feature when having to debug lost and incomplete orders. Problem orders.

## Additional information
Please view the below animated gif to 
1. demonstrate how it may look like 

![PROCESS VIDEO DEMO WITH EXAMPLES](https://pasteboard.co/IkkvhKV.gif)

### Global Config Settings

 - Config setting: Log stock changes in order history yes/no, defaults to no

ps. these settings may also be configured on the STOCK config level where this setting is decided uponper STOCK or per CHANNEL maybe

### Backend processing

 - Observers on stock change events trigger order history logging of the changes ONLY if the config setting to log stock changes is set to yes. Can maybe be kept very simple.

```
Jun 20, 2019 8:49:20 PM | REFUND | MYUSERNAME
Customer Not Notified 
Refunded Order:
Product SKU: PF.PP0H0A001-40 +1 qty to Local ToFold
Product SKU: PF.PP0H0A057-43 +1 qty to Local Stock
Product SKU: DS.90931.3.093-L +1 qty to Local Returns

```

and

```
Jun 20, 2019 8:34:29 PM | PENDING PAYMENT | MYUSERNAME
Customer Not Notified 
Created Order:
Product SKU: PF.PP0H0A001-40 -1 qty from Local Stock
Product SKU: PF.PP0H0A057-43 -1 qty from Remote Virtual
Product SKU: DS.90931.3.093-L -1 qty from Local Returns
Product SKU: DS.91136.3.053-L -1 qty from Remote Virtual

```

THE END

Hope this makes sense

**Comment by sidolov** [comment]
Hi @seansan , thank you for your request! The described behavior is already implemented, we log the source used for every shipment and return. I'm closing the issue! 
Thank you for your collaboration!
