### ISSUE TITLE
Feature Request: Allow Admin SOURCE CHANGE before order has been shipped

### ISSUE THREAD

**Issue by seansan** [magento/inventory#2345]
## Description
Allow Admin SOURCE CHANGE before order has been shipped

Often when a sale is made a logistics employee or the site admin mayb know : hey!! but we still have 1 of them lying around here or there. Or ... maybe a stock replenishment was executed just seconds before ...... 

It would be very nice if an admin is then still "capable" or re-assigning the source how to fulfill the order BEFORE the shipment is made. 

I mean in Magento 1 this was difficult to do ... but now with reservations ... we un-reserve the product from original source, and re-reserve the same product from a new source .... 

## Expected behavior (*)
Show a dropdown per product line item in the order, showing
 - where this product can be sourced from (not applicable is greyed out)

And give the option to select ANOTHER source for this order and SAVE the selection.

## Benefits
Allow order editing and solve many logistics problems. Dont have to recreate the order.

And from our perspective just simple logic. Why not change the source? The order has nto been shipped yet ....

## Additional information
Please view the below animated gif to 

demonstrate how it may look like 

![PROCESS VIDEO DEMO WITH EXAMPLES](https://pasteboard.co/IkkAKdr.gif)

### Global Config Settings

 - Config setting: Allow source change before order shipment yes/no, defaults to yes

ps. these settings may also be configured on the STOCK config level

### GUI Design and data preparation/collection

 - On order view show dropdown with available sources and the salable stock per location for that products only if order status = processing. 
- Else if order has been completed or closed show the final selected source and print as hardcoded (as string).
- On Select change show button (or onchange event) .. triggers AJAX request to server and changes source allocation of that sale product line item

### Backend processing

 - Controllers should process ajax request, update source allocation and reservation for that line item

THE END

Hope this makes sense

**Comment by seansan** [comment]
Dont know why the image / movie gif is gone -- used to work fine

**Comment by sidolov** [comment]
Hi @seansan  , the described behavior is already implemented. I'm closing the issue since it's not relevant.
Thank you for your involvement!
