### ISSUE TITLE
[Store Pickup] Name in the FrontendName as null

### ISSUE THREAD

**Issue by TBlindaruk** [magento/inventory#2348]
We had an issue on the Magento/InventoryInStorePickup/Model/PickupLocation/Mapper/PreProcessor/FrontendName.php:process method, that `$source->getName()` could return null value, but in the process method signatures it will return only string
https://github.com/magento/inventory/pull/2338/files#diff-626e080f1e31d03c1ea176897ee36648R28

So please decide what we should do with this and fix it.

**Comment by swnsma** [comment]
I think that we can do next:
- Remove Pickup Location Name pre-processor
- Fill Source 'Front Name' extension attribute in next cases:
-- Source is not a Pickup Location - do nothing.
-- Source has Front Name - do nothing.
-- Source has empty Front Name - use Source Name for this field.
- see \Magento\InventoryDistanceBasedSourceSelection\Plugin\FillSourceLatitudeAndLongitude for example

**Comment by swnsma** [comment]
Completed.
