### ISSUE TITLE
Avoid using Inventory Stock Index for default stock

### ISSUE THREAD

**Issue by ishakhsuvarov** [magento/inventory#2353]
### Description
Inventory Stock Index for default stock is implemented using MySql VIEW which may be performing slowly under load in specific conditions. There is not much sense in using this VIEW in the core codebase, as calls can be made directly to the legacy index tables. VIEW compatibility still has to be in place for third-party integrations.

### To Do
1. Identify possible usages of `inventory_stock_1` view in core MSI modules. (`StockIndexTableNameResolverInterface` dependency may be a hint)
2. Introduce logic bypassing VIEW to each usage. 
3. Make sure tests still pass. Based on existing experience tests should not be affected.

### Related Pull Request on the subject:
* https://github.com/magento/inventory/pull/2350
* https://github.com/magento/inventory/pull/2336
* https://github.com/magento/inventory/pull/2120

**Comment by konarshankar07** [comment]
Hello @ishakhsuvarov ,
Please close this issue.
Thanks

**Comment by ishakhsuvarov** [comment]
Thanks for pointing out @konarshankar07
