### ISSUE TITLE
Disable In-Store Pickup Delivery for Multishipping

### ISSUE THREAD

**Issue by swnsma** [magento/inventory#2358]
### Description

In-Store Pickup Shipping Method must not be available for Multi-shipping (at least for MVP).
Now it displays like a one more shipping method.
Please find way to hide it.

![image](https://user-images.githubusercontent.com/9420807/59995846-3fecfa00-9661-11e9-91e7-2d65eb9f2db2.png)

**Comment by websnap** [comment]
I've picked up current ticket.
@swnsma please assign it to me.
