### ISSUE TITLE
ElasticSearch automation.

### ISSUE THREAD

**Issue by nmalevanec** [magento/inventory#2370]
Tests to automated:
1, https://app.hiptest.com/projects/69435/test-plan/folders/441590/scenarios/2688565
2. https://app.hiptest.com/projects/69435/test-plan/folders/441590/scenarios/2688359
3. https://app.hiptest.com/projects/69435/test-plan/folders/441590/scenarios/2684477

**Comment by ishakhsuvarov** [comment]
Reopened, as `app/code/Magento/InventoryAdminUi/Test/Mftf/Test/ElasticSearchLayeredNavigationTest.xml` started to fail shortly after the merge.
