### ISSUE TITLE
CLI exception entity doesn't exist

### ISSUE THREAD

**Issue by jorgb90** [magento/inventory#2377]
### Preconditions (*)
1. Magento 2.3.2 Production
2. MSI

### Steps to reproduce (*)
1. Execute the command "bin/magento inventory:reservation:list-inconsistencies -r | bin/magento inventory:reservation:create-compensations"

### Expected result (*)
1. New reservations are created to either place or release a hold on salable quantity.

### Actual result (*)

```
[master]:public_html$ bin/magento inventory:reservation:list-inconsistencies -r | bin/magento inventory:reservation:create-compensations
Following reservations were created:
  - Argument "ORDERID:SKU:-1.000000:2" caused exception "The entity that was requested doesn't exist. Verify the entity and try again."
  - Argument "ORDERID:SKU:-1.000000:2" caused exception "The entity that was requested doesn't exist. Verify the entity and try again."
  - Argument "ORDERID:SKU:-1.000000:2" caused exception "The entity that was requested doesn't exist. Verify the entity and try again."
  - Argument "ORDERID:SKU:-1.000000:2" caused exception "The entity that was requested doesn't exist. Verify the entity and try again."
```

Replaced the actual orderid and SKU for privacy reasons.

**Comment by smoskaluk** [comment]
Duplicate https://github.com/magento/inventory/issues/2203
