### ISSUE TITLE
Filter products by sources

### ISSUE THREAD

**Issue by VZeroCool** [magento/inventory#2416]
### Summary (*)
My customer looking to sort SKU by warehouses

### Examples (*)
Like We can check at backend that how many salable qty there for every sources but its kind a weird.

### Proposed solution
Is there any report, export anything which can help to find out sources has how many SKUs ?
This might be helpful for a business owner. Because we also don't have filter by warehouse at products. 

May be I missed that part of MSI ? If any thing related to query available !!

**Comment by sidolov** [comment]
Hi @VZeroCool  , we are about to complete MSI project feature development and keep issues of defined scope only to have clean and transparent backlog. 
Unfortunately, the current issue is out of scope and should be closed. 
Thank you for your involvement!
