### ISSUE TITLE
Downloadable Product not Visible on Category Page after saving invalid information the first time

### ISSUE THREAD

**Issue by danmooney2** [magento/inventory#2423]
### Preconditions (*)

1. Magento 2.3.2 with MSI 2.3.0-release

### Steps to reproduce (*)

1. Add category
2. Add downloadable product to category
3. Save downloadable product with invalid domain URL
4. Re-save downloadable product using valid domain URL
5. Visit corresponding category page

### Expected result (*)

1. Category has downloadable product visible on page

### Actual result (*)

1. Downloadable product is missing on category page (it is completely empty)

![image](https://user-images.githubusercontent.com/30629803/61896435-9b1d4100-aeda-11e9-9cf4-99dacaa0f21c.png)

Corresponding internal issue: https://jira.corp.magento.com/browse/MC-18595

**Comment by smoskaluk** [comment]
Hi @danmooney2! May you please clarify steps -
3. Save downloadable product with invalid domain URL
4. Re-save downloadable product using valid domain URL

**Comment by danmooney2** [comment]
Closing as it seems to be unrelated; it was a hunch that it was ElasticSearch causing it but it has since been fixed in a separate ticket; closing
