### ISSUE TITLE
Adding source filter to product collection will be helpful

### ISSUE THREAD

**Issue by VZeroCool** [magento/inventory#2424]
### Summary (*)
Currently, there's no possibility to filter product collection via sources.

### Examples (*)
There's a class available which can filter by stock status. 
Magento\InventoryCatalog\Model\ResourceModel\AddIsInStockFieldToCollection
But not possible to filter via sources. 

### Proposed solution
A method similar to above might be helpful to retrieve products based on warehouse. 
We're about to move to production and this scenario came to action there's no way to check how many products left in sources.

Check below query for more understanding. 

https://magento.stackexchange.com/questions/283247/add-filter-for-sources-at-product-grid

**Comment by sidolov** [comment]
@VZeroCool such customizations should be implemented in the scope of the 3d party module if it's needed. Right now we haven't case for such filter. Thank you!

**Comment by seansan** [comment]
+1

I think this is a great addition. You wan to be able to view product collections based on availability in a source

In addition a request was made to be able to create a "category" from 1 stock in 1 source (for example a SALE category that accesses only!! the products that are in stock in 1 source and where the layered nav is also built on the actual products in that source only!)

**Comment by Brocknoviatch** [comment]
In stock filter
Sale filter
In stock in particular warehouse

These should all be standard part of Magento 2, not 3rd party installs. I can't think of an eCommerce store owner who doesn't want this functionality!
This should be reopened.
