### ISSUE TITLE
Deployment Breaks After Upgrading to Magento 2.3.2

### ISSUE THREAD

**Issue by sreenathnr** [magento/inventory#2445]
### Preconditions (*)

Magento 2.3.2
1. After Magento, upgrading from Magento 2.3.1 to 2.3.2

### Steps to reproduce (*)

1. Multi-stock Inventory Modules are enabled in Magento 2.3.1
2. Upgrade Magento 2.3.2 from Magento 2.3.1 by using composer.
3. Deployment initiated

### Expected result (*)

1. Deployment is a success with no Errors

### Actual result (*)

1. Deployment has the below errors.

` Fatal error: Uncaught Error: Cannot instantiate interface Magento\Framework\HTTP\ClientInterface in /opt/lampp/htdocs/example/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:50`

`Stack trace: #0 /opt/lampp/htdocs/example/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...') magento/magento2#1 /opt/lampp/htdocs/example/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(160): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...') magento/magento2#2 /opt/lampp/htdocs/example/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(246): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'client', 'Magento\\Invento...') magento/magento2#3 /opt/lampp/htdocs/example/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Invento...', Array, Array in /opt/lampp/htdocs/example/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 50`

**Comment by ankita-mundada** [comment]
Add  below line if not present in app\etc\di.xml

<"preference for="Magento\Framework\HTTP\ClientInterface" type="Magento\Framework\HTTP\Client\Curl">

This worked for me.

**Comment by ishakhsuvarov** [comment]
@ankita-mundada It should already be there in 2.3.2 release: https://github.com/magento/magento2/blob/ddf42caaf25311f10b23b95a92746f99943e045e/app/etc/di.xml#L212

**Comment by eduan** [comment]
> Please, check file app/code/etc/di.xml.
> it must contain a this line:
> preference for="Magento\Framework\HTTP\ClientInterface" type="Magento\Framework\HTTP\Client\Curl"

My local env was missing the di.xml
It helped me to solve

**Comment by ishakhsuvarov** [comment]
@eduan That's really strange. How did you get the code?

**Comment by PivitParkour94** [comment]
I had a similar issue. Debugged the issue by putting a breakpoint at `\Magento\Framework\ObjectManager\Factory\Dynamic\Developer::create` with a condition to only break on the `Magento\Framework\HTTP\ClientInterface`
Then stepped back to find what class called it which was a console command bundled in `Magento\InventoryDistanceBasedSourceSelection\Model\ImportGeoNames`
So then I disabled `Magento_InventoryDistanceBasedSourceSelection` and the install worked as expected. This seems to be a core bug...

**Comment by ishakhsuvarov** [comment]
Closing, as the preference was fixed in the core. 

See 
* https://github.com/magento/magento2/blob/2.3-develop/app/etc/di.xml#L213
* https://github.com/magento/magento2/blob/2.3.2/app/etc/di.xml#L212

**Comment by slanka-vsi** [comment]
remove generators folder or
run bin/magento setup:di:compile first then bin/magento setup:upgrade resolve the issue
