### ISSUE TITLE
Advanced Search Doesn't Return Results With Additional Stock.

### ISSUE THREAD

**Issue by nmalevanec** [magento/inventory#2453]
### Preconditions (*)

1. Magento with MSI 2.3-develop.
2. Additional Stock and Source created. Additional Stock assigned to Main Website.

### Steps to reproduce (*)

1. Create simple, virtual, downloadable, configurable or bundle product with additional stock.
2. Quick search created product(s) on storefront.
3. Verify quick search returns correct results.
4. Try to advanced search created product(s) by 'Name' or 'Descritption'

### Expected result (*)

1. Same as quick search, returns correct results.

### Actual result (*)

1. Advanced search doesn't return correct results.

**Comment by smoskaluk** [comment]
Not reproducing on 2.3.3-develop + MSI
