### ISSUE TITLE
Products assigned on custom stock doesn't appear on Category page with Elasticsearch 6 enabled

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#2470]
### Preconditions (*)

1. Magento 2.3.3
2. Enable Elasticsearch 6+ on Configuration page in admin ( Stores -> Configuration -> Catalog -> Catalog -> Catalog Search)
3. Custom stock with custom source created with 'Sales channel' - Main website
4. Create simple product assigned to some category and custom source with qty = 100

### Steps to reproduce (*)

1. Open your category page on frontend

### Expected result (*)

1. Product should be displayed

### Actual result (*)

1. Product is absent on category page

![image](https://user-images.githubusercontent.com/27818516/62784364-fba9a200-bac6-11e9-890c-fcad671ddb7e.png)

**Comment by ishakhsuvarov** [comment]
Fix delivered to the Magento core in the scope of internal Pull Request.

Commit reference: `9687ccf68d7d6c8b6059e3bc018e28ac60915962`
