### ISSUE TITLE
Nothing on storefront when using ElasticSearch 5

### ISSUE THREAD

**Issue by nathanjosiah** [magento/inventory#2471]
### Preconditions (*)
1. Magento 2.3.3 [regression Enterprise cloud environment configuration](https://wiki.corp.magento.com/pages/viewpage.action?spaceKey=DEVOPS&title=2.3+Test+Environments) which uses ElasticSearch 5.x (for this bug I was using 5.6.16)
2. No stocks or sources configured 
3. Simple product created under subcategory so it displays on storefront (just to show data displays before the steps below)

### Steps to reproduce (*)
1. See product from preconditions visible on storefront
2. Create new source Test Source 1 with Contact and address data set
3. Create new stock Test Stock 1 with Test Source 1 assigned
4. Add new simple product name Simple1/qty 10/assigned to new source with qty 100/weight 1/assigned to the subcategory

### Expected result (*)
✅ All products should be showing correctly

### Actual result (*)
❌ All products missing from storefront

### Notes
ℹ️ None of the error logs contain any errors related to this issue. This includes var/* as well as Elastic Search's logs.
ℹ️ According to @mkozell and @aljcalandra the nightly builds are using ES6 which is partly how this issue has gone undetected.

**Comment by ishakhsuvarov** [comment]
Duplicates #2470

**Comment by ishakhsuvarov** [comment]
Fix delivered to the Magento core in the scope of internal Pull Request.

Commit reference: `9687ccf68d7d6c8b6059e3bc018e28ac60915962`

**Comment by nathanjosiah** [comment]
This bug is not fixed by https://github.com/magento/magento2ce/pull/4616 

The added products will show on storefront but existing products will still all be gone.
