### ISSUE TITLE
Product doesn't show in category on storefront when using ElasticSearch 6

### ISSUE THREAD

**Issue by nathanjosiah** [magento/inventory#2472]
### Preconditions (*)
1. Magento 2.3.3 [regression Midsize cloud environment configuration](https://wiki.corp.magento.com/pages/viewpage.action?spaceKey=DEVOPS&title=2.3+Test+Environments) which uses ElasticSearch 6.x 

### Steps to reproduce (*)
1. Create new source Test Source 1 with Contact and address data set
2. Create new stock Test Stock 1 with Test Source 1 assigned
3. Add new simple product name Simple1/qty 10/assigned to new source with qty 100/weight 1/assigned to a new subcategory

### Expected result (*)
✅ Product should be showing correctly on storefront

### Actual result (*)
❌ Product is missing from storefront

**Comment by ishakhsuvarov** [comment]
Duplicates #2470

**Comment by ishakhsuvarov** [comment]
Fix delivered to the Magento core in the scope of internal Pull Request.

Commit reference: `9687ccf68d7d6c8b6059e3bc018e28ac60915962`
