### ISSUE TITLE
Configurable Product SKU not available in B2B Quick Order option

### ISSUE THREAD

**Issue by michaelyu0123** [magento/inventory#2479]
### Preconditions (*)

1. Magento 2.3.3
2. B2B
3. Secondary Website/Store/Store View created
4. Created Configurable Product with 2 color options
5. Enable secondary store url
6. Enable B2B quick order function
7. Hiptest: https://app.hiptest.com/projects/69435/test-runs/284130/folder-snapshots/2629527/scenario-snapshots/9953597/test-snapshots/12823752

### Steps to reproduce (*)

1. Go to secondary store url and create user
2. Click "Quick Order on top right of site
3. Enter configurable product sku for specific Configurable Product `Configurable Product 1`

### Expected result (*)

1. Able to enter SKU of configurable product 

### Actual result (*)

1. Cannot enter SKU of product with specific configuration. Only base product SKU
2.
<img width="1363" alt="Screen Shot 2019-08-12 at 3 13 11 PM" src="https://user-images.githubusercontent.com/9815466/62895148-de1d4800-bd13-11e9-8920-34b004150aa8.png">

**Comment by ishakhsuvarov** [comment]
I've slightly modified description and reopened as issue still reproduces.
