### ISSUE TITLE
Configurable product does not display on API index dump

### ISSUE THREAD

**Issue by MarkBerube** [magento/inventory#2480]
### Environment
- Magento 2.3.3 Cloud mid size with ES enabled

### Preconditions (*)
1. Magento 2.3.3
2. Follow hiptest up to step 149: https://app.hiptest.com/projects/69435/test-runs/284130/folder-snapshots/2592768/scenario-snapshots/9814475/test-snapshots/12646858

### Steps to reproduce (*)
1. Make API request

```
GET $endpoint/rest/all/V1/inventory/dump-stock-index-data/website/test?searchCriteria
-H "Content-Type: application/json" \ 
-H "Authorization: Bearer $admin_token" \
```

### Expected result (*)
```
[

{"sku": "simple product 1", "qty": 100, "is_salable": true}
,

{"sku": "virtual product 1", "qty": 100, "is_salable": true}
,

{"sku": "downlodable product 1", "qty": 100, "is_salable": true}
,

{"sku": "grouped product 1", "qty": 0, "is_salable": true}
,

{"sku": "configurable product 1 - Red", "qty": 100, "is_salable": true}
,

{"sku": "configurable product 1 - Black", "qty": 100, "is_salable": true}
,

{"sku": "configurable product 1", "qty": 0, "is_salable": true}
,
]
```

### Actual result (*)
```
[

{"sku": "simple product 1", "qty": 100, "is_salable": true}
,

{"sku": "virtual product 1", "qty": 100, "is_salable": true}
,

{"sku": "downlodable product 1", "qty": 100, "is_salable": true}
,

{"sku": "grouped product 1", "qty": 0, "is_salable": true}
,
]
```

**Comment by ishakhsuvarov** [comment]
@MarkBerube Please share configuration of the environment you used. Is it Elasticsearch enabled?

**Comment by MarkBerube** [comment]
@ishakhsuvarov Elastic search is enabled on this environment, environment information has been added

**Comment by nmalevanec** [comment]
Hello, @MarkBerube 
I'm not able to reproduce this issue
![Peek 2019-08-13 16-01](https://user-images.githubusercontent.com/11520943/62943787-f197e400-bde3-11e9-8fc1-4d4c1cf43931.gif)
Could You please add more details, or correct steps I did?

**Comment by MarkBerube** [comment]
@nmalevanec In the hiptests the configurable child products are set to default source and not the test source previously set up. So this is actually a problem with the hiptests and not the code itself.

**Comment by MarkBerube** [comment]
Test was just fixed, closing this issue.
