### ISSUE TITLE
Exception thrown on storefront when product is opened under category.

### ISSUE THREAD

**Issue by admanesachin** [magento/inventory#2481]
### Preconditions
Magento 2.3.3 regression Mid Size cloud environment configuration which uses ElasticSearch (http://m233-bt-mid-1.testregress.com/)
Test Source is configured.
Test Stock is Configured.
SubCategory created under Default Category.
ElasticSearch is configured (Stores -> Configuration -> Catalog -> Catalog -> Catalog Search)
Simple product created under subcategory and assigned source set to source created in preconditions.
Run full reindex and flush cache.

### Steps to reproduce (*)
Go to storefront and open product from Category created in preconditions.

### Expected result (*)
✅ Product should be opened and displayed.

### Actual result (*)
❌ Exception is thrown.

**Comment by ishakhsuvarov** [comment]
@admanesachin Please share information on the exception thrown. I've tested this scenario earlier today and didn't encounter this error.

**Comment by admanesachin** [comment]
@ishakhsuvarov  i am attaching
[ElasticSearch.txt](https://github.com/magento/inventory/files/3497560/ElasticSearch.txt)
 the Exception report. It can be still reproduced by following the steps outlined in the bug description

**Comment by ishakhsuvarov** [comment]
Thanks @admanesachin

**Comment by nathanjosiah** [comment]
The borg midsize regression envs only have ES6 installed which is why you are seeing this error.
