### ISSUE TITLE
Reports based on MSI information

### ISSUE THREAD

**Issue by jorgb90** [magento/inventory#2498]
### Description (*)
It would be great to have reports based on MSI information like for example how many revenue is done per source.

### Expected behavior (*)
A menu located under Reports in the Magento admin with all kinds of valuable information we can get from MSI.

### Benefits
I think a lot of people are interested in how the sources and stocks are used and how to optimize them.

### Additional information
None.

**Comment by sidolov** [comment]
Hi @maghamed , we are about to complete MSI project feature development and keep issues of defined scope only to have clean and transparent backlog. 
Unfortunately, the current issue is out of scope and should be developed in scope of MBI. 
Thank you for your involvement!
