### ISSUE TITLE
Add support of Extension Attributes to Search Request

### ISSUE THREAD

**Issue by swnsma** [magento/inventory#2507]
### Description
Add support of Extension Attributes to Search Request.
Revert commits 3b08bc32fd676fe1ccc9d84ecbe40a647caf23b4 and b26f762e51cdc62e52a64d8366b645f8162e5f9c

Need to be done as soon as https://github.com/magento/magento2/pull/24117 will be merged.
Other solution - create temporary module to fix it by preference.

See PR: https://github.com/magento/inventory/pull/2487

**Comment by novikor** [comment]
Resolved.
