### ISSUE TITLE
cart persistent, shipping rates survive changing store

### ISSUE THREAD

**Issue by davidlopes** [magento/inventory#2508]
With the persistent cart enabled we found that switching store, clear the cart but shipping information persists, including shipping rates.

### Preconditions (*)

1. Magento EE 2.3.1
2. PHP 7.1
3. 10.0.37-MariaDB-1~jessie-wsrep

### Steps to reproduce (*)
1. Add a product into cart
2. Go to checkout and fill address
3. Print Shipping Methods
4. Change Website
5. Cart is empty now. Repeat steps 1-2
6. Shipping methods are the same, even if they are not active in this website

### Expected result (*)
when cart clears, shipping information should clear as well .

### Actual result (*)
when cart clears, shipping information persists, even if is not valid

**Comment by ishakhsuvarov** [comment]
Hi @davidlopes 

This repository is intended for Magento Inventory only. Do you have any information that any of the inventory-related features causes this issue?

**Comment by davidlopes** [comment]
sorry

**Comment by davidlopes** [comment]
https://github.com/magento/magento2/issues/24222
