### ISSUE TITLE
Magento2.3.2 checkout address have't zip/postalcode then cause admin order shipment error

### ISSUE THREAD

**Issue by Aiweline** [magento/inventory#2518]
Type Error occurred when creating object: Magento\InventorySourceSelection\Model\Address

The zip/postalcode must be required in frontend in system level.

Tip:when you reproduce this issue,config this country needn't zip/code;
### Preconditions (*)

1.Customer have't insert postalcode in checkout address.

### Steps to reproduce (*)

1. place order.

### Expected result (*)

1. 
![image](https://user-images.githubusercontent.com/32635766/63312206-58148900-c333-11e9-9617-ee82fe8d570d.png)

### Actual result (*)

1. ![image](https://user-images.githubusercontent.com/32635766/63312159-28658100-c333-11e9-8c90-bd3c99cfeeed.png)

### Proposal (*)
postcode must be required in system level.

**Comment by smoskaluk** [comment]
Hi @Aiweline! May you please give more details about this issue, cause I'm not able to reproduce it. Zip/postal code is required field during checkout - how did you manage to skip to fill it?

**Comment by Aiweline** [comment]
> 嗨@Aiweline。感谢您的报告。
> 为帮助我们处理此问题，请确保您提供了以下信息：
> 
> * [ ]  问题摘要
> * [ ]  有关您的环境的信息
> * [ ]  重现步骤
> * [ ]  预期和实际结果
> 
> 请确保在重现**步骤后，可以**在vanilla Magento实例上重现该问题。要在我们的环境中部署vanilla Magento实例，请在问题中添加注释：
> 
> `@magento give me 2.3-develop instance` - 即将推出的2.3.x版本
> 
> 有关详细信息，请查看[Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#contributor-assist)文档。
> 
> @Aiweline你确认你能够在重现步骤后重现香草Magento实例上的问题吗？
> 
> * [ ]  是
> * [ ]  没有
> 
> * 加入[Magento Community Engineering Slack](http://tinyurl.com/engcom-slack)并在[#github](https://magentocommeng.slack.com/messages/C7KB93M32)频道中[提问](https://magentocommeng.slack.com/messages/C7KB93M32)。

I think this issue is a bug for magento!

**Comment by Aiweline** [comment]
> 嗨@Aiweline！请你详细说明这个问题，因为我无法复制它。在结账时，邮政编码是必填字段 - 您是如何设法跳过填写的？

I just set this country is not use zip/code!  So i think this issue is a bug for magento,need to prepare!

**Comment by Aiweline** [comment]
> 此存储库中的Magento \ InventorySourceSelection \ Model \ Address：[https](https://github.com/magento/inventory)：[//github.com/magento/inventory](https://github.com/magento/inventory)，所以我认为您应该注意该存储库的问题。

not at all, i don't use zip/code so cause this issue, when i fill zip/code it disapear.

**Comment by Aiweline** [comment]
Think your help,i set this country need zip/code to avoid this bug.
