### ISSUE TITLE
Double product reservation while using multishipping.

### ISSUE THREAD

**Issue by engcom-Foxtrot** [magento/inventory#2537]
### Preconditions (*)

1. Enable Multishipping.
2. Create a Product.
3. Create a Customer.

### Steps to reproduce (*)

1. As Customer, add all Product's available quantity to cart.
2. Go to Multishipping checkout.
3. Try to place an Order.

### Expected result (*)

Order successfully placed.

### Actual result (*)

An error occurs: "The requested qty is not available". All Product's quantity is reserved.

**Comment by ishakhsuvarov** [comment]
This issue is caused by different order flow for Single and Multi address checkout. 

Inventory applies it's plugins only in the sequence suitable for Single Address checkout.

It's worth considering to refactor Multishipping to be aligned with regular checkout or just changing Inventory logic.
