### ISSUE TITLE
Remove "Ship" functionality for store pickup orders

### ISSUE THREAD

**Issue by ishakhsuvarov** [magento/inventory#2568]
### To Do
1. For order Placed with In-Store Pickup "Ship" button on the order should be hidden from the order page.
2. Verify that Shipping is also forbidden by other means, including Web API, etc.

**Comment by naydav** [comment]
@CristinaNicoleta is working on this issue
Thanks

**Comment by ishakhsuvarov** [comment]
@nmalevanec Please check that point 2 is also implemented in your previous PR on the subject
