### ISSUE TITLE
Add Migration script from Magento 1.X -> Magento 2.3 with MSI on board

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#257]
Add Migration script from Magento 1.X -> Magento 2.3 with MSI on board

AC:
- it is possible to migrate from Magento 1 to Magento 2.3

**Comment by sidolov** [comment]
Hi @maghamed , we are about to complete MSI project feature development and keep issues of defined scope only to have clean and transparent backlog. 
Unfortunately, the current issue is out of scope and should be closed. 
Thank you for your involvement!
