### ISSUE TITLE
Order of Stocks in Products Grid

### ISSUE THREAD

**Issue by gwharton** [magento/inventory#2574]
### Preconditions (*)
1. Create a product
2. Create multiple sources
3. Adjust order or sources to indicate perhaps a main source and a number of lower priority sources.
3. Assign product to All Sources

### Steps to reproduce (*)
1. View sales order grid
2. Analyse the Products Grid Quantity per source column.

### Expected result (*)
1. Well it would be much better if the order of the Sources were listed in order of priority as set out in the sources config.

### Actual result (*)
1. Sources are listed in order that they are created in, not the order set by the operator.

![chrome_QACp6UN04C](https://user-images.githubusercontent.com/30697781/65379068-3142cd00-dcba-11e9-97c3-22608e2eb2f5.png)

![Wf2gtaYP82](https://user-images.githubusercontent.com/30697781/65379069-343dbd80-dcba-11e9-9563-8b46734c0549.png)

**Comment by kisroman** [comment]
Have a problem with this. What to do if we have 2 stocks with the same sources but different priorities? For example:
1 stock: source 2, source 1, source 3, source 4.
2 stock: source 1, source 3, source 2, source 4.
What to do it this situation?

**Comment by gwharton** [comment]
Hmmmm. Hadn't considered that. Looks like, as usual, things are not so simple afterall.
