### ISSUE TITLE
Customer address get the region of the previouse country when no region available

### ISSUE THREAD

**Issue by deiserh** [magento/inventory#2579]
### Preconditions
1. Create a customer with an address and a region.

### Steps to reproduce
1. Go to the customer account and edit the address
2. Change the country to a country that doesn't have a regions

### Expected result
1. The region field should be an empty text field

### Actual result
1. The text field is filled with the value of the previouse country

**Comment by vadimjustus** [comment]
This issue belongs to magento/magento2 repository. There is an equivalent issue open: https://github.com/magento/magento2/issues/23460
