### ISSUE TITLE
Alternative for IsProductSalableInterface when working with a list of items

### ISSUE THREAD

**Issue by azngeek** [magento/inventory#2592]
### Summary (*)

It is currently frustrating to work with ```IsProductSalableInterface``` as it is very slow. We do have a PWA-based Frontend and use it to filter for all products which can be sold. Is there a ways so that we can improve the performance of the query? For example provide a method which will check multiple skus instead of one.

### Examples (*)

This is an example for how we use it currently:

1. The search criteria builder will be used to do the pre filtering
2. Within the loop do another filtering using the ```IsProductSalableInterface```

```
        foreach ($this->sourceItemRepository->getList($searchCriteriaReplace)->getItems() as $item) {

                if ($this->isProductSalable->execute($item->getSku(), 1)) {
                   // put it in a list
                }
        }
```

### Proposed solution

It would be nice to have a solution where you can provide a list of skus or use it within the search criteria builder / or provide a possible SQL to retreive only saleable items.

**Comment by ishakhsuvarov** [comment]
Hi @azngeek 

Thank you for this proposal. This is indeed something we have to work on: both performance of this service and it's ability to process items in bulk.

Currently it looks like we might need some backward incompatible changes in the process of this work so it might be shifted to one of the future releases.

Additionally, I would also include `IsProductSalableForRequestedQtyInterface` to this refactoring, as it has exact same issues with it.

**Comment by azngeek** [comment]
@ishakhsuvarov Thanks for your fast response. So when dealing with this topic as we have an existing PWA-Frontend and currently some products are listed "in stock" but are not actually saleable, is there a preferable solution to limit the results to that items? 

How would you handle this? I was thinking about extending the Query-Builder or use plain SQL to do that "Filtering". Any suggestions?

**Comment by ishakhsuvarov** [comment]
@azngeek Currently we are not really dealing with that regardless of PWA or any other frontend. For Category / Search listing pages we use stock data, which might be slightly stale, but still system would prevent adding out of stock products down the road.

While this scenario is not 100% optimal it allows to keep decent performance level. One of the main goals for us, with this bulk service which you mentioned above, would be resolving performance bottlenecks around this scenario.
