### ISSUE TITLE
InventoryConfigurableProductIndexer uses all columns value in predicate for clearing index

### ISSUE THREAD

**Issue by Stepa4man** [magento/inventory#2599]
### Preconditions
1. Magento Inventory (MSI) installed
2. Create configurable product with several simple products linked to it

### Steps to reproduce
1. Set debug point at **Magento/InventoryConfigurableProductIndexer/Indexer/Stock/StockIndexer:131**
2. Go inside through the following path
**Magento/InventoryConfigurableProductIndexer/Indexer/Stock/StockIndexer:131**
**\Magento\InventoryIndexer\Indexer\IndexHandler::cleanIndex**
**\Zend_Db_Adapter_Abstract::delete**
3. Check value of $where variable in **\Zend_Db_Adapter_Abstract::delete**

### Expected result
1. $where variable contains only _sku_ in predicate `(sku IN ('Config product', 'Configurable Product 1'))`

### Actual result
1. $where variable contains only _sku_ in predicate  `(sku IN ('Config product', '4194.0000', '1', 'Configurable Product 1', '27972.0000', '1'))`
![image](https://user-images.githubusercontent.com/15912461/65773995-ab9da200-e13d-11e9-9799-2d08a1d145e9.png)
![image](https://user-images.githubusercontent.com/15912461/65773908-72653200-e13d-11e9-8ea0-535f408e54d3.png)

**Comment by sidolov** [comment]
Looks like issues is fixed in scope of https://github.com/magento/inventory/pull/2603
