### ISSUE TITLE
Exception trying to place order with product with no sources assigned

### ISSUE THREAD

**Issue by novikor** [magento/inventory#2600]
### Preconditions (*)
1. Create a source
![image](https://user-images.githubusercontent.com/26086561/65778141-0d660800-e14e-11e9-9787-10f9465d64d1.png)
2. Create a simple product. **Do not assign it to any sources.**
![image](https://user-images.githubusercontent.com/26086561/65778553-cdebeb80-e14e-11e9-973c-6a47583183d3.png)

### Steps to reproduce (*)
1. Go to the order creation page on the Admin Panel
2. Add the newly created product to the cart
3. Reload the page

### Expected result (*)

1. Nothing goes wrong

### Actual result (*)

![image](https://user-images.githubusercontent.com/26086561/65778491-ae54c300-e14e-11e9-9138-35a2f2cc1496.png)

**Comment by smoskaluk** [comment]
Hi @novikor ! I'm trying to reproduce your issue, but I get normal error message (on 2.3-develop branch). May you please give more detailed steps?
![image](https://user-images.githubusercontent.com/27818516/65862992-08849c80-e378-11e9-81d2-5b34b1846e4d.png)

**Comment by novikor** [comment]
Hi, @smoskaluk .
Well, I`ve described everything I did for reproducing the problem. Probably I will recheck it later and provide more info.

Also, I used 2.3-develop branch, and Magento was in the `developer` mode.
