### ISSUE TITLE
Sources Unassigned From Product After Manual Adding One To Configurable Product.

### ISSUE THREAD

**Issue by nmalevanec** [magento/inventory#2611]
### Preconditions (*)

1. Magento EE with MSI.
2. Additional Stock and assigned Source created.

### Steps to reproduce (*)

1. Navigate to admin area.
2. Create configurable product with one variation.
3. Create simple product.
4. Assign additional source to simple product.
5. Create schedule update for simple product.
6. Manually replace generated configurable variation with simple product.
7. Observe simple product.

### Expected result (*)

1. Additional source still assigned to simple 

### Actual result (*)

1. No sources assigned to simple product after manually adding one to configurable product.

**Comment by smoskaluk** [comment]
Not reproducing on MSI 2.3-develop branch
