### ISSUE TITLE
Stock status for sold out simple product don't change to 'Out of stock"

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#2619]
### Preconditions (*)

1. Create custom stock with custom source
2. Create simple product with qty = 10 on default source

### Steps to reproduce (*)

1. Place order with 10 items of your simple product and make full shipment 
2. Enable in configuration to display 'Out of stock' products
3. Open category page with your product on frontend
4. Check stock status of your product in admin

### Expected result (*)

1. Your product should be displayed
2. In admin product should have stock status = 'Out of stock' on default source

### Actual result (*)

1. Your product not present on category page
2. In admin product has qty = 0 but stock status = 'In stock' on default source
![image](https://user-images.githubusercontent.com/27818516/66397613-dc56c480-e9e4-11e9-8a4f-45034d1263ac.png)

**Comment by inkobject** [comment]
Just a note that I am seeing this behavior in my store.
