### ISSUE TITLE
Can't assign new Sales Channel for new Stock

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#262]
### Preconditions

1. Magento 2 with MSI module, branch --develop
2. PHP 7.0

### Steps to reproduce

1. In Admin -> Stores -> All stores create new website "Test" with new store and storeview 
2. In Admin -> Manage Stock create new stock and set for it new website "Test" as Sales Channel.
3. click save & close

### Expected result

1. New Stock created and new website assigned to it

### Actual result

1. You get error message "Could not replace Sales Channels for Stock" , 
2. New stock appear in grid but website "Test" is not assigned to it.

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/300
