### ISSUE TITLE
SetShippingAddressesOnCart 2.3.2 issue 

### ISSUE THREAD

**Issue by andy17612** [magento/inventory#2624]
### Preconditions (*)

1.magento 2.3.2
2.

### Steps to reproduce (*)

1. bin/magento setup:upgrade
2.bin/magento setup:di:compile

### Expected result (*)

1. Interception cache generation... 7/7 [============================] 100% 57 secs 372.0 MiB
Generated code and dependency injection configuration successfully.

### Actual result (*)

1. bin/magento setup:di:compile
Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% < 1 sec 48.0 MiB
Fatal error: Declaration of Magento\InventoryInStorePickupQuoteGraphQl\Model\Cart\SetShippingAddressesOnCart::execute(Magento\GraphQl\Model\Query\ContextInterface $context, Magento\Quote\Api\Data\CartInterface $cart, array $shippingAddressesInput): void must be compatible with Magento\QuoteGraphQl\Model\Cart\SetShippingAddressesOnCartInterface::execute(Magento\Framework\GraphQl\Query\Resolver\ContextInterface $context, Magento\Quote\Api\Data\CartInterface $cart, array $shippingAddressesInput): void in /app/code/Magento/InventoryInStorePickupQuoteGraphQl/Model/Cart/SetShippingAddressesOnCart.php on line 24

have somebody can help? thank you!

**Comment by ishakhsuvarov** [comment]
Hi @andy17612 

In-Store Pickup is not supposed to work with 2.3.2 release. You would have to modify it and fix errors on your own if you want to get it working.

In this specific case it looks like `InventoryInStorePickupQuoteGraphQl` is not compatible with the core version we have in 2.3.2.

**Comment by ishakhsuvarov** [comment]
Closing this ticket for now due to inactivitly
