### ISSUE TITLE
Not possible to create shipment for order with backordered simple product

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#2626]
### Preconditions (*)

1.Custom stock with custom source created and Main website assigned
2.Simple product with qty on custom source = 10 and enabled backorders

### Steps to reproduce (*)

1. Place order with 20 items of your simple product
2. Create full shipment for your order

### Expected result (*)

1. Shipment created successfully

### Actual result (*)

1. Shipment can't be created
![image](https://user-images.githubusercontent.com/27818516/66626519-2d430480-ec01-11e9-92d6-4f4531664c74.png)

**Comment by nmalevanec** [comment]
Looks like this is expected behavior. Source quantity should not be less then '0'.
