### ISSUE TITLE
Source deduction for backordered virtual product

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#2627]
### Preconditions (*)

1.Custom stock with custom source created and Main website assigned
2.Virtual product with qty on custom source = 10 and enabled backorders

### Steps to reproduce (*)

1. Place order with 20 items of your virtual product
2. Create full invoice for your order
3. Got to admin and check qty of your product on custom source

### Expected result (*)

1. Qty on custom source should be - 10

### Actual result (*)

1. Qty on custom source = 0

**Comment by nmalevanec** [comment]
Looks like this is expected behavior. Source quantity should not be less then 0.
