### ISSUE TITLE
Reference to removed plugin

### ISSUE THREAD

**Issue by xmav** [magento/inventory#2633]
### Preconditions (*)
1. Magento 2.3.3\2.3-develop

### Steps to reproduce (*)
1. Check  app/code/Magento/InventoryElasticsearch/etc/di.xml
2. Check app/code/Magento/Elasticsearch/etc/di.xml (in Magento reporsitory)

### Expected result (*)
1. There is no reference to removed plugin
2. There are no logs records for this in support_report.log
"[2019-10-09 01:09:46] report.INFO: Reference to undeclared plugin with name 'stockedProductsFilterPlugin'. [] []"

### Actual result (*)
1. There is reference to removed plugin(stockedProductsFilterPlugin) in app/code/Magento/InventoryElasticsearch/etc/di.xml
2. (This plugin was removed in magento elasticsearch module)

**Comment by ishakhsuvarov** [comment]
Fix was delivered to the core with 2.3.3 merge.
