### ISSUE TITLE
Stock status in admin for complex products don't change into 'Out of stock" if all child products sold out

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#2635]
### Preconditions (*)

1. Create custom stock with custom source
2. Create Configurable product with option 'red' qty = 10 on default source (or bundle, or grouped product)

### Steps to reproduce (*)

1. Place order with 10 items of your configurable product and make full shipment 
2. Check stock status of your product in admin

### Expected result (*)

1. In admin product should have stock status = 'Out of stock'

### Actual result (*)

1. In admin product has stock status = 'In stock'

**Comment by TadeuRodrigues** [comment]
@magento give me 2.3-develop instance - upcoming 2.3.x release
