### ISSUE TITLE
Search by city name fails for Store pickup selection

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#2645]
### Preconditions (*)

1. Enable Store pickup delivery method 
2. Create  stock with source 'Dallas' - active for store pickup
3. Create product with some inventory on your source

### Steps to reproduce (*)

1. Place order with your product from homapage
2. Select 'In-Store Pickup Delivery' as shipping method 
3. In window of Store selection enter in search city name 'Dallas'

### Expected result (*)

1. Store 'Dallas' appear as search result

### Actual result (*)

1. Search fails
![image](https://user-images.githubusercontent.com/27818516/67199843-e926df80-f40a-11e9-9811-210bca6fe03a.png)

**Comment by nmalevanec** [comment]
@smoskaluk, I'm not able to reproduce this issue. Please check Dallas postcode you've filled into Dallas source with postcode in offline tables.
