### ISSUE TITLE
Magento 2.3.x: MSI sync to Ebay

### ISSUE THREAD

**Issue by Louisabalance** [magento/inventory#2662]
### Preconditions (*)
We are using Magento 2.3.2 with MSI where we have several sources assigned to one stock.
After configuring Omnivore to export products and inventory to Ebay, we noticed that the extension is not able to handle multi source inventory but always only takes inventory from the default stock which is not used. Omnivore therefore always returns "0" inventory for all products that are not assigned to the default stock.

### Steps to reproduce (*)
1. Assign several sources to a stock in Magento 2.3.2
2. Install and configure Omnivore
3. Sync products and notice that Omnivore does only take inventory from "default stock"

### Expected result (*)
Expected result is that all "saleable quantity" of a product is being synced to Omnivore.

### Actual result (*)
Omnivore only syncs 0 inventory

There is currently no patch available to solve this issue. Has anyone faced something similar? Are there better extensions that already are able to handle Multi source inventory.

**Comment by maghamed** [comment]
hey @Louisabalance , this functionality should be provided by Omnivore extension
https://marketplace.magento.com/citybeach-omnivore.html but not Magento. Magento provides all needed API for these purposes, while the existing extension by Omnivore relies on deprecated API which may work only with Default Source/Stock.

**Comment by Louisabalance** [comment]
We solved this with moving to M2E pro.
Omnivore currently does not support MSI.
