### ISSUE TITLE
Product's Stock quantity not changed after Stock Source Import 

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#267]
### Preconditions

1. Magento with MSI module
2. Simple product with Stock Quantity = 100 and Qty on Default Source = 100 
3. Create .csv file for import with sku of your existing Simple product and set Qty = 10 for Default Source  (source_id = 1) 
  

### Steps to reproduce

1. Goto Admin -> System -> Import
2. Select "Import Type" = Stock Sources
3. Select "Import Behavior" = Add/Update 
4. Click on "Choose File" button in "Select File to Import" field and navigate to your .csv import file in your system
5. Click on "Check Data" button 
6. If you got success message "File is valid! To start import process press "Import" button" - press "Import" button
7. Success message 'Import successfully done" appear
8. Navigate to Admin -> Catalog -> Products and open product page of your Simple Product

### Expected result

1. Quantity in Assigned Sources field on Default Source is updated to "10" and Quantity in Stock of this product is the same  

### Actual result

1.  Quantity in Assigned Sources field on Default Source is updated to "10" , but Quantity in Stock of this product is "100" (old)
2. If you click to Save your product, the Stock Qty (100) will overwrites the Qty on Default Source - and result of Import will be lost

![screenshot_3](https://user-images.githubusercontent.com/27818516/33765734-eaa66e9a-dc22-11e7-9995-9e1c2cb4cc3f.jpg)

**Comment by amasty-pomaleyko** [comment]
This pull https://github.com/magento-engcom/msi/pull/269/commits solves the problem

**Comment by naydav** [comment]
@smoskaluk 
Need to recheck this issue after merging of https://github.com/magento-engcom/msi/pull/269/

**Comment by naydav** [comment]
Bug is fixed
