### ISSUE TITLE
Export stock sources: exports old products, that are no longer exists

### ISSUE THREAD

**Issue by vitmarks** [magento/inventory#2714]
### Preconditions (*)

1. Magento: 2.3.3
2. Create products and configurable products with stock via REST. I always manage the stock and products over the REST API. Maybe there is an issue.

### Steps to reproduce (*)

1. Create some simple/configurable products via REST
2. Delete some of them via REST
3. Create the same products again but with different sku and name and stock via REST

### Expected result (*)

1. Old/deleted products should be "deleted" from the system/db
2. The export of stock sources must contain data of existing products

### Actual result (*)

1. The export of stock sources list all products with stock and some products, that are already deleted from the system but still in the export.
2. in my case: I have 454 simple products, but the export shows 544

**Comment by ishakhsuvarov** [comment]
Hi @vitmarks 

Inventory manages source item information separately from the product entities, as removal of the product does not always mean that it's stock records should be removed as well. 

If that is the case in your specific business scenario I would also suggest removing unneeded source item records with the [`SourceItemsDelete`](https://github.com/magento/inventory/blob/2.3-develop/app/code/Magento/InventoryApi/Api/SourceItemsDeleteInterface.php) API after products are removed.  

This should bring the system behavior to the one you expect.
