### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Cannot instantiate interface Magento\InventoryReservationsApi\Model\ReservationBuilderInterface

### ISSUE THREAD

**Issue by andrewizotov** [magento/inventory#2715]
### Preconditions (*)
1. version 2.3.3

### Steps to reproduce (*)
1. run setup:upgrade

### Expected result (*)

1. setup:upgrade has to be done without errors

### Actual result (*)

php bin/magento setup:upgrade
PHP Fatal error:  Uncaught Error: Cannot instantiate interface Magento\InventoryReservationsApi\Model\AppendReservationsInterface in /private/var/www/tourvest/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:58
Stack trace:
#0 /private/var/www/tourvest/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Invento...')
#1 /private/var/www/tourvest/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(160): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Invento...')
#2 /private/var/www/tourvest/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(246): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Invento...', NULL, 'appendReservati...', 'Magento\\Invento...')
#3 /private/var/www/tourvest/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime( in /private/var/www/tourvest/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 58

Fatal error: Uncaught Error: Cannot instantiate interface Magento\InventoryReservationsApi\Model\AppendReservationsInterface in /private/var/www/tourvest/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 58

Error: Cannot instantiate interface Magento\InventoryReservationsApi\Model\AppendReservationsInterface in /private/var/www/tourvest/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 58

**Comment by andrewizotov** [comment]
I just added to app/etc/di.xml 
two lines :
`<preference for="Magento\InventoryReservationsApi\Model\ReservationBuilderInterface" type="Magento\InventoryReservations\Model\ReservationBuilder"/>
    <preference for="Magento\InventoryReservationsApi\Model\AppendReservationsInterface" type="Magento\InventoryReservations\Model\AppendReservations"/>
`
and my setup upgrade is finished

**Comment by OleksiiStepanov** [comment]
Looks like one of Inventory modules is not enabled. You  should enable modules Magento_InventoryReservation, Magento_InventoryReservationApi

**Comment by andrewizotov** [comment]
Hi @OleksiiStepanov , thanks a lot , it helped definitely .

**Comment by jrosell** [comment]
> I just added to app/etc/di.xml
> two lines :
> `<preference for="Magento\InventoryReservationsApi\Model\ReservationBuilderInterface" type="Magento\InventoryReservations\Model\ReservationBuilder"/> <preference for="Magento\InventoryReservationsApi\Model\AppendReservationsInterface" type="Magento\InventoryReservations\Model\AppendReservations"/> `
> and my setup upgrade is finished

I think it should be possible to disable all Magento_Inventory* modules without having to include this lines or at least should be documented here: https://devdocs.magento.com/extensions/inventory-management/#disable-inventory-management
