### ISSUE TITLE
If change SKU to the same but in upper case - qty per source is not appear in product grid in admin

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#2723]
### Preconditions (*)

1. New stock with new source created

### Steps to reproduce (*)

1. Create new simple product with SKU in lowercase, e.g "new test" and set some qty for it on the new source 
2. Change SKU to the same but in upper case, e.g. "NEW TEST".
3. Note that changed in catalog_product_entity table, but wrong in inventory_source_item

### Expected result (*)

1. In admin in Products grid Quantity per source is displaying for your product

### Actual result (*)

1. Quantity per source is not displaying

**Comment by smoskaluk** [comment]
@magento give me 2.3-develop instance

**Comment by ishakhsuvarov** [comment]
Closing, should be investigated / fixed in #2724
