### ISSUE TITLE
Inventory Reservation not taken into account when setting Product out of Stock

### ISSUE THREAD

**Issue by stkrelax** [magento/inventory#2725]
### Preconditions (*)

1. Magento 2.3.2
2. MSI with default Stock only ( default stock only is not a must but MSI is)

### Steps to reproduce (*)
1. set up one Product with qty 1 salable 
2. complete an order buying the product (a new entry in inventory_reservation was made)
3. post /V1/inventory/source-items set Product to qty 0 and status 0 (simulating the client updating the stock because it was purchased by you)
4. in admin or api try to ship the order.

### Expected result (*)
1. the order gets shipped

### Actual result (*)
1. Exception "Not all of your products are available in the requested quantity."
The Reason therefor is that normally without the clients update of the product the qty of the product would have been 1 and the shipping would have set it to 0. 
Now that the product has qty 0, magento is unable to substract the reservations. 

### Suggestion (*)
When updating a products qty the reservations should be included. So in this case the aty 0 would have become qty 1.

### Related 
https://github.com/magento/inventory/issues/2073
https://github.com/magento/magento2/issues/21646

**Comment by ishakhsuvarov** [comment]
@stkrelax Order is not shipped due to manual source item qty change which was done in step 3. Could you please share some insights on why that step is needed?

**Comment by stkrelax** [comment]
it is because we are not doing the stock management. The Client has the Stock and an order decreases the amount of item salable not depending if it is shipped .

**Comment by ishakhsuvarov** [comment]
@stkrelax Could you please share more info on your setup then? Are there any customizations or specific settings in place? What about `Manage Stock` and `Decrease Stock When Order is Placed`?

**Comment by merance2000** [comment]
We are having same issue. I changed the magento config to not deplete stock when order is made, only when shipped, this is not ideal because because you could oversell items. I also have the additional problem that my erp system connector also changes the stock to "0" once it is committed if there was only 1 on hand. Then we cannot clear the shipment. We need to either be able to commit item to order, but order can still ship with a committed item or for magento to allow negative inventory for shipments.

**Comment by stkrelax** [comment]
@ishakhsuvarov 
Manage Stock ist true and "Decrease Stock When Order is Placed" is true.

**Comment by stkrelax** [comment]
We had a look at the settings and tried to do like @merance2000 said. But as he said, this is not a solution because of oversell. 

So the stock should be managed by magento and the Stock should be decreased (or in the case reservated). there is no option to change this settings due to overselling.

So the Problem actually still exists.
