### ISSUE TITLE
Unexpected message appears if you try to add products to order via admin panel

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#2737]
### Preconditions (*)

1. Magento with MSI

### Steps to reproduce (*)

1. Create a simple product with quantity 10.
2. Go to Sales - Orders - Create New Order 
3. Select existing customer or add new. 
4. Add the simple product to order set quantity 10. 
5. Click Add selected products to order AR: 

### Expected result (*)

1. Products added to order without any issues

### Actual result (*)

1. Error message appears "The requested qty is not available".

**Comment by nmalevanec** [comment]
Not related to Inventory* modules. Also reproducible on 2.3-develop mainline.
