### ISSUE TITLE
How to use source selection on checkout?

### ISSUE THREAD

**Issue by kassner** [magento/inventory#2762]
For tax reasons, I need to define the source of the shipment for a particular cart before the order is placed, so I can charge for the taxes accordingly to the source+destination combination.

A bit of research let me to the source selection algorithm used by MSI. As written [here](https://github.com/magento/inventory/wiki/Source-Selection-Algorithm#how-magento-deals-with-ssa), a developer could hook the source selection during checkout:

> If 3PD would like to customize Inventory in future and decide to add Source Selection Algorithm at the time of checkout - he needs to introduce own factory, which produces InventoryRequestInterface based on Quote object.

Although the page gives a brief example of the factory using the Quote instead of the Order and I am able to implement them on my own, I could not find where the MSI code is called during the checkout phase, so I could hook my code into. I've added several breakpoints in classes related to the SourceSelection, but I not able to find it.

Is MSI used at all during checkout phase (with the exception of the `isSaleable` event)? Is there a way to pre-define which source a particular order should use when shipping?

Thanks!

**Comment by ishakhsuvarov** [comment]
Hi @kassner 

By default, MSI does not do any source selection operations during the .checkout. This is done to minimize performance impact for the client, as some of the Source Selection Algorithms may be computational-heavy or interact with third-party APIs. The only thing handled by MSI at the checkout is reservations, as placing a new order generally triggers a reservation append operation. This reservation is needed to prevent oversell on the Stock level and would be compensated down the road.

To run the SSA in realtime during checkout you would need some additional customizations, for example introduce a source level reservation mechanism or run the SSA and adjust stock level reservations. It really depends on your specific business case. None of this is currently implemented in Inventory modules, so you'd need to customize using existing extension points

**Comment by sidolov** [comment]
Hi @kassner I'm closing the issue since it's not implemented and may be developed by 3d party developers.
