### ISSUE TITLE
Credit memo: Salable Quantity Greater than Quantity

### ISSUE THREAD

**Issue by dhanus07** [magento/inventory#2773]
### Preconditions (*)

1. Magento 2.3.0 or 2.3.3 with [Magento Inventory (a.k.a MSI) functionality](https://github.com/magento/inventory)
2. Simple product is created. 

### Steps to reproduce (*)

1. Create an order with the simple product. 
2. Change SKU of ordered product.
3. Create an invoice.
4. Create a credit memo. (mark "Return to Stock")

### Expected result (*)

The salable quantity should not be greater than the quantity
![Screenshot (6)](https://user-images.githubusercontent.com/48516084/71088045-92981080-21c3-11ea-9234-d5c500826b33.png)

### Actual result (*)

The salable quantity is greater than the quantity
![Screenshot (5)](https://user-images.githubusercontent.com/48516084/71088077-a6dc0d80-21c3-11ea-8674-7b402c58538b.png)

**Comment by dhanus07** [comment]
@sdzhepa Any updates on this issue ??? This is issue occurring most often. do you have any patch for this issue in Magento 2.3.0?

**Comment by jorgb90** [comment]
@dhanus07 I think you can correct these differences by using the following CLI command:

bin/magento inventory:reservation:list-inconsistencies -r | bin/magento inventory:reservation:create-compensations
