### ISSUE TITLE
Can't Notify customer if product has inventory on stock but not on particular source

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#2785]
### Preconditions (*)

1. In store Pickup enabled
2. Stock created with 2 Store Pickup sources "Culver City" and "Los Angeles"
3. Product created with some qty on "Culver City" source

### Steps to reproduce (*)

1. Place order with selected "Store Pickup" delivery from "Los Angeles" Store
2. Open order in admin and click button to Notify Customer 

### Expected result (*)

1. You should get message: "The customer has been notified and shipment created." 

### Actual result (*)

1. Message appear: "The order is not ready for pickup".

![image](https://user-images.githubusercontent.com/27818516/72974924-93cae780-3dd8-11ea-9d8d-7f6969fc0bbd.png)

**Comment by ganeddact** [comment]
I'm experiencing this issue in both 2.4.2 and 2.4.3 versions.
How's the status of it?

**Comment by ChaseTheory** [comment]
@smoskaluk What was the solution here?
