### ISSUE TITLE
Wish list always empty if MSI is installed and using another source than default

### ISSUE THREAD

**Issue by TobiasLufinity** [magento/inventory#2817]
### Preconditions (*)
1. Magento 2.4-develop with sample data
2. Magento Inventory version 1.1-develop installed (https://github.com/magento/inventory)

### Steps to reproduce (*)
1. Go to admin and create a new Source (Stores -> Inventory -> Sources)
2. Create a new Stock and assign the newly created source to the stock (Stores -> Inventory -> Stocks). Also select Main Website in Sales Channels
3. Go to the product grid, select all product and make the mass action "Transfer Inventory To Source" to the newly created source. Check "Unassign from origin source after transfer."
4. Go to the front end page.
5. Login with the demo user.
6 Go to the front page and try to add something to the wish list

### Expected result (*)
You should be redirected to the wish list index page with an success message and the product added should be shown in the list like the image below

![Expected result](https://user-images.githubusercontent.com/32361984/73927239-4d45b480-48d1-11ea-9d0f-f493690ba81a.png)

### Actual result (*)
1. You are redirected to the wish list index page with an success message but the product does not show in the list like the image below

![Actual result](https://user-images.githubusercontent.com/32361984/73926477-fbe8f580-48cf-11ea-8483-a8a2b0673a83.png)

### Error location
The problem is in the Magento\Wishlist\Model\ResourceModel\Item\Collection::_renderFiltersBefore function which filter the select with an in stock filter using the _cataloginventory_stock_status_ table.
This table is not used to track stock or salable status when using MSI.

**Comment by Stepa4man** [comment]
I have the same

**Comment by Stepa4man** [comment]
Looks like this bug was already fixed. I'm closing it.

**Comment by arun-eglobeits** [comment]
I have the same issue too. Is there any reference link of the fix.

**Comment by arunsingh-jhon** [comment]
I have the same issue too. Is there any reference link of the fix.

**Comment by Stepa4man** [comment]
@arunsingh-jhon https://github.com/magento/magento2/commit/1f99b199a4c52852746f46c09ee12b48f4c707b8#diff-687c6956f0b6aeaeb974b7eaec603a42
Not sure, check this. 
I also found this opened PR, check if you can find it helpful
https://github.com/magento/magento2/pull/27527

**Comment by danish-tayyib-visionet** [comment]
@Stepa4man @arunsingh-jhon I am facing the same issue on magento 2.4.1. Is there an solution for this??

**Comment by wojtekn** [comment]
I spot that issue too. It looks 2.3.6 is affected. Based on code review I see it was fixed in 2.4, there was a quality patch created for 2.3.5 but 2.3.6 looks somehow broken - some code from that patch exists in 2.3.6, some don't. MDVA-30428 can't be applied for 2.3.6.

https://devdocs.magento.com/quality-patches/release-notes.html
