### ISSUE TITLE
Exception during creating New Source

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#282]
### Preconditions

1. Magento 2 with MSI module

### Steps to reproduce

1. Login to Admin
2.  Navigate to Stores -> Manage Sources
3. Click on "Add new Source" button 

### Expected result

1. Page for creation new Source opens

### Actual result

1. [Screenshot, logs]
1 exception(s):
Exception #0 (BadMethodCallException): Missing required argument $targetName of Magento\Inventory\Ui\Component\Control\Source\SaveSplitButton.

Exception #0 (BadMethodCallException): Missing required argument $targetName of Magento\Inventory\Ui\Component\Control\Source\SaveSplitButton.
#0 /var/www/html/slavam/msi/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Invento...', Array, Array)
#1 /var/www/html/slavam/msi/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Invento...', Array, Array)
#2 /var/www/html/slavam/msi/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Invento...', Array)
#3 /var/www/html/slavam/msi/lib/internal/Magento/Framework/View/Element/UiComponent/Control/ButtonProviderFactory.php(39): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Invento...', Array)
#4 /var/www/html/slavam/msi/lib/internal/Magento/Framework/View/Element/UiComponent/Context.php(272): Magento\Framework\View\Element\UiComponent\Control\ButtonProviderFactory->create('Magento\\Invento...')
#5 /var/www/html/slavam/msi/app/code/Magento/Ui/Component/AbstractComponent.php(116): Magento\Framework\View\Element\UiComponent\Context->addButtons(Array, Object(Magento\Ui\Component\Form))
#6 /var/www/html/slavam/msi/lib/internal/Magento/Framework/View/Layout/Generator/UiComponent.php(164): Magento\Ui\Component\AbstractComponent->prepare()
#7 /var/www/html/slavam/msi/lib/internal/Magento/Framework/View/Layout/Generator/UiComponent.php(142): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(Object(Magento\Ui\Component\Form))
#8 /var/www/html/slavam/msi/lib/internal/Magento/Framework/View/Layout/Generator/UiComponent.php(102): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(Object(Magento\Framework\View\Layout\Data\Structure), 'inventory_sourc...', Array, Object(Magento\Framework\View\Layout\Interceptor))
#9 /var/www/html/slavam/msi/lib/internal/Magento/Framework/View/Layout/GeneratorPool.php(80): Magento\Framework\View\Layout\Generator\UiComponent->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#10 /var/www/html/slavam/msi/lib/internal/Magento/Framework/View/Layout.php(344): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#11 /var/www/html/slavam/msi/generated/code/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#12 /var/www/html/slavam/msi/lib/internal/Magento/Framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#13 /var/www/html/slavam/msi/lib/internal/Magento/Framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#14 /var/www/html/slavam/msi/lib/internal/Magento/Framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#15 /var/www/html/slavam/msi/lib/internal/Magento/Framework/View/Layout.php(254): Magento\Framework\View\Layout\Builder->build()
#16 /var/www/html/slavam/msi/lib/internal/Magento/Framework/View/Layout.php(875): Magento\Framework\View\Layout->build()
#17 /var/www/html/slavam/msi/generated/code/Magento/Framework/View/Layout/Interceptor.php(414): Magento\Framework\View\Layout->getBlock('menu')
#18 /var/www/html/slavam/msi/app/code/Magento/Backend/Model/View/Result/Page.php(26): Magento\Framework\View\Layout\Interceptor->getBlock('menu')
#19 /var/www/html/slavam/msi/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(24): Magento\Backend\Model\View\Result\Page->setActiveMenu('Magento_Invento...')
#20 /var/www/html/slavam/msi/app/code/Magento/Inventory/Controller/Adminhtml/Source/NewAction.php(33): Magento\Backend\Model\View\Result\Page\Interceptor->setActiveMenu('Magento_Invento...')
#21 /var/www/html/slavam/msi/generated/code/Magento/Inventory/Controller/Adminhtml/Source/NewAction/Interceptor.php(24): Magento\Inventory\Controller\Adminhtml\Source\NewAction->execute()
#22 /var/www/html/slavam/msi/lib/internal/Magento/Framework/App/Action/Action.php(107): Magento\Inventory\Controller\Adminhtml\Source\NewAction\Interceptor->execute()
#23 /var/www/html/slavam/msi/app/code/Magento/Backend/App/AbstractAction.php(229): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#24 /var/www/html/slavam/msi/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#25 /var/www/html/slavam/msi/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Inventory\Controller\Adminhtml\Source\NewAction\Interceptor->___callParent('dispatch', Array)
#26 /var/www/html/slavam/msi/app/code/Magento/Backend/App/Action/Plugin/Authentication.php(143): Magento\Inventory\Controller\Adminhtml\Source\NewAction\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#27 /var/www/html/slavam/msi/lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Inventory\Controller\Adminhtml\Source\NewAction\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#28 /var/www/html/slavam/msi/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Inventory\Controller\Adminhtml\Source\NewAction\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#29 /var/www/html/slavam/msi/generated/code/Magento/Inventory/Controller/Adminhtml/Source/NewAction/Interceptor.php(39): Magento\Inventory\Controller\Adminhtml\Source\NewAction\Interceptor->___callPlugins('dispatch', Array, NULL)
#30 /var/www/html/slavam/msi/lib/internal/Magento/Framework/App/FrontController.php(55): Magento\Inventory\Controller\Adminhtml\Source\NewAction\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#31 /var/www/html/slavam/msi/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#32 /var/www/html/slavam/msi/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#33 /var/www/html/slavam/msi/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#34 /var/www/html/slavam/msi/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#35 /var/www/html/slavam/msi/lib/internal/Magento/Framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#36 /var/www/html/slavam/msi/lib/internal/Magento/Framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#37 /var/www/html/slavam/msi/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#38 {main}

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/283
