### ISSUE TITLE
When upgrading to 2.3.4 with encrypted drive, seeing "File name too long" error

### ISSUE THREAD

**Issue by iamsophiesk** [magento/inventory#2821]
### Preconditions
Issue when upgrading from Magento 2.3.3 -> 2.3.4.
Using Ubuntu 16.04 (possibly 18.04?) with encrypted home directory, and Magento installed in home directory (eg in `~/projects/magento`)

### Steps to reproduce
Perform upgrade from Magento 2.3.3 -> 2.3.4 and run commands as outlined on https://devdocs.magento.com/guides/v2.3/comp-mgr/cli/cli-upgrade.html 

### Expected result
The upgrade to run successfully.

### Actual result
Had the following error: 
```
error: cannot create /home/$USER/projects/magento/vendor/composer/9318cb01/Test/Mftf/Test/StorefrontBackordersEnabledOnConfigurationPageAndAppliedFromHomepageToWithConfigurableProductWithDropDownAttributeAndVariablesAssignedToNonDefaultSourceTest.xml
File name too long
```

---

I upgraded Magento 2.3.3 to 2.3.4 locally with no problems, running Ubuntu 18.04. When my colleague tried to update, running 16.04 with an encrypted home directory (where the project was installed), the update failed with the error above.

From http://www.linfo.org/file_name.html :
> ... modern Unix-like systems support long file names, usually up to 255 bytes in length. 

This file name is 160 characters, but the maximum number of characters allowed for a filename in an encrypted drive is 143: https://askubuntu.com/a/728525 

The workaround we've found is to install project in a different directory, but this seems like an oversight.

---

It looks like this has been reported on StackOverflow but with no resolution: https://magento.stackexchange.com/questions/302528/magento-2-3-4-composer-update-file-name-too-long 

Maybe it's worth noting that we are using Docker/Docksal for our development, but this seems to be an issue with the host computer rather than Docksal, as my colleague was able to get it working in a directory outside of his home (at `/var/www/html/magento`), still within Docker/Docksal.

---

This is raised from https://github.com/magento/magento2/issues/26728 - I was told to raise the issue here instead.

**Comment by wigman** [comment]
This is our current solution:

Disable all MSI modules, which is the only way to get this to work, unless you want to fork the MSI repo and change the filename there.

In `composer.json`:
```
replace: {
        "magento/module-inventory": "*",
        "magento/module-inventory-admin-ui": "*",
        "magento/module-inventory-api": "*",
        "magento/module-inventory-bundle-product": "*",
        "magento/module-inventory-bundle-product-admin-ui": "*",
        "magento/module-inventory-cache": "*",
        "magento/module-inventory-catalog": "*",
        "magento/module-inventory-catalog-admin-ui": "*",
        "magento/module-inventory-catalog-api": "*",
        "magento/module-inventory-catalog-search": "*",
        "magento/module-inventory-configurable-product": "*",
        "magento/module-inventory-configurable-product-admin-ui": "*",
        "magento/module-inventory-configurable-product-indexer": "*",
        "magento/module-inventory-configuration": "*",
        "magento/module-inventory-configuration-api": "*",
        "magento/module-inventory-distance-based-source-selection": "*",
        "magento/module-inventory-distance-based-source-selection-api": "*",
        "magento/module-inventory-distance-based-source-selection-admin-ui": "*",
        "magento/module-inventory-elasticsearch": "*",
        "magento/module-inventory-export-stock": "*",
        "magento/module-inventory-export-stock-api": "*",
        "magento/module-inventory-graph-ql": "*",
        "magento/module-inventory-grouped-product": "*",
        "magento/module-inventory-grouped-product-admin-ui": "*",
        "magento/module-inventory-grouped-product-indexer": "*",
        "magento/module-inventory-import-export": "*",
        "magento/module-inventory-indexer": "*",
        "magento/module-inventory-low-quantity-notification": "*",
        "magento/module-inventory-low-quantity-notification-admin-ui": "*",
        "magento/module-inventory-low-quantity-notification-api": "*",
        "magento/module-inventory-multi-dimensional-indexer-api": "*",
        "magento/module-inventory-product-alert": "*",
        "magento/module-inventory-reservations": "*",
        "magento/module-inventory-reservations-api": "*",
        "magento/module-inventory-reservation-cli": "*",
        "magento/module-inventory-sales": "*",
        "magento/module-inventory-sales-admin-ui": "*",
        "magento/module-inventory-sales-api": "*",
        "magento/module-inventory-sales-frontend-ui": "*",
        "magento/module-inventory-setup-fixture-generator": "*",
        "magento/module-inventory-shipping": "*",
        "magento/module-inventory-shipping-admin-ui": "*",
        "magento/module-inventory-source-deduction-api": "*",
        "magento/module-inventory-source-selection": "*",
        "magento/module-inventory-source-selection-api": "*",
        "magento/module-inventory-requisition-list": "*",
        "magento/module-inventory-advanced-checkout": "*",
}
```

**Comment by se45ky** [comment]
I have the same problem here.

**Comment by thebraziliandeveloper** [comment]
Me too, having the same problem.

**Comment by volmar** [comment]
For me what worked was moving the repo out of  /home directory to /opt, which is not encrypted. Now if we want to change this we need to reduce filename size.
