### ISSUE TITLE
Many Wiki links are dead (404)

### ISSUE THREAD

**Issue by chadwixk** [magento/inventory#2822]
Many of the links in the [wiki](https://github.com/magento/inventory/wiki/Magento-MSI-APIs) are not found.

Example: [SourceItemsSaveInterface](https://github.com/magento/inventory/blob/2.3-develop/app/code/Magento/InventoryApi/Api/SourceItemsSaveInterface.php)

**Comment by sidolov** [comment]
Hi @chadwixk , @TadeuRodrigues , links are fixed now. Thank you for the input!

**Comment by chadwixk** [comment]
@sidolov awesome! That was fast :)
