### ISSUE TITLE
Swatch of configurable product that has salable qty = 0 is still shown on frontend after reindex and cache flush

### ISSUE THREAD

**Issue by duckchip** [magento/inventory#2828]
### Preconditions (*)

1. 2.3.2, 2.3.3, 2.3.4
2. inventory-composer-metapackage enabled

### Steps to reproduce (*)

1. Create a configurable product with simples attached to it, using a swatch attribute
2. Give them all qty = 1
3. Order and invoice a configuration
4. Do a reindex and cache flush

### Expected result (*)

1. The ordered swatch has now saleable qty = 0 and is not shown in the swatches list on the product detail page after a reindex and cache flush
2. The end user doesn't see the swatch as saleable.

### Actual result (*)

1. The ordered swatch has now saleable qty = 0 and is still shown in the swatches list on the product detail page after a reindex and cache flush
2. The end-user gets an error that the product is not for sale.

I assume that the list of swatches in the frontend is based on the qty attribute and not on the saleable qty attribute. 

For the end-user it is very annoying to see an error like this. It gives them the idea that a specific configuration is still available while it's not.

**Comment by duckchip** [comment]
this issue is fixed by PR #2740

**Comment by duckchip** [comment]
I re-openend the issue since this happens every time before the order with the specific product is shipped. Only then the swatch is removed 

This is not intended behaviour to me.

**Comment by smoskaluk** [comment]
Closing issue due it not reproducing on mainline MSI branch (1.2-develop)
