### ISSUE TITLE
Extra compensation reservation when Credit Memo created

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#2859]
### Preconditions (*)

1. Magento 2.4-develop with MSI 1.2-develop

### Steps to reproduce (*)

1. Create 2 simple productы with qty = 100 
2. Place order with 1 item of both these products
3. Create full `Invoice`
4. Create full `Credit Memo` with not checked `Return to Stock` for one of products
5. Open 'Products' grid in admin
6. Check 'inventory_reservation' table 

### Expected result (*)

1. Qty for product is reduced and get equal to salable qty

### Actual result (*)

1. Qty for product is reduced , but salable qty is wrong

![wrong_sal](https://user-images.githubusercontent.com/27818516/75689856-93acea00-5caa-11ea-8ade-d2a4bb48dc0e.png)

this error caused by wrong extra compensation reservation for this product in table inventory_reservation

![wrong_reserv](https://user-images.githubusercontent.com/27818516/75689865-990a3480-5caa-11ea-81c1-d19ad3e88049.png)

**Comment by nmalevanec** [comment]
@smoskaluk, verified on latest 2.4-develop with latest 1.2-develop MSI, everything works perfectly fine, issue not reproduced. If new details will occur, please add them to description and reopen this issue.

**Comment by erfanimani** [comment]
@smoskaluk did you ever find out why this happened?

**Comment by erfanimani** [comment]
@smoskaluk this is most likely due to this MSI bug: https://github.com/magento/inventory/issues/3304

It's triggered when MSI is used in combination with asynchronous sales email sending
