### ISSUE TITLE
Eliminate Source_Id from SourceInterface and SourceItemInterface, make SourceConfiguration to use SourceCode 

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#289]
Eliminate Source_Id from SourceInterface and SourceItemInterface, make SourceConfiguration to use SourceCode instead of Source_id

More details available in [story](https://github.com/magento-engcom/msi/wiki/Introduce-SourceCode-attribute-for-Source-and-SourceItem-entities) description

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/307
