### ISSUE TITLE
Cannot sell out of stock or disabled product from admin area

### ISSUE THREAD

**Issue by adarshkhatri** [magento/inventory#2895]
### Preconditions (*)

1. Magento 2.3.3
2. Product 1 => 0 stock (out of stock)
3. Product 2 => disabled

### Steps to reproduce (*)

1. Login to admin
2. Create an order for "Product 1" and "Product 2" 

### Expected result (*)

1. Allow creating order with out of stock or disabled product from ADMIN area

### Actual result (*)

1. 
![image](https://user-images.githubusercontent.com/8390252/77380712-f6883180-6dcf-11ea-8a16-ea837902b445.png)

**Comment by sidolov** [comment]
Hi @adarshkhatri, described expected result is not correct and current behavior is expected. 
We cannot allow selling disabled products, for the out of stock products such option is available if backorders are enabled. 
I'm closing the issue since it's not relevant. 
Thank you for your contribution!

**Comment by adarshkhatri** [comment]
Hi @sidolov 
The problem is, if I enable backorder then it will be available in front end too. There are multiple reasons we don't want to make items available for frontend but only sell from backend:

One of them is: the supplier doesn't allow us to sell from front end but allow us to sell from in-store.

Also, some discontinued items we would still want to sell from admin area because the supplier does have as many qty as we want till further notice but don't allow us to advertise or have it in frontend. 

**In Magento 1 it was possible and without MSI in Magento 2 it is possible.**

Main problem for me is Magento 1 was serving the solutions best and this Magento 2 is not. I think the Magento team forgot about "Published vs Publish".

**Comment by adarshkhatri** [comment]
Also, I have tested with **Backorders**, it does allow us to create order but cannot ship.

Product inventory setting:
![image](https://user-images.githubusercontent.com/8390252/77493759-09663900-6e98-11ea-85a3-82c0bfc1c0e9.png)

When trying to ship, it throws this error:
![image](https://user-images.githubusercontent.com/8390252/77493830-46cac680-6e98-11ea-91fc-268f4b95cee9.png)

**Comment by adarshkhatri** [comment]
Any update on this?

**Comment by HenKun** [comment]
@sidolov Sure this is closed correctly? Magento 2 without MSI allows creating orders of out-of-stock products from admin area. They explicitely implemented `skipSaleableCheck` property in `Magento\Catalog\Helper\Product`. This property is set to `true` in constructor of `vendor/magento/module-sales/Controller/Adminhtml/Order/Create.php`. This explicitely allows creating those orders from admin panel. MSI changes this behavior, was this really on purpose?

**Comment by HenKun** [comment]
@magento give me 2.4-develop instance

**Comment by praveen-chelumalla** [comment]
We also got same issue and requirement also be same like  we want to sell some products in the admin area but not in the front end  so what we did we created one website for backend and assigned those products those want to sell in the backend and also set customer sharing as global and we achieved it.

**Comment by simonmaass** [comment]
is there any update on this?
