### ISSUE TITLE
Improve strict types static tests

### ISSUE THREAD

**Issue by naydav** [magento/inventory#294]
Now we have problem with our checking in **\Magento\Test\Php\LiveCodeTest::testStrictTypes**

Now we have hardcoded check
```
if (strstr($file, 'strict_types=1') === false)
```

But we need to suppose also cases like
```
declare(strict_types = 1);
```

Generally, we can use
http://php.net/manual/en/function.token-get-all.php

**Comment by obuchowski** [comment]
This task is no more needed
