### ISSUE TITLE
Introduce new Service for performance efficient conversion `Product_IDs -> SKUs`

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#296]
Some time ago in Magento 2 a service for conversion `SKUs ->  Product_IDs ` has been addded
```
namespace Magento\Catalog\Model;

/**
 * Product ID locator provides all product IDs by SKU.
 * @api
 * @since 101.1.0
 */
interface ProductIdLocatorInterface
{
    /**
     * Will return associative array of product ids as key and type as value grouped by SKUs.
     *
     * @param array $skus
     * @return array
     * @since 101.1.0
     */
    public function retrieveProductIdsBySkus(array $skus);
}
```
which returns Product_IDs by given SKUs. 
But we still don’t have efficient service which provides opposite conversion 
`Product_IDs -> SKUs`

In the scope of this task we will add this service for Catalog module, because currently we have  something like this:
```
$product = $this->productRepository->getById($stockItem->getProductId());
             $searchCriteria = $this->searchCriteriaBuilder
                 ->addFilter('sku', $product->getSku())
                 ->create();
             $sourceItems = $this->sourceItemRepository->getList($searchCriteria)->getItems();
```

which is definitely not efficient from the performance point of view.

The service should be placed in the same location where `SKUs ->  Product_IDs` service placed.
and have similar naming/logic/semantic

**Comment by obuchowski** [comment]
https://github.com/magento-engcom/msi/pull/306 Pull request is for this issue and also for https://github.com/magento-engcom/msi/issues/297  issue

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/322
