### ISSUE TITLE
Stock status of grouped product not considering 'default qty' option

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#2982]
### Preconditions (*)

1. Create custom stock with custom source
2. Create simple product with qty = 1 on custom source
3. Create grouped product with simple product as option and set 'default qty' for it = 2

### Steps to reproduce (*)

1. Open grouped product page on frontend

### Expected result (*)

1. Grouped product should be 'Out of stock'

### Actual result (*)

1. Grouped product is 'In stock', but you can't add it to the shopping cart

**Comment by nmalevanec** [comment]
Not a bug. Default quantity in grouped product is user defined and should not affect grouped product stock status.
