### ISSUE TITLE
Fix flaky AdminCreateShipmentWithChangedSimpleProductIntoConfigurableCustomStockTest

### ISSUE THREAD

**Issue by lenaorobei** [magento/inventory#2990]
### Preconditions (*)
Install Magento with extensions:
- Page Builder
- Adobe Stock Integration
- Inventory

### Steps to reproduce (*)
Run MFTF tests

### Expected result (*)
All tests pass

### Actual result (*)
`AdminCreateShipmentWithChangedSimpleProductIntoConfigurableCustomStockTest ` fails with timeout
<img width="902" alt="Screen Shot 2020-04-23 at 4 58 37 PM" src="https://user-images.githubusercontent.com/17548019/80153742-b9a48b80-8583-11ea-8256-cd4738e5abea.png">

**Comment by sidolov** [comment]
Fixed in scope of https://github.com/magento/inventory/pull/3034
