### ISSUE TITLE
Fix flaky AdminCreateShipmentWithDeletedSimpleProductDefaultStockTest

### ISSUE THREAD

**Issue by slavvka** [magento/inventory#2991]
### Preconditions (*)
Install Magento with extensions:
- Adobe Stock Integration
- Inventory

### Steps to reproduce (*)
Run MFTF tests

### Expected result (*)
All tests pass

### Actual result (*)
`MSI_Multi_Mode.AdminCreateShipmentWithDeletedSimpleProductDefaultStockTest ` fails with timeout

![Screenshot 2020-04-23 18 57 07](https://user-images.githubusercontent.com/9741905/80160954-90402b80-8594-11ea-81e1-8050085e2f15.png)

![image](https://user-images.githubusercontent.com/9741905/80160958-9504df80-8594-11ea-8573-92db115e11bc.png)

**Comment by sidolov** [comment]
Fixed in scope of https://github.com/magento/inventory/pull/3034
