### ISSUE TITLE
Fix flaky AdminCreateShipmentWithChangedSimpleProductIntoConfigurableDefaultStockTest

### ISSUE THREAD

**Issue by slavvka** [magento/inventory#2994]
### Preconditions (*)
Install Magento with extensions:
- Adobe Stock Integration
- Inventory

### Steps to reproduce (*)
Run MFTF tests

### Expected result (*)
All tests pass

### Actual result (*)
`Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.AdminCreateShipmentWithChangedSimpleProductIntoConfigurableDefaultStockTest` fails without error message
![Screenshot 2020-04-24 16 53 26](https://user-images.githubusercontent.com/9741905/80260041-a27da080-864c-11ea-87e4-14ddf8754f06.png)
![Screenshot 2020-04-24 16 56 25](https://user-images.githubusercontent.com/9741905/80260046-a3aecd80-864c-11ea-8899-5d541604c2ac.png)
![Screenshot 2020-04-24 16 56 41](https://user-images.githubusercontent.com/9741905/80260050-a6112780-864c-11ea-8add-c808793feb41.png)
![Screenshot 2020-04-24 16 56 52](https://user-images.githubusercontent.com/9741905/80260053-a8738180-864c-11ea-8f5a-3afc6f2f7a65.png)

**Comment by sidolov** [comment]
Fixed in scope of https://github.com/magento/inventory/pull/3034
