### ISSUE TITLE
Fix flaky StorefrontReorderOfTheOrderWithConfigurableProductWithDropDownAttributeOnTestStockFromHomepageTest

### ISSUE THREAD

**Issue by sivaschenko** [magento/inventory#2997]
### Steps to reproduce (*)
Run `app/code/Magento/InventoryAdminUi/Test/Mftf/Test/StorefrontReorderOfTheOrderWithConfigurableProductWithDropDownAttributeOnTestStockFromHomepageTest.xml` MFTF test

### Expected result (*)
Test should pass

### Actual result (*)
Test randomly fails on the mainline pull requests

Curl error thrown for http POST to /session/1f661f00fec7990651953ba67f5a78e4/log with params: {"type":"browser"}

Operation timed out after 60000 milliseconds with 0 out of -1 bytes received

![image](https://user-images.githubusercontent.com/2028541/80387524-a9045600-88a0-11ea-8732-07340ecc9496.png)

**Comment by sidolov** [comment]
Fixed in scope of https://github.com/magento/inventory/pull/3034
