### ISSUE TITLE
Unable to add product with multi-source inventory to wishlist with 

### ISSUE THREAD

**Issue by FrankStappers** [magento/inventory#3018]
### Preconditions (*)

1. Magento Commerce 2.3.4, vanilla 

### Steps to reproduce (*)

1. Create a new inventory source -named 'new-source'-  in the Magento Admin
2. Create a new stock inventory -named 'new-stock'- the Magento Admin, assign 'new-source' and default website to the 'new-stock'. Ensure that the setup is similar to:
<img width="1118" alt="Screenshot 2020-04-04 at 23 40 40" src="https://user-images.githubusercontent.com/7890079/78461960-ce50da80-76cd-11ea-9afa-f49da12672c4.png">
3. Create a simple product and only assign "new-stock" as in inventory:
<img width="1379" alt="Screenshot 2020-04-04 at 23 48 56" src="https://user-images.githubusercontent.com/7890079/78462065-ed9c3780-76ce-11ea-8113-3bf113cb01b5.png">
4. Visit the the simple product product detail page in frontend.
5. Add the product to the wishlist.
6. The following error shows:
<img width="1297" alt="Screenshot 2020-04-05 at 00 00 50" src="https://user-images.githubusercontent.com/7890079/78462252-96976200-76d0-11ea-80c4-7d2800a7d48d.png">

### Expected result (*)

1. The product should be added to the wishlist.

### Actual result (*)

1. The product is not added to the wishlist.

**Comment by mbrinton01** [comment]
When a fix is made for this issue, PR needs to cover adding product to wishlist from all possible locations:

- Product detail page
- Category page
- Cart

**Comment by bubasuma** [comment]
Internal Magento team is working on this issue right now.

**Comment by magento-quality-patches** [comment]
The patch solving a similar issue is available in [Magento Quality Patches](https://support.magento.com/hc/en-us/articles/360047139492) package (MQP)
 
**Patch**
MDVA-30428: Fixes the issue where customers cannot add a product to wishlist if this product is assigned to a custom inventory source.

**Compatible versions**
Magento OpenSource/Commerce/Commerce Cloud 2.3.3 - 2.3.5, 2.4.0
 
:warning: We strongly recommend testing all patches in a staging or development environment before deploying to production.
 
**Applying a patch - Magento OpenSource/Commerce**
 
1. `$ composer require magento/quality-patches`
2. `$ ./vendor/bin/magento-patches apply MDVA-30428`
 
See [MQP Magento Commerce documentation](https://devdocs.magento.com/guides/v2.4/comp-mgr/patching/mqp.html)
 
**Applying a patch - Magento Commerce Cloud**
See [MQP Magento Commerce Cloud documentation](https://devdocs.magento.com/cloud/project/project-patch.html)
 
**Patch Details**
https://support.magento.com/hc/en-us/articles/360049495812

**Comment by orthener** [comment]
This patch not working with 2.4.1. BUT problem still present in M2.4.1.
MDVA-30428 not present in available list for M2.4.1
Some changes are already present in `Magento\Wishlist` module and patch can't be applyed. Got an error:

> Error: patch can't be applied
Applying patch m2-hotfixes/MDVA-30428__fixes_add_a_product_with_custom_inventory_to_wishlist__2.3.5-p1.patch failed.
error: vendor/magento/module-wishlist/Model/Adminhtml/ResourceModel/Item/Product/CollectionBuilder.php: alreay exist
error: patch error: vendor/magento/module-wishlist/Model/ResourceModel/Item/Collection.php:7
error: vendor/magento/module-wishlist/Model/ResourceModel/Item/Collection.php: can not apply patch 
error: vendor/magento/module-wishlist/Model/ResourceModel/Item/Product/CollectionBuilder.php: alreay exist
error: vendor/magento/module-wishlist/Model/ResourceModel/Item/Product/CollectionBuilderInterface.php: alreay exist
error: patch error: vendor/magento/module-wishlist/Model/Wishlist.php:181
error: vendor/magento/module-wishlist/Model/Wishlist.php: can not apply patch
error: patch error: vendor/magento/module-wishlist/etc/adminhtml/di.xml:24
error: vendor/magento/module-wishlist/etc/adminhtml/di.xml: can not apply patch
error: patch error: vendor/magento/module-wishlist/etc/di.xml:78
error: vendor/magento/module-wishlist/etc/di.xml: can not apply patch

**Comment by bubasuma** [comment]
Hi @orthener as you noticed the patch is not available for 2.4.1 meaning not compatible with 2.4.1.

**Comment by glo35082** [comment]
@magento give me 2.4-develop instance with inventory
