### ISSUE TITLE
Product having zero salable quantity results in stock in product list page and out of stock in view page.

### ISSUE THREAD

**Issue by maharzan86** [magento/inventory#3060]
Preconditions (*)

    1. Magento 2.3.5-p1(MSI enabled)

Steps to reproduce (*)

    1. Create a simple product with qty = 1
    2. Place an order that will cause the product to have 0 salable quantity
    3. The Salable Quantity drops to zero, while the Quantity remains at 1.

Expected result (*)

    1. The product, having Salable Quantity 0, should display out of stock label in both product list page and product view page.

Actual result (*)

    1. The product remains in stock in product list page and out of stock in view page.

P.S. If you open the product page then it does show correctly as out of stock product.

admin panel stock

![スクリーンショット 2020-05-28 10 32 17](https://user-images.githubusercontent.com/45053620/83100525-1ea35200-a0eb-11ea-835d-773f15c658f2.png)

product list page

![スクリーンショット 2020-05-28 13 51 25](https://user-images.githubusercontent.com/45053620/83100549-2e229b00-a0eb-11ea-9642-378f5e9abbc8.png)

product view page

![スクリーンショット 2020-05-28 13 55 54](https://user-images.githubusercontent.com/45053620/83100567-3bd82080-a0eb-11ea-9d03-00967efa9caa.png)

Does anyone facing same? Please help me on this thanks!

**Comment by maharzan86** [comment]
@magento give me 2.4-develop instance

**Comment by maharzan86** [comment]
@magento I want to check this issue in 2.4-develop instance. Provide me 2.4-develop instance.

**Comment by sidolov** [comment]
Closed as duplicate for https://github.com/magento/inventory/issues/3062
