### ISSUE TITLE
Unable to unassign a source from a stock

### ISSUE THREAD

**Issue by phoenix128** [magento/inventory#311]
A critical PHP error is raised in adminhtml while trying to unassign any source from any stock.

### Preconditions
1. PHP 7
2. Magento 2.3-dev

### Steps to reproduce
1. Open any stock page
2. Unassign a source from an existing stock

### Expected result
1. Source is removed

### Actual result
1. PHP error is raised

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/312
