### ISSUE TITLE
Command inventory:reservation:list-inconsistencies gives fatal error

### ISSUE THREAD

**Issue by helmsmantest** [magento/inventory#3127]
### Preconditions (*)
Magento version 2.3.5-p1

### Steps to reproduce (*)

1. After migration we've got product with the following SKU "702675"
2. I'm getting fatal error when I'm trying to check product's compensations (by running bin/magento inventory:reservation:list-inconsistencies)

### Expected result (*)

Get all necessarry data about product's stock
Order [order inc ID]:
  - Product [product SKU] should be compensated by -1.000000 for stock 1

### Actual result (*)

Fatal error:  Uncaught TypeError: Argument 1 passed to Magento\Inventory\Model\ResourceModel\IsProductAssignedToStock\Interceptor::execute() must be of the type string, integer given, called in /var/www/html/iwantfabricm2.loc/public_html/iwantfabric/vendor/magento/module-inventory-reservation-cli/Model/SalableQuantityInconsistency/FilterManagedStockProducts.php on line 56 and defined in /var/www/html/iwantfabricm2.loc/public_html/iwantfabric/generated/code/Magento/Inventory/Model/ResourceModel/IsProductAssignedToStock/Interceptor.php:20
Stack trace:
#0 /var/www/html/iwantfabricm2.loc/public_html/iwantfabric/vendor/magento/module-inventory-reservation-cli/Model/SalableQuantityInconsistency/FilterManagedStockProducts.php(56): Magento\Inventory\Model\ResourceModel\IsProductAssignedToStock\Interceptor->execute(702675, 1)
#1 /var/www/html/iwantfabricm2.loc/public_html/iwantfabric/vendor/magento/module-inventory-reservation-cli/Model/GetSalableQuantityInconsistencies.php(109): Magento\InventoryReservationCli\Model\SalableQuantit in /var/www/html/iwantfabricm2.loc/public_html/iwantfabric/generated/code/Magento/Inventory/Model/ResourceModel/IsProductAssignedToStock/Interceptor.php on line 20

**Comment by Stepa4man** [comment]
Hi, @helmsmantest 
thanks for report
Already fixed in https://github.com/magento/inventory/pull/2912
And looks like it should be in 1.1 and 1.2 packages.

Please make sure you have latest updates from inventory.

**Comment by DigitalStartupUK** [comment]
@Stepa4man At what point will these changes it make it over to M2?

**Comment by Stepa4man** [comment]
Hi @DigitalStartupUK , thanks for the question.

I just checked it out. I don't see this in any released version. So most probably it will appear with the next release.

In case if you don't want to wait you can get [patch](https://patch-diff.githubusercontent.com/raw/magento/inventory/pull/2912.diff)
And apply it to your project. So you can solve it till the next update

UPDATE: Link to the patch is updated so you can get the patch for 1.1.* version instead 1.2.*
