### ISSUE TITLE
Visual swatch attribute option of Configurable product on addtional stock is visible after order placement with all it's quantity

### ISSUE THREAD

**Issue by VasylShvorak** [magento/inventory#3133]
### Preconditions (*)

1. Magento EE 2.4.0-beta2
2. Additional source is created
![image](https://user-images.githubusercontent.com/26908019/87422425-4d18b600-c5e1-11ea-88dc-9641793b7eff.png)
3. Additional stock is created
![image](https://user-images.githubusercontent.com/26908019/87422525-71749280-c5e1-11ea-97c7-0407079c0496.png)

### Steps to reproduce (*)

1. Create configurable product with Price=10$ and swatch attribute:
- "Catalog Input Type for Store Owner" = Visual Swatch
- swatches with color and labels - 'red' and 'blue'
- On "Step 3" select "Apply single quantity to each SKUs"->"Assign Sources", choose Additional source and set Quantity Per Source=100 :
![image](https://user-images.githubusercontent.com/26908019/87423016-4dfe1780-c5e2-11ea-927a-99137c3efa51.png)

2. Go to "Home page"
3. Create new customer
4. Open Configurable product page
5. Select color visual swatch option "red" and add it to the shopping cart with qty = 100
6. Place order
7. Open Configurable product page again

### Expected result (*)

1. Visual swatch option "red" of  Configurable product is not visible 

### Actual result (*)

1. Visual swatch option "red" of  Configurable product is shown
2. Error message "The requested qty is not available" is shown when try option "red" to cart
![image](https://user-images.githubusercontent.com/26908019/87423669-5acf3b00-c5e3-11ea-9a19-fad25205c2fd.png)

**Comment by VasylShvorak** [comment]
Closed as issue was caused due of misconfiguration

**Comment by rliukshyn** [comment]
@VasylShvorak I am dealing with the same issue, could you please provide clarification on what exactly was misconfigured?

thanks
