### ISSUE TITLE
Unreleased bug fix causing fatal error

### ISSUE THREAD

**Issue by Pr00xxy** [magento/inventory#3147]
### Description

Pull request https://github.com/magento/inventory/pull/2912 fixed type error bug causing fatal errors.

however no release addressing this issue has been created.

Release 1.1.5 was created shortly after the merge of this fix.

Tag [1.1.5](https://github.com/magento/inventory/blob/610b63244bb0fc1d72a87ee0fbd14b46f6915622/InventoryReservationCli/Model/SalableQuantityInconsistency/FilterManagedStockProducts.php#L56) does not include the fix
Version 1.1.5 [source](https://github.com/magento/inventory/archive/1.1.5.zip) does not include the fix

**Comment by sidolov** [comment]
Hi @Pr00xxy , you are right, the mentioned fix will be included in the upcoming 1.1.6 release. 
I'm closing the issue since it's already fixed.
