### ISSUE TITLE
Error of sorting by Sales Channels column in Manage Stock grid

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#320]
### Preconditions

1. Magento develop branch with MSI module
2. Create several new Stocks

### Steps to reproduce

1. Login to Admin
2. Go to Stores -> Manage Stocks 
3. Click on title "Sales Channels" in the grid to do sorting

### Expected result

1. Sorting works properly

### Actual result

1 Error "A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later."

![sorting](https://user-images.githubusercontent.com/27818516/34051962-1bd7d76e-e1c9-11e7-8ca2-c803d4490a0b.jpg)

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/329
