### ISSUE TITLE
Search by keyword by part of the name of Stock doesn't work in Manage Stocks grid

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#325]
### Preconditions

1. Magento with MSI module
2. New Stock "Test Stock 1" created 

### Steps to reproduce

1. Go to Admin -> Stores -> Manage Stocks
2. Try to do "Search by keyword" with word "Test" 

### Expected result

1. Search should return "Test Stock 1" in the grid

### Actual result

1. Search returns no result

**Comment by stansm** [comment]
Please assign to me
