### ISSUE TITLE
Search by keyword by part of the name of Source doesn't work in Manage Sources grid

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#326]
1. Magento with MSI module
2. New Stock "Test Source 1" created 

### Steps to reproduce

1. Go to Admin -> Stores -> Manage Sources
2. Try to do "Search by keyword" with word "Test" 

### Expected result

1. Search should return "Test Source 1" in the grid

### Actual result

1. Search returns no result

**Comment by stansm** [comment]
Please assign to me
