### ISSUE TITLE
Investigate and fix problem with testImportWithDifferentSkuCase

### ISSUE THREAD

**Issue by naydav** [magento/inventory#335]
Investigate and fix problem with `\Magento\CatalogImportExport\Model\Import\ProductTest::testImportWithDifferentSkuCase`

**Comment by josh-carter** [comment]
@maghamed @naydav I believe this can be closed now as its fixed with #545 which has been merged into develop

**Comment by smoskaluk** [comment]
@josh-carter I have fail during the import                          
![image.png](https://images.zenhubusercontent.com/5a8d30c24b5806bc2bc7c6e4/db162694-87ff-4065-a289-9dc2009ee759)

**Comment by josh-carter** [comment]
@smoskaluk I'll pick this back up

**Comment by josh-carter** [comment]
@smoskaluk When you found this I'm guessing a product with sku `simple1` exists?

**Comment by smoskaluk** [comment]
@josh-carter Yes, it existed
