### ISSUE TITLE
Missing release tag 1.2.0-p1 required by Magento 2.4.0-p1

### ISSUE THREAD

**Issue by Vinai** [magento/inventory#3354]
### Summary (*)
The package `magento/product-community-edition` 2.4.0-p1 requires `magento/inventory-metapackage` with version `1.2.0-p1`.
Obviously, the package has been built, since 2.4.0-p1 is installable, but sadly it is not possible to manually resolve the dependency without the release tag.

### Proposed solution

1. Check out the commit that was used to build `magento/inventory-metapackage` `1.2.0-p1`
2. `git tag 1.2.0-p1`
3.  `git push --tags`

**Comment by sdzhepa** [comment]
Hello @Vinai 

Thank you for reporting and collaboration!

Adobe team start working on this issue and to process it we need additional details from you.
Could you please provide more details on what the user/customer tried to do and how? (preconditions, steps, etc)

Unfortunately "sadly it is not possible to manually resolve the dependency without the release tag." is not clear enough

Also, 2.4.0-p1 is also >1 year old, I do not see why a user/customer did not have an issue until now. 

Thank you in advance!

**Comment by Vinai** [comment]
> Could you please provide more details on what the user/customer tried to do and how?

When analyzing behavior of a Magento installation without access to the code base, I often use the repositories under https://github.com/magento to see what code is included in a release. This is easier than downloading a given package in a given version, or installing an instance for the given release.
In this case, I am looking at a 2.4.0-p1 Magento instance.  
In the product metapackage `composer.json` I can see the dependency for `magento/inventory-metapackage` with version `1.2.0-p1`.
My next step is to open https://github.com/magento/inventory/ and select the release tag for `1.2.0-p1` to inspect `_metapackage/composer.json`. However, this is not possible as there is no `1.2.0-p1` release tag.

There are two branches, `1.2.0-p1-develop` and `1.2.0-p1-alpha`, but no release tag.
I assume `1.2.0-p1-alpha` was used as the base to generate the `1.2.0-p1` `magento/inventory-metapackage` package, but I can't be sure. All other releases are properly tagged. The same is true for all other magento repositories - only this tag is missing.

Another scenario is when independently generating release packages based on the repositories. Without a tag, a special exception has to be created. It would be helpful if the core Magento repositories consistently used release tags.

> Also, 2.4.0-p1 is also >1 year old, I do not see why a user/customer did not have an issue until now.

This is correct - the 2.4.0-p1 inventory metapackage exists. The problem is the underlying source for the package can not be determined based on a release tag.

If it where a lot of work to fix this issue, it would probably not be worth the effort.
But since it is such little work, it would be helpful if the core team would be able to add the missing tag.

Assuming the branch `1.2.0-p1-alpha` was indeed used, it takes only a minute to run:

```sh
git clone git@github.com:magento/inventory.git
cd inventory
git checkout 1.2.0-p1-alpha
git tag 1.2.0-p1
git push origin --tags
cd ..
rm -rf inventory
```

**Comment by sshrewz** [comment]
Thanks for providing us with details, @Vinai, and for giving us the branch information. Rest assured that we are looking into this and will advise as soon as we have a resolution.

**Comment by sidolov** [comment]
Hi @Vinai ! 1.2.0-p1 tag and release were created on GitHub: https://github.com/magento/inventory/releases/tag/v1.2.0-p1 
I'm closing the issue as done.
Thank you for your input!

**Comment by Vinai** [comment]
@sidolov Thanks for your help, but you tagged the wrong ref.

The tagged version is the commit [6884797](https://github.com/magento/inventory/commit/688479772926c71b65ce4e73b6fed35ebad837ea):
https://github.com/magento/inventory/blob/v1.2.0-p1/_metapackage/composer.json#L3


The correct version is the commit [2a6fdb4](https://github.com/magento/inventory/commit/2a6fdb4e08dc307cd92ca4a7a0958128611be757):
https://github.com/magento/inventory/blob/1.2.0-p1-alpha/_metapackage/composer.json#L3

The correct ref is the head of the branch [1.2.0-p1-alpha](https://github.com/magento/inventory/tree/1.2.0-p1-alpha).
This branch seems to be what was used to build the official release.

On a related note, it would be extremely nice to have consistent tags, that is, without a leading `v`.
To create a tag `1.2.0-p1` the branch with the same name first would need to be deleted or renamed.

I can't reopen the issue.
Would you like me to open a new one, or would you prefer to reopen this issue yourself?
