### ISSUE TITLE
Configurable products marked out of stock - Magento 2.4.4

### ISSUE THREAD

**Issue by pixel-paul** [magento/inventory#3358]
### Preconditions (*)
1. Magento 2.4.4
2. PHP 8.1
3. Inventory modules

### Steps to reproduce (*)

1. Add a configurable product
2. Add 3 child products with stock > 0
4. Test purchase products until the product is marked out of stock
5. Add more items to the product inventory

### Expected result (*)
1. Product is marked as in stock when inventory is added back in

![magento2](https://user-images.githubusercontent.com/389303/182834615-9ebcc3e0-cee9-4523-9d4b-25973374e6ca.png)

### Actual result (*)

1. Product remains out of stock

![magento1](https://user-images.githubusercontent.com/389303/182834948-876066b9-83cf-4e3e-ba45-652ba25bfcf8.png)

I would imagine that applying this patch [https://support.magento.com/hc/en-us/articles/4428085214093](https://support.magento.com/hc/en-us/articles/4428085214093) would resolve the issue, however this patch is not availale for 2.4.4

**Comment by pixel-paul** [comment]
This appears to be reolved in 2.4.5

**Comment by cptX** [comment]
> This appears to be reolved in 2.4.5

I can verify that it's not resolved in 2.4.5!

**Comment by paresh6002** [comment]
@cptX @pixel-paul I have made PR here. so It would solve this issue. so can you please verify?

**Comment by cptX** [comment]
@paresh6002 currently I have 2.4.6 installed and it is working properly. It's impossible for me to test 2.4.4 at the moment.
Also, I have set up indexing on cron, which maybe changes things. Before I was working on a test setup and didn't have indexing on cron.

**Comment by pixel-paul** [comment]
I was able to use the patch provided in this ticket to fix my issue:

https://github.com/magento/inventory/issues/3350
