### ISSUE TITLE
After skipping the source quantity from configurable products child variants edit, the quantity set to zero (blank)

### ISSUE THREAD

**Issue by Varshal24** [magento/inventory#3379]
### Preconditions (*)

1. Magento 2.4.5-p1
2. Inventory 1.2.3
3. Magento 2.4.6
4. Inventory 1.2.4

### Steps to reproduce (*)

1. Create one or more extra sources
2. Create configurable products
3. Add one or more simple product
4. Set simple product quantity using default source and save the product

   ![image](https://user-images.githubusercontent.com/106960621/227112626-806d126c-53dd-4535-9b51-6556894a8a9e.png)

5. Then go into Edit Configuration and select (Skip quantity at this time) in the Quantity per source and than save the product

   ![image](https://user-images.githubusercontent.com/106960621/227114694-5e369f95-55bc-4b34-a02d-3f3f246279b4.png)

6. The quantity will remove from the simple product.

   ![image](https://user-images.githubusercontent.com/106960621/227114509-05896670-d55d-4285-b26f-59ab803f7b17.png)

7. In this inventory_source_item the entry of those products quatity will also remove. 

### Description (*)
The Quantity is removed from configurable products child variants. And the entry of those source_item from inventory_source_item table is removed because of that the product is showing out of stock in the front end. 

### Expected result (*)

1. If we select (Skip quantity at this time) option in Quantity per source than the quantity shouldn’t have to change. It should have to be the same as before.

### Actual result (*)

1. After saving the config product with simple product selecting (Skip quantity at this time) option in 	Quantity per source than the simple product quantity is set to blank.

**Comment by danielpfarmer** [comment]
We're seeing the same issue. Has anyone found a solution to this?

**Comment by IanFiretoys** [comment]
same here, I logged this on the main magento branch here: https://github.com/magento/magento2/issues/37433 as it affects non-MSI installations by simply overwriting the source qty of all existing children in the configurable rather than removing the source outright

**Comment by Varshal24** [comment]
This issue has been solved in the magento developer branch . These are the two commits regarding it (https://github.com/magento/inventory/commit/204131ea0ee8383d099db15ae3475ee957b52480) & (https://github.com/magento/magento2/commit/1e17b1e86203e2989ad2fb15b0f4e97c1d5d1def)) .

**Comment by yurirn** [comment]
@Varshal24 How do I apply this fix in Magento 2.4.5?

**Comment by Varshal24** [comment]
@yurirn You can fix this issue by creating an patch.

**Comment by devphp74** [comment]
@Varshal24 I have the same problem, I saw that you said to apply a patch, 

but which of the commits do I have to apply? (204131e) or (magento/magento2@1e17b1e))

can you help me?

**Comment by Varshal24** [comment]
@devphp74 You can use (https://github.com/magento/inventory/commit/204131ea0ee8383d099db15ae3475ee957b52480) to resolve the issue. However, I suggest that the best approach is to upgrade your shop to the latest version of Magento, which will automatically resolve this issue.
