### ISSUE TITLE
Invoice is not being generated for virtual products after delete that product from admin

### ISSUE THREAD

**Issue by imran9935** [magento/inventory#3381]
### Preconditions (*)
I have tested it only below mentioned magento versions,and issue is reproducible.

1. Magento - 2.4.5-p1
2. Inventory - 1.2.3
3. Magento - 2.4.6
4. Inventory - 1.2.4

### Description (*)
When we  try to create invoice of deleted virtual product then it gives the error like “Following products with requested skus were not found: sku” (screenshot), as invoice generate perfectly for simple product after delete the simple products.

![image](https://user-images.githubusercontent.com/113010604/233259872-1e795db5-a629-4ce6-bf89-5d8611d22847.png)

### Steps to reproduce (*)
 1.  Go to admin panel and create a virtual product.
 2.  Place the order of that virtual product.
 3.  Delete that virtual product from admin and reindex it.
 4. Try to generate invoice of that virtual product then observe.

### Expected result (*)
The deleted virtual product invoice should be generated, as it works perfectly for simple products.

### Actual result (*)
Deleted product invoice is not being generated for virtual products.

### Additional information (*)
1. As we have checked that when we delete product from the admin then product is not being deleted from inventory_source_item table  as this issue (https://github.com/magento/magento2/issues/36992). is still  exists in Magento 2.4.5-p1 and 2.4.6, As we have seen that after remove the deleted products data from  inventory_source_item table then invoice is being generated perfectly.

2. As we have checked and found that the deleted sku is still coming in this variable $notFoundedSkus inside execute method in this file Magento\InventoryCatalog\Model\GetProductIdsBySkus that’s why  it is giving the error during invoice for deleted virtual products.

**Comment by Kashyap1999** [comment]
Hi @imran9935,
There is a configuration "Synchronize with Catalog" located in Stores > Configuration > Catalog > Inventory > Stock Options. This setting automatically synchronizes inventory data according to catalog changes. this configuration will run the consumer "inventory.source.items.cleanup" when catalog changes occur.
after enabling this setting your issue has been solved. Now you can close this issue.
