### ISSUE TITLE
Rename module InventoryConfiguration to InventoryLowStockNotification (include API module)

### ISSUE THREAD

**Issue by naydav** [magento/inventory#341]
In scope of InventoryConfiguration module, we don't provide possibility to add new configuration fields to current configuration object
All logic of this module is related only to LowStockNotification, so need to rename this module correspondingly

**Comment by vasilii-b** [comment]
Hi!
Small update here: talked with @rogyar and decided to postpone this issue until all related branches are merged to `develop`.
