### ISSUE TITLE
Move canSubtractQty move on website level

### ISSUE THREAD

**Issue by naydav** [magento/inventory#345]
Now `cataloginventory/options/can_subtract` is related to store view level
Need to move this option to website level

**Comment by roma-glushko** [comment]
PR https://github.com/magento-engcom/msi/pull/357 has been created for this task. Thank you!

**Comment by roma-glushko** [comment]
Hi @naydav The configuration scope was overridden from InventorySales module. Should we create any tests here? Thanks.
