### ISSUE TITLE
Move Link between Source and Stock into API

### ISSUE THREAD

**Issue by naydav** [magento/inventory#347]
Now we have a few service for managing link between Stock and Source
`GetAssignedSourcesForStockInterface`
`AssignSourcesToStockInterface`
`UnassignSourceFromStockInterface`

And we have `\Magento\Inventory\Model\StockSourceLink` whish is not part of API (working with entity only under hood of module)

But now looks like StockSourceLink became part of API (have got fields related to business value)

So need to move this object to Api/Data, Provide repository, commands for this entity (the same way as for SourceItem)
Also, need to cover new services with api-functional tests

New interfaces:
- `\Magento\InventoryApi\Api\Data\StockSourceLinkInterface`
- `\Magento\InventoryApi\Api\StockSourceLinksSaveInterface::execute(StockSourceLinkInterface[] $links)`
- `\Magento\InventoryApi\Api\StockSourceLinksDeleteInterface::execute(StockSourceLinkInterface[] $links)`
- ` \Magento\InventoryApi\Api\GetSourceLinkListInterface::execute(SearchCriteria $searchCriteria)`

Maybe need to add one more sugar service like
`\Magento\InventoryApi\Api\GetSourceLinkForStock($stockId)`

**Comment by roma-glushko** [comment]
Hi @naydav Could you check if we are good at the current API implementations. Then I will implement  API functional tests for them. Thanks!

**Comment by maghamed** [comment]
https://github.com/magento-engcom/msi/pull/358

**Comment by maghamed** [comment]
resolve conflicts and run all tests
