### ISSUE TITLE
Notify Quantity - Use Default check-box on product page in Sources tab not applying after Save

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#363]
*Preconditions* 
* Magento with MSI module
Navigate to Admin -> Stores -> Configuration -> Catalog -> Inventory (MSI)
In Product on Source Configuration set "Notify for Quantity Below" = 1

*Steps to reproduce*

Navigate to Product page in Admin
Go to "Assigned Sources" grid on Sources tab 
Set "Notify Quantity" for Default Source = 5
Click button "Save"
Check check-box for Default Source for Notify Quantity - Use Default
Click button "Save"

*Expected result*
*  Notify Quantity for Default Source have to be set = 1 (default)

*Actual result*
* Notify Quantity for Default Source didn't change

**Comment by EfremovaVI** [comment]
duplicate - https://github.com/magento-engcom/msi/issues/364

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/604
