### ISSUE TITLE
Fix Magento\InventoryCatalog\Plugin\InventoryApi\ApplyDataToLegacyCatalogInventoryAtReservationPlacingPlugin

### ISSUE THREAD

**Issue by naydav** [magento/inventory#368]
Need to uncomment and fix problem in
`\Magento\InventoryCatalog\Plugin\InventoryApi\ApplyDataToLegacyCatalogInventoryAtReservationPlacingPlugin::afterExecute`
- unskip skipped tests (green now but should fail)

Functionality initially created in #269

**Comment by maghamed** [comment]
@bartekszymanski 
looks like test for CreditMemo is still broken
```
1) Magento\Sales\Controller\Adminhtml\Order\CreditmemoTest::testAddCommentAction
Failed asserting that 93.0 matches expected 95.
```

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/646

**Comment by naydav** [comment]
CreditMemo will be fixed after finishing
https://github.com/magento-engcom/msi/issues/393
