### ISSUE TITLE
Validation fails when Groupped product creating 

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#370]
### Preconditions

1. Magento with MSI

### Steps to reproduce

1. Create Groupped product as Admin user
2. Click "Save" button

### Expected result

1. Product successfully saved

### Actual result

1. "Validation Failed" message

**Comment by mishanino** [comment]
disable sources in product edit for grouped produt
the task has not been fully completed
it is planned to disable for all types of products except simple and virtual

**Comment by naydav** [comment]
@smoskaluk 
Need to recheck on develop branch
