### ISSUE TITLE
Can't place order if Qty of product allocated not on Default Stock 

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#372]
### Preconditions

1. Magento MSI
2. Test Stock created with Test Source assigned to it
3. Main website unassigned from Default Stock and assigned to Test Stock

### Steps to reproduce

1. Create Simple Product 1 with Qty on Default Source = 1 and Qty on Test Source = 10 in Admin
2. Go to frontend - Main website and try to add Simple Product 1 to the shopping cart with Qty = 2 

### Expected result

1. Simple Product 1 added to the cart and order placed correctly

### Actual result

1. Message "We don't have as many "Simple Product 1" as you requested." appeared

**Comment by naydav** [comment]
Is depends on
https://github.com/magento-engcom/msi/issues/520
