### ISSUE TITLE
Validation Failed Message when creating Simple Product

### ISSUE THREAD

**Issue by josh-carter** [magento/inventory#375]
### Preconditions

1. Magento MSI

### Steps to reproduce

1. Create Simple product as Admin user
2. Click "Save" button

### Expected result

1. Product successfully saved

### Actual result

1. Product successfully saved but "Validation Failed" message is shown.

Looks to be the same issue as reported by @smoskaluk in #369 & #370

**Comment by smoskaluk** [comment]
@josh-carter Unfortunally I couldn't reproduce this issue by steps you provided. May you please give more details how to reproduce it?

**Comment by mishanino** [comment]
Closed, because not reproduced
