### ISSUE TITLE
Adapt Returns (SalesInventory). All returns should happen on Default Source

### ISSUE THREAD

**Issue by vrann** [magento/inventory#377]
As a **merchant** I want to **take returns from my customers** so that **I can accept returned orders even when I have multiple inventory locations configured**.

**Background:**
In Magento, it is possible for orders to be returned. This may be for multiple reasons, such as a defective product, or a product that does not fit. Regardless of return reason, Magento must be able to accept returned orders and allow the merchant to decide if returned items should be placed back in stock so they are available for future sale.

In MSI, it is possible (theoretically) to create advanced logic to return items from an order to multiple sources. This could depend (for example) on the number of sources used to fulfill the original order, and merchant preferences.  For Milestone 1 of MSI development, all returns should be made to the default source, regardless of how they were originally fulfilled.

Later epics can enhance and expand this functionality. However, even on future epics, there is a hard requirement that a customer cannot be expected to return items in an order to more than one physical location.

**Acceptance Criteria:**
* After MSI is enabled, orders can be returned successfully
* Existing merchant option `Return to Stock` on Credit Memo screen is retained
* Merchant can select which products and quantities to be refuned and returned on Credit Memo screen (existing functionality)
* If merchant enables `Return to Stock` for one or more items, items are added to the default stock
* When RMA is used (Commerce only feature), address provided to customer = address of default source
  
**What to Demo:**

*Open Source scenario*

* MSI Enabled
* Multiple sources created and enabled
* Create simple product and assign it to multiple sources
* Create simple product two and assign it to multiple sources
* Create order from frontend 
 * Both simple product and simple product two are included in order
 * Quantity for both products > 1
* Show order completes successfully
* Open order in admin panel
* Invoice entire order
* Create Credit Memo
  * For simple product, select `Return to Stock` and `Qty to Refund` > 1
  * For simple product two, unselect `Return to Stock` and `Qty to Refund` > 1
* Show compensation reservation has been made for simple product in the order (in database)
* Show qty selected for simple product has been added to default source

*Additional Commerce only scenario*

* Create order from frontend 
 * Both simple product and simple product two are included in order
 * Quantity for both products > 1
* Show order completes successfully
* Open order in admin panel
* Invoice entire order
* Request RMA from frontend My Account
* Approve RMA from admin panel
* Show address provided to customer = address of default source

**Comment by vrann** [comment]
@mbrinton01 "Show qty selected for simple product has been added to default source" will not work per @maghamed 

Proposal:
- we use the top priority source which used for the order fulfillment

Persist result of source selection is implemented in #640.

Update AC

**Comment by vrann** [comment]
@mbrinton01 we agreed to split this story into two parts: CreditMemo and RMA

**Comment by smoskaluk** [comment]
@mbrinton01     After creation credit memo product returns to the source, from where it was deducted after shipping, what is not according AC.  according @maghamed , RMA functionality not implemented yet. May you please update this epic issue.
