### ISSUE TITLE
Product with negative Quantity doesn't change Stock status to "Out of stock"

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#379]
### Preconditions

1. Magento MSI
2. Simple product created

### Steps to reproduce

1. Open Product page in Admin
2. Set Quantity for your Product = -100 and save

### Expected result

1. Stock status of product has to be changed into "Out of stock"

### Actual result

1. Stock status of product remains "In  stock"

![screenshot_1](https://user-images.githubusercontent.com/27818516/34731282-9371467a-f56a-11e7-8495-b444dceb8af0.jpg)

**Comment by naydav** [comment]
Closed due to changed approach
We don't want to have stock status as dynamically calculated field in backend
This field is only one of condition for `is salable` flag on frontend
