### ISSUE TITLE
Bundle product get "Out of stock" status when created

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#380]
### Preconditions

1. Magento MSI
2. Simple product created with Qantity 100

### Steps to reproduce

1. Create Bundle product with your Simple product as "Budle Items" 

### Expected result

1. Bundle product should be "In stock"

### Actual result

1. Bundle product has status "Out of stock"

**Comment by naydav** [comment]
Possible solution

1) Create module InventoryBundleIndexer.
2) If at least one bundle child is in stock, so bundle should be in stock too.

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/527
