### ISSUE TITLE
Configurable product get "Out of stock" status when its simple configurations products are "In stock"

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#397]
### Preconditions

1. Magento MSI

### Steps to reproduce

1. Create Configurable product any type, don't set Quantity for it, but set Qty for its simple configurations products = 100 

### Expected result

1. Configurable product should be "In stock" 

### Actual result

1. Configurable product "Out of stock"

**Comment by eduard13** [comment]
@smoskaluk could you please have a look at the change that I've made?
I guess that there should be a better solution, by checking if all the assigned simple products are in stock, and after that we have to set the stock?

**Comment by smoskaluk** [comment]
@eduard13 hi, i am sorry, didn't see your comment. For code review please contact @maghamed or @naydav

**Comment by slacka1** [comment]
Is this supposed to be fixed in MSI 1.1.0?  I'm having this issue in 1.1.0.  Is it because parent is getting set to out-of-stock due to thresh-hold and parent not having inventory itself?
