### ISSUE TITLE
Processing of different order statuses. Cancel Order, Partial cancel

### ISSUE THREAD

**Issue by vrann** [magento/inventory#404]
As a **merchant** with MSI enabled I want to **be able to cancel orders** so that **I can respond to customer requests**.

**Background:**
As a part of regular order processing, merchants can cancel orders from the admin panel. Orders can be cancelled if they have not yet been invoiced. For orders with more than one line item or product quantity > 1, it is possible to partially cancel an order. From the admin panel, the merchant cannot select *which* items should be cancelled. When the merchant clicks the `Cancel` button in the header on an order, all items that have not been invoiced will be cancelled. Any items that have been invoiced will remain on the order. At that point, if the merchant wants to refund the invoiced items, they need to create one or more credit memos to do so.

**Acceptance Criteria:**
* Merchant can cancel orders from the admin panel
* Only items that have not been invoiced or shipped are cancelled
* When order is cancelled, items are returned to stock
* When returned to stock, items are returned to the source(s) allocated on the order for each item

**What to Demo:**
* MSI Enabled
* Multiple sources created and enabled
* Two sample products created 
* Each sample product assigned to >1 source
* Create order from admin panel containing both sample products, each with qty > 1
* Open order in admin panel
* Partially invoice order
* Partially ship order
* Cancel order
* Show correct qty of each item has been returned
  * To correct source(s)
  * Shipped items are not returned
  * Invoiced items are not returned

**Comment by vrann** [comment]
@mbrinton01 during the grooming we agreed that this story should cover shut complete cancel case. Compensation reservation should be created.

Also, in fact, this functionality should already been implemented. The task for verification of the order cancel and updating test cases is created for QA department

**Comment by smoskaluk** [comment]
https://app.hiptest.com/projects/69435/test-plan/folders/432042
