### ISSUE TITLE
Provide base implementation for \Magento\Inventory\Model\GetStockItemQuantityInterface

### ISSUE THREAD

**Issue by naydav** [magento/inventory#420]
Need to implement `\Magento\Inventory\Model\ResourceModel\Stock\GetStockItemQuantity::execute`
with logic related on source items data (but not based on idex data)

**Comment by p-bystritsky** [comment]
\Magento\Inventory\Model\GetStockItemQuantityInterface is already removed.

**Comment by naydav** [comment]
Implemented as 'stub' object
https://github.com/magento-engcom/msi/blob/develop/app/code/Magento/Inventory/Model/ResourceModel/Stock/GetStockItemData.php
Generally, implementation which is not related to index data will be useless
