### ISSUE TITLE
Product edit page: can't unassign pressed source.

### ISSUE THREAD

**Issue by RomaKis** [magento/inventory#422]
Steps to reproduce:
1. Create product "Simple Product 1". Save it.
2. Create it two additional source, except default("source_1" and "source_2").
3. Assign two or more created sources to "Simple Product 1" -> save product.
4. Try to unassign "source_1" from "Simple Product 1".

Expected result:  "source_1" is unassigned.
Actual result: "source_2" is unassigned.

5. Save  "Simple Product 1".

Expected result:  "source_1"  is presented is source list.
Actual result: "source_1"  is absent is source list. Only "Default Source" is presented.

**Comment by Etty** [comment]
#khcd2018

**Comment by Etty** [comment]
#khcd2018

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/501
