### ISSUE TITLE
Grouped product get "Out of stock" status when its grouped simple and virtual products are "In stock"

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#423]
### Preconditions

1. Magento MSI single stock mode
2. Simple and virtual products created with Quantity = 100 and Stock status "In stock"

### Steps to reproduce

1. Create Grouped product, add to it Simple and Virtual products as grouped products

### Expected result

1. Grouped product should be "In stock" 

### Actual result

1. Grouped product "Out of stock"

**Comment by naydav** [comment]
Possible solution:

Create module InventoryGroupedIndexer.
If at least one child is in stock, so grouped should be in stock too.

**Comment by RomaKis** [comment]
Need to uncomment test from  https://github.com/magento-engcom/msi/issues/454.
