### ISSUE TITLE
Unskip and fix \Magento\Catalog\Controller\ProductTest::testViewActionConfigurable

### ISSUE THREAD

**Issue by naydav** [magento/inventory#424]
`\Magento\Catalog\Controller\ProductTest::testViewActionConfigurable`

`1) Magento\Catalog\Controller\ProductTest::testViewActionConfigurable
Failed asserting that 0 matches expected 1.
/home/travis/build/magento-engcom/msi/dev/tests/integration/testsuite/Magento/Catalog/Controller/ProductTest.php:116`

**Comment by RomaKis** [comment]
This issue will be fixed in https://github.com/magento-engcom/msi/pull/411.

**Comment by RomaKis** [comment]
Blocked by https://github.com/magento-engcom/msi/issues/385.

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/634
