### ISSUE TITLE
Update StockItemDataChecker

### ISSUE THREAD

**Issue by naydav** [magento/inventory#426]
Now in
dev/tests/integration/testsuite/Magento/CatalogInventory/Model/StockItemSave/StockItemDataChecker.php:21 we have additional check in `checkIntegrityWithInventory`

We need to do this check as optional (because test must be green without MSI)
We can use 
```
/** @var Manager $moduleManager */
$moduleManager = Bootstrap::getObjectManager()->get(Manager::class);
// soft dependency in tests because we don't have possibility replace tests from different modules
if ($moduleManager->isEnabled('Magento_Inventory')) {
   ...
}
```

Or need to copy current tests to MSI branch and provide one more check related to multi stocks
Both of implemenations are located in related PR

**Comment by RomaKis** [comment]
We have closed PR https://github.com/magento-engcom/msi/pull/445 due to low priority. When this task will be actual it can be reopened.
