### ISSUE TITLE
Source deduction at Order complete

### ISSUE THREAD

**Issue by naydav** [magento/inventory#430]
Need to 
1) Deduct qty on source items according to `ShippingAlgorithmProviderInterface`
2) Create compensate reservations
3) Cover functionality with integration tests

**Comment by p-bystritsky** [comment]
Shipment is saved in two places: \Magento\Sales\Api\ShipmentRepositoryInterface::save (used in API) and \Magento\Shipping\Controller\Adminhtml\Order\Shipment\Save::_saveShipment (used in admin).
