### ISSUE TITLE
Add support for "use_config_manage_stock" in MSI

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#441]
In Magento we have 
*Manage Stock* configuration option. By default, this option is enabled. It decreases the number of products in stock when they are purchased.

This function needs to be disabled only for products with no need to manage the stock (for example, downloadable products). To do so, just unmark the Use Config Settings checkbox for Manage Stock option for a needed product (Catalog > Manage Products) and set your own value.

this behavior should be supported in MSI

**Comment by naydav** [comment]
Index part is finished
Need to adapt only reservations mechanism
