### ISSUE TITLE
Adapt MSI product status to backorder functionality

### ISSUE THREAD

**Issue by p-bystritsky** [magento/inventory#444]
Depends on
https://github.com/magento-engcom/msi/issues/379

1. Make possible to set product status to "In Stock" when backorders are allowed.
2. Unskip test \Magento\InventorySales\Test\Integration\IsBackorderedProductInStockTest::testBackorderedZeroQtyProductIsInStock

**Comment by chrom** [comment]
#443

**Comment by chrom** [comment]
PR #437
