### ISSUE TITLE
Add `is shippable` concept in shipping result

### ISSUE THREAD

**Issue by naydav** [magento/inventory#463]
`\Magento\InventoryShipping\Model\ShippingAlgorithmResult\ShippingAlgorithmResultInterface` presents result of working shipping algorithm

1) Need to introduce new method `isShippable` in interface
2) Update `\Magento\InventoryShipping\Model\DefaultShippingAlgorithm`
3) Cover with integration test

**Comment by larsroettig** [comment]
@naydav  pls review my commit thank you

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/505
