### ISSUE TITLE
Update source code and name creates new source instead of updating existing

### ISSUE THREAD

**Issue by Stepa4man** [magento/inventory#467]
During changing source name and source code magento creates new one instead of updating existing

### Preconditions
1. Create new msi source

### Steps to reproduce
1. Go to edit source
2. Change source name and source code
3. Save source

### Expected result
1. Source updated, existing source became with new name and code, source code updates at inventory_source_stock_link table using cascade strategy

### Actual result
1. New source created, old wasn't renamed

**Comment by vrann** [comment]
Issue fixed as a scope of #477
