### ISSUE TITLE
Impossible to delete just one source from stock

### ISSUE THREAD

**Issue by Stepa4man** [magento/inventory#468]
Deleting source on source grid at inventory/stock/edit page (pushing bucket icon) deletes from grid wrong source, blocks all bucket icons on the grid and removes all sources from stock (it is visible only after refreshing) in spite of deleting just one item.

### Preconditions
1. Create new stock
2. Create several sources
3. Assign 2+ sources to the new stock
4. Save stock

### Steps to reproduce

1. Go to inventory/stock/edit page
2. On the source grid click on any delete bucket icon
![image](https://user-images.githubusercontent.com/15912461/35471307-63933026-0361-11e8-9532-9cecface09bb.png)
3. Refresh page

### Expected result
1. Deleted source disappears from grid
2. Delete bucket icon still do their work - delete any other item
3. After refreshing in grid we should see items that we didn't delete

### Actual result
1. All sources deleted from stock
2. Other bucket icons don't work for deleting another source

**Comment by AlexandrKozyr** [comment]
reproduced locally.
got next error:
![image](https://user-images.githubusercontent.com/9674839/35471825-caeee418-036b-11e8-8bd5-f85be13f1b3f.png)

**Comment by AlexandrKozyr** [comment]
the problem was with wrong UI component initialization. fixed
