### ISSUE TITLE
MSI: Resolve Country and Region view in grid

### ISSUE THREAD

**Issue by naydav** [magento/inventory#47]
Create/Update testing scenario to check following functionality.
Source Grid displays region correctly when:
- specified custom region entered manually
- specified region selected from predefined values

**Comment by amasty-pomaleyko** [comment]
There are 2 fields: region and region_id 
![rxnznwl](https://user-images.githubusercontent.com/33220959/33994651-6a5951d4-e0ec-11e7-96d0-59a5783cade9.png)

**Comment by smoskaluk** [comment]
https://hiptest.net/app/projects/69435/test-plan/folders/409122/scenarios/1640894
https://hiptest.net/app/projects/69435/test-plan/folders/409122/scenarios/1640994
