### ISSUE TITLE
Unskip StockStatusFilterTest

### ISSUE THREAD

**Issue by RomaKis** [magento/inventory#478]
Unskip Magento/CatalogSearch/Model/Search/FilterMapper/StockStatusFilterTest. 
Need to correct the test as now it looks like not an integration test, it only copy Magento 2 code logic.

Tests to unskip: 
- testApplyFullFilterWithoutOutOfStock();
- testApplyFullFilterWithOutOfStock();
- testApplyGeneralFilterWithoutOutOfStock();
- testApplyGeneralFilterWithOutOfStock().

**Comment by ishakhsuvarov** [comment]
Looks like fix was merged in https://github.com/magento/magento2/pull/15690

Thanks @kisroman
