### ISSUE TITLE
Adapt SalesInventory module to use Return mechanism to Source from MSI

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#491]
>Magento_SalesInventory module allows retrieve and update stock attributes related to Magento_Sales, such as status and quantity.

**Comment by larsroettig** [comment]
Hi @maghamed ,
can you pls discirbe this Ticket more. Currently we don't know about from which source is the product ship. Should we resend to **Hamburg Shoe Store** or to **central return centre**  etc? 

I think an Plugin for **\Magento\SalesInventory\Model\Order\ReturnProcessor::execute** should be engue.

**Comment by vrann** [comment]
Should be closed in favor #349
