### ISSUE TITLE
Create InventoryConfiguration module, add GetStockItemDataTest

### ISSUE THREAD

**Issue by RomaKis** [magento/inventory#502]
- Create InventoryConfiguration.
- Move to InventoryConfiguration next classes:
Magento\Inventory\Model\ResourceModel\IsSalableCondition\GetMinQtyStockCondition
Magento\Inventory\Model\ResourceModel\IsSalableCondition\GetManageStockCondition
and move its declaration to di.xml.
- add test for Magento\InventoryIndexer\Model\GetStockItemData similar as Magento\Inventory\Test\Integration\Stock\IsProductSalableTest.

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/504
