### ISSUE TITLE
Problem with selecting source to assign on product page

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#508]
### Preconditions
Magento MSI
Product created and assigned to default Source
2 additional Sources created

### Steps to reproduce
Open product page in admin to edit
Click button "Assign Sources"
select one of the additional sources to assign

### Expected result
Only one Source have to be selected 

### Actual result
Both Sources are selected

**Comment by RomaKis** [comment]
This is Magento bug with ui grid. I created public issue for it https://github.com/magento/magento2/issues/13660.
