### ISSUE TITLE
Could not save Source Item Configuration - error when assigning additional source to the Virtual and Downlodable products

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#510]
### Preconditions

1. Magento MSI
2. Virtual and Downloadable products created
3. Additional Source created

### Steps to reproduce

1. Open one of these products to edit in admin
2. Click button "Assign Sources"
3. Select new Source to assign
4. Click button "Done"
5. Set Qty for this new Source
6. Click button "Save"

### Expected result

1. Product has to be saved 
2. New Source has to be assigned

### Actual result

1. Exception message "Could not save Source Item Configuration"
2. New Source is not assigned

**Comment by naydav** [comment]
Will be fixed in
https://github.com/magento-engcom/msi/pull/472

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/472
