### ISSUE TITLE
Perform refactoring on interfaces and classes related to product salabiility

### ISSUE THREAD

**Issue by aleron75** [magento/inventory#517]
To keep language and domain consistency, perform the following refactoring:

- Rename `GetSalableProductQtyInterface` to `GetProductSalableQtyInterface`
- Rename `GetSalableProductQty` to `GetProductSalableQty`
- Move `GetProductSalableQtyInterface`, `IsProductSalableInterface`  under `InventorySalesApi` module
- Move `IsProductSalable` and `GetProductSalableQty` under `InventorySales` module
- Adjust all reference to the above elements accordingly
- Move all the logic related to Reservations to `InventoryReservations` module

**Comment by naydav** [comment]
Pls, don't forget to rename class properties according to interfaces renaming

**Comment by maghamed** [comment]
And comment blocks in interfaces and classes

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/533
