### ISSUE TITLE
Implement data consistency between Stocks and Reservations

### ISSUE THREAD

**Issue by aleron75** [magento/inventory#531]
As a result of moving Reservation logic under specific modules (see issue #517) we remove the foreign key to the Stock table from the Reservation table.

This can lead to data inconsistency when a stock is deleted and some reservations are still referring to it.

@maghamed: we will discuss implementation details later on (possible solution: plugin on Stock deletion) but in the meantime, I open this issue not to forget to work on this.

**Comment by maghamed** [comment]
This GitHub ticket should address this issue - https://github.com/magento-engcom/msi/issues/2140

CLI Toolings should help with Inventory Consistency
