### ISSUE TITLE
Prevent admin to overwrite Stock Data when order placed while he was editing product page

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#538]
Currently we have Qty/Stock Status fields on the Product editing page in Magento Backend
so, we have both product data and Inventory data on the same form
and it happens, that admin opens product editing page as he wants to change name/description/media data etc.
but Magento sends whole data on a form to server
and we save it all together , re-writing the previous state
thus, if at the time of admin was editing product attributes, order has been placed and inventory has been deducted
saving product form - we just loose this inventory deduction
so, the system will behave like this. 
1. Initial state. Qty = 10
2. Admin opens product page (Qty = 10 )
3. Customer place an order and make deduction  -5   (Qty = 10- 5 = 5)
4. Customer updates product description and save product (sending Qty = 10 , old value)
it’s very hard to track such issue , and re-create data consistency

More discussion about this issue here - https://youtu.be/WrrH_iwFHaE

so, the simplest solution - just not to send Stock data if value of Qty/Stock Status has not changed.
We  have initial Pull Request for this 
https://github.com/magento-engcom/msi/pull/537

which affects Magento CE (two fields: Qty / Stock Status). 
This is just UI part (no backend handling added)

but we also need to apply the similar approach for SourceItem grid we introduce in the scope of MSI

AC:
- we can edit product with source items and place orders at the same time. Non-stock attributes from the product edit page should not override stock information saved when order is placed in single-stock mode
- we can edit product with source items and place orders at the same time. Non-stock attributes from the product edit page should not override stock information saved when order is placed in multi-stock mode

**Comment by mbrinton01** [comment]
Moved to Milestone 2

**Comment by sidolov** [comment]
Moved to internal backlog since the epic out of scope.
