### ISSUE TITLE
DOCS - Add user guide to Flare for 2.3

### ISSUE THREAD

**Issue by jhill-magento** [magento/inventory#544]
Add all content for the user guide to MadCap Flare project for the Magento Admin User Guide 2.3. This work is currently in progress. 

- Generate new TOC for Flare
- Replace existing content on Managing Inventory
- Add content for partial shipments, adding SSA and shipment specifics for multi shipments, from source, overrides and SSA recommendations
- Add concepts for single vs multi source, expanding to multi source, features, with jump list of links to additional content
- Replace existing info on global and product level inventory management, currently in two places and badly documented
- Add content for backorder configuration, currently not documented in the user guide
- Update all screen shots
- Update all reference content including Stores menu, configuration options global/store/etc
- Create and add workflow diagrams and examples for all features

**Comment by lorikrell** [comment]
Need to verify - looks to pertain to the Flare source. Verifying in GH branch 2.3 merchant.

**Comment by lorikrell** [comment]
Completed update:
TOC generated for content
Determined existing content to replace
Large format screenshots taken for existing content
Diagrams started
Added content for 
- backorders
- learn more
- sources (create/manage/grid)
- stocks (create/manage/grid)
- expanding to multi
- overview of single and multi source

Still determining order and shipment existing content to modify.

**Comment by lorikrell** [comment]
Completed - added to Open Source, Commerce, and B2B. 
https://docs.magento.com/m2/ee/user_guide/catalog/inventory-management.html
https://docs.magento.com/m2/ce/user_guide/catalog/inventory-management.html
https://docs.magento.com/m2/b2b/user_guide/catalog/inventory-management.html
