### ISSUE TITLE
Implement RSS feed to Low Stock Notifications

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#555]
Implement RSS feed to Low Stock Notifications

**Comment by larsroettig** [comment]
Hi @maghamed, 
you mean RSS feed on this ticket or? 


I think in this Ticket we must implement **Magento\Framework\App\Rss\DataProviderInterface**

**Comment by vrann** [comment]
@larsroettig yes, RSS feed

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/631
