### ISSUE TITLE
Uncaught TypeError: data.slice is not a function - during the save of Configurable product (Related to PR 540)

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#567]
Uncaught TypeError: data.slice is not a function - during the save of Configurable product

![conf msi](https://user-images.githubusercontent.com/27818516/36382014-36875e36-1590-11e8-834e-b60702b3a585.jpg)

Related to https://github.com/magento-engcom/msi/pull/540

**Comment by RomaKis** [comment]
Will be fixed in https://github.com/magento-engcom/msi/pull/540.
