### ISSUE TITLE
Reservation for configurable products

### ISSUE THREAD

**Issue by seruymt** [magento/inventory#573]
After placing order, together with the simple products, a reservation is also created for the configured products. But, as far as I know, a configurable product isn't in product types list for which stock management is maintained.

*Need to check with other product types (bundle etc.)

**Comment by p-bystritsky** [comment]
The same behavior with bundle product. Grouped works correct.

**Comment by naydav** [comment]
Need to recheck this behaviour on current dev branch

**Comment by p-bystritsky** [comment]
@naydav now we have error  "Not all of your products are available in the requested quantity."  while placing Order that contains Configurable or Bundle products.

**Comment by p-bystritsky** [comment]
Should be fixed in https://github.com/magento-engcom/msi/pull/805/
