### ISSUE TITLE
"Validation Failed" obscure message.

### ISSUE THREAD

**Issue by RomaKis** [magento/inventory#578]
app/code/Magento/Inventory/Model/SourceItem/Command/SourceItemsSave.php,line 63-64:
```
if (!$validationResult->isValid()) {
            throw new ValidationException(__('Validation Failed'), null, 0, $validationResult);
        }
```
User don't understand what is wrong and what  he/she should to do to save product correctly. $validationResult can have multiple errors it isn't good practice to show it all. Need to investigate what is the best solution.

**Comment by denteblu** [comment]
Seems like a frontend issue, the `ValidationException` returned has a `getErrors()` method that collect all the validation errors.

In `ValidationException` comment is stated that:
> ValidationException exists to be compatible with the Web-API (SOAP and REST) implementation >which currently uses Magento\Framework\Exception\AggregateExceptionInterface returned as a result of ServiceContracts call to support Multi-Error response.

I suggest to investigate on frontend side where the ValidationException is rendered for the user to show a multi-error response.
