### ISSUE TITLE
Add possibility To Delete Stocks in Admin Panel

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#59]
Add possibility To Delete Stocks in Admin Panel

*In case of any questions - send an email to engcom@magento.com, or ask a question in #MSI Slack channel

**Comment by naydav** [comment]
Example of Delete controller
https://github.com/naydav/Magento2Samples/blob/2.2.0-dev/app/code/Engine/Location/Controller/Adminhtml/Region/Delete.php

Mass Delete controller
https://github.com/naydav/Magento2Samples/blob/2.2.0-dev/app/code/Engine/Location/Controller/Adminhtml/Region/MassDelete.php
