### ISSUE TITLE
Admin user exports Stock Source data

### ISSUE THREAD

**Issue by jhill-magento** [magento/inventory#593]
Admin user exports Stock Source data

How to export/import

System > Export > Stock Sources

Filters can be used (optionally)

Click Continue

.csv file is generated with correct columns: source_code, sku, status, quantity

.csv file contains correct values

**Comment by lorikrell** [comment]
Updated content in https://github.com/magento-engcom/msi/wiki/Using-MSI-with-Products#export---import-for-product-updates

Moving content to Confluence for review.

**Comment by lorikrell** [comment]
Completed, will update as needed
