### ISSUE TITLE
DOCS - Admin user deletes Stocks

### ISSUE THREAD

**Issue by jhill-magento** [magento/inventory#595]
Post Beta 1.0.0

**Task**: Admin user deletes Stocks. Process is they remove the Sales Channel, add it to another stock, then delete this Stock. 

**Warnings**: If they try deleting Stock with Sales Channel (1+) associated. Sources do not matter. They cannot delete the Default Stock atm. 

**Caveats**: If they move the sales channel to another stock with different sources with orders not in shipment/invoice stage, may need to rerun SSA to update shipping/source allocation?

**Process**:
From the Manage Stock grid
* Edit a stock, click Delete in the header (this feature is not yet implemented)

    * If stock has no Sales Channels assigned, stock is deleted
    * If stock has Sales Channels assigned, "Stock has at least one sale channel and could not be deleted."
    * If stock being edited is Default Stock, "Default Stock could not be deleted."

From the grid using Mass Action tool (TBD)
* Select one or more Stocks
* Use Delete mass action

    * If stock(s) has no Sales Channels assigned, stock is deleted
    * If stock(s) has Sales Channels assigned, "Stock has at least one sale channel and could not be deleted."
    * If Default Stock is selected for Delete mass action, "Default Stock could not be deleted."

**Comment by lorikrell** [comment]
Documented and live in manage section. https://github.com/magento-engcom/msi/wiki/Create-Stock#manage-stock
