### ISSUE TITLE
DOCS - Admin user deletes Sources

### ISSUE THREAD

**Issue by jhill-magento** [magento/inventory#596]
Post Beta 1.0.0

**Task**: Admin user deletes Sources. 

**Warnings**: They cannot delete the Default Source atm. 

**Caveats**: What happens if a product only has 1 source assigned and that source is deleted? Currently, you can remove all sources from a product. 

From the Manage Sources grid

* Edit a source, click Delete in the header (TBD)
    * Source is deleted
    * If source being edited is Default Source, "Default Source could not be deleted."

From the grid using mass action (TBD)

* Select one or more Sources
* Use Delete mass action
    * Source(s) is deleted
    * If Default Source is selected for Delete mass action, "Default Source could not be deleted."

**Comment by lorikrell** [comment]
Closing - no longer needed. Cannot delete sources.
