### ISSUE TITLE
Create Inventory Module Skeleton

### ISSUE THREAD

**Issue by okorshenko** [magento/inventory#6]
**Module name**: Inventory 
**Edition**: Community Edition

**Acceptance Criteria**
 - [ ]  Module skeleton is created (module config, composer.json, README, license, module can be installed)

**Comment by maghamed** [comment]
why do we call it warehouse? and warehouse management? 
Source is more precise word for this, because small merchants don't work with warehouses, that's naming appropriate for bit EE merchants
In our case this is a source, because it unites all possible kind of stocks
