### ISSUE TITLE
Marketing tab - Widget List - Duplication - Blank Page

### ISSUE THREAD

**Issue by gx2g** [magento/inventory#61]
I just updated from Magento 2.1.7 to 2.1.8 and I noticed when I log in to my dashboard and click on the marketing tab, I see two widget list links and both of them go to a blank page. Can you please tell me if this is a bug?

**Comment by maghamed** [comment]
hey @gx2g  looks like you need to create this issue in the Magento 2  issue tracker
https://github.com/magento/magento2/issues
or ask your question on the Magento Forum

Current Issue tracker is devoted to #MSI (Multi Source Inventory) project only
