### ISSUE TITLE
Adapt Stock Item Configurations

### ISSUE THREAD

**Issue by vrann** [magento/inventory#611]
New Configuration interfaces uses Stock Item configuration and there are already interfaces (per #520)

We need to ensure that there are no other configuration options are working. White box testing is more efficient here.

https://github.com/magento-engcom/msi/wiki/Inventory-Options-List

Later story for Reservations:
- Reservation are adjusted for is_manage_stock functionality
- Reservations during order creation should be created for virtual and downloadable
- Synchronization of reservation for legacy system

AC:
- Stock Configuration options works correctly with the MSI
- When is_manage_stock is set to NO=> reservations are are not placed

Demo-able Scenarios:
- stock configuration options scenarios should be presented and demonstrated that they are unblocked:
-- quote
-- checkout

**Comment by mbrinton01** [comment]
Link: https://github.com/magento-engcom/msi/wiki/Inventory-Options-List

**Comment by smoskaluk** [comment]
https://app.hiptest.com/projects/69435/test-plan/folders/457014
https://app.hiptest.com/projects/69435/test-plan/folders/457015
https://app.hiptest.com/projects/69435/test-plan/folders/457024
