### ISSUE TITLE
Add Support of PHP 7 Syntax for MSI APIs 

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#62]
Add Support of 

1.  [Return types](https://wiki.php.net/rfc/return_types) declaration
2.  [Scalar type hinting](http://php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration) 

For [Inventory API](https://github.com/magento-engcom/magento2/tree/develop/app/code/Magento/InventoryApi/Api) service contracts.

**Comment by larsroettig** [comment]
Hi @maghamed,
I think we have two problems(issues) in the current code base. 
First many Function has not one type or use string or void type
Examples:

- https://github.com/magento-engcom/magento2/blob/8de5f9312674d766e9c98a989d1bfecf29e81139/app/code/Magento/InventoryApi/Api/Data/SourceInterface.php#L107
- https://github.com/magento-engcom/magento2/blob/msi-php7/app/code/Magento/InventoryApi/Api/Data/SourceInterface.php#L139

The second issues is we use often  **return SourceInterface[]**
but this is not allowed for PHP return types. 
For every **Interface[]** we need some **list object** with a **traversable** implementation.

First of all, we must think how we can solve this issue and discuss the way.

Branch:
https://github.com/magento-engcom/magento2/tree/msi-php7

**Comment by maghamed** [comment]
According to the guide, we provided https://github.com/magento-engcom/magento2/wiki/PHP-7-Syntax-usage-for-Magento-Contribution
we don't support in our code:
1. Nullable types
2. Void return type

But that does not mean that we can't have such contracts in our interfaces. The only issue that these contracts would not be strictly checked on the level of language. 
But we can still declare return types in PHP Doc Blocks like this:
```php
 * @return bool|null 
```

Regarding array type hinting, like this one `return SourceInterface[]`.
It's not supported in any version of PHP neither 7.0 nor 7.1 not even going to be supported in 7.2
That's because PHP does not contain type information in the array internals. Thus, the only possibility to implement this currently is at runtime. 

Some time ago there was even a proposal to fix that https://wiki.php.net/rfc/arrayof
BUT it was not accepted, because guys did not come to the agreement how to fix that correctly. 
Also, the proposal was regarding PHP 5.6 Thus, there was no scalar type hinting at that moment. So, providing a type hinting just for object array was not a comprehensive decision. Here is the discussion regarding this - http://grokbase.com/t/php/php-internals/141f1kzdm8/introducing-array-of-rfc
I believe array type hinting will appear in PHP when type hinting would be supported in arrays internally.

Thus, what I propose to do is to keep the same strategy as we follow along with the Magento codebase.
```
  * @return  SourceInterface[]
```

**Comment by naydav** [comment]
Linked PR
https://github.com/magento-engcom/msi/pull/100

**Comment by naydav** [comment]
Merged in https://github.com/magento-engcom/msi/pull/100
