### ISSUE TITLE
Can't add product to cart if its inventory allocated on non-default stock

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#628]
### Preconditions

1. Magento with MSI
2. New Source created - "Source1"
3. New Stock created - "Stock1" with assigned "Source1" and Sales channel - "Main Website"
4. Simple product "Sim1" created with only "Source 1" assigned, stock status "In stock" and Qty = 100 

###Steps to reproduce

1. Go to main website
2. Verify that product "Sim1" has "In stock" status
3. Try to add  product "Sim1" to the cart

### Expected result

1. Product has to be added to cart 

### Actual result

1. Exeption message "This product is out of stock."

![image](https://user-images.githubusercontent.com/27818516/36844690-6fe22eee-1d5c-11e8-92b0-63e68ea9131d.png)

**Comment by p-bystritsky** [comment]
May be solved in https://github.com/magento-engcom/msi/issues/520.
