### ISSUE TITLE
Adapt Magento\CatalogInventory\Observer\UpdateItemsStockUponConfigChangeObserver

### ISSUE THREAD

**Issue by RomaKis** [magento/inventory#632]
When save Catalog configuration in admin need to check changes and change products statuses.

We have Inventory configuration in admin.
After changing such options e. g. as min_qty or notify below we need to check which products statuses should change and do it. Now UpdateItemsStockUponConfigChangeObserver is doing it. But as we have multi stock system we need to adapt it.

Now if you change e. g. min_qty in admin configuration and save it, it will not work correctly
you need to do reindex.

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/677
