### ISSUE TITLE
Create Shipment for Every Source Deduction

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#640]
Currently, when we run Source Selection Algorithm and Deduct source items we don't store this information in Database.

Interface of the shipment should be extended to support source deduction information.
Separate Shipment should be created for every source deduction

AC:
- multiple shipments should exist for every source used for the order

**Comment by smoskaluk** [comment]
@seruymt       
https://github.com/magento-engcom/msi/issues/940
https://github.com/magento-engcom/msi/issues/941
https://github.com/magento-engcom/msi/issues/942 
https://github.com/magento-engcom/msi/issues/943

**Comment by seruymt** [comment]
This task is no longer relevant
