### ISSUE TITLE
During saving new created for first time Configurable product - Notice: Undefined index: is_in_stock in /var/www/html/magento2ce/msi3/app/code/Magento/ConfigurableProduct/Model/Product/VariationHandler.php on line 203

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#653]
*Preconditions* 
* Magento with MSI
* No additonal Sources and Stocks created

*Steps to reproduce*
* Create Configurable product and assign its variations to Default Source
* Click to Save 

*Expected result*
* Product saved successfully

*Actual result*
* Notice: Undefined index: is_in_stock in var/www/html/magento2ce/msi3/app/code/Magento/ConfigurableProduct/Model/Product/VariationHandler.php on line 203

**Comment by p-bystritsky** [comment]
Cannot reproduce
