### ISSUE TITLE
Exception when trying to create Grouped or Bundle product in admin

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#654]
1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): The configuration parameter "componentType" is a required for "configurable" component.

Exception #0 (Magento\Framework\Exception\LocalizedException): The configuration parameter "componentType" is a required for "configurable" component.
#0 /var/www/html/magento2ce/msi3/lib/internal/Magento/Framework/View/Element/UiComponentFactory.php(396): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataItem(Array, Array, false)
#1 /var/www/html/magento2ce/msi3/lib/internal/Magento/Framework/View/Element/UiComponentFactory.php(305): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataItem(Array, Array, false)
#2 /var/www/html/magento2ce/msi3/lib/internal/Magento/Framework/View/Element/UiComponentFactory.php(208): Magento\Framework\View\Element\UiComponentFactory->mergeMetadata('product_form', Array, false)
#3 /var/www/html/magento2ce/msi3/lib/internal/Magento/Framework/View/Layout/Generator/UiComponent.php(140): Magento\Framework\View\Element\UiComponentFactory->create('product_form', NULL, Array)
#4 /var/www/html/magento2ce/msi3/lib/internal/Magento/Framework/View/Layout/Generator/UiComponent.php(102): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(Object(Magento\Framework\View\Layout\Data\Structure), 'product_form', Array, Object(Magento\Framework\View\Layout\Interceptor))
#5 /var/www/html/magento2ce/msi3/lib/internal/Magento/Framework/View/Layout/GeneratorPool.php(80): Magento\Framework\View\Layout\Generator\UiComponent->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#6 /var/www/html/magento2ce/msi3/lib/internal/Magento/Framework/View/Layout.php(344): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#7 /var/www/html/magento2ce/msi3/generated/code/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#8 /var/www/html/magento2ce/msi3/lib/internal/Magento/Framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#9 /var/www/html/magento2ce/msi3/lib/internal/Magento/Framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#10 /var/www/html/magento2ce/msi3/lib/internal/Magento/Framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#11 /var/www/html/magento2ce/msi3/lib/internal/Magento/Framework/View/Layout.php(254): Magento\Framework\View\Layout\Builder->build()
#12 /var/www/html/magento2ce/msi3/lib/internal/Magento/Framework/View/Layout.php(875): Magento\Framework\View\Layout->build()
#13 /var/www/html/magento2ce/msi3/generated/code/Magento/Framework/View/Layout/Interceptor.php(414): Magento\Framework\View\Layout->getBlock('menu')
#14 /var/www/html/magento2ce/msi3/app/code/Magento/Backend/Model/View/Result/Page.php(26): Magento\Framework\View\Layout\Interceptor->getBlock('menu')
#15 /var/www/html/magento2ce/msi3/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(24): Magento\Backend\Model\View\Result\Page->setActiveMenu('Magento_Catalog...')
#16 /var/www/html/magento2ce/msi3/app/code/Magento/Catalog/Controller/Adminhtml/Product/NewAction.php(71): Magento\Backend\Model\View\Result\Page\Interceptor->setActiveMenu('Magento_Catalog...')
#17 /var/www/html/magento2ce/msi3/generated/code/Magento/Catalog/Controller/Adminhtml/Product/NewAction/Interceptor.php(24): Magento\Catalog\Controller\Adminhtml\Product\NewAction->execute()
#18 /var/www/html/magento2ce/msi3/lib/internal/Magento/Framework/App/Action/Action.php(107): Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor->execute()
#19 /var/www/html/magento2ce/msi3/app/code/Magento/Backend/App/AbstractAction.php(229): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#20 /var/www/html/magento2ce/msi3/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#21 /var/www/html/magento2ce/msi3/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor->___callParent('dispatch', Array)
#22 /var/www/html/magento2ce/msi3/app/code/Magento/Backend/App/Action/Plugin/Authentication.php(143): Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#23 /var/www/html/magento2ce/msi3/lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#24 /var/www/html/magento2ce/msi3/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#25 /var/www/html/magento2ce/msi3/generated/code/Magento/Catalog/Controller/Adminhtml/Product/NewAction/Interceptor.php(39): Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor->___callPlugins('dispatch', Array, NULL)
#26 /var/www/html/magento2ce/msi3/lib/internal/Magento/Framework/App/FrontController.php(55): Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#27 /var/www/html/magento2ce/msi3/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#28 /var/www/html/magento2ce/msi3/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#29 /var/www/html/magento2ce/msi3/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#30 /var/www/html/magento2ce/msi3/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#31 /var/www/html/magento2ce/msi3/lib/internal/Magento/Framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#32 /var/www/html/magento2ce/msi3/lib/internal/Magento/Framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#33 /var/www/html/magento2ce/msi3/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#34 {main}

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/656
