### ISSUE TITLE
Adjust StockItem aggregation functionality to support Disabled Sources

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#66]
Adjust StockItem aggregation functionality to support Disabled Sources.

Currently, indexation mechanism does not take into account that some of the sources could be disabled. So that, all the source items in the scope of this Source should be inaccessible as well.

We need to fix that logic.

So, if there are 3 Sources assigned to the single Stock.
Source A: Qty - 10 Status: In Stock
Source B: Qty - 20 Status: In Stock
Source C: Qty - 30 Status: In Stock

But **Source B is disabled** 

**Current Indexation result is**: 10 + 20 + 30 = 60

**Expected Behaviour**: 10 + 30 = 40

Changes should be covered with Unit Tests and **MUST** be covered by integration tests (because we can not check full re-indexation work via api-functional tests)

**Comment by larsroettig** [comment]
https://github.com/magento-engcom/magento2/pull/76

**Comment by naydav** [comment]
Merged in https://github.com/magento-engcom/msi/pull/76
