### ISSUE TITLE
QA Additional Test Scenarios

### ISSUE THREAD

**Issue by vrann** [magento/inventory#663]
Add test cases for the following functionality
- B2B
-- shared catalog
-- 
- EE: 
-- Giftcard

**Comment by smoskaluk** [comment]
https://jira.corp.magento.com/secure/enav/#?query=project%20%3D%20%22MAGETWO%22%20AND%20fixVersion%20%3D%20%22Unscheduled%22%20AND%20cycleName%20in%20(%22MSI%20Regression%22)
