### ISSUE TITLE
Support "Update on Save" Indexation for StockItem index

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#67]
Currently, StockItem index supports just "Update by Schedule" when you need to set-up Cron which will launch the Inventory reindex.

We need to support "Update on Save"  as well when changes of Source inventory would be applied immediately for StockItem index

**Comment by maghamed** [comment]
Fixed in the scope of #106 PR

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/141
