### ISSUE TITLE
Disabling-enabling Source assigned to Simple product doesn't effect on its appearance on category page on frontend

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#670]
### Preconditions

1. Magento with MSI
2. New stock with new source "Source1" created with Main website assigned as Sale Channel 
3. Simple product created and assigned to New source

### Steps to reproduce

1. Verify Simple product appear on category page on Main website
2. Disable "Source1" in admin

### Expected result

1. Simple product should dissappear from category page

### Actual result

1. Simple product still present on category page

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/835
