### ISSUE TITLE
If unassign from the Stock that Source which assigned to Simple product doesn't effect on its appearance on category page on frontend

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#671]
### Preconditions

1. Magento with MSI
2. New stock with new source "Source1" created with Main website assigned as Sale Channel
3. Simple product created and assigned to "Source1" 

### Steps to reproduce

1. Verify product present on Category page on frontend
2. Unassign "Source1" from the stock
3. Run reindex (added)
4. Verify category page on frontend

### Expected result

1. Product should dissappear from category page

### Actual result

1. product still present on category page

**Comment by AleksLi** [comment]
@smoskaluk I have one question for you. 
When you unassign the source from the stock and this stock was only one in the stock, should stock become unassigned from the main Website (when you're saving stock data)?

**Comment by maghamed** [comment]
need to verify this bug by initial steps to reproduce.

**Comment by smoskaluk** [comment]
@AleksLi Unless you manually unassign Main website from the stock, it will be assigned
