### ISSUE TITLE
Verify Order Cancel functionality. Link all relevant test cases to the story

### ISSUE THREAD

**Issue by vrann** [magento/inventory#673]
Order cancel functionality should be tested according to the requirements in the story. Verify that compensational reservation is created for the cancelled order.

**Comment by vrann** [comment]
- create order via admin panel to test it

**Comment by smoskaluk** [comment]
https://hiptest.net/app/projects/69435/test-plan/folders/432042/scenarios/1621263
https://hiptest.net/app/projects/69435/test-plan/folders/432042/scenarios/1637079
https://hiptest.net/app/projects/69435/test-plan/folders/432042/scenarios/1637602
https://hiptest.net/app/projects/69435/test-plan/folders/432042/scenarios/1637636

**Comment by mbrinton01** [comment]
Scenarios are approved.
