### ISSUE TITLE
Create interface for the sources list for returns

### ISSUE THREAD

**Issue by vrann** [magento/inventory#674]
* create interface for the sources list available for returns (parametrized by order id sku)
    * should return list of sources sorted by priority

This interface will be used for the credit memo and RMA functionality to select the source where the product should be returned.

**Comment by larsroettig** [comment]
Hi @vrann,
we should create new Module **InventoryCreditMemoApi**? Second question if we ship an order I can not find from which source we have to ship this SKU or it is for later currently we return the same list for all products? 



```php
namespace Magento\InventoryCreditMemoApi;

use Magento\InventoryApi\Api\Data\SourceInterface;

interface GetSourcesListForReturn
{

    /**
     * Return list of sources sorted by priority
     *
     * @param int $orderId
     * @param string $sku
     * @return SourceInterface[]
     */
    public function execute(int $orderId, string $sku): array;

}
```
