### ISSUE TITLE
Create Plugins to invalidate StockItem indexes when Stock-to-Source assignments have been changed

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#68]
Create Plugins to invalidate StockItem indexes when Stock-to-Source assignments have been changed.

For now, we don't mark index as invalid after some changes happened in Sources-to-Stocks assignment.

Precondition: 
Source A:  assigned to Stock 1
Source B:  assigned to Stock 2

after that, we decided to assign:
Source B:  assigned to Stock 1

after this operation, we need to invalidate whole ` Stock 1` index, because all the StockItems for `Stock 1` should be re-calculated.

It's a good architectural task because we need to invalidate not the *whole indexes* , but specific dimensions (Stocks) which were affected

**Comment by larsroettig** [comment]
Hi @maghamed,
I started with the implementation on Saturday. I would like disuse about the implementation.

I found the following function in the Interface.
https://github.com/magento-engcom/magento2/blob/a77be455ad9d34bece4f109c60ed2f1a3890b564/lib/internal/Magento/Framework/Indexer/IndexerInterface.php#L107

But I see a  performance problem because I can not specifies which data is invalid if is the indexer in the scheduled mode. For big merchant need a full reindex hours only because one Source is not assigned anymore.

My current Implementation: 
```php

<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

namespace Magento\Inventory\Plugin;

use Magento\Framework\Indexer\IndexerInterfaceFactory;
use Magento\Inventory\Indexer\StockItemIndexerInterface;
use Magento\InventoryApi\Api\UnassignSourceFromStockInterface;

class UnassignSourceFromStock
{

    /**
     * @var \Magento\Framework\Indexer\IndexerInterface
     */
    private $indexer;

    /**
     * @param IndexerInterfaceFactory $indexerFactory
     */
    public function __construct(IndexerInterfaceFactory $indexerFactory)
    {
        /** @var  $indexer */
        $this->indexer = $indexerFactory->create();
        $this->indexer->load(StockItemIndexerInterface::INDEXER_ID);
    }


    public function aroundExecute(
        UnassignSourceFromStockInterface $subject,
        \Closure $proceed,
        int $sourceId
    ) {
        if ($this->indexer->isScheduled()) {
            $this->indexer->invalidate();
        } else {
            $this->indexer->reindexRow($sourceId);
        }
    }
}
```

**Comment by maghamed** [comment]
Results after the discussion : 

- Pugin (in Inventory module) looks like appropriate solution for Interface belonging to InventoryAPI module (there is no pluginization in the same Module, which is forbidden by Magento guidelines)
- Plugin should just invalidate cache, not make a re-indexation (like this one - `$this->indexer->reindexRow($sourceId)`)
- Process of invalidation should be agnostic to the way of re-indexation (Update on Save or by Schedule), thus we no need to have a check like this: `$this->indexer->isScheduled()`
- There should not be business logic in constructor

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/141
