### ISSUE TITLE
'Reorder' button is visible for customer if ordered item is out of stock

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#680]
### Preconditions

1. Create simple product "Simple 1" with qty=1
2. Creat customer account on Main website

### Steps to reproduce

1. Create order with product "Simple 1" by Logged in customer 
2. Goto "My Orders" tab on personal cabinet of your customer
3. Verify that placed order information is present

### Expected result

1. Button "Reorder" should't be visible for placed order

### Actual result

1. Button "Reorder" present for placed order

**Comment by serhiyzhovnir** [comment]
Working on it

**Comment by serhiyzhovnir** [comment]
#distributed-cd

**Comment by serhiyzhovnir** [comment]
@naydav 
The reason of an issue is not triggered **$this->stockHelper->assignStatusToProduct($product)** for products that loads via Products collection.
I've added an observer for assigning a status to all products in products collection after load.
Please, check changes.
https://github.com/magento-engcom/msi/pull/762
Thank you!

**Comment by smoskaluk** [comment]
It's implemented that button "Reorder" disappear only after shipment for oder created
