### ISSUE TITLE
I can add to the cart product as many times as i want even if its qty == 1

### ISSUE THREAD

**Issue by RomaKis** [magento/inventory#693]
I can add to the cart product as many times as I want even if its qty == 1

### Steps to reproduce
1. Create simple product "Simple 1" and assign it to category "Category 1"
2.  Add product to default stock and set its qty to 1.
3. Go to frontend. Locate to "Category 1".
4. Press "Add to Cart" button on "Simple 1"  5 times.

### Expected result
1. I can add this product to the cart only 1 time.

### Actual result
1. I can add it to the cart  as many times as I want.

Note: If I added 5 times product to the cart I can see 5 products in the cart, but if I open mini cart and try change product's qty to 4 I'll get error message. Seems like this functionality works good in mini cart.

**Comment by virfaure** [comment]
#distributed-cd

**Comment by maghamed** [comment]
#749
