### ISSUE TITLE
Reservation and compensational reservation applying to stock, which assigned to Main website as sales channel

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#695]
### Preconditions

1. Magento MSI
2. Main Website assigned to Default stock as Sales channel
3. "New stock 1" created with "new source 1" assigned 

### Steps to reproduce

1. Simple product "Sku1" created and assigned only to "Default Source" with Qty = 10
2. Go to admin and place order with  "Sku1"
3. Go to Manage Stocks and assign "Main website"as Sales channel to "New stock 1"
4. Go to orders and cancel your order with "Sku1" product
3. Open table " inventory_reservation" in your DB

### Expected result

1. Reservation created for "Sku1" for Default stock (id 1)
2. Compensational reservation created for "Sku1" for Default stock (id 1)

### Actual result

1. Reservation created for "Sku1" for Default stock (id 1)
2. Compensational reservation created for "Sku1" for "New stock 1" (id 2)
![image](https://user-images.githubusercontent.com/27818516/37652616-c1d051e4-2c44-11e8-9267-42125219fa84.png)

**Comment by maghamed** [comment]
Ecpected behaviour
