### ISSUE TITLE
Adapt MSI to use Default Stock

### ISSUE THREAD

**Issue by p-bystritsky** [magento/inventory#698]
Use table name resolver to get View name.
Move logic to InventoryCatalog
\Magento\InventoryIndexer\Plugin\InventoryApi\ReindexAfterSourceItemsSavePlugin - implement TODO
Magento/InventoryIndexer/Plugin/InventoryApi/ReindexAfterStockSourceLinksDeletePlugin.php  - do not invalidate cache when used Default Stock.
Check re-indexation when source is enabled/disabled. (separate pr)

**Comment by p-bystritsky** [comment]
Investigate all possible INSERT's into this table:
1. \Magento\CatalogInventory\Model\Indexer\Stock\AbstractAction::_syncData - column names taken from cataloginventory_stock_status_idx
2. \Magento\InventoryCatalog\Model\ResourceModel\SetDataToLegacyStockStatus::execute - UPDATE

**Comment by naydav** [comment]
Need to fix all comments from
https://github.com/magento-engcom/msi/pull/707

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/803
