### ISSUE TITLE
Fatal error: Uncaught TypeError: during the saving of configurable product

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#714]
### Preconditions

1. Magento MSI
2. New stock with new source created

### Steps to reproduce

1. Create configurable product with dropdown attribute and assign variables to default sorce
2. Try to save configurable product
3. 

### Expected result

1. Product saved succesfully

### Actual result

1. Fatal error: Uncaught TypeError: Argument 1 passed to Magento\InventoryConfigurableProduct\Observer\ProcessSourceItemsObserver::processSourceItems() must be of the type array, string given, called in /var/www/html/magento2ce/msi6/app/code/Magento/InventoryConfigurableProduct/Observer/ProcessSourceItemsObserver.php on line 60 and defined in /var/www/html/magento2ce/msi6/app/code/Magento/InventoryConfigurableProduct/Observer/ProcessSourceItemsObserver.php:71 Stack trace: #0 /var/www/html/magento2ce/msi6/app/code/Magento/InventoryConfigurableProduct/Observer/ProcessSourceItemsObserver.php(60): Magento\InventoryConfigurableProduct\Observer\ProcessSourceItemsObserver->processSourceItems('', 'con2-red ') #1 /var/www/html/magento2ce/msi6/lib/internal/Magento/Framework/Event/Invoker/InvokerDefault.php(72): Magento\InventoryConfigurableProduct\Observer\ProcessSourceItemsObserver->execute(Object(Magento\Framework\Event\Observer)) #2 /var/www/html/magento2ce/msi6/lib/internal/Magento/Framework/Event/Invoker/InvokerDefault.php(60): M in /var/www/html/magento2ce/msi6/app/code/Magento/InventoryConfigurableProduct/Observer/ProcessSourceItemsObserver.php on line 71

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/753
