### ISSUE TITLE
Downloadable product with stock status in admin "Out of stock" displays "In stock" status on product page on frontend

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#718]
### Preconditions

1. Magento MSI single mode
2. Downloadable product created with any link added, Qty > 0 and stock status "Out of stock"

### Steps to reproduce

1. Open product page on frontend by direct url

### Expected result

1. Product has to be "Out of stock" on frontend

### Actual result

1. Product "In stock" on frontend

### Proposals
- introduce shipment step for virtual and downloadable product -- just to apply source selection

**Comment by StasKozar** [comment]
Has fix in https://github.com/magento-engcom/msi/pull/692
