### ISSUE TITLE
Investigate fails test on Grouped products

### ISSUE THREAD

**Issue by serhii-balko** [magento/inventory#719]
1. Magento\GroupedProduct\Test\TestCase\CreateGroupedProductEntityTest::test with data set "CreateGroupedProductEntityTestVariation4_0" (CreateGroupedProductEntityTestVariation4_0)
Control 'out of stock' is not visible.
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'out of stock'
+'in stock'

2. Magento\GroupedProduct\Test\TestCase\CreateGroupedProductEntityTest::test with data set "CreateGroupedProductEntityTestVariation3_0" (CreateGroupedProductEntityTestVariation3_0)
The product has not been found by SKU
Failed asserting that false is true.

3. Magento\GroupedProduct\Test\TestCase\CreateGroupedProductEntityTest::test with data set "CreateGroupedProductEntityTestVariation6_0" (CreateGroupedProductEntityTestVariation6_0)
Form data not equals to passed from fixture:
quantity_and_stock_status:
	- is_in_stock: "Out of Stock" instead of "In Stock"
Failed asserting that a string is empty.

4. Magento\GroupedProduct\Test\TestCase\CreateGroupedProductEntityTest::test with data set "CreateGroupedProductEntityTestVariation9_0" (CreateGroupedProductEntityTestVariation9_0)
Form data not equals to passed from fixture:
quantity_and_stock_status:
	- is_in_stock: "Out of Stock" instead of "In Stock"
Failed asserting that a string is empty.

5. Magento\CatalogSearch\Test\TestCase\SearchEntityResultsTest::test with data set "SearchEntityResultsTestVariation6_0" (SearchEntityResultsTestVariation6_0)
A product with name Test grouped product 1008189182 was not found.
Failed asserting that false is true.

http://10.234.212.108:8080/job/Functional-Tests-CE/86/testReport/

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/731#pullrequestreview-106815402
