### ISSUE TITLE
Disable ScalableInventory module before MSI installation

### ISSUE THREAD

**Issue by mbrinton01** [magento/inventory#725]
Current EE (Commerce) includes the ScalableInventory module. This must be disabled before MSI can be installed.

Documentation needs to cover the following cases:
* Merchant upgrades from prior version of Magento to version with MSI (2.3+) --> ScalableInventory must be disabled before install
* Merchant installs clean version of Magento with MSI (2.3+) --> documentation explains that ScalableInventory module is no longer included and has been replaced by MSI. No changes required in installation steps for merchant

Note: this only applies to EE (Commerce). CE / Open Source is not impacted.

**Comment by lorikrell** [comment]
Added to https://github.com/magento-engcom/msi/wiki/Overview#beta-msi-install  for EE 2.3.0-alpha + MSI Beta 1.0.0.

**Comment by lorikrell** [comment]
Closing as complete. Content available in wiki. Content will be further available in User Guide content. Reopen or create a new ticket as needed if requirements change.
