### ISSUE TITLE
Source selection persisted for reorders

### ISSUE THREAD

**Issue by mbrinton01** [magento/inventory#726]
When an order is reordered, the sources used for delivery of the original order should be persisted on the reorder.

As with any order, the merchant can optionally override the sources and re-run the source selection algorithm on demand.

Only applies to reorders with same shipping address and same contents (items and quantities).

**Comment by sidolov** [comment]
Hi @mbrinton01  we are about to complete MSI project feature development and keep issues of defined scope only to have a clean and transparent backlog.
Unfortunately, the current issue is out of scope and should be closed.
Thank you for your involvement!
