### ISSUE TITLE
Default state for MSI after upgrade and installation

### ISSUE THREAD

**Issue by mbrinton01** [magento/inventory#730]
If a merchant upgrades from a prior version of Magento (2.0, 2.1, 2.2, etc.), MSI should be disabled as a part of the upgrade process. The merchant can optionally enable MSI after the upgrade is complete.

If a merchant installs a clean version of Magento including MSI (2.3+), MSI should be enabled by default. The merchant can optionally disable MSI after the installation is complete.

What to Demo:
* Upgrade Magento to current MSI branch from prior version --> MSI is disabled
* Install current MSI branch --> MSI is enabled

**Comment by vkublytskyi** [comment]
@mbrinton01 Magento Cloud uses complex scenario for code generation and static assets deployment during install and upgrades which makes stages when `magento setup:install` or `magento setup:upgrade` too late for managing MSI modules availability. Disabling MSI modules on Magento upgrades may be handled during modules installation by Composer. And this approach works pretty well for all Composer-based installations.

However, there is a case when Magento may be installed with Git. This approach is recommended only for Magento contributing developers and not should be used by SI, merchants or extension developers.

Is it ok if provided requirements will be implemented only for Composer-based Magento Installations?

**Comment by mbrinton01** [comment]
Volodymyr, this approach is acceptable. We make an assumption that all developers using Git installation will also be comfortable with enabling and disabling modules.

Mark Brinton
Senior Technical Product Manager

[/Users/mbrinton/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_1238786169]

512 575 9377  mobile
@markabrinton  twitter

**Comment by maghamed** [comment]
https://github.com/magento-engcom/inventory-composer-installer
