### ISSUE TITLE
Cannot Compare Grouped Products on Storefront.

### ISSUE THREAD

**Issue by nmalevanec** [magento/inventory#734]
### Preconditions
1. Magento MSI. Single Stock Mode.
2. 2.3-develop

### Steps to reproduce
1.  Navigate to admin.
2. Create two simple products s1 and s2.
3. Create two grouped products g1 and g2. Add s1 as grouped product to g1 and s2 to g2.
4. Navigate to storefront.
5. Register customer.
6. Navigate to http://domain/g1.html
7. Press "Add To Compare".
8. Navigate to http://domain/g2.html
9. Press "Add To Compare".
10. Observe Link "Compare Products" shows 2 items.
11. Click link "Compare Products"

### Expected result
1. Both grouped products appear on page for comparison.

### Actual result
1. Compare Products page is empty. No products appear on page.

**Comment by RomaKis** [comment]
Seems like this bug isn't reproducible anymore.
![image](https://user-images.githubusercontent.com/17450979/38129281-0bc8ef80-3407-11e8-85e0-6bf11fdc8507.png).

And new Jenkinks build doesn't have fails with comparing products http://10.234.237.24:8080/job/Functional-Tests-CE/92/testReport/. 
So I close this issue.
