### ISSUE TITLE
Grouped product doesn't appear on category page on frontend and can't be found by search

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#735]
### Preconditions

1. Magento MSI
2. New stock with new source created
3. Create category
3. Simple product created assigned to defaul source with Qty =10

### Steps to reproduce

1. Create Grouped product with Simple product as child product 
2. Add it to your category
3. Try to add to search 

### Expected result

1. Grouped product appear on category page
2. Grouped product found by search

### Actual result

1. Grouped product doesn't appear on category page,
2. Grouped product can't be found by search

**Comment by naydav** [comment]
Will be fixed in scope of #805
