### ISSUE TITLE
Can't Add Bundle Product to Cart.

### ISSUE THREAD

**Issue by nmalevanec** [magento/inventory#736]
### Preconditions
1. Magento with MSI. Single Stock mode.
2.  2.3-develop

### Steps to reproduce
1. Navigate to admin area.
2. Create simple product "s1". Set qty to "100". Be sure it's in stock.
3. Create bundle product "b1" with simple product "s1" as bundle item. Set Default Quantity = 1.
4. Navigate to storefront http://domain/b1.html.
5. Click "Customize and Add to Cart" button.
6. Leave "Qty" field with default "1" and press button "Add to Cart".

### Expected result
1.  Product added to cart.

### Actual result
1. "This product is out of stock." error message appear, cart stays empty.

**Comment by larsroettig** [comment]
@nmalevanec I cannot reproduce this issue 
Testet with Version  3b5a20b7041472fd293733fc381db35409ee6913 - MSI 2.3-develop


![backend](https://user-images.githubusercontent.com/5289370/37864496-1eec8342-2f70-11e8-996c-162e344ca4fa.png)

![bundletest](https://user-images.githubusercontent.com/5289370/37864486-f6baa480-2f6f-11e8-87c4-6508a06877bf.png)

**Comment by jayachandraoggy** [comment]
I faced the similar issue, I tried re indexing after creating the bundle product and then it worked fine.
