### ISSUE TITLE
Out of Stock Bundle Product Shows Up on Storefront as In Stock.

### ISSUE THREAD

**Issue by nmalevanec** [magento/inventory#738]
### Preconditions
1.  Magento with MSI. Single Stock mode.
2. 2.3-develop

### Steps to reproduce
1. Navigate to admin.
2. Create simple product "s1" with qty = 100, In Stock = "Yes".
3. Create bundle "b1" product with "s1" as option.
4. Set bundle "b1" Stock Status" = "Out of Stock".
5. Navigate to storefront http://domain/b1.html.

### Expected result
1. Bundle product should be Out of Stock.

### Actual result
1. Bundle product shows up as In Stock.

**Comment by AleksLi** [comment]
I've tried to reproduce this bug. I have some troubles with it. If I added only one product as an option in for "b1" product on storefront product "b1" is  [out of stock](http://joxi.ru/krDLxDkIEvWZor). It becomes in stock only when I added 2 products as options for "b1" product.

**Comment by nmalevanec** [comment]
@AleksLi, thanks for reply. I've double checked this issue on current 2.3-develop, and I am able to reproduce it just with single option for bundle product. Here is my "b1" bundle in admin:

![image](https://user-images.githubusercontent.com/11520943/37900743-c7ab4134-30f7-11e8-811c-a6b089544fc6.png)

![image](https://user-images.githubusercontent.com/11520943/37900762-d6331448-30f7-11e8-9705-1a51c4af4b70.png)

And this is my "b1" on storefront:

![image](https://user-images.githubusercontent.com/11520943/37900913-4801f7f6-30f8-11e8-863b-8c08ec4ce4bb.png)

**Comment by naydav** [comment]
@josh-carter 
Will be fixed in scope of https://github.com/magento-engcom/msi/pull/805

**Comment by TomashKhamlai** [comment]
Checked. It is out of stock on Storefront now
