### ISSUE TITLE
Failed test on Jenkins Magento\Downloadable\Test\TestCase\CreateDownloadableProductEntityTest

### ISSUE THREAD

**Issue by StasKozar** [magento/inventory#741]
Failed CreateDownloadableProductEntityTest on Jenkins
Magento_Downloadable_Test_TestCase_CreateDownloadableProductEntityTest / Magento\Downloadable\Test\TestCase\CreateDownloadableProductEntityTest.test with data set "CreateDownloadableProductEntityTestVariation7_0"
 Stack Trace
Magento\Downloadable\Test\TestCase\CreateDownloadableProductEntityTest::test with data set "CreateDownloadableProductEntityTestVariation7_0" (CreateDownloadableProductEntityTestVariation7_0)
Control 'out of stock' is not visible.
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'out of stock'
+'in stock'

/var/www/html/dev/tests/functional/tests/app/Magento/Catalog/Test/Constraint/AssertProductOutOfStock.php:41
/var/www/html/dev/tests/functional/vendor/magento/mtf/Magento/Mtf/ObjectManager/Factory.php:57
/var/www/html/dev/tests/functional/vendor/magento/mtf/Magento/Mtf/ObjectManager.php:81
/var/www/html/dev/tests/functional/vendor/magento/mtf/Magento/Mtf/Constraint/AbstractConstraint.php:155
/var/www/html/dev/tests/functional/vendor/magento/mtf/Magento/Mtf/Constraint/Composite.php:109
/var/www/html/dev/tests/functional/vendor/magento/mtf/Magento/Mtf/TestCase/Injectable.php:231
/var/www/html/dev/tests/functional/vendor/magento/mtf/Magento/Mtf/TestCase/Functional.php:300
/var/www/html/dev/tests/functional/vendor/magento/mtf/Magento/Mtf/TestCase/Functional.php:217
/var/www/html/dev/tests/functional/vendor/magento/mtf/Magento/Mtf/TestCase/Injectable.php:210
/var/www/html/dev/tests/functional/vendor/magento/mtf/Magento/Mtf/TestCase/Injectable.php:166

**Comment by larsroettig** [comment]
@StasKozar can be close because it is merged ?

**Comment by StasKozar** [comment]
@larsroettig yes.
