### ISSUE TITLE
Failed to load resource: the server responded with a status of 400 during checkout with bundle product

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#744]
### Preconditions

1. Magento MSI
2. New stock with new source created
3. Simple product created and assigned to default stock with qty=100
4. Bundle product created with simple product as child and save
5. Set stock status "In stock" and save

### Steps to reproduce

1. Add bundle product to cart and proceed to checkout

### Expected result

1. Order placed correctly

### Actual result

1. [Screenshot, logs]On "Payment method" step: warning "Not all your products are available in the requested quantity" 
![bundle order_1](https://user-images.githubusercontent.com/27818516/37836576-7874a972-2ebb-11e8-8cf1-65e51af0dce9.jpg)

**Comment by larsroettig** [comment]
Problem is in **checkItemsQuantity** function i will check it and build a fix for it
`\Magento\InventorySales\Plugin\CatalogInventory\StockManagement\ProcessRegisterProductsSalePlugin::checkItemsQuantity
`

Currently, I get 3 Errors from `$this->isProductSalableForRequestedQty->execute`
![phpstorm](https://user-images.githubusercontent.com/5289370/37864964-262fe6f2-2f76-11e8-8ea6-cbf34d1e87ed.png)

**Comment by larsroettig** [comment]
We should test this issue after we merge and finish:
https://github.com/magento-engcom/msi/pull/707
https://github.com/magento-engcom/msi/pull/692
