### ISSUE TITLE
 Integrity constraint violation: 1062 Duplicate entry

### ISSUE THREAD

**Issue by larsroettig** [magento/inventory#75]
### Preconditions
- Create two Sources
- Assign **SKU-1**  quantity to  **Source 1** -  5 quantity and **Status in Stock**
- Assign **SKU-1**  quantity to  **Source 2** -  5 quantity and **Status out of Stock**

### Steps to reproduce
- Try Save in the in fixtures or in the backend

### Expected result
Can save without error

### Actual result
<img width="2560" alt="savemultiple_php_-_magento2_-___volumes_webroot_www_magento2_" src="https://user-images.githubusercontent.com/5289370/30003755-cc54cb0e-90c2-11e7-8997-64b7c167409c.png">

#### In the Backend can **Status out of Stock** not saved. 
<img width="1314" alt="test___products___inventory___catalog___magento_admin" src="https://user-images.githubusercontent.com/5289370/30003887-42e547ba-90c5-11e7-8f37-127fe83ea980.png">

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'SKU-1' for key 'PRIMARY', query was: INSERT INTO `inventory_stock_item_stock_32_replica` (`sku`,`quantity`,`status`) VALUES (?, ?, ?), (?, ?, ?)
 /Volumes/webroot/www/magento2/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php:555

### With the following test case, it works fine!
Assign **SKU-1** quantity to **Source 1** - 5 quantity and **Status in Stock**
Assign **SKU-1** quantity to **Source 2** - 5 quantity and **Status in Stock**

**Comment by larsroettig** [comment]
With the following test case, it works fine!
Assign SKU-1 quantity to **Source 1** - 5 quantity and **Status in Stock**
Assign SKU-1 quantity to **Source 2** - 5 quantity and **Status in Stock**

**Comment by naydav** [comment]
Fixed after index refactoring
