### ISSUE TITLE
Skipped Integration Test (ActionTest) with wrong assigned ticket.

### ISSUE THREAD

**Issue by AleksLi** [magento/inventory#761]
\Magento\Catalog\Model\Product\ActionTest skipped with https://github.com/magento-engcom/msi/issues/385 as the referenced ticket.

### Steps to Reproduce
1. Remove ```$this->markTestSkipped('https://github.com/magento-engcom/msi/issues/385');``` this string.
2. \Magento\Catalog\Model\Product\ActionTest::testUpdateAttributes() - run this test. 

**_It failed. It joins wrong tables. Other developer works on it right now._**

**Comment by ishakhsuvarov** [comment]
Test is not skipped anymore. Closing
