### ISSUE TITLE
Apply PHP 7.1 syntax for all MSI interfaces being released 

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#784]
Since we've removed 7.0 agents on Travis, and left just agents with PHP 7.1 onboard 
we can apply PHP 7.1 syntax for all the existing interfaces we currently have in MSI

Next features could be applied

- nullable types
- void return types for functions (good from CQRS code)
- Class constant visibility  (private accessor for constants)
- Multi-catch exception handling

**Comment by vrann** [comment]
- pdepend issue
- issue with pluginization of the function which return void -- drop support php 7.0 will help; issue is fixed in php 7.2 track so we don't do implementation form MSI side
