### ISSUE TITLE
Configurable product isn't visible on frontend on Default Stock and Default Source

### ISSUE THREAD

**Issue by RomaKis** [magento/inventory#785]
### Preconditions
1. Install M2 with MSI
2. Create configurable product "Configurable 1" with children in stock.
3. Assign configurable to "Category 1"

### Steps to reproduce
1. Navigate on frontend to "Category 1".

### Expected result
1. Product "Configurable 1" is visible on category page.

### Actual result

1. Product "Configurable 1" is  NOT visible on category page.

Seem like there are several problems. I call proceed() instead of MSI realization in next plugins :
1. `InventoryCatalog/Plugin/CatalogInventory/Model/ResourceModel/Stock/Status/AdaptAddStockDataToCollectionPlugin` . 
2. `Magento/InventoryCatalogSearch/Plugin/Model/Adapter/Mysql/Aggregation/DataProvider/SelectBuilderForAttribute/AdaptApplyStockConditionToSelectPlugin`
3.`Magento/InventoryCatalogSearch/Plugin/Search/FilterMapper/AdaptStockStatusFilterPlugin`

And then "Configurable 1" is visible on category page. Not sure if problems are in all 3 plugins. Need to investigate.

**Comment by vadimjustus** [comment]
Issue can not be reproduced and seems to be out dated...
