### ISSUE TITLE
Simple product displayed on category page as "In stock" after all salable qty have been bought

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#786]
### Preconditions

1. Magento MSI
2. New stock with new source created
3. Simple product created with qty 10 on default source

### Steps to reproduce

1. Verify your simple product presents on category page and has status "In stock"
2. Place order with your simple product with qty = 10
3. Open your category again

### Expected result

1. Your simple product have to disappear from the category page

### Actual result

1. Simple product still displayed on category page

**Comment by p-bystritsky** [comment]
Already fixed in https://github.com/magento-engcom/msi/blob/2.3-develop/app/code/Magento/InventoryCatalog/Plugin/InventoryApi/SetDataToLegacyCatalogInventoryAtSourceItemsSavePlugin.php#L94-L104

**Comment by smoskaluk** [comment]
Bug is still present on mainline

**Comment by maghamed** [comment]
this is desirable behaviour
