### ISSUE TITLE
"Disassociated Products" configurable grid doesn't show information correctly

### ISSUE THREAD

**Issue by RomaKis** [magento/inventory#787]
### Preconditions
1. Isntall M2 with MSI.
2.  Create one new source "Source eu".
3.  Create one new stock "Stock eu" and assing "Source eu" to it.

### Steps to reproduce
1.  Go to admin panel.
2.  Go to configurable product creation page.
3. Create configurable product with two configuration. 
4. Save configurable product.
5. Try to edit configuration and check only one value for attribute. 
6. Go to "Step 4: Summary".

### Expected result

1. "Disassociated Products" grid show information correctly

### Actual result

1. "Disassociated Products" grid missed information about "Quantity Per Source"
![image](https://user-images.githubusercontent.com/17450979/38027609-ecebf9c8-3298-11e8-9794-f655b305e5bf.png)

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/802
