### ISSUE TITLE
Can not create order with bundle product on storefront.

### ISSUE THREAD

**Issue by nmalevanec** [magento/inventory#790]
### Preconditions
1. Magento 2.3 with MSI.
2. Clean installation, no additional sources or stocks.

### Steps to reproduce
1. Login to admin area.
2. Create simple product "s1" with qty = 100.
3. Create bundle product "b1" with "s1" product as an option.
4. Navigate to storefront http://domain/b1.html
5. Press "Customize and Add to Cart" button.
6. Press "Add to Cart" button with qty = 1.
7. Proceed to checkout and place order.

### Expected result
1. Order successfully created.

### Actual result
1. 'Not all of your products are available in the requested quantity.' message appears,
2. Order not created.

### Additional info
If enable backorders, you can buy bundle. But after first purchase it becomes out of stock with negative qty.

Probably we should call the standard behaviour in Magento/InventorySales/Plugin/CatalogInventory/StockManagement/ProcessRegisterProductsSalePlugin::aroundRegisterProductSale() in case of product type is bundle(or any other, which currently not supported)

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/805
