### ISSUE TITLE
Incorrect salable quantity calculation

### ISSUE THREAD

**Issue by p-bystritsky** [magento/inventory#791]
### Preconditions

1. Magento in Single-Stock mode.

### Steps to reproduce

1. Create Simple, Downloadable or Virtual Product with quantity 10.
2. Order 1 Product.
3. Add to Cart 1 Product.
4. Update Product quantity in Cart to 9.

### Expected result

9 Products in Cart.

### Actual result

Error message appears.

### Note
This is caused by incorrect  Salable Quantity calculation - it should not account Product in Cart.

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/807
