### ISSUE TITLE
Order cancellation works incorrect.

### ISSUE THREAD

**Issue by p-bystritsky** [magento/inventory#792]
### Preconditions

1. Magento in Single-Stock mode.

### Steps to reproduce

1. Create Simple, Downloadable or Virtual Product with quantity 10
2. Order 10 Product.
3. Cancel Order.

### Expected result

10 Products are available on sale.

### Actual result

Product is Out of Stock.

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/807
