### ISSUE TITLE
Incorrect process of Out-of-Stock Threshold.

### ISSUE THREAD

**Issue by p-bystritsky** [magento/inventory#793]
### Preconditions

1. Magento in Single-Stock mode.

### Steps to reproduce

1. Create Simple, Downloadable or Virtual Product with quantity 10.
2. Set Out-of-Stock Threshold of created Product to 10.
3. Visit Product's page on storefront.

### Expected result

Product is Out of Stock.

### Actual result

Product is In Stock.

**Comment by smoskaluk** [comment]
@RomaKis Still reproducing for simple product after full reindex and flushing cache

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/1077
