### ISSUE TITLE
[BUG][CATALOG->Products] On the Products grid page, in the "Quantity" column, it displays [object Object] when you use Advanced Inventory.

### ISSUE THREAD

**Issue by ivy00johns** [magento/inventory#808]
![image.png](https://images.zenhubusercontent.com/5a679b134b5806bc2bc400ab/f5890350-b90e-48f4-b018-a4ca824b5297)

**Comment by naydav** [comment]
already fixed in current develop branch (`2.3-develop`)

**Comment by ivy00johns** [comment]
Verified bug was fixed.
