### ISSUE TITLE
[CATALOG->Products] Adding a Configurable Product in MSI causes an error to appear on page upon "Saving".

### ISSUE THREAD

**Issue by ivy00johns** [magento/inventory#809]
![image.png](https://images.zenhubusercontent.com/5a679b134b5806bc2bc400ab/dfd26c7e-e15f-4a8c-a95d-6337d6d44e36)

**Comment by naydav** [comment]
already fixed in current develop branch (`2.3-develop`)

**Comment by ivy00johns** [comment]
Verified the bug was fixed.
