### ISSUE TITLE
php bin/magento setup:upgrade command throw exception

### ISSUE THREAD

**Issue by RomaKis** [magento/inventory#814]
### Preconditions
1. Install M2 with MSI.

### Steps to reproduce
1. Run `php bin/magento setup:upgrade`.

### Expected result

1.  No errors.

### Actual result
1. Notice: Undefined index: Create Table in /home/roma/Desktop/dev.msi.com/lib/internal/Magento/Framework/Setup/Declaration/Schema/Db/MySQL/Definition/Constraints/ForeignKey.php on line 75

Seems like 
` $createMySQL = $data['Create Table'] ?? $data['Create View'];` will resolve this issue.

**Comment by aleron75** [comment]
![screenshot from 2018-04-16 11-14-43](https://user-images.githubusercontent.com/1199894/38800536-d58f2bf0-4167-11e8-9452-195db6791814.png)

Had the same issue today while trying to do a fresh install, the attached screen shot is from a debug session that makes it clear the origin of the problem, that is: we have a `Create View` index but the `fromDefinition()` method searches for a `Create Table` index.

Hope it helps.

**Comment by aleron75** [comment]
I confirm that this worked for me:

`$createMySQL = $data['Create Table'] ?? $data['Create View'];`

**Comment by aleron75** [comment]
Sorry, just seen that this was fixed in PR #821 but I don't get whiy this was not in `2.3-develop` branch /cc @ishakhsuvarov

**Comment by ishakhsuvarov** [comment]
@aleron75 magento/magento2#14507 (which is equal to magento-engcom/msi#821) was never merged into `2.3-develop`. It was closed due to incorrect PR base. Feel free to resubmit correctly.
Thanks

**Comment by aleron75** [comment]
submitted PR #927 - waiting for CI suite to finish running /cc @ishakhsuvarov
