### ISSUE TITLE
[BUG][STOCK] When you go to the "STORES->Manage Stocks" the grid no longer displays. Instead it displays the message "No such entity.".

### ISSUE THREAD

**Issue by ivy00johns** [magento/inventory#815]
![image.png](https://images.zenhubusercontent.com/5a679b134b5806bc2bc400ab/e87807f1-8393-4de8-afc2-3191ce42df20)

**Comment by ivy00johns** [comment]
Rebuilt my store and the error went away.

**Comment by ivy00johns** [comment]
I rebuilt my Vagrant box twice now (./init_project -fc) and the error remains.

**Comment by naydav** [comment]
Pls, provide all of steps from the test
We will repeat these steps manually

**Comment by ivy00johns** [comment]
I spent most of yesterday working on this issue. I've isolated the Tests that I believe are causing the issue, but I still don't have the steps to manually replicate it. I will post them once I have them.

**Comment by ivy00johns** [comment]
I finally discovered the way to replicate this issue. 

1. Go to "STORES" => "All Stores".
2. Click on "Create Website".
3. Enter the following details:
     - Name: Basic MSI Website 1 5ac4e6eab36ab
     - Code: basic_msi_website_1_5ac4e6eab36a
4. Click on "Save Web Site".
5. Go to "STORES" => "Manage Stocks".
6. Note the message "No such entity" is present.

**Comment by ivy00johns** [comment]
Apparently the website field has a character limit (<32 chars) but no field validation. I will modify the Tests to input valid strings. But we should add field validation and a character limit to this field like other key fields in the UI.
