### ISSUE TITLE
"Not all your products are available in the requested quantity" on payment step during checkout with configurable product

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#823]
### Preconditions

1. Magento MSI
2. New stock with new source created

### Steps to reproduce

1. Configurable product created and assigned to default source
2. Add configurable product to the cart and proceed to checkout

### Expected result

1. Order placed correctly

### Actual result

1. On "Payment method" step: warning "Not all your products are available in the requested quantity"

![image](https://user-images.githubusercontent.com/27818516/38193465-dcbd9b2a-367a-11e8-8ed1-0d4fb48aa02c.png)

**Comment by maghamed** [comment]
Fixed in the scope of #790 

@smoskaluk please verify and close current issue
