### ISSUE TITLE
Search in Low Stock Report grid is broken 

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#824]
### Preconditions

1. Magento MSI
2. Simple product with Qty 1 and Notify Qty 2 on Default source

### Steps to reproduce

1. Open Low Stock Report
2. Try  to use search in the grid, eg. select "default" in "source code" column  

### Expected result

1. Search should work properly

### Actual result

1. Grid dissapeared and no search result displayed

![image](https://user-images.githubusercontent.com/27818516/38196402-917439ec-368b-11e8-80e5-c8b19f50d940.png)

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/840
