### ISSUE TITLE
Wrong quantity of simple product in single stock mode after placing order with it

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#826]
### Preconditions

1. Magento MSI single stock mode
2. Simple product "sku1" created with Quantity = 10

### Steps to reproduce

1. Place order with "sku1" qty =10
2. Open "sku1" product page in admin  

### Expected result

1. Quantity should be = 0

### Actual result

1. Quantity still = 10

**Comment by RomaKis** [comment]
This issue inn't actual. Qty should decrease only after shipment creation.
