### ISSUE TITLE
There is no verification of qty to deduct during shipment submitting 

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#827]
### Preconditions

1. Magento MSI
2. New stock with new source created
3. Simple product "sim1" created with Qty = 100 on default source

### Steps to reproduce

1. Place order with "sim1" with qty = 1
2. Open your order in admin and click "Ship"
3. In shipment go to "Items to ship" field and click "Add manually"
4. Set in "Qty To Deduct" = 100 and submit shipment

### Expected result

1. It should not be allowed to deduct more items then ordered

### Actual result

1. Go to product "sim1" page in admin and verify Qty on default source - 100 items deducted from the  source

**Comment by maghamed** [comment]
Need to verify this behaviour on PR - https://github.com/magento-engcom/msi/pull/788

**Comment by TomashKhamlai** [comment]
@maghamed, it is not reproducible on 2.3-develop neither on 430-Source_Deduction that was locally merged to 2.3-develop.
Tested Magento EE from magento-engcom on MSI branch.

**Comment by TomashKhamlai** [comment]
It doesn't allow you to deduct more items then ordered according to order information.
![order](https://user-images.githubusercontent.com/11827230/38425726-5506f550-39bd-11e8-947b-b49ced97f9cb.png)

The whole amount of the products is deducted according to inventory information.
![inventory](https://user-images.githubusercontent.com/11827230/38425701-4291b752-39bd-11e8-8f93-c598de189712.png)

So yes, it is still reproducible, but I saw the step in the actual result when it was too late.

**Comment by p-bystritsky** [comment]
Not reproducible on current dev-branch.
