### ISSUE TITLE
Inventory index (MSI) invalidated after shipment created

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#828]
### Preconditions

1. Magento MSI
2. New stock with new source created
3. Simple product "sim1" created with Qty = 100 on default source

### Steps to reproduce

1. Place order with "sim1" 
2. Create and submit shipment
3. Go to System -> Index Management

### Expected result

1. All indexes should be validated

### Actual result

1. Inventory index (MSI) invalidated

**Comment by p-bystritsky** [comment]
Cannot reproduce.
