### ISSUE TITLE
Merchant should see the salable qty for product in single source mode.

### ISSUE THREAD

**Issue by RomaKis** [magento/inventory#836]
### Preconditions

1. Magento MSI single stock mode
2. Simple product "sku1" created with Quantity = 10

### Steps to reproduce

1. Place order with "sku1" qty =10
2. Open "sku1" product page in admin  

### Expected result

1. Quantity still = 10, but salable qty should be visible as 0.

### Actual result

1. Quantity still = 10. There is no salable qty information for a product.

**Comment by RomaKis** [comment]
After discussion with @mbrinton01 decided to show the same tab "Salable quantity" as is shown on multi source mode.

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/865
