### ISSUE TITLE
[BUG][STOCK] On the "Manage Stock" page using Mass Delete on a filtered list of Stocks delete all of the Stocks on the page, instead of the selected Stock.

### ISSUE THREAD

**Issue by ivy00johns** [magento/inventory#844]
*_Pre-reqs_*
* You need to have a few Stocks in your DB before you can replicate this bug.

*_Video_*
https://www.screencast.com/t/MH266llkNJHf

*_Steps_*
1. Click on "Filters".
2. Enter the 'Name' of a particular Stock.
3. Click on "Apply Filters".
4. You should have a single result in the grid.
5. Check the checkbox for the single Stock.
6. Click on "Actions".
7. Select "Delete".
8. Click on "Ok".
9. You should see the following error:
    * ![image.png](https://images.zenhubusercontent.com/5a679b134b5806bc2bc400ab/8da79bb4-d547-48d1-b7f0-2eb9f62eb97c)
10. Click on "Clear All" to clear the Active Filters.
11. Note that the "Default Stock" is the only Stock in the list.

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/864
