### ISSUE TITLE
Associated Product popup is not opened when you want to add simple product to the configurables

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/inventory#851]
### Preconditions

1. Stores > Configuration > Catalog > Inventory > Stock Options > Display Out Of Stock Products = Yes.
2. Product attribute:
 - > Default Label: **attribute1**
 - > Type: **Dropdown**
 - > Options: **option1**
 - > Scope: **Global**
3. Assign **attribute1** to **Default** attribute set.
4. Simple product with **Stock Status = Out Of Stock** and **attribute1 = option1** created.

### Steps to reproduce

1. Log in as an admin user.
2. Navigate to the Products > Inventory > Catalog
3. Click **Add Product** dropdown and select a **configurable** product type
4. Fill out all required fields
 - > Name: **configurable1**
 - > SKU: **configurable1**
 - > Price: $10
5. Enter category name in 'Categories' suggest and press 'New Category' button
 - > Category Name: cat1
 - > Parent Category: Default Category
6. Click "Create Category" button in 'Create Category' popup
7. Click 'Create Configurations' button in 'Configurations' section
8. Click 'Next' button in the wizard to select attribute values/options
9. Click "Select All" link to check checkboxes to every option, press "Next" button two times
10. Click 'Generate Products' button
11. At "Current Variations" grid check Display checkboxes and fill data with values from Test Data
 - > Quantity: 100 for option
12. In Configuration > Current Variations Grid choose in Actions > Select > Choose a different Product

### Expected result
:heavy_check_mark: Select Associated Product popup is opened.

### Actual result
:x: 'Something went wrong' message appeared

![image](https://user-images.githubusercontent.com/27818516/38362725-8f3318d2-38da-11e8-8b6b-5b7d75075303.png)

**Comment by RomaKis** [comment]
@vadimjustus, hi. Seems like problem is `Magento/InventoryCatalog/Ui/DataProvider/Product/Listing/Modifier/QuantityPerSource`. It is called on product greed and in product edit page when try to load associated products. And it leads to error :)

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/973
