### ISSUE TITLE
Salable Quantity column has 0 value for all of the products in the grid after they were imported 

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/inventory#855]
### Preconditions
1. Magento 2.3 with MSI. 
2. Create additional source and stock
3. Create sevral products different type with Qty on both sources

### Steps to reproduce
1. Export all the products to .csv file
2. Delete all products with mass action
3. Perform full reindex
4. Perform import with Add/Update action
5. Navigate to Catalog > Products

### Expected result
1. Products are present in the grid as they were before Step 2

### Actual result
1. Salable Quantity column has 0 value for all of the products.

![image](https://user-images.githubusercontent.com/27818516/38375720-8ae5b468-38ff-11e8-9101-e50b7d3af21e.png)

**Comment by maghamed** [comment]
@TomashKhamlai  what's the status of Inventory index?

**Comment by naydav** [comment]
Looks like index was not run
