### ISSUE TITLE
Product grid mass inventory actions

### ISSUE THREAD

**Issue by mbrinton01** [magento/inventory#863]
As a **merchant** I want to **assign and unassign products to/from sources in bulk** so that **I can manage my inventory across sources without having to edit each product individually**.

As a **merchant** I want to **transfer inventory quantity between sources in bulk** so that **I can manage my inventory across sources without having to edit each product individually**.

**Background:**
With the introduction of MSI, merchants have the ability to create multiple sources and assign products to these sources. From the admin panel, merchants can assign a product to one or more sources from the product detail page. However, there is no way to assign or unassign multiple products at one time in the admin panel. Also, if a merchant migrates from an earlier (pre-MSI) version of Magento, all of their products and inventory quantity will be migrated to the Default source. After they have created one or more new additional sources, they need a way to transfer inventory from one source to another.

**Approach for Assign/Unassign of Products to Sources**
The current Product grid (under `Catalog->Products`) allows merchant admin users to select more than one product and then perform bulk actions on the selected products. For example, products can be deleted, their status can be modified, or their attributes can be updated. This feature is powerful because it allows merchants to select only the products they want to update using filters, and then update all the selected products in a single action. For assignment and unassignment of products to sources, new options should be added to the existing `Actions` drop-down above the products grid:
* Assign to Source
  * This option is used to assign all of the selected products to a specified source. After 'Assign to Source' is selected, the user must be prompted for the name of the Source they want to assign using a drop-down list of available sources
  * This action assigns each product selected to the specified source. It does not create or adjust any quantity for the selected source.
* Unassign from Source
  * This option is used to unassign all of the selected products from a specified source. After 'Unassign from Source' is selected, the user must be prompted for the name of the Source they want to unassign from using a drop-down list of available sources
  * This action unassigns each product selected from the specified source. As a result of this action, any existing inventory quantity for the product+source combination will be lost

**Approach for Transferring Inventory between Sources**
To allow for transferring inventory between sources, a new option should be added to the existing `Actions` drop-down above the products grid:
* Transfer Inventory
  * This option is used to transfer some or all of the inventory from the selected products to a specified source. After 'Transfer Inventory' is selected, the user must be prompted for the name of the Source they want to transfer inventory quantity to using a drop-down list of available sources.
  * A second option is also presented to the user: 'From Default Source Only'. This option should be a checkbox.
  * If the 'From Default Source Only' option is NOT selected, all inventory quantity (aggregate across all sources for each product) for each selected product should be assigned to the specified source. It should remain assigned to any existing sources, but the quantity should be zero to reflect the inventory transfer took place.
  * If the 'From Default Source Only' option is selected, all inventory quantity on the Default Source only for each selected product should be assigned to the specified source. It should remain assigned to any existing sources. The quantity on the Default Source should be zero to reflect the inventory transfer took place.
  
**Acceptance Criteria:**
* For Assign to Source
  * One or more selected products are assigned to Source specified by user
  * Any existing Source assignments are not changed
  * Any existing inventory quantity is not changed
* For Unassign from Source
  * One or more selected products are unassigned from the Source specified by user
  * If any inventory quantity exists for the selected product+source combination, this quantity is lost as a result (the product is no longer assigned)
  * Any existing Source assignments other than the specified Source are not changed
  * Any existing inventory quantity other than on the specified Source is not changed
* For Transfer Inventory
  * One or more selected products are assigned to Source specified by user
  * If 'From Default Source Only' option is NOT selected, aggregate inventory quantity across all Sources for each selected product is assigned to Source specified by user
  * If 'From Default Source Only' option is NOT selected, selected products are not unassigned from any Sources
  * If 'From Default Source Only' option is NOT selected, quantity on all sources other than specified Source is set to 0 value for each selected Product
  * If 'From Default Source Only' option is selected, inventory quantity on Default Source only for each selected product is assigned to Source specified by user
  * If 'From Default Source Only' option is selected, selected products are not unassigned from any Sources
  * If 'From Default Source Only' option is selected, quantity on Default Source is set to 0 value for each selected product
* After completing any action, user receives same prompt as other existing actions
  * Example: `A total of x record(s) were updated.` for successful actions
* Feature is documented in Merchant documentation
  
**What to Demo:**
* MSI Enabled
* Multiple Sources created and products assigned
* Select multiple products from grid
* Run 'Assign to Source' action
  * Selected products are assigned to specified Source
  * User views success message with number of products updated
* Run 'Unassign from Source' action
  * Selected products are unassigned from specified Source
  * User views success message with number of products updated
* Run 'Transfer Inventory' action with 'From Default Source Only' NOT selected
  * Aggregate inventory from selected products is assigned and set for specified Source
  * User views success message with number of products updated
* Run 'Transfer Inventory' action with 'From Default Source Only' selected
  * Inventory from Default Source only is assigned and set for specified Source

**Comment by phoenix128** [comment]
Currently working on: https://github.com/magento-engcom/msi/tree/issue-863-mass-actions
