### ISSUE TITLE
Validation for URL key doesn't work and this leads to HTTP ERROR 500

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/inventory#868]
### Preconditions
1. Go to Stores > Manage Sources and add new source
 - > Name: new
 - > Code: new
 - > Country: United States
 - >  State/Province: California
 - >  Postcode: 90230
 2. Go to Stores > Manage Stocks
 3. Add new stock and assign source
 4. Reindex and flush cache
 5. Create simple product and assign it at least to one source
  - > Name: simple1
  - > Sku: simple1
  - > Qty: 100
  - > Category: cat1

### Steps to reproduce
1. Create simple product and assign it at least to one source
  - > Name: simple1
  - > Sku: simple1
  - > Qty: 100
  - > Category: cat1

### Expected result
:heavy_check_mark: The value specified in the URL Key field would generate a URL that already exists. To resolve this conflict, you can either change the value of the URL Key field (located in the Search Engine Optimization section) to a unique value, or change the Request Path fields in all locations listed below:
- simple1.html

### Actual result
:x: HTTP ERROR 500

Fatal error: Method Magento\Ui\TemplateEngine\Xhtml\Result::__toString() must not throw an exception, caught TypeError: Argument 2 passed to Magento\InventoryLowQuantityNotification\Model\SourceItemConfiguration\Command\Get::execute() must be of the type string, null given, called in /var/www/html/pr/app/code/Magento/InventoryLowQuantityNotification/Ui/DataProvider/Product/Form/Modifier/SourceItemConfiguration.php on line 95 in /var/www/html/pr/app/code/Magento/Ui/Component/Wrapper/UiComponent.php on line 0

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/870
