### ISSUE TITLE
API Access

### ISSUE THREAD

**Issue by duselton** [magento/inventory#872]
Trying to get swagger to show the API endpoint information for these features. We see three endpoints. We created an API user, took the token and put in swagger, but it throws an error.

### Preconditions

Magento Developer 2.3
1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

{"messages":["attribute  is not of type `object`"],"schemaValidationMessages":[{"level":"error","domain":"validation","keyword":"type","message":"instance type (string) does not match any allowed primitive type (allowed: [\"object\"])","schema":{"loadingURI":"#","pointer":""},"instance":{"pointer":""}}]}

1. [Screenshot, logs]

**Comment by maghamed** [comment]
thanks for bug report @duselton , we are going to finalize Web API endpoints shortly.

**Comment by smoskaluk** [comment]
@duselton Can't reproduce this issue. Please check if you use PHP 7.1
