### ISSUE TITLE
Make Stock Name field unique.

### ISSUE THREAD

**Issue by p-bystritsky** [magento/inventory#876]
Now multiple stocks with the same name can be created. This field should be unique.

**Comment by vrann** [comment]
@mbrinton01 from business perspective unlike product coming from different sources, stocks  tends less to have same names and it will be confusing to have them with the same name. There are fewer stocks, all input by same merchant from their data. No business reason to allow it

**Comment by mbrinton01** [comment]
Agree, there is not a valid business use case for having multiple stocks with the same name. It must be unique.
