### ISSUE TITLE
Notify Quantity applied to Product in Advanced Inventory on Product page in Admin doesn't work

### ISSUE THREAD

**Issue by RomaKis** [magento/inventory#878]
### Preconditions
1. M2 with MSI.
2. Create new source.
3. Create simple or virtual product and assign it to created source.

### Steps to reproduce:
1. Open created product.
2. Click button "Advanced Inventory".
3. Set in 'Notify for Quantity Below' field = 5.
4. Click button "Done".
5. Click button "Save" .
6. Go to 'Assigned Sources' tab.
7. In the 'Assigned Sources' grid click on check-box for 'Notify Quantity Use Default' for created source.

**Expected result:**
Notify Quantity for created source = 5.

**Actual result:** 
Notify Quantity for created source = 1.

**Comment by naydav** [comment]
`Notify Quantity` and  `Notify Quantity Use default` became per Source configuration option
1) Single source mode
UI should not be changed. Value is saved for Default Source

2) Multi Source mode
Fields in advanced inventory tab should be removed

Need to have save behaviour like as for `qty` and `in_stock` fields

**Comment by RomaKis** [comment]
@naydav, what does it mean
```
Single source mode
UI should not be changed. Value is saved for Default Source
```
?

1. Value is saved in `inventory_low_stock_notification_configuration` table.
2. Default behavior is used.
