### ISSUE TITLE
"Out-of-Stock Threshold" works incorrectly in Advanced Inventory

### ISSUE THREAD

**Issue by p-bystritsky** [magento/inventory#880]
### Preconditions

1. Magento in Single or Multistock mode.
2. Some Category visible on the Storefront.

### Steps to reproduce

1. Create a Product, assign it to Category.
2. Set some it's Quantity to 100.
3. Make sure Product is visible in Category on the Storefront.
4. Open Product's Advanced Inventory.
5. Set "Out-of-Stock Threshold" to 100.
6. Make sure Product is not visible in Category on the Storefront.
7. Open Product's Advanced Inventory.
8. Set "Out-of-Stock Threshold" to 99.

### Expected result
 Product is visible in Category on the Storefront.

### Actual result
 Product is not visible in Category on the Storefront.

**Comment by RomaKis** [comment]
This issue is caused by cache. Seems like it will be fix in https://github.com/magento-engcom/msi/pull/835. Need to retest after PR will be merged.
