### ISSUE TITLE
During creating shipment Fatal error: Uncaught TypeError: 

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#882]
### Preconditions

1.Magento MSI
2. New stock with new source and Main Website assigned
3. Simple product created and assigned to new source

### Steps to reproduce

1. Place order with simple product
2. Create shipment for this order 

### Expected result

1. Shipment created

### Actual result

1. Fatal error: Uncaught TypeError: Return value of Magento\InventoryShipping\Model\SourceDeduction\SourceDeductionService::execute() must be an instance of Magento\InventoryShipping\Model\SourceDeduction\void, none returned in /var/www/html/magento2ce/reg/app/code/Magento/InventoryShipping/Model/SourceDeduction/SourceDeductionService.php:113 Stack trace: #0 /var/www/html/magento2ce/reg/app/code/Magento/InventoryShipping/Observer/SourceDeductionProcessor.php(166): Magento\InventoryShipping\Model\SourceDeduction\SourceDeductionService->execute(Object(Magento\InventoryShipping\Model\SourceDeduction\Request\SourceDeductionRequest)) #1 /var/www/html/magento2ce/reg/lib/internal/Magento/Framework/Event/Invoker/InvokerDefault.php(72): Magento\InventoryShipping\Observer\SourceDeductionProcessor->execute(Object(Magento\Framework\Event\Observer)) #2 /var/www/html/magento2ce/reg/lib/internal/Magento/Framework/Event/Invoker/InvokerDefault.php(60): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\Invento in /var/www/html/magento2ce/reg/app/code/Magento/InventoryShipping/Model/SourceDeduction/SourceDeductionService.php on line 113

**Comment by maghamed** [comment]
@smoskaluk what PHP version are you on? `Void` PHP type is added since PHP 7.1 , I bet you are still on PHP 7.0

**Comment by smoskaluk** [comment]
Yes, you are right. But:
![image](https://user-images.githubusercontent.com/27818516/38599961-1ea693ba-3d6b-11e8-901d-8967ad2ff8a9.png)

**Comment by maghamed** [comment]
@smoskaluk  it was announced several months ago, that support pf PHP 7.0.* is dropped in Magento 2.3

requirements should be updated on the DevDocs.

Here is accurate article - https://community.magento.com/t5/Magento-DevBlog/From-PHP-7-0-to-PHP-7-2-in-Magento-2-3/ba-p/91371

**Comment by smoskaluk** [comment]
This what I mean - DevDocs should be updated
