### ISSUE TITLE
Exception is thrown if reindexation was not performed.

### ISSUE THREAD

**Issue by p-bystritsky** [magento/inventory#883]
### Steps to reproduce

1. Create New Stock, assign it to default Sales Channel.
2. "One or more indexers are invalid." message appears. Do not perform reindexation.
3. Create a Category visible on Storefront.
4. Visit Category page on Storefront.

### Expected result

Category page is opened.

### Actual result

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'msi.inventory_stock_2' doesn't exist

**Comment by maghamed** [comment]
We already have this bug created.

Expected behavior here is wrong - we can't generate Category page.
All we can do - is just to show "something went wrong" error message.
Because index table is not created.

**Comment by p-bystritsky** [comment]
@maghamed yes, we already have https://github.com/magento-engcom/msi/issues/743.
