### ISSUE TITLE
Need to move ReservationBuilderInterface to ReservationApi module

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#886]
Need to move interface `\Magento\InventoryReservations\Model\ReservationBuilderInterface`
into 
`Magento\InventoryReservationsApi\Api\ReservationBuilderInterface`

because now all the modules dependent on both InventoryReservations and InventoryReservationsApi which is wrong

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/944
