### ISSUE TITLE
Resolve dependency on Inventory Module because of reference to a resource for permission

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#887]
Resolve dependency on Inventory Module because of reference to a resource for permission
`const ADMIN_RESOURCE = 'Magento_Inventory::source';`

Currently, some modules, i.e. InventoryShipping dependent on both InventoryApi and Inventory because of this

Ideally, it should be just reference on InventoryApi

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/974
