### ISSUE TITLE
Notify for Qty below in Assigned sources grid not selected to use default configuration value for new created product

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#890]
### Preconditions

1. Magento MSI
2. New stock with new source created

### Steps to reproduce

1. Create simple product and assign it to new source
2. Go to Assigned Sources grid and varify if 'Use default for Notify Qty below' selected 

### Expected result

1. 'Use default for Notify Qty below' should be selected 

### Actual result

1. 'Use default for Notify Qty below' is not selected

**Comment by naydav** [comment]
@larsroettig 
Pay attention to this task
https://github.com/magento-engcom/msi/issues/1282
and this PR
https://github.com/magento-engcom/msi/pull/1352

Looks like it was the same problem
And we already have the fix
Need to check it

**Comment by bartekszymanski** [comment]
Checked it and seems to be fixed

**Comment by makkoff** [comment]
Can't reproduce this issue on magento 2.3 msi.
![Peek 2019-06-06 12-54](https://user-images.githubusercontent.com/49763551/59024379-77cf0180-885a-11e9-9dd0-5a8307ede323.gif)
