### ISSUE TITLE
Stock status title is visible on "Advanced Inventory" in multi source mode

### ISSUE THREAD

**Issue by RomaKis** [magento/inventory#891]
### Preconditions
1. M2 with MSI.
2. Create new source.

### Steps to reproduce

1. Go to creating simple product 
2. Stock status isn't visible on product edit page.
3. Press "Advanced Inventory"

### Expected result

1.  Stock status isn't visible  on Advanced Inventory page

### Actual result

1. [Screenshot, logs]
![image](https://user-images.githubusercontent.com/17450979/38674854-957d7dd4-3e5e-11e8-9702-86eda9d1c414.png)

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/914
