### ISSUE TITLE
No sorting in Source Items grid.

### ISSUE THREAD

**Issue by p-bystritsky** [magento/inventory#892]
### Preconditions

1. Create multiple Sources.
2. Create a Product.
3. Create multiple Source Items for the Product.

### Steps to reproduce

Source Items grid should be sorted somehow.

### Expected result

Source Items are in some order.

### Actual result
Source Items order seems to be random.
![index](https://user-images.githubusercontent.com/22593218/38675238-b71403e0-3e5f-11e8-8c06-3237131c92aa.png)

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/999
