### ISSUE TITLE
'Price drop' Product Alert for Grouped product and Bundle product is scheduled but not sent by email to the Customer

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/inventory#893]
### Preconditions
1. Execution of
```mysql
SELECT @@global.time_zone, @@session.time_zone;
```
returns:
```
+--------------------+---------------------+
| @@global.time_zone | @@session.time_zone |
+--------------------+---------------------+
| SYSTEM             | SYSTEM              |
+--------------------+---------------------+
1 row in set (0,00 sec)
```
2. Execution of
```bash
file /etc/localtime
```
returns:
```
symbolic link to /usr/share/zoneinfo/Europe/Kiev
```
3. Execution of
```bash
cat /etc/php/7.0/cli/php.ini | grep -i 'date.timezone'
```
returns:
```
; http://php.net/date.timezone
date.timezone = Europe/Kiev
```
4. Execution of
```bash
cat /etc/php/7.0/apache2/php.ini | grep -i 'date.timezone'
```
returns:
```
; http://php.net/date.timezone
date.timezone = Europe/Kiev
```
5. Stores > Settings > Configuration > General > General > Locale Options > Timezone is set to "Eastern European Standard Time (Europe/Kiev)"
6. Magento is in MultiStock mode but website is assigned to Default Stock
7. Customer is created and has access to emails.
8. Go to Catalog -> Products
9. Click button "Add Simple product"
 - > "Enable Product" = "Yes"
 - > Name = "Simple Product 1"
 - > Price = "10"
 - > Weight = "1"
 - > Category = "Category 1"
 - > "Default Source" in sources grid
 - > Qty for  "Default Source" = 100
 - > "Product in Websites" = "Main Website"
10. Click button "Save & Close"
11. Click button "Add Virtual product"
 - > "Enable Product" = "Yes"
 - > Name = "Virtual Product 1"
 - > Price = "10"
 - > Weight = "1"
 - > Category = "Category 1"
 - > "Default Source" in sources grid
 - > Qty for  "Default Source" = 100
 - > "Product in Websites" = "Main Website"
12. Click button "Save & Close"
13. Click button "Add Grouped product"
 - > "Enable Product" = "Yes"
 - > Name = "Grouped Product 1"
 - > Weight = "1"
 - > Category = "Category 1"
 - > "Product in Websites" = "Main Website"
 - > In "Grouped Products" Tab click button "Add Products to Group"
 - > Select "Simple product 1" and "Virtual product 1" in grid
 - > Click button "Add selected products"
 - > Set Default Quantity for both products = 2
14. Click button "Save & Close"
15. Click button "Add Bundle Product"
 - > "Enable Product" = "Yes"
 - > Name = "Bundle Product 1"
 - > Weight = "1"
 - > Category = "Category 1"
 - > "Product in Websites" = "Main Website"
 - > "Ship Bundle Items" = Together
16. In Bundle Item Tab click button 'Add option"
 - > "Option title" = option 1
 - > "Input type" = drop-down
17. Click button "Add products to option"
18. Select "Simple Product 1" on "Add Products to Option" page
19. Click button "Add selected products"
 - > "Default Quantity" for "Simple Product 1"  = 5
20. Click button "Save & Close"
21. Go to Stores -> Configuration -> Catalog -> Catalog -> Product Alerts
22. Set for "Allow Alert When Product Price Changes" = Yes
23. Click button "Save Config"
24. Go to Stores -> Configuration -> Catalog -> Catalog -> Product Alerts Run Settings
25. Adjust Start Time to be 10 minutes ahead of the current system time
26. Click button "Save Config"
27. Flush Cache

### Steps to reproduce
1. Open "Bundle Product 1" product page
2. Click on "Notify me when the price drops"
3. Verify success message "You saved the alert subscription."
4. Open "Grouped Product 1" product page
5. Click on "Notify me when the price drops"
6. Verify success message "You saved the alert subscription."
7. Go to Catalog -> Products
8. Edit Bundle Product 1
9. Go to "Product Alerts" tab
10. Verify in "Alert Price" grid present record of alert for the Customer
11. Go to Catalog -> Products
12. Edit Grouped Product 1
13. Go to "Product Alerts" tab
14. Verify in "Alert Price" grid present record of alert for the Customer
15. Go to Catalog -> Product
16. Edit Grouped Product 1
17. Change the price to be lower
18. Click button "Save"
19. Verify message "You saved the product."
20. Execute `php bin/magento cron:run`
21. Execute mysql -uroot -p123123q -e"select * from msi.cron_schedule where job_code like '%alert%';" where '123123q' is the password for MySQL root user and 'msi' is the Magento database
22. Verify that 'executed_at' and 'finished_at' has the NULL value and look what is set in 'scheduled_at'
23. Wait for the "scheduled_at" time to come
24. Execute `php bin/magento cron:run`

### Expected result
1. The Customer has an email about price drop (2 changes in one email)

### Actual result
1. The Customer has no an email about price drop about any of the products

**Comment by TomashKhamlai** [comment]
@vrann, it is reproducible on 2.3-develop from [magento-engcom/magento2ce](https://github.com/magento-engcom/magento2ce.git)

**Comment by maghamed** [comment]
Tomash, Please create corresponding bug in Magento Jira

**Comment by TomashKhamlai** [comment]
@maghamed, internal ticket [MAGETWO-90636](https://jira.corp.magento.com/browse/MAGETWO-90636) was created to address this issue.

There are also tickets that are related, however, they do not pay much attention to details:
test - [MAGETWO-31798](https://jira.corp.magento.com/browse/MAGETWO-31798)
bug - [MAGETWO-56359](https://jira.corp.magento.com/browse/MAGETWO-56359)
