### ISSUE TITLE
"Quantity" field is present on Configurable/Grouped/Bundle product creation page in multisource mode.

### ISSUE THREAD

**Issue by p-bystritsky** [magento/inventory#894]
### Steps to reproduce

1. Create Source.
2. Try to create Configurable/Grouped/Bundle product.

### Expected result

Field "Quantity" is absent in Product creation form.

### Actual result

Field "Quantity" is present in Product creation form (and is active for Configurable product).

**Comment by naydav** [comment]
It is not a bug
It is proper behaviour

We don't support Bundle and Grouped products for Multi Source (MVP)
