### ISSUE TITLE
Disabled "Advanced Inventory" button.

### ISSUE THREAD

**Issue by p-bystritsky** [magento/inventory#896]
### Steps to reproduce

1. Go to the product creation page.
2. Press "Advanced Inventory" button.
3. In modal window set "Manage Stock" to "No", press "Done".

### Expected result

1. "Advanced Inventory" button stays active.

### Actual result
1. "Advanced Inventory" button becomes disabled.

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/945
