### ISSUE TITLE
Separate UI and Business logic for Inventory Module

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#898]
Separate UI and Business logic for Inventory Module.
Create new module "InventoryAdminUi" and move all the presentation logic there

**Comment by AlexandrKozyr** [comment]
Issue is in progress. Branch 898_separate_ui_business_logic

**Comment by AlexandrKozyr** [comment]
@maghamed the issue has been done.
Changes:
1. created new module InventoryAdminUi
2. presentation logic from Inventory module has been moved to module InventoryAdminUi
3. removed redundant use initialization of \Magento\Framework\Exception\NotFoundException in 
msi/app/code/Magento/InventoryAdminUi/Controller/Adminhtml/Stock/Delete.php
4. refactored msi/app/code/Magento/InventoryAdminUi/Controller/Adminhtml/Stock/StockSourceLinkProcessor.php
dependency on classes changed to dependency on interface.
5. manually tested few positive scenarios for stock and source user interfaces (created few sources, created stocks with sources/deleted stocks);

Committed in branch 898_separate_ui_business_logic.

**Comment by AlexandrKozyr** [comment]
created pull request that solves this issue.
