### ISSUE TITLE
"Out of Stock" Configurable product displayed on Category page.

### ISSUE THREAD

**Issue by p-bystritsky** [magento/inventory#904]
### Steps to reproduce

1. Create custom Source.
2. Create custom Stock, assign Source to it, assign current Sales Channel.
3. Create Category visible on Storefront.
4. Create Configurable Product with 1 SubProduct, assign it to Category.
5. Make sure Configurable Product is visible on Storefront.
6. Disable SubProduct.
7. Open Category on Storefront.

### Expected result

1. Configurable Product is absent in Category.

### Actual result

1. Configurable Product is "Out of Stock", but visible in Category.

**Comment by maghamed** [comment]
#981

**Comment by maghamed** [comment]
Not an MSI bug, 
approved by @mbrinton01 

https://app.zenhub.com/workspace/o/magento-engcom/msi/issues/856#issuecomment-392030116
