### ISSUE TITLE
Fix Performance Degradation in StockItem Indexation

### ISSUE THREAD

**Issue by naydav** [magento/inventory#91]
Several improvements need to be done for current indexation mechanism. As currently, we have a performance issue which leads to the whole re-indexation when any changes in SourceItem Qty happened (which is wrong).

**1)** Currently `inventory_source_item` table is used in **mview** configuration.
https://github.com/magento-engcom/magento2/blob/develop/app/code/Magento/Inventory/etc/mview.xml#L11
And system observes for  `source_id` column.

But expected behavior should be an observation of `source_item_id` column. So our algorithm for `\Magento\Inventory\Indexer\StockItem\StockItem::executeList` should be like
1) Obtain list of `source_item_id`
2) Filter this list. We need to remove items which are related to disabled sources, and items with `out_of_stock` status
3) Get index data only for these SKU that are related to  `source_item_id` list after filtering
4) Update index data via `multiple insert on update`
Now our behavior (get stocks, after that get sources) looks is familiar to full reindex

**2)** Also we need to track changes in the `inventory_source_stock_link` table. In this case, we will work with `source_id` list. So maybe we need to create separate index processor which will be work with `source_id`.

**Comment by larsroettig** [comment]
Hi, I have some problems with implementation.

The first Problem is we can not have more than one view in **mview.xml**. 

```
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:Mview/etc/mview.xsd">
    <view id="inventory_stock_item" class="Magento\Inventory\Model\Indexer\StockItem\Mview\StockItemAction"
          group="indexer">
        <subscriptions>
            <table name="inventory_source_item" entity_column="source_item_id"/>
        </subscriptions>
    </view>
    <view id="inventory_stock_item" class="Magento\Inventory\Model\Indexer\StockItem\Mview\LinkAction" group="indexer">
        <subscriptions>
            <table name="inventory_source_stock_link" entity_column="source_id"/>
        </subscriptions>
    </view>
</config>
```

The sound Problem if I will implement two Indexer we need some abstract
indexer. But I don't like to get two indexers for the same index in the backend. 

**Solutions:**
- Allowed to implement two views in **mview.xml** 
- Implement the logic for reindexing by `source_item_id` as service class without own Indexer 

Info:
I think we can not remove the logic for `inventory_source_stock_link` invalidation
