### ISSUE TITLE
Cannot read property source_code of undefined

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/inventory#911]
### Preconditions
1. Magento in Multistock Mode
2. Magento CE MSI

### Steps to reproduce
1. Start creating Simple Product as usual
2. Click Add Sources and select all sources (two or more) and click Done
3. Press F12
4. Instead of specifying Qty for each source, click on remove icon in the Default Source row.

### Expected result
1. No error in the browser console

### Actual result
1. An error in the browser console (Google Chome)
![img_13042018_163023_0](https://user-images.githubusercontent.com/11827230/38737612-717a54c2-3f38-11e8-9103-8d06b221971a.png)

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/997
