### ISSUE TITLE
[Configuration-Sources] Pagination worked in Manage Sources grid - Admin user

### ISSUE THREAD

**Issue by ivy00johns** [magento/inventory#933]
1. Login to backend as admin
2. Go to Stores -> Manage Sources
3. Click button "Add New Source"
4. fill New Source data in General tab - Name, Code etc:
    * name = Test Source 1
    * code = test_source_1
5. Set your New Source "Is Enabled" = Yes
6. Fill all fields with data of your New Source in Contact Info tab
7. Fill in address data of your New Source in Address Data tab:
    * Country: United States
    * State/Province: California (CA)
    * City: Culver City
    * Street: 6161 West Centinela Avenue
    * Postсode: 90230
8. Set In "Carriers" tab "Use global Shipping configuration" to Yes
9. Click button "Save & close"
10. Confirmation message "The Source has been saved" appears
11. verify that data in all tabs is correct
12. Login to backend as admin
13. Go to Stores -> Manage Sources
14. Set up for the Manage Sources grid to display 20 rows per page
15. Verify that test sources 1-20  are displayed on page 1
16. click on page 2
17. verify that test sources 21-22 are displayed on page 2
18. click back on page 1
19. Verify that test sources 1-20  are displayed on page 1
20. Then Pagination worked correctly in Manage Sources grid

----

HipTest Original ID: 1408745

**Comment by ivy00johns** [comment]
Merged to Mainline.

**Comment by smoskaluk** [comment]
https://app.hiptest.com/projects/69435/test-plan/folders/409122/scenarios/1408745
