### ISSUE TITLE
Button "Back" from shipment page doesn't return to Source selection page

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#940]
### Preconditions

1. Create order with simple product with qty on 2 different sources on the same stock
2. 

### Steps to reproduce

1. Open order in admin and click "Ship"
2. On Source selection page select one source and click "Create shipment" 
3. On New shipment page click button "Back"

### Expected result

1. You should return to Source selection page

### Actual result

1. You return to Order edition page

**Comment by nmalevanec** [comment]
Will be fixed in magento-engcom/msi#948
