### ISSUE TITLE
On Source selection page not possible to create separate shipments for different products from different sources 

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#941]
Merchant not able to ship different products from different sources from one order

### Preconditions

1. Magento MSI
2. Create order with 2 simple products with inventory qty allocated on 2 different sources on the same stock

### Steps to reproduce

1. Open order in admin and click "Ship"
2. On Source selection page select source 1 and set for product 1 full qty to deduct, and for product 2 qty to deduct = 0 to be able to ship it from another source separatly 

### Expected result

1. You can separate shipments for each products

### Actual result

1. It is not allowed to set qty to deduct = 0

**Comment by seruymt** [comment]
Task #640 is no longer relevant
