### ISSUE TITLE
[Configuration-Stocks-Delete Stock] Stock deleted from Stock page by Admin user when it has no Sales Channel assigned

### ISSUE THREAD

**Issue by ivy00johns** [magento/inventory#949]
1. Login to backend as admin
2. Go to Stores -> Manage Stocks
3. Click button "Add New Stock"
4. Fill in field "Name" = "Test Stock 1"
5. Click button "Save & close"
6. Success message "The Stock have been saved" appeared
7. Login to backend as admin
8. Go to Stores -> Manage Stocks
9. Open Test Stock page to edit from the Manage Stock grid 
10. Click button "Delete" in the header
11. verify message "You deleted 1 Stock(s)." appeared
12. verify that Stock deleted from the Manage Stock grid
13. Then Stock succesfully deleted 

----

HipTest Original ID: 1413387

**Comment by smoskaluk** [comment]
https://app.hiptest.com/projects/69435/test-plan/folders/409602/scenarios/1413387
