### ISSUE TITLE
[Configuration-Stocks] Sources assigned to the Stock can be deleted by clicking trash icon by Admin user

### ISSUE THREAD

**Issue by ivy00johns** [magento/inventory#951]
1. Login to backend as admin
2. Go to Stores -> Manage Stocks
3. Click button "Add New Stock"
4. Fill in field "Name" = "Test Stock 1"
5. Click button "Save & close"
6. Success message "The Stock have been saved" appeared
7. Login to backend as admin
8. Go to Stores -> Manage Sources
9. Click button "Add New Source"
10. fill New Source data in General tab - Name, Code etc:
    * name = Test Source 1
    * code = test_source_1
11. Set your New Source "Is Enabled" = Yes
12. Fill all fields with data of your New Source in Contact Info tab
13. Fill in address data of your New Source in Address Data tab:
    * Country: United States
    * State/Province: California (CA)
    * City: Culver City
    * Street: 6161 West Centinela Avenue
    * Postсode: 90230
14. Set In "Carriers" tab "Use global Shipping configuration" to Yes
15. Click button "Save & close"
16. Confirmation message "The Source has been saved" appears
17. verify that data in all tabs is correct
18. Login to backend as admin
19. Go to Stores -> Manage Stocks
20. Open "Test Stock" from the Manage Stock grid
21. Click button "Assign Sources" In "Sources" Tab
22. modal window "Assign Sources" opened
23. Select  Sources to be assigned in the grid
    * name 1 = Test Source 1
    * name 2 = Test Source 2
    * name 3 = Test Source 3
    * name 4 = Test Source 4
24. Click button "Done"
25. Verify that selected Sources appeared in the "Assigned Sources" grid
26. Click button "Save & close"
27. Success message "The Stock have been saved" appeared
28. Login to backend as admin
29. Go to Stores -> Manage Stocks
30. Open "Test Stock" from the Manage Stock grid
31. verify that "Test Source 1", "Test Source 2", "Test Source 3", "Test Source 4" assigned to the stock
32. click trash icon for the "Test Source 2" 
33. verify that "Test Source 1", "Test Source 3", "Test Source 4" still present in the grid
34. verify that "Test Source 2" deleted from the grid
35. click button "Save & Continue"
36. verify that "Test Source 1", "Test Source 3", "Test Source 4" still present in the grid
37. verify that "Test Source 2" is absent in the grid
38. click trash icon for the "Test Source 1" 
39. verify that "Test Source 3", "Test Source 4" still present in the grid
40. verify that "Test Source 1" deleted from the grid
41. click button "Save & Continue"
42. verify that "Test Source 3", "Test Source 4" still present in the grid
43. verify that "Test Source 1" is absent in the grid
44. Then Sources assigned to the Stock deleted successfully by clicking trash icon in admin

----

HipTest Original ID: 1499556

**Comment by smoskaluk** [comment]
https://app.hiptest.com/projects/69435/test-plan/folders/409123/scenarios/1499556
