### ISSUE TITLE
Introduce new module InventoryCatalog

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#96]
In a sake of better modularity of Inventory Domain.
It's proposed to introduce new module InventoryCatalog

With typical structure to Magento 2 modules 

Read This Design for more details - https://github.com/magento-engcom/msi/wiki/The-Concept-of-Default-Source-and-Domain-Driven-Design

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/102
