### ISSUE TITLE
[Configuration-Catalog-Products-Configurable product] Manage Stock on Configuration page turned off in admin for Configurable Product on Test stock

### ISSUE THREAD

**Issue by ivy00johns** [magento/inventory#968]
1. Login to backend as admin
2. Go to Stores -> Manage Sources
3. Click button "Add New Source"
4. fill New Source data in General tab - Name, Code etc:
    * name = Test Source 1
    * code = test_source_1
5. Set your New Source "Is Enabled" = Yes
6. Fill all fields with data of your New Source in Contact Info tab
7. Fill in address data of your New Source in Address Data tab:
    * Country: United States
    * State/Province: California (CA)
    * City: Culver City
    * Street: 6161 West Centinela Avenue
    * Postсode: 90230
8. Set In "Carriers" tab "Use global Shipping configuration" to Yes
9. Click button "Save & close"
10. Confirmation message "The Source has been saved" appears
11. verify that data in all tabs is correct
12. Login to backend as admin
13. Go to Stores -> Manage Stocks
14. Click button "Add New Stock"
15. Fill in field "Name" = "Test Stock 1"
16. In "Sales Channels" Tab select website "Main Website"
17. Click button "Assign Sources" In "Sources" Tab
18. modal window "Assign Sources" opened
19. Select  "Test Source 1"  in sources list
20. Click button "Done"
21. Click button "Save & close"
22. Success message "The Stock have been saved" appeared
23. Login to backend as admin
24. Go to Catalog -> Categories
25. Select Default Category on Categories Tree
26. Click button "Add Subcategory"
27. set "Enable Category" to "Yes"
28. set "Include in Menu" to "Yes"
29. Fill in "Category Name" = "Category 1"
30. Click button "Save"
31. Success  message "You saved the category." appears
32. Verify that Category 1 appeared in Categories tree as subcategory of Default category. 33. Login to backend as admin
34. Go to Catalog -> Products
35. Click button "Add Configurable Product"
36. set "Enable Product" to "Yes"
37. fill Name = "Configurable Product 1"
38. set Price = "10"
39. set Weight = "1"
40. select Category = "Category 1"
41. Open "Content" tab
42. In "Decription" text field put text "Best product"
43. in "Product in Websites" tab  select "Main Website"
44. click button 'Create Configuration"
45. On page "Step 1" - Select attribute "color"
46. click button "Next"
47. On page "Step 2" create new values "Red" and 'Black" and check them in
48. click button "Next"
49. On page "Step 3" select "Apply single quantity to each SKUs"
50. click button "Assign Sources"
51. In Assign Sources grid select "Test Source 1" and click "Done"
52. Set Quantity for source = 100
53. click button "Next"
54. On page "Step 4" click button  "Generate Products"
55. click button "Save"
56. Success  message "You saved the product." appears
57. Verify that created variation products are present on "Configuration" tab
58. Login to backend as admin
59. Go to Catalog -> Products
60. Open "Configurable Product 1-red" page to edit
61. Go to "Assigned Sources" tab on product page
62. Set Stock status for "Test Source 1" as "Out of Stock"
63. Click button "Save & Close"
64. Open "Configurable Product 1-blue" page to edit
65. Go to "Assigned Sources" tab on product page
66. Set Stock status for "Test Source 1" as "Out of Stock"
67. Click button "Save & Close"
68. Verify that "Configurable Product 1" dissapeared from Category page on frontend
69. Go to Stores -> Configuration -> Catalog -> Inventory
70. In "Manage Stock Options" tab for "Manage Stock" function uncheck "Use system value" and set it to "No"
71. Click button "Done"
72. Click button "Save Config"
73. Verify message "You saved the configuration."
74. Run reindex and flush cache
75. Go to "Home page"
76. Verify that "Configurable Product 1" dissapeared from Category page

----

Original HipTest ID: 1551168

**Comment by smoskaluk** [comment]
https://app.hiptest.com/projects/69435/test-plan/folders/457025/scenarios/1551168

**Comment by ivy00johns** [comment]
Merged to Mainline.
