### ISSUE TITLE
[Configuration-Catalog-Products-Configurable product] Manage Stock on Configuration page turned off in admin for Configurable Product on Default stock

### ISSUE THREAD

**Issue by ivy00johns** [magento/inventory#969]
1. Login to backend as admin
2. Go to Stores -> Manage Sources
3. Click button "Add New Source"
4. fill New Source data in General tab - Name, Code etc:
    * name = Test Source 1
    * code = test_source_1
5. Set your New Source "Is Enabled" = Yes
6. Fill all fields with data of your New Source in Contact Info tab
7. Fill in address data of your New Source in Address Data tab:
    * Country: United States
    * State/Province: California (CA)
    * City: Culver City
    * Street: 6161 West Centinela Avenue
    * Postсode: 90230
8. Set In "Carriers" tab "Use global Shipping configuration" to Yes
9. Click button "Save & close"
10. Confirmation message "The Source has been saved" appears
11. verify that data in all tabs is correct
12. Login to backend as admin
13. Go to Stores -> Manage Stocks
14. Click button "Add New Stock"
15. Fill in field "Name" = "Test Stock 1"
16. Select  "Test Source 1"  in sources list
17. Click button "Done"
18. Click button "Save & close"
19. Success message "The Stock have been saved" appeared
20. Login to backend as admin
21. Go to Catalog -> Categories
22. Select Default Category on Categories Tree
23. Click button "Add Subcategory"
24. set "Enable Category" to "Yes"
25. set "Include in Menu" to "Yes"
26. Fill in "Category Name" = "Category 1"
27. Click button "Save"
28. Success  message "You saved the category." appears
29. Verify that Category 1 appeared in Categories tree as subcategory of Default category. 30. Login to backend as admin
31. Go to Catalog -> Products
32. Click button "Add Configurable Product"
33. set "Enable Product" to "Yes"
34. fill Name = "Configurable Product 1"
35. set Price = "10"
36. set Weight = "1"
37. select Category = "Category 1"
38. in "Product in Websites" tab  select "Main Website"
39. click button 'Create Configuration"
40. On page "Step 1" - Select attribute "color"
41. click button "Next"
42. On page "Step 2" create new values "Red" and 'Black" and check them in
43. click button "Next"
44. On page "Step 3" select "Apply single quantity to each SKUs"
45. Click button "Assign Sources"
46. In Assign Sources grid select "Default Source" and click "Done"
47. set Quantity = 100
48. click button "Next"
49. On page "Step 4" click button  "Generate Products"
50. click button "Save"
51. Success  message "You saved the product." appears
52. Verify that created variation products are present on "Configuration" tab
53. Login to backend as admin
54. Go to Catalog -> Products
55. Open "Configurable Product 1-red" page to edit
56. Go to "Assigned Sources" tab on product page
57. Set Stock status for "Default source" as "Out of Stock"
58. Click button "Save & Close"
59. Open "Configurable Product 1-blue" page to edit
60. Go to "Assigned Sources" tab on product page
61. Set Stock status for "Default source" as "Out of Stock"
62. Click button "Save & Close"
63. Verify that "Configurable Product 1" dissapeared from Category page on frontend
64. Go to Stores -> Configuration -> Catalog -> Inventory
65. In "Manage Stock Options" tab for "Manage Stock" function uncheck "Use system value" and set it to "No"
66. Click button "Done"
67. Click button "Save Config"
68. Verify message "You saved the configuration."
69. Run reindex and flush cache
70. Go to "Home page"
71. Verify that "Configurable Product 1" disappeared from Category page

----

Original HipTest ID: 1695735

**Comment by ivy00johns** [comment]
Merged to Mainline.

**Comment by smoskaluk** [comment]
https://app.hiptest.com/projects/69435/test-plan/folders/457025/scenarios/1695735
