### ISSUE TITLE
Integration tests for MSI#822 (virtual/downloadable source deduction)

### ISSUE THREAD

**Issue by vadimjustus** [magento/inventory#977]
Integration tests for source deduction for virtual and downloadable products are failing for multi source mode. Fixtures need to be fixed for `\Magento\InventoryShipping\Test\Integration\SourceDeductionForVirtualProductsOnMultiStockTest`. 

- See discussion in https://github.com/magento-engcom/msi/pull/921 for more details

**UAC:**
- Integration tests for `InventoryShipping` module are green
- Tests in `\Magento\InventoryShipping\Test\Integration\SourceDeductionForVirtualProductsOnMultiStockTest` aren't marked as incomplete

**Comment by p-bystritsky** [comment]
Corresponding PR is merged into https://github.com/magento-engcom/msi/pull/921
