### ISSUE TITLE
\Magento\Inventory\Model\Source\Command\SaveInterface $commandSave returns []

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/inventory#979]
### Preconditions
1. Magento MSI in Single Stock mode

### Steps to reproduce
1. Execute `curl -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Bearer <token>' -d '{"source":{"longitude":-74.0059731,"carrier_links":[],"source_code":"default","postcode":"10007","country_id":"US","name":"Default Source","description":"Soundwalk Source","use_default_carrier_config":true,"latitude":40.7143528,"enabled":true}}' 'http://<host>/rest/all/V1/inventory/source/default'`
or
`curl -X POST "http://<host>/rest/all/V1/inventory/source/" \
-H 'Content-Type: application/json' \
-H 'Authorization: Bearer <token>' \
-d '{"source":{"source_code":"nondefault","name":"Non default","email":"yhiteca@gmail.com","contact_name":"Tomash Khamlai","enabled":true,"description":"Non default source","latitude":40.7143528,"longitude":-74.0059731,"country_id":"US","region_id":12,"region":"California","city":"Culver City","street":"6161 West Centinela Avenue","postcode":"90230","phone":"(555) 555-5555","use_default_carrier_config":true}}'`

### Expected result
1. Returns the new source object 

### Actual result
1. Returns:
`[]`

**Comment by maghamed** [comment]
not an issue, command method should return `void`
