### ISSUE TITLE
Move Product on Stock Assigning from Inventory Module to InventoryCatalog

### ISSUE THREAD

**Issue by naydav** [magento/inventory#98]
Need to move to new module
- https://github.com/magento-engcom/msi/blob/develop/app/code/Magento/Inventory/view/adminhtml/ui_component/product_form.xml
- related setup scripts
- Source Items logic
- API

**Comment by sergy-gzh** [comment]
looking into it. Meet Magento BE 2017 contribution day.

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/139
