### ISSUE TITLE
'The stock item was unable to be saved' on MSI in Single Stock Mode

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/inventory#984]
This issue is related to [issue-985](https://github.com/magento-engcom/msi/issues/985)

### Preconditions
1. Magento MSI EE
2. Single Stock Mode

### Steps to reproduce
1. Navigate to Catalog > Products
2. Click 'Add Product' button
 - > Name: 6gj ?&? &&&?
 - > SKU: 6gj ?&? &&&?
 - > Price: $10
 - > Set weight and assign it to a category
3. Click 'Save'

### Expected result
1. The product is successfully saved (According to the behaviour on 2.2-develop)

### Actual result
1. Error:
'The stock item was unable to be saved. Please try again.'
![problem](https://user-images.githubusercontent.com/11827230/38996486-f90116e6-43f3-11e8-83ae-84853169c4a0.png)

**Comment by p-bystritsky** [comment]
Question mark should not be allowed in SKU.

**Comment by TomashKhamlai** [comment]
Internal ticket [MAGETWO-90760](https://jira.corp.magento.com/browse/MAGETWO-90760) was created to address this issue.
