### ISSUE TITLE
Argument 2 passed to Magento\InventoryLowQuantityNotification\Model\SourceItemConfiguration\Command\Get::execute() must be of the type string, null given

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/inventory#985]
### Preconditions
1. Magento MSI EE
2. Multi Stock Mode

### Steps to reproduce
1. Navigate to Catalog > Products
2. Click 'Add Product' button
 - > Name: 6gj ?&? &&&?
 - > SKU: 6gj ?&? &&&?
 - > Price: $10
 - > Set weight and assign it to a category
3. Click 'Save'

### Expected result
1. The product is successfully saved (According to the behaviour on 2.2-develop)

### Actual result
1. Fatal error: Method Magento\Ui\TemplateEngine\Xhtml\Result::__toString() must not throw an exception, caught TypeError: Argument 2 passed to Magento\InventoryLowQuantityNotification\Model\SourceItemConfiguration\Command\Get::execute() must be of the type string, null given, called in /var/www/html/pr/app/code/Magento/InventoryLowQuantityNotification/Ui/DataProvider/Product/Form/Modifier/SourceItemConfiguration.php on line 95 in /var/www/html/pr/app/code/Magento/Ui/Component/Wrapper/UiComponent.php on line 0

**Comment by TomashKhamlai** [comment]
Behavior changed. Now the problem is the same as in issue #984

**Comment by p-bystritsky** [comment]
Question mark should not be allowed in SKU.
