### ISSUE TITLE
Add Strict Typing for all PHP code added in the scope of MSI poject

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#99]
Based on the Community Poll we've conducted 
https://twitter.com/iminyaylo/status/905049975175962624

it makes sense to add `declare(strict_types=1);` for all PHP code in the scope of MSI

**Comment by naydav** [comment]
Also, need to add typecasting to Controllers and DataProviders

Example
https://github.com/magento-engcom/msi/blob/develop/app/code/Magento/Inventory/Controller/Adminhtml/Source/Edit.php#L51
In this case `$sourceId` is string

But expected type is `integer`
https://github.com/magento-engcom/msi/blob/develop/app/code/Magento/InventoryApi/Api/SourceRepositoryInterface.php#L51

After enabling Strict typing we will have got \TypeError
So need to add typecasting to all Controllers and DataProviders

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/192
