### ISSUE TITLE
Validation failed during saving created simple product with '0' qty on source

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#991]
### Preconditions

1. Magento MSI
2. New stock with new source created

### Steps to reproduce

1. Create new simple product
2. Assign it to new source, set stock status 'Out of stock' 
3. Click 'Save'

### Expected result

1. Simple product saved successfully

### Actual result

1. 'Validation Failed!' - warning message

*New product presents in the Products grid

**Comment by naydav** [comment]
@smoskaluk 
Can not reproduce on the current 2.3-develop branch
Pls, recheck

**Comment by smoskaluk** [comment]
On latest 2.3-develop branch to reproduce - Qty field should be empty

**Comment by maghamed** [comment]
This issue should be fixed on UI level.

Currently, Qty is required field - and that's correct.
This should work similarly from both UI and Web API

What we need to do - is to add red asterisks symbolizing required field to the grid for each Qty field,
also, UI validation should be added, not allowing to send the form with empty Qty values.

And by default page should assign `0.0` Qty after Product to Source assignment
