### ISSUE TITLE
Cannot add Configurable product to cart on Custom Stock.

### ISSUE THREAD

**Issue by p-bystritsky** [magento/inventory#992]
### Preconditions
1. Magento with enabled MSI

### Steps to reproduce
1. Login to admin area.
2. Navigate to Store > Manage Sources.
3. Add new source "Test Source"(code: "test_source").
4. Navigate to Store > Manage Stocks.
5. Add new stock "Test Stock". Assign it to current(default) website.
6. Assign "Test Source" to "Test Stock".
7. Perform reindex and flush cache.
8. Navigate to Catalog > Products.
9. Start creating configurable product.
10. Fill necessary data:
Product Name: "configurable product"
SKU: configurable product
Price: 3
11. Start creating configurations.
12. At "Select Attributes" step select color attribute.
13. At "Attribute Value" step create two options: "blue" and "red".
14. At "Bulk Images & Price" step check "Apply single quantity to each SKUs" and assign "test_source" with qty = 100 (NOTE: do not make assign options to Default Source).
15. Generate products.
16. Set some weight for generated products.
17. Save configurable.
18. Navigate to storefront, configurable product view page 
19. Try to add some configurable product option to cart.

### Expected result
1.  Configurable product variation successfully added to cart.

### Actual result
1. "This product is out of stock." error message appers.

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/1014
